### ISSUE TITLE
Use python template framework instead of setup_util.replace

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1017]
Instead of the setup_util function, there must be some well-established python libraries for this type of template-based substitution. We could run this before we even call `install.sh`, so that it would be safe to move *all* compilation and building to the `install.sh`. 

Naturally we would want a well-established library, as we would be putting it through a grind of different languages, config file formats, etc--it would need to hold up in 100 different scenarios ;-)

Idea from IRC chat

**Comment by msmith-techempower** [comment]
No longer relevant.
