### ISSUE TITLE
Link to the used versions (of the tests) from the blog post

### ISSUE THREAD

**Issue by Skamander** [TechEmpower/FrameworkBenchmarks#102]
Hi,

on your blog you link to the websites of the various frameworks/server/etc. which where used in the benchmark. Is it possible for round 3 to link also to the source code which was used from the various frameworks? Maybe make a branch before you start your tests and link to that afterwards? 

Thanks again for the tests. Its interesting to see how people improve the performance of various frameworks.

**Comment by LadyMozzarella** [comment]
We should be now logging the latest git commit number when running the tests, so it should be pretty easy to link back to the code used at that commit.

**Comment by msmith-techempower** [comment]
Kicking this way down the road.

**Comment by nbrady-techempower** [comment]
Added to results website project tab
