### ISSUE TITLE
Windows Continuous Integration

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1038]
@aschneider-techempower found this awesomeness: http://www.appveyor.com/

If we could copy the Travis-CI setup over to appveyor (or another similar service--any suggestions?) then we could also verify the tests that require a windows OS. We could also have someone make big improvements to the windows install toolset and be ensured that they were not breaking frameworks

**Comment by akoeplinger** [comment]
+1 to AppVeyor. You might want to talk to @feodorfitsner from AV about the open questions.

**Comment by FeodorFitsner** [comment]
There are all the latest Python versions installed on AppVeyor build workers: http://www.appveyor.com/docs/installed-software#languages-libraries-frameworks unless you need something unusual. You can drastically reduce build time by removing Python installation. There is an item to [install pip/virtualenv](https://github.com/appveyor/ci/issues/232), but let me know what else you are missing there.

**Comment by hamiltont** [comment]
We should be able to use the pre-installed python for running our toolset! We only build python from source when testing one of the frameworks inside `frameworks/Python`, but I expect that won't be necessary at first as most of the python frameworks target linux. Thanks for the help @akoeplinger @FeodorFitsner

**Comment by hamiltont** [comment]
FYI, after looking at the database issue more closely, I want to note that *most* of the Windows tests target mysql. AppVeyor has mysql available already, so we might be able to setup windows-CI without too much initial concern over the database setup by just initially allowing only mysql-targeting tests to run in that environment.

**Comment by nbrady-techempower** [comment]
This is still a bit of a ways off with many details changed
