### ISSUE TITLE
Remove Manual MongoDB 2.6 installation from Travis-CI

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1047]
Once travis-ci/travis-cookbooks#350 is live, Travis-CI will be using MongoDB 2.6, and we no longer need to manually upgrade them from 2.4 in `run-ci.py`. This mainual upgrade was the primary cause of #989, and generally adds 30-60sec to launching our Travis workers

**Comment by msmith-techempower** [comment]
I believe this is resolved.
