### ISSUE TITLE
Questions about the request timeouts used for benchmarking

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1052]
According to #855, Wrk associates each request with a time limit, such as 5 seconds. If a request returns after the time limit, it is counted as an error. This was apparently a problem for benchmarking frameworks under heavy load conditions, because once the request queue was too full _all requests were being counted as failures_ by wrk, as all requests were waiting in the queue more than 5 seconds while previous requests were being processed. 

This would be hugely frustrating, because the longer this heavy load benchmark runs the worse your server appears to perform. This is true even if it was doing as much work is possibly with the current CPU--once your queue is in a _very full_ state you are done. Apparently, there's no way to saturate+back-off+repeat, but only "hit the server as hard and fast as you can." 

The solution to this problem was to **make the timeout wrk uses for each request equal to the concurrency.** That means that at concurrency level 256, each request that completes _within 256 seconds!_ is counted as a successful request. That's over 4 minutes allowed for a single request!! [The code](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L50) looks like this: 

```
{wrk} {headers} -d {duration} -c {max_concurrency} --timeout {max_concurrency} <snip>
```

I wanted to open an issue to discuss problems and potential different approaches. 

Problems: 
- I would expect to see a lot of requests timing out on huge concurrency levels. The current approach may have the confusing effect of reducing total request timeouts as concurrency increases
- If a framework intentionally refuses to worsen an already bad situation, it would be penalized for that while non-intelligent solutions that provide horrid quality of service would not. For example, if a webserver knows it could not service a newly arrived request within the next 2 minutes, it may refuse that request. Any refusal error code would be counted as an error, whereas just queuing might eventually be counted as a normal request-response. 
- To rephrase the above point, the current approach makes an inherent assumption about how the queue organizes, prioritizes, and handles requests. It also seems to assume that the queue should be large enough to hold all the requests (because holding them all and responding slowly counts as ok, whereas instant rejections count as errors). If a framework does this differently in some manner they think is more intelligent, they are probably being penalized for it at the moment. 

Solution thoughts: 
- The timeouts can become insane (4 minutes!). Perhaps they should just be adjusted to more real-world appropriate levels, like max 120 seconds? 
- Perhaps just use a reasonable static timeout, like 30sec? This would let all frameworks optimize for what we consider acceptable quality of service. Basically we would be saying  if you can't handle a request in X seconds just drop it. This would then allow each framework to configure items like queue length, prioritization, etc. If a framework enters the complete decimation mode discussed above it would just take the hit that thousands of requests timed out. This seems fairly real-world to me, as you would just reconfigure the server to start dropping requests (if there was no option to load balance)

**Comment by msmith-techempower** [comment]
Still not sure where we stand on this one - kicking down the road.

**Comment by msmith-techempower** [comment]
Here we are two years later, and I'm still not sure where we stand on this one.

It LOOKS like our timeout is now set to 8 across the board, so I am going to close this and if anyone disagrees, feel free to reopen.
