### ISSUE TITLE
Add support for outdated flag in benchmark_config

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1065]
This seems like a slick way for maintainers to tag tests and be sure that the website will just display a nice message about "this test is not shown because a maintainer indicated it is outdated (want to <a href="https://github.com/TechEmpower/FrameworkBenchmarks">update it?</a>)" or something.

**Comment by nbrady-techempower** [comment]
Added to https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
