### ISSUE TITLE
Vagrant: Add Windows Support

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1073]
vagrant supports windows out of the box. If we could update our `core.rb` and `checks.rb` script to support windows, then `vagrant-development` could be used to launch a windows virtual machine configured to run this toolsuite

**Comment by nbrady-techempower** [comment]
This currently works, though we need to get mounting/binding working. That's on the roadmap. https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
