### ISSUE TITLE
Add CPU, memory, and IO utilization info under load

### ISSUE THREAD

**Issue by matrixik** [TechEmpower/FrameworkBenchmarks#108]
Suggested here:
https://groups.google.com/d/msg/golang-nuts/Y2zj01FGUK0/opsbES8f3r8J

> Another thing worth looking at is memory usage under load.  This is really a measure of the effectiveness of the GC, and how data is laid out internally.  The results won't surprise anyone probably but the magnitude of the results might.  When you chose a platform with scale in mind you have tackled throughput -- but memory usage dictates how many machines you'll need almost as much.

Best regards,
Dobrosław Żybort

**Comment by hamiltont** [comment]
Implemented in master using [dstat](https://github.com/TechEmpower/FrameworkBenchmarks/blob/ca9ee21ddfcbdb237cf5c8cbf94a62a3b24f2d56/toolset/benchmark/framework_test.py#L549)
