### ISSUE TITLE
Websocket tests

### ISSUE THREAD

**Issue by kbrock** [TechEmpower/FrameworkBenchmarks#1085]
Hi,

Websocket support is listed in #133 but a few apps seem to implement websocket. Are there specs out for functionality?

There is a fun [article](http://eric.themoritzfamily.com/websocket-demo-results-v2.html) in 2012 that attempts to benchmark websocket implementations in a number of servers. Could that [code](https://github.com/ericmoritz/wsdemo/tree/v2) be leveraged here?

`echo` is one form of benchmark, much like the static file serving, but I'm more interested in a chat app. Would that be too complicated of a sample app to coordinate across so many languages? (E.g. node would want to use socket.io but that doesn't work with a standard websocket client)

Also, an http client at this scale seems difficult to implement. Would a websocket load tester be too much work to implement?

Thanks for the great project

**Comment by nbrady-techempower** [comment]
This would require some additional tooling along with the new test type. Probably not something for the near future but added to the [Test Types Roadmap](https://github.com/TechEmpower/FrameworkBenchmarks/projects/3)
