### ISSUE TITLE
Replace --include and --exclude with generic --filter option

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1094]
Seems like we could add something like this: 

     parser.add_argument('--filter', nargs='+', help='Arbitrary filtering of benchmarks using format [key](==|!=)[value]')

Which could be used to filter on any key in the `benchmark_config` as so: 

    toolset/run-tests.py --filter os==linux --filter database_os!=windows --filter approach==Realistic

It could be made backwards compatible e.g. `--include foo` could be shorthand for `--filter name==foo`
("name" is not currently a key, it's just an example)

**Comment by msmith-techempower** [comment]
I actually prefer the current flags.
