### ISSUE TITLE
Add load generation tool used to results.json

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1096]
To future-proof the json result files, it would be good to know exactly what load generation tool was used. Currently we use `wrk`, older rounds used a different tool, and there's nothing saying we won't switch again to something ([vegeta](https://github.com/tsenart/vegeta), httperf, etc). It should be fairly simple to drop a static string into the json results indicating what generator (and perhaps what version number) was used, and update this string each time the load generation tool is switched

**Comment by msmith-techempower** [comment]
Kicking down the road.
