### ISSUE TITLE
PHP uses Redis cache on different host

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1099]
#1087 causes a number of the PHP-based tests to use Redis for caching opcodes (parsed php files) and data (parsed php configuration files). During the rounds the web servers and the redis install are run on different servers, and therefore this "cache" actually introduces an extra network delay for each request to the webserver. 

We should minimally remove this Redis cache. Preferably it can be replaced by a cache on the same host as the web server, such as APC, APCu, Xcache, etc. Fixing this is likely fairly simple for someone familiar with PHP

**Comment by msmith-techempower** [comment]
Kicking this down the road.

**Comment by msmith-techempower** [comment]
Resolved - we disabled all redis tests.
