### ISSUE TITLE
Stabilize Rust Version to 1.0 when it arrives

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1102]
Currently `rust.sh` installs the latest version of Rust. Rust is in beta and fast movement is still to be expected, as well as a lot of breakage. However, once v1.0 arrives we should hardcode the version. Also, if possible, we should install rust into a prefix folder instead of installing natively onto the host machine. 

cc @torhve

**Comment by LadyMozzarella** [comment]
A little update: Looks like we're now at Rust 1.0 Beta. [Announcing Rust 1.0 Beta](http://blog.rust-lang.org/2015/04/03/Rust-1.0-beta.html).

I think we can at least hard code this version for now: https://static.rust-lang.org/dist/rust-1.0.0-beta-x86_64-unknown-linux-gnu.tar.gz

**Comment by msmith-techempower** [comment]
I think @torhve had a version before, but he's waiting for available time to open a PR.

**Comment by LadyMozzarella** [comment]
[Rust 1.0.0 is stable as of today](http://www.rust-lang.org/install.html).

**Comment by steveklabnik** [comment]
I just opened https://github.com/TechEmpower/FrameworkBenchmarks/pull/1636 to get this going.

I didn't see a rust installer in the tree though, am I missing something?

**Comment by msmith-techempower** [comment]
I believe this is resolved.
