### ISSUE TITLE
verify database connectivity once for all databases before running any of the tests

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1103]
the toolset alreday does some DB setup before each test, like restarting or something. It should probably also verify database connectivity too, using something like `nc -vz <db host> <db port>`. This would be really helpful for cassandra and mongodb, who are not ready to start handling connections just because `service <foo> restart` has returned

See #1082

**Comment by marko-asplund** [comment]
@hamiltont please see my take on implementing this feature in PR #1357

**Comment by hamiltont** [comment]
Fixed in #1357, thanks @marko-asplund!
