### ISSUE TITLE
Cabal occasionally fails on Travis-CI due to low memory

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1117]
Is there something that can be done to cause it to use less memory? 

[Here](https://travis-ci.org/hamiltont/FrameworkBenchmarks/jobs/38398368) is an example of a failed build that should pass verification according to multiple prior builds, multiple followup builds, and my local testing. It's dumping a lot of this into `err.txt` when trying to verify yesod

```
INFO:run-ci:cabal: Error: some packages failed to install:
INFO:run-ci:auto-update-0.1.2 failed during the building phase. The exception was:
INFO:run-ci:ExitFailure 9
INFO:run-ci:This may be due to an out-of-memory condition.
INFO:run-ci:bench-0.0.0 depends on system-filepath-0.4.12 which failed to install.
INFO:run-ci:bson-0.3.1 depends on data-binary-ieee754-0.4.4 which failed to install.
INFO:run-ci:byteorder-1.0.4 failed during the building phase. The exception was:
INFO:run-ci:ExitFailure 9
INFO:run-ci:This may be due to an out-of-memory condition.
INFO:run-ci:cereal-0.4.1.0 failed during the building phase. The exception was:
```

Note: Travis workers are currently linux containers with relative limits (e.g. container x gets at least 25% of the total RAM), so it's entirely feasible that some workers have enough memory to complete, whereas other workers are more saturated and don't have that extra memory. Something else to mention in #1070 - two identical jobs can still have different available host resources, which can cause problems like this issue

**Comment by msmith-techempower** [comment]
Sometimes `-j1` helps... sometimes it doesn't.

**Comment by msmith-techempower** [comment]
I BELIEVE this is addressed.
