### ISSUE TITLE
Set errexit flag before sourcing installer files

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1118]
In `fw_depends` we should eventually turn on errexit right before sourcing the file, like this: 

    if [ -f $FWROOT/toolset/setup/linux/systools/${depend}.sh ]; then
      echo Installing system tool: $depend in $relative_wd
      set -e
      . $FWROOT/toolset/setup/linux/systools/${depend}.sh

This will ensure that we are guaranteed to get a return from the subshell, and generally leads to better bash code all around. However, it's honestly a pain to write bash with errexit sometimes, and even mroe so with the tons of technology TFB uses. So this issue is just a bookmark until travis-ci is 100% green, when this change can be made and we can easily identify which frameworks break as a result

**Comment by msmith-techempower** [comment]
No longer relevant as we do not use installer files.
