### ISSUE TITLE
Gemini startup appears to be unreliable (at least in Travis-CI)

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1119]
Looking at some recent travis builds e.g. 447-458 from [here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds) I noticed that gemini seems to cycle between pass/fail quite a lot - it's almost 50/50. There's no logic changes that I can see - nothing in git indicates major changes that should cause this, and the failed runs have messages such as this: 

```
INFO:run-ci:Server: Resin/4.0.36
INFO:run-ci:Content-Type: text/html; charset=utf-8
INFO:run-ci:Content-Length: 489
INFO:run-ci:Date: Sun, 19 Oct 2014 11:40:50 GMT
INFO:run-ci:
INFO:run-ci:<html><head><title>Temporarily Unavailable</title><style>body { background-color: white; color: black; }p { font-family: Arial, Helvetica, Sans-serif; font-size: 12px; }h2 { font-family: Arial, Helvetica, Sans-serif; font-size: 14px; font-weight: bold; }pre { font-size: 9px; }</style></head><body><h2>Temporarily Unavailable</h2>
INFO:run-ci:<p>This web site is temporarily unavailable due to maintenance work.  Please check back later.</p>
INFO:run-ci:<!-- Application not yet initialized. -->
INFO:run-ci:</body></html>
```

My only thought is that either a) there needs to be some "am I alive" check before you return from start in `setup.py` because the 60 second wait is not enough, or different travis workers have different properties that can cause gemini to not be installed or started correctly, such as less RAM.

**Comment by msmith-techempower** [comment]
I believe this is resolved.
