### ISSUE TITLE
Quiet down the bash scripts

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1124]
If we pass some "debug level" stuff from python down into the bash scripts, we can selectively enable or disable certain types of printing. 

At the moment I think two prime targets are bash tracing (set -x), which prints at least one line of output for each line of bash, and apt-get, which prints something like 1000 lines for most of our commands. It's very simple to create variables such as `$APT_OPTS=-q` or `$TRACE=false` and use these throughout our bash scripts, and then set these variables from python before calling into bash. I'm partial to always setting apt to quiet mode when inside travis, as it's not outputting high value stuff (the only high value stuff is errors, which quiet mode doesn't affect) and you only get 10k lines before Travis stops updating their "terminal". Currently we use something like 3-6k of these lines on nothing more than apt. 

Perhaps this is something that can be included in #920

**Comment by nbrady-techempower** [comment]
Moving to the roadmap
