### ISSUE TITLE
Avoid travis timeouts during lengthy build steps

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1127]
When we call into `install.sh` files or `setup.py` they frequently run large builds. Commands inside these big builds sometimes take quite a while to return, and we occasionally see 

     No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

In our specific case, this is not normally a stalled build but just a heavyweight build step taking extra time on a loaded travis worker. 

The simple fix is to launch a helper thread that puts out a small bit of output every 10(ish) minutes to ensure this doesn't happen. For example, [this build](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/38298373) normally does not error, but in this case it did because of this issue

**Comment by msmith-techempower** [comment]
I BELIEVE this is resolved.
