### ISSUE TITLE
Round 10?

### ISSUE THREAD

**Issue by bitemyapp** [TechEmpower/FrameworkBenchmarks#1132]
Would really like to see results with weighttp and GHC 7.8 go live :) :+1:

**Comment by d9k** [comment]
When?
Things slightly changed.

**Comment by msmith-techempower** [comment]
We are presently releasing preview runs. No promises, but we are aiming for round 10 at the end of this week (really... no promises).

**Comment by d9k** [comment]
Thanks a lot!
I'm glad it would happen :)
