### ISSUE TITLE
Convert identity file paths to absolute path before creating benchmarker

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1143]
The identity file can be specified in a lot of ways e.g. `foo`, `../../bar/foo`, `C:/foo`, `~/foo`, etc. Inside the codebase I see a few different places where this is converted into an absolute path. IMO it would be better to handle this in one location (argument parsing), and in the rest of the toolset just assume you're dealing with an absolute path. 

This is mostly a reminder so I this issue is not forgotten

**Comment by nbrady-techempower** [comment]
I believe this is no longer relevant.
