### ISSUE TITLE
Fix plaintext settings

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1144]
I forgot to add plaintext as a special case when merging #1129. [This](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L300) needs to be updated slightly to this: 

```
        if test_type == 'plaintext': # One special case
          remote_script = self.__generate_concurrency_script(test.get_url(), self.port, test.accept_header, levels=[256,1024,4096,16384], pipeline="16")
        elif test.requires_db:
          remote_script = self.__generate_query_script(test.get_url(), self.port, test.accept_header)
        else:
          remote_script = self.__generate_concurrency_script(test.get_url(), self.port, test.accept_header)
```

I'm busy on a differnet topic if someone has time to put in a quick commit that would be great

**Comment by LadyMozzarella** [comment]
It appears that this was supposed to be closed with the pull request that reverenced this issue, closing. Please reopen if it isn't actually fixed in master.
