### ISSUE TITLE
Vagrant development setup xplatform improvement

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1147]
Currently, when you clone the project to a Windows machine using the favored "repo has *nux line-endings, I'll use my system's line-endings", the code exists locally with Windows-flavor line-endings.

When a user tries to `vagrant up`, the code is copied into the vagrant instance with the Windows-style line-endings which causes everything to break.

There should probably be a stage of this copy where line endings are transformed from ANY-style to *nux-style during the `vagrant up` call.

**Comment by nbrady-techempower** [comment]
fix'd forever.
