### ISSUE TITLE
Java tests - java.util.Random usage may lead to non-optimal performance in heavy concurency conditions

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#1152]
[Java documentation](http://docs.oracle.com/javase/7/docs/api/java/util/Random.html) states the following:
>Instances of java.util.Random are threadsafe. However, the concurrent use of the same java.util.Random instance across threads may encounter contention and consequent poor performance. Consider instead using ThreadLocalRandom in multithreaded designs. 

[Here](http://java-performance.info/java-util-random-java-util-concurrent-threadlocalrandom-multithreaded-environments) you can find a nice article with comparision IMO.

And the files where java.util.Random is used :
```shell
:~/source/FrameworkBenchmarks$ grep -r "import java.util.Random;" ./
./frameworks/Java/grizzly-jersey/src/main/java/hello/DbResource.java:import java.util.Random;
./frameworks/Java/play1siena/app/controllers/Application.java:import java.util.Random;
./frameworks/Java/ninja-standalone/src/main/java/controllers/SetupController.java:import java.util.Random;
./frameworks/Java/ninja-standalone/src/main/java/controllers/HelloDbController.java:import java.util.Random;
./frameworks/Java/activeweb/src/main/java/app/controllers/DatabaseController.java:import java.util.Random;
./frameworks/Java/spring/src/main/java/com/techempower/spring/web/WorldDatabaseController.java:import java.util.Random;
./frameworks/Java/dropwizard/src/main/java/com/example/helloworld/resources/WorldResource.java:import java.util.Random;
./frameworks/Java/restexpress/src/main/java/hello/controller/MysqlController.java:import java.util.Random;
./frameworks/Java/restexpress/src/main/java/hello/controller/MongodbController.java:import java.util.Random;
./frameworks/Java/play1/app/controllers/Application.java:import java.util.Random;
./frameworks/Java/vertx/WebServer.java:import java.util.Random;
./frameworks/Java/play2-java/play2-java-ebean/app/controllers/Application.java:import java.util.Random;
./frameworks/Java/play2-java/play2-java-jpa/app/controllers/Application.java:import java.util.Random;
./frameworks/Java/spark/src/main/java/hello/web/SparkApplication.java:import java.util.Random;
./frameworks/Java/dropwizard-mongodb/src/main/java/com/example/helloworld/resources/WorldResource.java:import java.util.Random;
:~/source/FrameworkBenchmarks$

**Comment by dgryski** [comment]
A similar issue affects the Go code.  The calls to rand.Intn() are all serialised behind a mutex internally.

**Comment by msmith-techempower** [comment]
Kicking down the road.

**Comment by zloster** [comment]
There is new [pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1941) which removes old Finagle sources and adds only "Plaintext" and "JSON serialization" tests - so this will solve the remarks for the commented code described in my comment [above](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1152#issuecomment-62548232).
