### ISSUE TITLE
Gather tests should fall back on benchmarker.cfg 

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1159]
If you don't pass a Benchmarker instance to `gather_tests`, it will create a default one. Because Benchmarker has a number of dynamically created members from the call `self.__dict__.update(args)` in `Benchmarker.__init__`, we need a dict of those dynamic arguments. At the moment I'm using the example configuration to build that dict: 

```
default_config = setup_util.get_fwroot() + "/benchmark.cfg.example"
```

This has caused multiple issues as people don't realize that `benchmark.cfg.example` is actually used by TFB on a regular basis. I'm very open to any better way to deal with this, but I couldn't find one. Perhaps there's some way to access the argument list from the utils.py file and use that to build a much more future-proof list of defaults? 

What I'd propose to do is modify the above to also look for a `benchmark.cfg` file - if that one is found let's use that as the first configuration option, and then use the example file to add any new keys to the dictionary that were not found in the `benchmark.cfg` file

**Comment by msmith-techempower** [comment]
I think this is fine; closing for now.
