### ISSUE TITLE
results.json files in round result repositories seem broken

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1165]
Looking at the repositories for round 9 and round 8, I cannot find a single file that contains all the results. I looked at all the `results.json` files I could find - none of them lists more than 2-3 frameworks. 

It appears that the results would need to be parsed out of all the raw files?! The [file used by the results website](http://www.techempower.com/benchmarks/results/round9/peak.json) contains all the data, but this isn't the file in the data repos - it appears someone did the necessary parsing to flatten all the raw files into one complete `results.json` file. 

Could this same process be applied to the files in the data repositories, so that each data repo has a few `results.json` files that are complete and ready to be used as input?

**Comment by msmith-techempower** [comment]
I believe this is resolved.
