### ISSUE TITLE
Document source_code in the README

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1176]
As mentioned in #1175, there's no explanation of source_code in the main readme. Here's a short one: The source_code file is used to count the lines of code in the project - each file listed in source_code has its lines counted and the result is include in results.json. TFB does not use the numbers in any of the graphs but we include them for other consumers of the data

**Comment by LadyMozzarella** [comment]
Closing - now documented in documentation.
