### ISSUE TITLE
Fix Falcore

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1181]
Falcore is out of date and `falcore.JSONResponse` is no longer in the framework.

**Comment by LadyMozzarella** [comment]
Looks like Falcore was fixed with [Pull Request #1234](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1234) and is currently [working on master](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/52758450) as of 2015/03/03. Good to close?
