### ISSUE TITLE
Benchmark for HTTP Servers

### ISSUE THREAD

**Issue by edsiper** [TechEmpower/FrameworkBenchmarks#1182]
There are a bunch of HTTP servers around and  _lazy benchmarks_  published around them. I would like to request if you can do a spin of your FrameworkBenchmarks for static content and similar things that are not in the scope of your primary project.

The main goal of this request is to measure how well each server is doing after a few months on each new release and look for potential improvement areas. If your HTTP server runs slower than other, I am sure and improvement will come up.

Current projects who should sign up:
- [Monkey HTTP Server](http://monkey-project.com), https://github.com/monkey/monkey
- [NginX](http://nginx.org)
- [LighttpD](http://www.lighttpd.net/)
- [Hiawatha](https://www.hiawatha-webserver.org/)

Some interest tests would be:
- Non-keepalive 
- Keepalive
- Small, medium and big file sizes
- Error handling (on high load)
- etc.

**Comment by nbrady-techempower** [comment]
This isn't something we would implement anytime soon but it's definitely something to think about as we rework the toolset. I'll add this to the roadmap as a future idea. Thanks!
