### ISSUE TITLE
consider using wrk2 for raw or CO corrected percentiles

### ISSUE THREAD

**Issue by ceeaspb** [TechEmpower/FrameworkBenchmarks#1220]
consider using https://github.com/giltene/wrk2 for CO corrected percentiles, related to #31 and #854.

**Comment by wg** [comment]
Hello folks, FYI wrk 4.0.0 has been released with fairly dramatic improvements to performance and stats accuracy. I've eliminated sampling and now record all latencies below the configured timeout, and CO correction takes a similar approach to the one used by HdrHistogram.

I'd encourage you to take advantage of the Lua scripting support to generate your output files in a more useful format, perhaps JSON. It's much easier than parsing the human-friendly output and you can get any percentiles you desire: https://github.com/wg/wrk/blob/master/scripts/report.lua

**Comment by bhauer** [comment]
@wg This sounds great. Thanks for letting us know! Hopefully we can find some time between Round 10 and 11 to experiment with wrk 4.

**Comment by bhauer** [comment]
I've changed this to a Round 12 milestone.

**Comment by msmith-techempower** [comment]
Resolved by #1864
