### ISSUE TITLE
Add 'install' key to benchmark_config.json

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1224]
When trying to test a given framework under `Python`, I see it installing EVERYTHING python-related because the install scripts cover all requirements. An example of this is with `bottle` which has a `py2`, `py3`, and `pypy` implementation.

Question - should we change up the directory structure a bit for these since it seems like each of those python implementations act like different languages?

~/FrameworkBenchmarks/frameworks/Python2
~/FrameworkBenchmarks/frameworks/Python3
~/FrameworkBenchmarks/frameworks/PyPy

instead of just

~/FrameworkBenchmarks/frameworks/Python

Then, there would be a `bottle` directory under each, but the `benchmark_config`, `install.sh`, and `bash_profile.sh` would only need to set up and use the specific version of python based on the dir.

@hamiltont @methane Thoughts?

**Comment by hamiltont** [comment]
Thought about this some more. 

Some info from `find frameworks/Python -name install.sh -exec grep fw_depends {} \;` shows that most of the python tests have py2 and py3 implementations:

```
fw_depends python3
fw_depends python2 python3 pypy nginx
fw_depends python2 python3
fw_depends python2 python3 pypy
fw_depends python2 python3 pypy nginx
fw_depends python2 python3
fw_depends python2 python3
fw_depends python2 nginx
fw_depends python2 nginx
```

I get the point -  if you just want to test `django-py3` why are you also compiling py2 and pypy, but it seems like it's easier to deal with that burden in this case than to have three directories that all have to be maintained e.g. `frameworks/Python2/django`, `frameworks/Python3/django`, and `frameworks/PyPy/django`

**Comment by methane** [comment]
Additionally, I'll add PyPy3 in Round 11.

**Comment by msmith-techempower** [comment]
lmao I love methane's response.

I believe what @hamiltont is getting at is that there should probably be a single directory `frameworks/Python` and therefore a single test directory (like `frameworks/Python/django`) that has setup scripts for all of the python implementations (`py2`, `py3`, `pypy`, etc).

**Comment by hamiltont** [comment]
Yup. That's basically what we have now, and sadly the installer system doesn't support separate `install.sh` files for specific tests. Perhaps that's something to add in R11 - an `install` option to `benchmark_config` that serves the same purpose as the current `setup` option - then tests that wanted could have `install_py2.sh`, `install_py3.sh`, etc, and we could have the best of both worlds - simple folder structures for the frameworks *and* the ability to say `--test django-py3` without requiring a py2/pypy/pypy3 download+compile.

**Comment by msmith-techempower** [comment]
Okay, this is addressed imho.
