### ISSUE TITLE
Potentially Modify Test Methodology

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1227]
There are related issues but I can't find them currently. From #1220 @giltene writes this: 

I would consider modifying the test methodology.

The problem I have with the current methodology is that it reports a number that has no real relevance to what the servers can actually bear under load. E.g. what value is there is knowing that net processed almost 200K plaintext ops/sec if some of those ops took over 14 seconds (in a 15 second test), and where 3% of requests failed with a timeout?. What can someone learn from that about the throughput that net can handle in comparison to some other server that did 30K ops per second with some operations taking 7 seconds, and where 2% failed with a timeout? Would anyone deploy either server with those loads per node in mind? What does the data tell us about the behavior of these servers at 20Kops/sec? What does it tell us about the rate at which these servers actually can actually handle in an acceptable setup that you would actually capacity plan for?

My recommendation would be to modify the "score" from "peak number of widgets per second seen passing through system (regardless of latency or failure rates)" to "peak number of widest per second load under which a required service level was maintained for a sustained (many-minutes) period of time".

The service level should be stated with e.g. these steps in mind:
90% (e.g. 10msec)
99.9% (e.g. 200msec)
Max (e.g. 2 seconds)

Actual levels can vary per operation. E.g. above may be good numbers for plaintext and son, but DB stuff may need to be more forgiving.

A scripting system can slew the rate on wrk2 tests to find the breaking point for the above criteria, and establish the stable level (you'll want a run that passes, and a run at a high rate that fails). An initial set of short "ranging" runs can be used to guess at the "knee" before starting the longer tests.

A different (yet similar), more visual approach would be to (for each test type e.g. plain text, json, etc.) produce runs at multiple predetermined throughputs on all frameworks, and to capture the percentile spectrum for each frameworks, under each test type, under each fixed throughout load. These captured percentile spectrum logs (in the percentile format HdrHistogram outputs) cab be then used to plot any set of frameworks against each other on a common chart (for a given test type and throughout, or for arbitrary sets). You can even provide a page where you can select the result sets to plot together, providing a convenient and visual comparison of the how various frameworks behavior under the given load. You can see an example of such a chart in wrk2's README.md . And you can find example page with Javascript to read and plot a set of charts here: http://hdrhistogram.github.io/HdrHistogram/plotFiles.html

I realize that this is a significant change to the testing methodology, but I think that it would give much more valuable information for the consumers of your test round information.

**Comment by msmith-techempower** [comment]
Removing the milestone on this one as it is a more general discussion of methodologies.

**Comment by msmith-techempower** [comment]
I am closing this issue not because it is not relevant but because it has not had any traction in two years.

We may revisit this in the future.
