### ISSUE TITLE
data consistency from the round 9 plaintext test

### ISSUE THREAD

**Issue by ceeaspb** [TechEmpower/FrameworkBenchmarks#1229]
following on from discussion on #1220, I had a look at the raw data for example:
https://github.com/TechEmpower/TFB-Round-9/blob/master/peak/linux/final/20140318081122/plaintext/cpoll_cppsp/raw

Apologies if these are documented somewhere but I couldn't find anything on them:

- it looks like the latency data presented in the report is taken from the last test, ie highest concurrency. It would be worth documenting if that is the case (apologies if I missed it), as my expectation was that the latency figures there would be from the "best" throughput test.

- the errors : not sure where those are coming from as the latency number is from the last test, but the errors are sometimes reported as zero even if there were errors reported by wrk : eg. cpoll_cppsp - there are errors for the last 3 tests but 0 errors reported in the data and latency tables.

**Comment by msmith-techempower** [comment]
We have updated to wrk4 which should resolve a lot of the issues with latency numbers.
