### ISSUE TITLE
Gunicorn for Python 3

### ISSUE THREAD

**Issue by aschneider-techempower** [TechEmpower/FrameworkBenchmarks#1241]
I noticed gunicorn was being installed for python 2 and pypy in the vagrant development boxes, but not for python 3. I'm not quite sure why. This occurred with the pyramid test, but may be the case for the other Python tests.

**Comment by msmith-techempower** [comment]
I believe this has been resolved.

**Comment by GMLudo** [comment]
To my knowledge, yes.
