### ISSUE TITLE
Vagrant shared folders do not allow chown

### ISSUE THREAD

**Issue by zane-techempower** [TechEmpower/FrameworkBenchmarks#1243]
Mike is about to break vagrant on the `meganuke` branch. We were having issues with file-sharing and the inability to change and control the ownership of files. This causes complications when the runner of the tests, `testrunner` should also be the owner of the files installed in `installs/` but isn't (`vagrant` is).

These issues are alleviated by spinning up a brand-new Ubuntu instance and doing the cloning/setup manually as this prevents the issues that arise from `FrameworkBenchmarks` being a shared folder into the vagrant instances.

**Comment by hamiltont** [comment]
So I've figured out the answer to this. Short description: shared folders in vagrant don't really support posix operations. You can set the owner / group / modes at mount time, but after the mount commands like chown/chmod do nothing and you cannot have files owned by two different users anywhere inside the shared folder. 

This naturally sucks, but after some playing there's an easy fix - bind mount a normal linux folder over top of the "installs" folder as so: 

```
echo "Mounting over your installs folder"
mkdir -p /tmp/TFB_installs
mkdir -p /FrameworkBenchmarks/installs
sudo mount -o bind /tmp/TFB_installs $FWROOT/installs
```

This masks the original installs folder, so while `/FrameworkBenchmarks` is synchronized to the host system, `/FrameworkBenchmarks/installs` is not. However, you can now chown/chmod `installs` and anything under it as expected. 

I have verified that this solution works with the mono installation (which requires installs to be owned by testrunner), and now I need to implement it consistently by closing #1488
