### ISSUE TITLE
Replace manual SSH+SFTP with Python library

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1245]
Using something like [Paramiko](http://www.paramiko.org/) would have a number of benefits:
- better handling of things like known_hosts, id_rsa, etc on the host machine
- no requirement for password-less SSH
- no requirement for password-less sudo on remote system (can easily pass sudo password)
- no dependance on host ssh/sftp binaries, just another python module listed in our requirements.txt file
- much cleaner code (more pythonic if you're into that ;-) )

It's also a fairly simple transition, just remove our manual calls to subprocess with calls to the paramiko library

**Comment by nbrady-techempower** [comment]
I'll add this to the roadmap as something to think about when restructuring the toolset.

**Comment by GMLudo** [comment]
Hi,

I don't know at all it should fit your needs, however, we already use Ansible as a Python library to automate some actions programmatically.

Maybe less complicated than integrate paramiko.
You have also asyncssh, but I have no idea if it's easier or more complicated to use than paramiko.

Regards.
