### ISSUE TITLE
Python: Add wheezy.web

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1246]
https://pythonhosted.org/wheezy.web/examples.html

also 

http://faruk.akgul.org/blog/python-web-frameworks-benchmark/

**Comment by ebramanti-techempower** [comment]
Going to start working on this, that second post looks super interesting. Especially if this framework gets similar to Node.js performance.

**Comment by knewmanTE** [comment]
I'll work on this.

**Comment by LadyMozzarella** [comment]
Closing. #1429 merged.
