### ISSUE TITLE
PHP: Add Smceframework-MVC

### ISSUE THREAD

**Issue by imadige** [TechEmpower/FrameworkBenchmarks#1254]
we moved
https://github.com/smceframework

Framework PHP-C++ build
https://github.com/smceframework/framework

Projects/Apps
https://github.com/smceframework/projects

**Comment by imadige** [comment]
we moved
https://github.com/smceframework

Framework PHP-C++ build
https://github.com/smceframework/framework

Projects/Apps
https://github.com/smceframework/projects

**Comment by hamiltont** [comment]
@imadige - Looks interesting. If you turn that code snippet into a pull request, then Travis-CI will automatically verify that it integrates with FrameworkBenchmarks correctly

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
