### ISSUE TITLE
Ability to run test for specific languages

### ISSUE THREAD

**Issue by matrixik** [TechEmpower/FrameworkBenchmarks#126]
Would be nice to have ability to run tests for specific languages

`--test-lang go python` would run: `go, webgo, django-stripped, django, flask` and any added at future test written in given languages.

Best regards,
Dobrosław Żybort

**Comment by nbrady-techempower** [comment]
Added to toolset roadmap https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
