### ISSUE TITLE
Nancy tests using libevent failing after conversion of setup file from .py to .sh

### ISSUE THREAD

**Issue by lgratrix-techempower** [TechEmpower/FrameworkBenchmarks#1268]
Related to Travis build 802.6

Attempted to convert setup.libevent.py to setup_libevent.sh for nancy
After changing reference to Nancy.Hosting.Aspnet dll from version 0.17.1 to 0.23.0, as only 0.23.0 exists in lib folder was unable to successfully run tests, due to receiving multiple method not available errors.

**Comment by msmith-techempower** [comment]
All the mono tests are still pretty fubar... kicking this down the road.

**Comment by msmith-techempower** [comment]
Related to #1565 I believe. Should be able to be resolved now.

**Comment by nbrady-techempower** [comment]
I believe this has been resolved. Any further issues can be marked in #2074
