### ISSUE TITLE
Travis whitelist branches

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1277]
When the techempower team creates new branches on the project and then open pull requests on those branches, each commit is tested by travis twice. We should only have travis test branches that we explicitly want until a PR is opened

```
# whitelist
branches:
  only:
    - master
```

**Comment by nbrady-techempower** [comment]
The only problem with this is if you fork the repo and create your own test branches, those also would not run.

From here on there shouldn't be any branches other than `master` and whatever we decide the current frozen round branch will be called. 

Also, to skip travis runs you can add `[ci skip]` in commit messages.
