### ISSUE TITLE
Remove php-senthot framework

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1283]
senthot hasn't passed verification since R7 ( see #694 ), and as far as I can tell there has been no community involvement to help address that in all this time. The [project code](https://github.com/senthot/Framework) on github has not been updated in a year, and there appears to be minimal community (< 10 stars). I took a crack at fixing the verification issues, but couldn't figure it out. 

Also worth mentioning is that the only issue on the senthot github project is accusation that senthot copied code from [thinkphp](https://github.com/liu21st/thinkphp) (see senthot/Framework#2), and looking at some of the code I can see the similarity (here's one example - [senthot](https://github.com/senthot/Framework/blob/master/Senthot/Common/functions.php#L317) vs [thinkphp](https://github.com/liu21st/thinkphp/blob/2.1/ThinkPHP/Common/functions.php#L625) ), although of course I don't know enough to say anything certain 

if anyone from the senthot community is reading this, please speak up!

**Comment by bhauer** [comment]
I've renamed this task so that it stands as a record that, in fact, Senthot has been removed.
