### ISSUE TITLE
Possible to do redis benchmark for cpoll_cppsp?

### ISSUE THREAD

**Issue by hwongcom** [TechEmpower/FrameworkBenchmarks#1297]
Would like to test cpoll_cppsp for redis and ssdb. Can you do that?

**Comment by hamiltont** [comment]
@hwongcom - In most cases, the TFB team relies on the community to provide test implementations and  we focus on the toolset needed to run the myriad of technologies.

I think your best bet here is to either 1) implement these tests yourself, and send us a pull request 2) talk with someone in the cppsp community and ask them to implement these. We are very happy to help anyone trying to add tests such as these, but we are mainly experts on how the FrameworkBenchmarks toolset works, not on how to implement specific tests using cppsp

I'm going to close this for now, but feel free to reopen if you want to chat about this more
