### ISSUE TITLE
Include non-keepalive benchmark and use wrk2 to get accurate latency records.

### ISSUE THREAD

**Issue by xfeep** [TechEmpower/FrameworkBenchmarks#1309]
1. So far wrk/wrk2 can not do non-keepalive benchmark.
2. But only non-keepalive benchmark can measure the server efficiency of creation & closing connections.
3. for keepAlive benchmark wrk2 can get more accurate latency records e.g. 99.99% latency.

**Comment by hamiltont** [comment]
See #1220 and #1227 - I would recommend closing this in favor of those, although your point about non-keepalive is well received. My current thinking is that we should potentially support both wrk and wrk2 for some transition period, and add a field `benchmarker` (of value `wrk` or `wrk2`) to the `results.json` files. This needs to be discussed with the other contributors before being implemented

Once R10 is completed the process of including wrk2 can be begun
