### ISSUE TITLE
Is there a protocol for requesting removal of a framework? | Remove Silica Request

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1320]
### [PHP's Silica Framework](https://github.com/changloong/Silica)
It looks like this framework didn't complete in round 9. Silica hasn't had any new commits since May 8, 2013. See issue [#721](https://github.com/TechEmpower/FrameworkBenchmarks/issues/721).

**Comment by hamiltont** [comment]
AFAIK opening an issue is the best method. I'll try to take a look at this
f/w tonight and see if there's something to salvage

**Comment by LadyMozzarella** [comment]
Closing this issue. Pull Request [#1325 Remove Php's Silica Framework](Remove Php's Silica Framework) was merged 2015 Feb 10.

**Comment by hamiltont** [comment]
Oop, I forgot to look at this and get back to the thread. THanks for finishing it!
