### ISSUE TITLE
Have php-fpm listen via socket instead of port 9000

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1322]
Currently [php-fpm.conf](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/config/php-fpm.conf#L153) listens on port 9001. Conventional wisdom is that listening on a socket file, like `/var/run/php-fpm.sock`, is much faster. This change would break quite a bit, as many frameworks depend on this, but it would also better reflect production setups

**Comment by nbrady-techempower** [comment]
Looks like some php frameworks are now doing this
