### ISSUE TITLE
PHP/C: Add Smceframework

### ISSUE THREAD

**Issue by imadige** [TechEmpower/FrameworkBenchmarks#1334]
https://github.com/smceframework2

100 % C code.

###Features
Dependency Injection
Dependency Injection CACHE
Dependency Injection Singleton
EventManager
Loader
Collection
Output
Session
Memcache
Redis
HttpException
Response
Router
Acl
Url

###Install
$ cd cframework
$ sudo apt-get install php5-dev libpcre3-dev gcc make
$ ./install

php.ini set
extension=smce.so
$ service apache2 restart

**Comment by hamiltont** [comment]
Cool! Same feedback as I left you on #1254 - it's unlikely we are going to have time to be pulling in new frameworks ourselves in the near future; we normally rely on the community surroundig each framework to send us a PR. There are vagrant scripts to spin up our environment to help make that integration easier, and any PRs will automatically be tested by Travis-CI to ensure they are correct. So if you'd like to see smce/smce2 in the benchmarks sooner, your best best is going to be to build the PR yourself

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
