### ISSUE TITLE
Automatically create runner_user if non-existent 

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1337]
We already assume we have sudo rights, so let's just check for runner_user and create if it doesn't exist. There was chatter about this affecting the vagrant setup as well, perhaps fixing this in the TFB core toolset would fix any issues that might be there too

**Comment by hamiltont** [comment]
FYI, currently the `installer.py` doesn't really care if the `chown -R runner_user:runner_user` command fails, so if you don't have that user created you would only get a brief INSTALL ERROR message and nothing more serious (e.g. the install would continue as though nothing major had happened). Given how much we depend on this user it should be a show-stopping error if it's non existent.

**Comment by msmith-techempower** [comment]
No longer relevant as `testrunner` was retired.
