### ISSUE TITLE
runner_user should check it has all needed permissions before running

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1338]
Noticed this while poking around: 

```
bash: /root/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: Permission denied

INSTALL ERROR: CalledProcessError: Command 'sudo -u tfbrunner -E -H bash -c "export TROOT=/root/FrameworkBenchmarks/frameworks/C/haywire && export IROOT=/root/FrameworkBenchmarks/installs && source $FWROOT/toolset/setup/linux/bash_functions.sh && source /root/FrameworkBenchmarks/frameworks/C/haywire/install.sh"' returned non-zero exit status 1
```

Problem is that `runner_user` must have read+execute (and in many cases, write) permission on the TFB files. However, when you use an absolute path in bash instead of a relative path, you need execute permission on *every* folder in the path you're targeting. In my case, as I'm operating out of /root here, tfbrunner doesn't have execute permission on `/root`, which doesn't even give execute permission to it's group e.g. `drwx------   8 root root 4096 Feb 23 00:46 root`.

For the time being my fix will be to not run TFB as the root user (which really only matters in the context of virtual machines and linux containers, I doubt others are experiencing this daily...), but a longer term solution may be needed

**Comment by msmith-techempower** [comment]
For the most part, I run out of a user's home directory and add the runner user to my group.

**Comment by hamiltont** [comment]
Yea that works fine, because in most cases `/home` is marked as executable for any user account. I just put TFB inside `/root`, and even following the wiki directions that won't ever work. It's a low-priority issue ;-)

**Comment by hamiltont** [comment]
@msmith-techempower found another permission issue that's more serious because it affects almost all users. This should be added to the readme ASAP, because at least for the 3 frameworks I tested, they all fail silently if this permission is not available. Perhaps this could just be added [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/7ce3abe01706b844427cfe3b4d81b937de3d6925/toolset/setup/linux/installer.py#L64) to make it automatic. 

    # User tfbrunner needs read write access to all framework folders owned by tfb
    # as many frameworks use setup.sh to compile stuff inside their framework folder
    chmod -R g+w ~/FrameworkBenchmarks/frameworks

**Comment by msmith-techempower** [comment]
It would need to be generic enough to work regardless of the location of the project
`chmod -R g+w ${FWROOT}/frameworks`
Also, it should be noted (if not already explicitly done in the script) that runner_user also needs group-write access on `$IROOT` and `results`.

**Comment by hamiltont** [comment]
> Also, it should be noted (if not already explicitly done in the script) that runner_user also needs group-write access on $IROOT and results.

Great points. Currently TFB chown's IROOT to runner_user. I think it's better to leave everything owned by the original user, and have the script ensure that IROOT, results, and frameworks are all group-writable

**Comment by hamiltont** [comment]
> needs group-write access on results

Ha ha, suddenly I understand why it took so long for me to debug this - I wasn't getting the log output!!

**Comment by msmith-techempower** [comment]
I THINK this is pretty much resolved now.
