### ISSUE TITLE
Broken link in README to `frameworks/Go/go/setup.py`

### ISSUE THREAD

**Issue by bamos** [TechEmpower/FrameworkBenchmarks#1341]
Found with https://github.com/bamos/girl

**Comment by LadyMozzarella** [comment]
[Here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/README.md#testing-on-both-windows-and-linux) is where the broken link is. The link is 'the script for Go'

**Comment by LadyMozzarella** [comment]
Closing. No longer in readme :)
