### ISSUE TITLE
Disable turbo boost on benchmarking machines

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1342]
See [google groups thread](https://groups.google.com/forum/#!topic/framework-benchmarks/y9dsB6BCLgo) and [the docs](https://www.kernel.org/doc/Documentation/cpu-freq/boost.txt). 

CC @richdougherty

**Comment by richdougherty** [comment]
Awesome thanks.

**Comment by hamiltont** [comment]
Just tried to address this, and I couldn't find the referenced boost file, even on an Ubuntu 14.04 machine that I'm positive has the turbo boost feature. Any hints?

**Comment by methane** [comment]
Is this post help you?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/processor_state_control.html#d0e28869

**Comment by zloster** [comment]
Particularly these two lines in the docs above:
* When you need the low processor speed variability that the P1 P-state provides, execute the following command to disable Turbo Boost.
`[ec2-user ~]$ sudo sh -c "echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo"`
* When your workload is finished, you can re-enable Turbo Boost with the following command.
`[ec2-user ~]$ sudo sh -c "echo 0 > /sys/devices/system/cpu/intel_pstate/no_turbo"`

**Comment by hamiltont** [comment]
Awesome - thanks. I haven't fully investigated this yet. If someone wants to send in a PR go ahead, otherwise I'll get back to this when I find some time

**Comment by richdougherty** [comment]
Thanks for looking at this. I've only disabled Turbo Boost on a dedicated server. We weren't able to disable tests through the OS so we had to disable it in the BIOS. I don't have any experience with disabling Turbo Boost on EC2 unfortunately.

**Comment by msmith-techempower** [comment]
No clue about this; kicking down the road.

**Comment by msmith-techempower** [comment]
Seems to be a BIOS issue which we cannot fully control; closing for now.
