### ISSUE TITLE
Remove Gemini's WEB-INF lib folder

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1352]
And download using maven

See [discussion](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1344#issuecomment-75894054)

As gemini is a TE project, I'd push to make it a perfect implementation in the TFB project, and to me a perfect implementation downloads the necessary files. 

Naturally this is a low priority, just creating the issue so it's not forgotten

**Comment by zloster** [comment]
@nbrady-techempower I think this old issue could be closed. Last time I've checked the Gemini project was migrated to [using Ivy](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/gemini/ivy.xml). The [lib](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/gemini/Docroot/WEB-INF/lib) folder contains only the Gemini JARs.

**Comment by nbrady-techempower** [comment]
@zloster Indeed, thanks!

**Comment by msmith-techempower** [comment]
@nbrady-techempower @zloster We cannot remove Gemini's `WEB-INF` folder **yet** because `Gemini` is not open source, so we need to include **at least** our jars.
