### ISSUE TITLE
Unify Ur/Web naming convention in preview results

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#1360]
I already mentioned this one on IRC, but for completeness I'll repeat it here.

In the Round 10 preview results, Ur/Web tests show up as "ur/web", "urweb-mysql", and "urweb-postgres".  I'd prefer the more uniform "urweb", "urweb-mysql", and "urweb-postgres".  I *thought* I'd changed benchmark_config months back to have that effect, but I may have gotten it wrong.  The old names might also be in some cache maintained by TechEmpower.

Is it possible to get the name switch implemented for the final Round 10 results?  Thanks!

**Comment by LadyMozzarella** [comment]
I could be wrong, but I believe you can specify what name you'd like to show up in the results by adding 'display_name' to the test configurations. I'm not seeing it in the benchmark_config file for Ur/Web on master. Looks like the issue is only with the default test, which I think is relying on some other way of stringing together a name because it knows that "default" isn't what you want.

From the readme:

> display_name (metadata): How to render this test permutation's name on the results web site. Some permutation names can be really long, so the display_name is provided in order to provide something more succinct.

Example in readme:

    {
      "framework": "compojure",
      "tests": [{
        "default": {
          "setup_file": "setup",
          "json_url": "/compojure/json",
          "db_url": "/compojure/db/1",
          "query_url": "/compojure/db/",
          "fortune_url": "/compojure/fortune-hiccup",
          "plaintext_url": "/compojure/plaintext",
          "port": 8080,
          "approach": "Realistic",
          "classification": "Micro",
          "database": "MySQL",
          "framework": "compojure",
          "language": "Clojure",
          "orm": "Micro",
          "platform": "Servlet",
          "webserver": "Resin",
          "os": "Linux",
          "database_os": "Linux",
          "display_name": "compojure",
          "notes": "",
          "versus": "servlet"
        },
        "raw": {
          "setup_file": "setup",
          "db_url": "/compojure/dbraw/1",
          "query_url": "/compojure/dbraw/",
          "port": 8080,
          "approach": "Realistic",
          "classification": "Micro",
          "database": "MySQL",
          "framework": "compojure",
          "language": "Clojure",
          "orm": "Raw",
          "platform": "Servlet",
          "webserver": "Resin",
          "os": "Linux",
          "database_os": "Linux",
          "display_name": "compojure-raw",
          "notes": "",
          "versus": "servlet"
        }
      }]
    }

**Comment by achlipala** [comment]
Thanks, that looks promising!  I've created a PR.
