### ISSUE TITLE
Retroactively tag rounds 8 and 9

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1365]
Given the round date, we could likely pinpoint the commit used for R8 and R9 to within a few commits forward/backwards. I think that having this tagged would be valuable so people can quickly switch between them

**Comment by hamiltont** [comment]
Ok, looking at the [repo for R9](https://github.com/TechEmpower/TFB-Round-9), I compared the dates that the "final" rounds were run with the dates that commits were placed onto the master branch

Here is what I have found, using `git log --pretty=format:"%ci,%h,%aN %s" master` for nice output

__Folder `ec2/linux/final/20140414145806`, dated `2014-04-14`__
2014-04-18 10:37:29 +0100,5a27e8f,Christopher Jackson Added Gorail to Benchmark!
2014-04-12 23:00:55 +0400,d1705fc,Nikita Tsukanov Updated evhttp-sharp

__Folder `i7/linux/final/20140318080616`, dated `2014-03-18`__
__Folder `peak/linux/final/20140318081122`, dated `2014-03-18`__
2014-03-19 13:07:11 +0100,4c67f02,Gjero Krsteski remove unused things
2014-03-18 13:14:29 +0200,45c1154,Martin Tzvetanov Grigorov [wicket] - use plain JDBC, drop Hibernate

__Folder `peak/windows/final/20140307133328`, dated `2014-03-07`__
2014-03-09 13:53:52 -0700,f590f79,Mark Kolich Up'ing Curcao toolkit version to 2.0-M11
2014-03-06 14:20:46 +0100,fab6e22,Raphael Andre Bauer push to Ninja 3.1.1

It's clear that multiple different commits on master were used for the "final" versions of R9, so my next step was to identify how different they were. [Here's the history log](https://gist.github.com/hamiltont/611280ee96852446de08), which doesn't look too bad until you see that there are a lot of merge commits in there. [Here's the full log](https://gist.github.com/hamiltont/5c9d0e4c88e474721b73), and it's got over 500 individual commits added to master between Mar 6 and Apr 18. 

To create the logs, I used `git log --pretty=format:"%ci,%h,%aN %s" fab6e22..5a27e8f` and `git shortlog fab6e22..5a27e8f` respectively. 

The 500 commits happening is terrifying, but a bit of further digging shows that there were only ~10 individual commits (contained within a single merge) between `2014-03-07` and `2014-03-18`, which to me tells the story that the R9 final happened with no problems on peak and i7, and getting to ec2 was troublesome and took from `2014-03-18` until `2014-04-14`, during which the repo continued progress as normal. 

Given this last paragraph, I'd move to have commit `2014-03-19 13:07:11 +0100,4c67f02,Gjero Krsteski remove unused things` tagged as the official R9 commit, as it's the correct "final" commit for i7/linux and peak/linux, and it's one beyond the correct final commit for peak/windows. Its completely incorrect for ec2/linux, so perhaps it's worth having a R9-ec2 tag as well.

**Comment by LadyMozzarella** [comment]
Were we able to narrow down the Round 8 tag? Based on simply comparing dates on the Round 8 repo with the [commits around that time](https://github.com/TechEmpower/FrameworkBenchmarks/commits/e90429ffc8113365f36421a888f3aa69b78c9d26), I believe that commit 40489856a0480c85227993d91de7d66e9224f8b4 could be tagged as R8.

Date range between Round-8 and Round-8-Final on ec2: Dec. 9, 2013 -  Dec. 13, 2013
Date range between Round-8 and Round-8-Final on i7: Dec. 8, 2013 - Dec. 14, 2013

I support 4c67f021cd4968416c3d26e628110b47adcd1d00 as Round 9 official commit. Here are my tag/release recommendations based on my quick review:

* R8: 40489856a0480c85227993d91de7d66e9224f8b4
* R9: 4c67f021cd4968416c3d26e628110b47adcd1d00
* R9-ec2: 4eeb8039e62caa8516e092e7e49663cefbcebbc5 - This appears to be the [commit prior to gorail](https://github.com/TechEmpower/FrameworkBenchmarks/commits/5a27e8f0d07f50cdf7f8c83b3b4b1de03b6c462a). It doesn't look like gorail was a part of Round 9.

**Comment by hamiltont** [comment]
This looks correct to me! We should probably go ahead and add the `round10` tag to the tip of the current `round10

**Comment by hamiltont** [comment]
PS - would it be too much trouble to also do a `git checkout` + `git clean` + `tar` and upload releases to [here](https://github.com/TechEmpower/FrameworkBenchmarks/releases) for R8,9,10?

**Comment by LadyMozzarella** [comment]
I would definitely like to have them up on the releases. So, fair request. I can add this to my to-do list. :)
