### ISSUE TITLE
Bring lwan source code into TFB repository

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1372]
Instead of just [pulling in a commit](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/lwan/install.sh) from the lwan repository, the TFB team would prefer to have the relevant source code stored inside our repository, especially as it's a [fairly small amount](https://github.com/lpereira/lwan/tree/master/techempower). The install.sh should download the lwan framework, and then compile+link the small bit of code in our repository against that. 

AFAIK every other framework uses this approach currently, if that's incorrect please comment

Ping @lpereira @bhauer @msmith-techempower

**Comment by lpereira** [comment]
No objections. I'll do this as soon as Round 10 is out.

**Comment by msmith-techempower** [comment]
Bump.

Where do we stand on this?

**Comment by knewmanTE** [comment]
@lpereira any update on this?

**Comment by nbrady-techempower** [comment]
Closing in favor of #2554 and #2706
