### ISSUE TITLE
Unify Cassandra installation methods

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#1379]
Cassandra is currently installed in a different manner for CI and benchmark setups and running both on a particular machine may cause problems.
The benchmark mode (`database.sh`) is the preferred installation method and it should be used also for CI (`run-ci.py`).

**Comment by hamiltont** [comment]
As the initial author if runci, I intentionally chose to have two code paths, and that was after a week or so of trying to make database.sh fit. Here's why

Using CI to refer to travis here :

- CI cannot support full configuration replacement, they depend on specialized config files. Try to swap a config on there and the DB'es more than likely won't turn on. 
- CI often requires specialized preparation e.g. downgrade from an existing DB version before being able to upgrade to the version we actually want
- CI environment changes much more frequently and Ubuntu LTS, especially the database config. They actively work on bringing the latest versions online as soon as possible, whereas the target Ubuntu LTS is much more stable
- debugging and programming inside the tracks environment is an order of magnitude harder than in a VM or local setup. I can easily merge a change to database.sh and not worry, whereas a change to runci requires a ton of attention 

I considered having if statements inside database.sh, but 1) there would be a lot of them and 2) it was honestly wickedly hard to get the databases to work properly, so having a second file insulates runci from most PRs as i mentioned above. Normally, if a database setup is actually broken inside travis you will know right away as everything starts turning red. That obviously won't be the case for cass as you're the only one using it ATM, but after weighing the pros and con's of duplicating the db setup I think two code paths is the right choice

**Comment by marko-asplund** [comment]
@hamiltont Thanks for providing background info on this. Based on this, I'll close the issue.

**Comment by hamiltont** [comment]
No problem! FWIW, I *do* think I should have `run-ci.py` exlicitely test for the key `TRAVIS=1` and refuse to run without it. Currently it does a baby version of this [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/run-ci.py#L500), but it should be more strongly worded to clarify to everyone that run-ci isn't intended for their usage
