### ISSUE TITLE
Set Cassandra listen_address and rpc_address param values during installation

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#1382]
Cassandra clients fails to connect to the server unless `listen_address` and `rpc_address` are properly set to the database host IP address. This should happen in ´cassandra/conf/cassandra.yaml` during database installation.

**Comment by marko-asplund** [comment]
@hamiltont While debugging Cassandra related problems with @msmith-techempower we bumped into this issue. I guess there's currently no environment variable set when database.sh is run for checking the DB host IP address, right? The DB host IP address would be needed for Cassandra installation. How about placing this (and possibly other infra params) in a config file that could be transferred over sftp to the DB host? The installation script could then source this file.

**Comment by hamiltont** [comment]
Cool. There's a few ways to address this, some questions first. 

1 - Can we utilize environment variables inside cassandra's yaml config, or does it only do plain text? 
2 - Why doesn't always using `127.0.0.1` work? Everything is on one network, so the server should be safe to bind to that and as long as the client knows the proper IP address of `10.something.whatever` everything should work. Is there something I'm missing? We don't need any of the fancy "find the clusters" stuff, and having one static value in the config that works for all flat networks is a better solution than either sed-ing the file or using an environment variable.

**Comment by hamiltont** [comment]
> I guess there's currently no environment variable set when database.sh is run for checking the DB host IP address, right?

Correct. There used to be, but it was a bit hacky and frankly all the databases worked with 127.0.0.1 bind points anyways, so we simplified everything at some point IIRC

**Comment by marko-asplund** [comment]
1 - I don't think variables are supported inside cassandra.yaml. the variable should also be set to a valid value, if variables were supported.
2 - 127.0.0.1 usually refers to the loopback interface and you can't connect to that interface outside the machine itself, so AFAIK this would work. The other servers probably bind to _all_ interfaces which is why you can connect to them from the same machine using 127.0.0.1. Binding to all interfaces doesn't work with Cassandra (see https://wiki.apache.org/cassandra/FAQ#cant_listen_on_ip_any).

**Comment by hamiltont** [comment]
1 - gotcha
2 - oops, you're right. How's this: remove the `listen_address` line and rely on the default address? 

If my suggestion in (2) above is no use, here's how to make the necessary change easily - update [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/installer.py#L33) to read as so: 

    p.communicate("export TFB_DBHOST=%s\n" % self.benchmarker.database_host)
    p.communicate(remote_script)

Then update database.sh to utilize TFB_DBHOST. I don't see benefit to write/source another file over just doing this one export inline - do you?

**Comment by hamiltont** [comment]
FYI, that there's a reason I'm against sending these types of environment variables to the client/database that I haven't mentioned here - it removes the ability for someone to utilize their `/etc/hosts` file for contacting the remote servers. Currently I can say `--database-host database` if I'm updated my hosts file, whereas doing the above variable-based solution would remove that ability. There are a few other issues that we think may be addressed in the long term by using hosts entries, so I'm hoping to go with a solution like (2) above that doesn't break the hosts functionality

**Comment by marko-asplund** [comment]
According to @msmith-techempower the DB host may have multiple network interfaces, so it's not guaranteed that Cassandra will automatically bind to the correct one.

Your suggestion to set TFB_DBHOST should work, but would break the hosts functionality.

The Vagrant-based development environment setup configures the name "TFB-database" in /etc/hosts. Is there a similar name or alias in the hosts file also in other environments that is 1) guaranteed to be present in all environments and 2) map to the IP address of the DB that the tests will connect to?

If there isn't one, could an alias like `db.fwbm.local` (or similar) be added?
I could then use this name in Cassandra configuration, so changes in /etc/hosts should take effect after restarting the Cassandra server.

**Comment by hamiltont** [comment]
Ah ok, didn't realize the official setup has multiple nics. Just use the environment variable as I [recommend above](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1382#issuecomment-77664022) and don't worry about support for `/etc/hosts`, I can fix that up myself if we decide it's broadly enough used to support.

**Comment by marko-asplund** [comment]
@hamiltont ok, thanks for the suggestions.
I just submitted PR #1383 that should fix the Cassandra installation issue.
It would be great if you could review this.

**Comment by nbrady-techempower** [comment]
I'm going to close this for now, as the way we install databases is about to change. I think that change also excludes an cassandra installation. So we can approach this as a new database when that merge happens.
