### ISSUE TITLE
run-ci: "Got errors when using git to detect your changes"

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#1384]
CI build build change verification check fails with errors:
```
...
INFO:run-ci:Found 2 usable tests (2 valid for linux, 2 valid for linux and {mysql,postgres,mongodb,cassandra,sqlite,none}) in directory '$FWR
OOT/frameworks/Java/servlet3-cass'
INFO:run-ci:Using tests [u'servlet3-cass', u'servlet3-cass-raw'] to verify directory $FWROOT/frameworks/Java/servlet3-cass
fatal: ambiguous argument '845f9987f770...f860e5ba2044': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR:run-ci:Got errors when using git to detect your changes, assuming that we must run this verification!
ERROR:run-ci:Error was:
ERROR:run-ci:Did you rebase a branch? If so, you can safely disregard this error, it's a Travis limitation
INFO:run-ci:Running mode prereq with commmand toolset/run-tests.py --install server --install-only --test '' --verbose
...
```

for details see: https://travis-ci.org/marko-asplund/FrameworkBenchmarks/jobs/53495677

**Comment by hamiltont** [comment]
This probably has something to do with [this change](https://github.com/travis-ci/travis-core/pull/383). I can confirm that the commits described in `TRAVIS_COMMIT_RANGE` (specifically `845f9987f770...f860e5ba2044` in your case) are not actually present in the cloned repository. 

While this is broken it will reduce our ability to short-circuit some of the builds inside travis. The short-circuit detections that don't use this environment variable set by Travis-CI will continue to work as expected. 

Until I can patch up run-ci.py the best bet is to use your own travis queue as much as possible so you can cancel unnecessary jobs

**Comment by msmith-techempower** [comment]
This seems resolved.
