### ISSUE TITLE
Move all system-wide installations inside IROOT

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1387]
The end-goal here is to totally avoid system-wide installs for non-essential software, and place everything we can inside `IROOT`, such that deleting `IROOT` means you have a "fresh" machine. This also means that we don't have to worry about what software is already on the machines when TFB runs, because installing our own local version avoids nasty things like dependency conflicts (and as a bonus, takes us one step closer to support for multiple linux flavors). 

At the moment this issue is slowly being solved software by software. Some of the software installer files are still doing system-wide, and some of them have been transitioned to using local installations inside IROOT.

We cannot control the start state of the Travis-CI machines, so we've seen a ton of issues where a software install file is trying to do a system-wide installation and running into problems because travis already has that software installed system wide. The correct fix, from the point of view of this project, is to replace this line with something that does a local installation inside IROOT.

One tricky component of this process is that numerous toolsets utilize `$HOME` e.g. `$HOME/.rvm` - if possible it would be great to overwrite this caching location to also be inside IROOT for the same reasons as above

**Comment by msmith-techempower** [comment]
Kicking this on down the road.

**Comment by msmith-techempower** [comment]
We have made a lot of progress towards this, but I'm taking the milestone off since it will almost assuredly never fully be completed.

**Comment by nbrady-techempower** [comment]
Moving this to the ongoing column of the roadmap https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
