### ISSUE TITLE
Ruby Rack Thin & Unicorn - Verification Failed

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1390]
After running Round 10, Preview ~~2~~ ~~3~~ 4 this test failed and appears to be passing locally:

* [rack-thin](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/rack-thin (single query, multiple queries, and data updates)): 

  ```bash
--------------------------------------------------------------------------------
  VERIFYING QUERY
--------------------------------------------------------------------------------
Accessing URL http://10.0.3.2:8080/queries?queries=2 
Response: 
"HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Connection: keep-alive
Content-Length: 21
Server: thin 1.6.2 codename Doc Brown
```

* [rack-unicorn](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-09-peak-preview4/latest/logs/rack-unicorn/out.txt#L65)

  ```bash
--------------------------------------------------------------------------------
  VERIFYING QUERY
--------------------------------------------------------------------------------
Accessing URL http://10.0.3.2:8080/queries?queries=2 
Response: 
"HTTP/1.1 500 Internal Server Error
Server: nginx/1.4.1
Date: Tue, 10 Mar 2015 18:22:43 GMT
Transfer-Encoding: chunked
Connection: keep-alive
```

**Comment by LadyMozzarella** [comment]
Closing. [They're passing locally](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/57577548#L6378) (rbx tests always fail on Travis-CI), will reopen or open a new issue if we see the same problems in Round 11.

**Comment by msmith-techempower** [comment]
This is still a problem - we did not even get a capture of the data in round 10 for rack-thin. We got zero responses and 100% errors.

**Comment by LadyMozzarella** [comment]
Maybe with #1505 we can better debug this. This one is tricky because it's passing in Travis-CI and also locally. It only appears to fail when the benchmarks are actually run on the benchmark hardware, so it's much more difficult to find the issue.

**Comment by LadyMozzarella** [comment]
Especially since we won't be running it again until Round 11 previews.
