### ISSUE TITLE
Ruby ngx_mruby - Verification Failed

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1392]
After running Round 10, Preview ~~2~~ 3 this test failed and appears to be passing locally:

* [ngx_mruby](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/ngx_mruby) (json serialization, single query, multiple queries, and plaintext): `setup.sh: line 6: /home/techempower/FrameworkBenchmarks/installs/nginx_mruby/sbin/nginx: No such file or directory`

**Comment by kbrock** [comment]
I looked at [ngx_mruby](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-18-peak-preview7/latest/logs/ngx_mruby/out.txt) and it looks like it is now working. Is this good, or should I dig deeper into this?

thanks

**Comment by LadyMozzarella** [comment]
I think it's good. Thanks. Closing issue.

**Comment by kbrock** [comment]
thanks for diving into these issues @LadyMozzarella
