### ISSUE TITLE
Python's Bottle, Flask, Wsgi, and Uwsgi Nginx Uwsgi - Verification Failed

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1396]
After running Round 10, Preview ~~2~~ 3 these test failed and appears to be passing locally (looks like they're all the same error and probably related to nginx):

* [bottle-nginx-uwsgi](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/bottle-nginx-uwsgi): `ize is greater than the system max net.core.somaxconn (128).`
* [flask-nginx-uwsgi](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/flask-nginx-uwsgi): `Listen queue size is greater than the system max net.core.somaxconn (128).`
* [wsgi-nginx-uwsgi](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/wsgi-nginx-uwsgi): `Listen queue size is greater than the system max net.core.somaxconn (128).`
* [uwsgi-nginx-uwsgi](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/uwsgi-nginx-uwsgi): `Listen queue size is greater than the system max net.core.somaxconn (128).`

**Comment by hamiltont** [comment]
#1408 could help address this type of problem in the future. This setting should *not* have been 128
