### ISSUE TITLE
Java's Dropwizard Mongodb - Verification Failed

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1398]
After running Round 10, Preview 3 this [test failed](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-06-peak-preview3/latest/logs/dropwizard-mongodb/out.txt) and appears to be passing locally:

* dropwizard-mongodb (single query, multiple query): 

  ```bash
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /db. Reason:
<pre>    There was an error processing your request. It has been logged (ID aff8e8e6db08b360).
</pre></p><br/> 
```

**Comment by hamiltont** [comment]
Perhaps because of #1487 ?

**Comment by LadyMozzarella** [comment]
Probably since it passes locally. Closing. We can see what happens when we start doing fixes in Round 11.
