### ISSUE TITLE
Wicket preview runs for round 10 fails due to configuration issue

### ISSUE THREAD

**Issue by martin-g** [TechEmpower/FrameworkBenchmarks#1403]
All 3 preview runs for Java/wicket framework for round 10 failed.
At https://groups.google.com/d/msg/framework-benchmarks/yyK8VclJ6Zc/fRPKc-Aq7i4J @msmith-techempower provided logs showing that there is an error with the connection to Cassandra.
Wicket uses only MySQL for its tests so Cassandra is not really needed: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/wicket/benchmark_config
It looks like there is an issue with the configuration of the tests runner.

**Comment by msmith-techempower** [comment]
The error in question is from the [test log](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-06-peak-preview3/2015-03-06.txt):

```
--------------------------------------------------------------------------------
  Running Test: wicket
--------------------------------------------------------------------------------

database connection test results:
mysql: is GO!
mongodb: is GO!
redis: is GO!
postgresql: is GO!
cassandra: is _NO_ GO!: ERROR: [Errno 111] Connection refused
INFO:root:Running setup module start (cwd=/home/techempower/FrameworkBenchmarks/frameworks/Java/wicket)
```

After testing, it seems this runs locally just fine. After the next preview run (started last night) finishes, I will do some direct testing on the peak hardware to see if I can find more information.

The `cassandra: is _NO_ GO!:` bit is the part that seems like an error to me, but after looking through the code, it seems this was added as part of starting the test (we check if `wicket` requires a database, and conditionally restart each of the db services and print out whether each started).

**Comment by hamiltont** [comment]
FYI, the error message about cassandra is [just printed](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/benchmarker.py#L550) - it doesn't stop wicket from running. So it's a red herring in this case - something *is* wrong with cassandra here, but that's not going to affect wicket's performance, so something else is happening

**Comment by martin-g** [comment]
It seems many frameworks still fail because of this problem: https://www.techempower.com/benchmarks/previews/round11/#section=data-r11&hw=peak&test=fortune

**Comment by dashorst** [comment]
I've created a pull request that makes the Wicket DB test not fail silently, but rather return a proper error code (and message). See #1703

**Comment by martin-g** [comment]
Are Wicket tests running fine now in Travis?
They were failing for round 11 but this ticket has been closed 24 days ago, which I think is after publishing of the results of round 11.

**Comment by msmith-techempower** [comment]
[Here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/100877306) is a very recent `wicket` run on Travis-CI that appears to be passing.

**Comment by martin-g** [comment]
Awesome!
Thank you!

**Comment by dashorst** [comment]
:+1:

**Comment by martin-g** [comment]
Not sure what is wrong with the whole infrastructure but again there are no results for most of the tests for Wicket in round 12 :-/
https://www.techempower.com/benchmarks/#section=data-r12

**Comment by bhauer** [comment]
Let's reopen this one.

**Comment by martin-g** [comment]
The logs don't say much:
https://github.com/TechEmpower/TFB-Round-12/blob/4fa436eac69341b31dcf56de73bfea904eb93f0f/peak/linux/2016-02-22-final/latest/logs/wicket/out.txt
https://github.com/TechEmpower/TFB-Round-12/blob/4fa436eac69341b31dcf56de73bfea904eb93f0f/peak/linux/2016-02-22-final/latest/logs/wicket/err.txt

**Comment by nbrady-techempower** [comment]
@martin-g as you've already pointed out, we're tracking this in #2074. Hopefully resolved.
