### ISSUE TITLE
Ruby: Add Lotus and Cuba

### ISSUE THREAD

**Issue by Vikaton** [TechEmpower/FrameworkBenchmarks#1412]
You should consider adding Lotus(http://lotusrb.org)- pretty fast MVC framework- and Cuba(cuba.is).

This frameworks for Ruby are surprisingly fast when Running MARI and puma webserver.

God knows how they are like with JRuby

Also, Which web servers do you guys use for your Ruby frameworks tests?

**Comment by hamiltont** [comment]
I think many of the [ruby frameworks](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Ruby) provide configurations for multiple webservers. We test all configurations provided, so if you want to test two different webservers with the same codebase you just put a second configuration into the benchmark_config file, [like so](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Ruby/sinatra/benchmark_config#L27)

**Comment by Ap0ph1s** [comment]
Cool, also check this out between Lotus vs Cuba: https://gist.github.com/Ap0ph1s/ba0e350e5f50d54806b5

If you don't know what Cuba was/is: Its one of the fastest Ruby frameworks, just behind rack-JRuby.

**Comment by jodosha** [comment]
:+1:

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
