### ISSUE TITLE
Run multiple benchmarkers for each framework test

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1414]
This is a future-looking commit, something that would likely only happen after we setup a continuous solution. 

Anyways, there are a ton of benchmarkers available. At the moment we utilize a single one at a time. It might be valuable to do more than that

http://www.joedog.org/siege-home/
https://httpd.apache.org/docs/2.2/programs/ab.html
https://github.com/giltene/wrk2
https://github.com/wg/wrk
..etc

**Comment by nbrady-techempower** [comment]
Gonna put this on the toolset roadmap since we are pretty much there with continuous.
