### ISSUE TITLE
Use GitHub Wiki feature 

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1415]
I think a wiki with a well-done TOC is much better than a monolithic readme. Lots of things could go on here - stuff like 
 - “basic concepts” (e.g. there are three servers, this is what they do)
 - “Intro to codebase” (here’s the major files)
 - “software installation process” (setup.sh and install.sh usage in detail)
 - others?

**Comment by LadyMozzarella** [comment]
:+1: 

* "Project Overview"
* "What is TechEmpower?"
* "Quick Start Guide" (set up vagrant, run a simple test...)
* "Add a Framework"
* "Framework Requirements"
* "Tests" (detailed test explanation for the tests that the frameworks need to implement)
* "Testing" (Travis CI, How to test your newly implemented framework)
* "Community" (How to contact/get help, potentially preferred git workflow practices)
* "FAQ"
* "Framework/Language Experts" (who are the experts that can assist with each framework/language)

I think there's a lot of potential here and it would be much easier to use as a reference for people working on the project. There's also a lot of information that's on techempower.com/benchmarks that doesn't necessarily need to be and could be moved to the wiki here. I think that it would be nice to have the developer need-to-know information centralized in the wiki, leaving the results site with only needing to cover the significance tests, how to interpret the results, and a link back to github to contribute. 

[Github's Projects with Great Wikis Showcase](https://github.com/showcases/projects-with-great-wikis)

**Comment by hamiltont** [comment]
ping @bhauer for input

**Comment by hamiltont** [comment]
Seems like we're on the same page, but to be clear I should say my goal here is a wiki for information about the TFB project (setup, usage, interpretation, etc) and not information about who maintains which test, etc. Basically, we should keep a sparse global Readme (that cna hopefully link to the wiki a lot), and the READMEs for each language detailing language-specific stuff (e.g. Perl's readme covers how to setup perl-specific virtual environments)

**Comment by hamiltont** [comment]
Added a [documentation](https://github.com/TechEmpower/FrameworkBenchmarks/labels/documentation) tag for things that might be address-able in a wiki format

**Comment by msmith-techempower** [comment]
Agreed with essentially all of this. We have tried to keep the `README.md` up to date with installation instructions, but it is a HUGE scroller now.

**Comment by hamiltont** [comment]
Cool, I'll tag it R11

**Comment by hamiltont** [comment]
Hmm, as @msmith-techempower mentioned in IRC, even though the wiki is technically a git project that can be cloned, it appears that github doesn't support PR's against the wiki repository. Various workarounds are used by other projects. See [this stackoverflow posting](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). Kind of a shame, I'd really like to use the PR features for documentation and wiki contributions. 

An alternative is to utilize an external service like readthedocs, where we would just add a `docs` folder to our project with markdown files, so that community members could send in pull requests for documentation. THoughts/suggestions?

**Comment by GMLudo** [comment]
@hamiltont +1 for `docs` approach.

**Comment by LadyMozzarella** [comment]
I guess I like both options separately just fine. 

For Github's wiki it's nice that you an restrict the editing to people that are official collaborators, but that does limit it quite a bit with all other contributors having to just open issues to get things resolved.

readthedocs does sound like it's more straight forward and would be better to allow the community to update (and allow for review of what's going in/being taken out). My only drawback with this one is that I liked the idea of being able to keep the project and docs separate, but related. 

Would it be strange to start an entirely new TE repo only for documentation, which would use readthedocs, and take pull requests? It looks like that's what [mongodb](https://github.com/mongodb/docs) has done for their docs.

**Comment by LadyMozzarella** [comment]
Okay. I have been playing with readthedocs today (http://exampleframeworkbenchmarksdocs.readthedocs.org/) and I think it will work out pretty well. So, I think it would be nice to just make a few decisions and go with them.

1. Should we create a new repo just for the docs, or create a separate directory inside of the existing project?
2. Are we okay with using readthedocs?

@msmith-techempower, @bhauer - Do you have preferences?

**Comment by hamiltont** [comment]
Chiming in - I'm fine with either a docs folder or a separate directory. I'm fine with using RTD, although I haven't seen/heard of any alternatives besides sphinx

**Comment by LadyMozzarella** [comment]
Okay. I'm closing this issue. We now have a live readthedocs site at http://tfb-documentation.readthedocs.org/ and a new repo for documentation at https://github.com/TechEmpower/TFB-Documentation. 

If we'd like to revisit using readthedocs later, we can. For now I'm going to work on converting documentation issues from this repo to the other one. Also, the new docs can definitely use some TLC. I'm working on going through them, but it's time consuming. If anyone sees anything that can be improved/ needs attention please submit an issue (or pull request!) at the documentation repo. 

I will submit a pull request removing unnecessary readme files once I'm sure that the documentation has made it in.
