### ISSUE TITLE
Javascript: Add Koa

### ISSUE THREAD

**Issue by ebramanti-techempower** [TechEmpower/FrameworkBenchmarks#1425]
Koa.js is a smaller, more expressive Node framework from the team who made Express. Koa uses generators to avoid Node's callback hell and make error-handling much easier. I'm curious about how this will affect performance compared to Express.js.

Here's some extremely basic differences between Koa & Express, with an extremely small performance comparison included in the MD: https://github.com/koajs/koa/blob/master/docs/koa-vs-express.md

**Comment by ebramanti-techempower** [comment]
I've completed the test server for this framework. However, I need to do some more work before PR. Koa required a bump of Node to a newer version, and this is creating some problems for some of the other Node frameworks (particularly ones that use SQL). I'm taking a look into it, and you can check out my progress [here](https://github.com/ebramanti-techempower/FrameworkBenchmarks/tree/koa).

**Comment by hamiltont** [comment]
@ebramanti-techempower FWIW, I *think* the best thing here would be if you could use something like `nvm` to enable each framework to choose the nodejs version it uses. See #995

**Comment by ebramanti-techempower** [comment]
@hamiltont I can work on this, but should we not be updating nodejs test to latest version of Node anyways? The optimizations/bug fixes introduced in Node over the past two versions should be working with the current Node framework tests. 

Just wondering, because I know using `nvm` will save me a ton of time but that shouldn't stop me from making our current tests compatible with the latest version of Node.

**Comment by hamiltont** [comment]
Updating nodejs is a great idea! If possible, let's do both - update nodejs to the latest, and use nvm to isolate the environment of each nodejs-based framework

**Comment by ebramanti-techempower** [comment]
@hamiltont So I'm working on setting up `nvm`, but every time I try to source the necessary .sh file I'm getting weird errors. I'm not sure whether it has to do with our own scripts, or `nvm`. However, since I'm getting error 2, I'm assuming it's something related to `nvm`.

What's weird is the command works in `install.sh` for installing the necessary binary, but when I try to source `nvm.sh` in `setup.sh` it completely does not work. Here is my error output for reference:

    INFO:root:Running setup module start (cwd=/home/vagrant/FrameworkBenchmarks/frameworks/JavaScript/nodejs)
    INFO:root:To run nodejs manually, copy/paste this:
          export FWROOT=/home/vagrant/FrameworkBenchmarks && \
          export TROOT=/home/vagrant/FrameworkBenchmarks/frameworks/JavaScript/nodejs && \
          export IROOT=/home/vagrant/FrameworkBenchmarks/installs && \
          export DBHOST=127.0.0.1 && \
          export MAX_THREADS=8 && \
          cd /home/vagrant/FrameworkBenchmarks/frameworks/JavaScript/nodejs && \
          sudo -u testrunner -E -H stdbuf -o0 -e0 bash -ex setup.sh
    Setup nodejs: + sed -i 's|localhost|127.0.0.1|g' hello.js
    Setup nodejs: + sed -i 's|mongodb//.*/hello_world|mongodb//127.0.0.1/hello_world|g' hello.js
    Setup nodejs: + export NVM_HOME=/home/vagrant/FrameworkBenchmarks/installs/nvm
    Setup nodejs: + NVM_HOME=/home/vagrant/FrameworkBenchmarks/installs/nvm
    Setup nodejs: + source /home/vagrant/FrameworkBenchmarks/installs/nvm/nvm.sh
    Setup nodejs: ++ NVM_SCRIPT_SOURCE=NVM_HOME
    Setup nodejs: ++ nvm_has unsetopt
    Setup nodejs: ++ type unsetopt
    Setup nodejs: ++ '[' -z '' ']'
    Setup nodejs: ++ '[' -n /home/vagrant/FrameworkBenchmarks/installs/nvm/nvm.sh ']'
    Setup nodejs: ++ NVM_SCRIPT_SOURCE=/home/vagrant/FrameworkBenchmarks/installs/nvm/nvm.sh
    Setup nodejs: ++++ dirname /home/vagrant/FrameworkBenchmarks/installs/nvm/nvm.sh
    Setup nodejs: +++ cd /home/vagrant/FrameworkBenchmarks/installs/nvm
    Setup nodejs: +++ pwd
    Setup nodejs: ++ export NVM_DIR=/home/vagrant/FrameworkBenchmarks/installs/nvm
    Setup nodejs: ++ NVM_DIR=/home/vagrant/FrameworkBenchmarks/installs/nvm
    Setup nodejs: ++ unset NVM_SCRIPT_SOURCE
    Setup nodejs: ++ '[' -z '' ']'
    Setup nodejs: ++ export NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
    Setup nodejs: ++ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
    Setup nodejs: ++ '[' -z '' ']'
    Setup nodejs: ++ export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
    Setup nodejs: ++ NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
    Setup nodejs: ++ '[' -z '' ']'
    Setup nodejs: ++ export NVM_IOJS_ORG_VERSION_LISTING=https://iojs.org/dist/index.tab
    Setup nodejs: ++ NVM_IOJS_ORG_VERSION_LISTING=https://iojs.org/dist/index.tab
    Setup nodejs: +++ nvm_alias default
    nodejs: setup.sh and framework processes have terminated
    Setup nodejs: ++ VERSION=
    Setup nodejs: Setup has terminated
    Setup nodejs: setup.sh process exited with 2
    INFO:root:Executed setup.sh, returning 1

Also, my current install.sh command:

    #!/bin/bash

    fw_depends nodejs

    export NVM_HOME=${IROOT}/nvm
    source $NVM_HOME/nvm.sh
    nvm install 0.10.8

**Comment by ebramanti-techempower** [comment]
An example og how I got around the problem here, but there must be a better way...

https://github.com/ebramanti-techempower/FrameworkBenchmarks/blob/nvm-nodejs/frameworks/JavaScript/nodejs/setup.sh

**Comment by hamiltont** [comment]
Hmm, I'll try to take a crack at this tomorrow and see if I can cleanup the nodejs installation to be more consistent, that may help find/resolve these types of annoyances. 

Quick question - is `nvm` actually a thing, or is it always `npm`?

**Comment by msmith-techempower** [comment]
@ebramanti-techempower You can get a better idea of what is exactly happening by running the verification step manually:
```
      export FWROOT=/home/vagrant/FrameworkBenchmarks && \
      export TROOT=/home/vagrant/FrameworkBenchmarks/frameworks/JavaScript/nodejs && \
      export IROOT=/home/vagrant/FrameworkBenchmarks/installs && \
      export DBHOST=127.0.0.1 && \
      export MAX_THREADS=8 && \
      cd /home/vagrant/FrameworkBenchmarks/frameworks/JavaScript/nodejs && \
      sudo -u testrunner -E -H stdbuf -o0 -e0 bash -ex setup.sh
```
As-is, this will run everything, but you can break each line into a single command to run and see where it's breaking. Additionally, you can `cat setup.sh` **instead** of calling the last line and then manually execute each line (after the `#!/bin/bash` line; don't execute this) to get an even more fine-grained detail of what's happening.

Ultimately, this is what the suite is doing behind the scenes, but you should become familiar with the manual process for debugging purposes like this.

@hamiltont Do you think it is worth expanding the explanation line and exploding the `setup.sh` into it instead of explaining how we execute it? As an example, here is what I am suggesting the explanation would look like for Gemini:

```
        export FWROOT=/home/techempower/FrameworkBenchmarks && \
        export TROOT=/home/techempower/FrameworkBenchmarks/frameworks/Java/gemini && \
        export IROOT=/home/techempower/FrameworkBenchmarks/installs && \
        export DBHOST=127.0.0.1 && \
        export MAX_THREADS=8 && \
        export OUT=/home/techempower/FrameworkBenchmarks/results/ec2/latest/logs/gemini/out.txt && \
        export ERR=/home/techempower/FrameworkBenchmarks/results/ec2/latest/logs/gemini/err.txt && \
        cd /home/techempower/FrameworkBenchmarks/frameworks/Java/gemini && \
source $IROOT/java7.installed
        sed -i 's|db.ConnectString = .*/|db.ConnectString = '"$DBHOST"':3306/|g' Docroot/WEB-INF/GeminiHello.conf
        sed -i 's|root-directory=".*/FrameworkBenchmarks/frameworks/Java/gemini|root-directory="'"$TROOT"'|g' Docroot/WEB-INF/resin.xml
        sed -i 's|db.Driver.Class = .*|db.Driver.Class = com.mysql.jdbc.Driver|g' Docroot/WEB-INF/GeminiHello.conf
        sed -i 's|db.Driver.UrlPrefix = .*|db.Driver.UrlPrefix = jdbc:mysql://|g' Docroot/WEB-INF/GeminiHello.conf
        mkdir -p Docroot/WEB-INF/classes
        ant compile
        $RESIN_HOME/bin/resinctl -conf $TROOT/Docroot/WEB-INF/resin.xml start
```

This would illustrate to the user exactly what is happening in the suite AND give them a line-by-line script to follow for debugging.

**Comment by ebramanti-techempower** [comment]
@hamiltont `nvm` is node version manager. It allows us to version Node depending on the test.

@msmith-techempower I'll keep taking a crack at this. I thought for the longest time that Python was executing this shell script, which is why I might be getting this error. Clearly not though, as we switched completely to shell scripts for execution.

**Comment by msmith-techempower** [comment]
You aren't really doing anything wrong, but you should probably make `nvm` its own install upon which you can depend.

That is, move your shell script stuff out of your `install.sh` into something in `toolset/setup/linux/languages` like `rvm.sh` (used for Ruby versions).

**Comment by ebramanti-techempower** [comment]
Koa tests and `nvm` have been merged into `master`, so I'll close the issue out!
