### ISSUE TITLE
Tests on peak hardware indicate stalling

### ISSUE THREAD

**Issue by denkab** [TechEmpower/FrameworkBenchmarks#1434]
Results of preview 7 show that there may be a problem, where the machine idles smack in the middle of the test. Test was run from STARTTIME 1426802547 to ENDTIME 1426802562, but at 1426802550.043 and 1426802551.043 all CPUs went 100 idle (which would not support a theory that a GC event was responsible).

**Comment by hamiltont** [comment]
@denkab if you could link to the precise lines in the precise result files you're referencing, I think it would help everyone be on the same page

**Comment by denkab** [comment]
https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-18-peak-preview7/20150318094034/update/spring/raw is where start/end times are noted, and https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-18-peak-preview7/20150318094034/update/spring/stats is where idling is recorded at the times noted above.
