### ISSUE TITLE
New Git Workflow

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1437]
Since we're approaching the end of Round 10, I wanted to suggest that we consider a new process. I know @hamiltont had suggested it at some point to help get PRs merged.

Many pull requests in Round 10 couldn't be merged because they weren't fixing something and as a result have moved further and further away from the current master branch. 

I think there should be some kind of continuous development workflow, so that those PR can be prepared for the next Round. 

Here's an idea for a simple workflow: 
![branchingtfb](https://cloud.githubusercontent.com/assets/4926965/6785370/6a522150-d142-11e4-9b62-69f055f360c7.jpg)

In this process we would basically always be finalizing a round while we're developing the next round. I think it would help us to not have a backlog of issues and pull request and will also help us push out new rounds more consistently.

_Note: I believe it would be best to begin implementation when we begin the fixes only sprint of Round 11._

**Comment by hamiltont** [comment]
Great idea! So we could have something like a "round11" branch to continue
progress while round10 is being finalized in master, right?

**Comment by msmith-techempower** [comment]
I honestly have no idea how I've been doing it this long and never thought of having a branch for the round we're running.

**Comment by msmith-techempower** [comment]
@LadyMozzarella Great idea.

**Comment by LadyMozzarella** [comment]
The little diagram I made is just an idea. There are a bunch of different ways of accomplishing the same thing, but I think that picking the most simple workflow is best for what we're doing. Especially since new people create pull requests regularly and we need something simple for them to get started contributing quickly and easily. 

@hamiltont - Yes. We can open a Round 11 features branch and begin now, but I guess I didn't suggest it because all of the PRs are currently targeting master and it seemed easier to just wait until round 11 fixes to request that people place their target branch as round 12 features (but we can totally do it...).

**Comment by hamiltont** [comment]
Sure. One thought, and I'll use the current situation (with round 10 being the current target round, round 11 being the next target round) as an example. The proposal above would have these two branches:
- `master` intended for round 10 work
- `round11` intended for round 11 work

Would it make more sense to have master continue going forward, like this: 
 - `master` intended for round11 or anything else not fitting into round 10
 - a branch `round10` that we only pull fixes into? 

It's mainly a preference thing, but to me it seems more intuitive to have master keep going forward.

**Comment by msmith-techempower** [comment]
Yeah, I tend to agree with @hamiltont as above - it is PROBABLY easier bookkeeping on our end to have a `round10` branch and allow other branches to continue development against future rounds on `master`.

**Comment by LadyMozzarella** [comment]
That would definitely solve my issue with all of the PRs that are targeted for master and would definitely keep it easy for new contributors. While in my head I'd like to think of master as the current round and cleanest branch for reference purposes, I agree with that flow because it appears that it would be the easiest to maintain. We would just have to remind people that if they're wanting to merge something in to fix a test, the pull request would have to be against the branch for the current round of fixes (in this case round-10 branch). So, if we move ahead with this idea I believe that we can start now and start getting some new stuff merged in ... yes? :)

**Comment by hamiltont** [comment]
Agreed, we can do this immediately if desired, and I personally vote in
favor of starting immediately. You can easily create a branch round10 from
the current master, and then start merging the waiting PRs into master. If
there remain any fixes necessary for round10, merge them both into master
and into round10.

**Comment by msmith-techempower** [comment]
Fork off a `round-10` branch off of `master` now, and I'll start using with the final runs.

**Comment by LadyMozzarella** [comment]
[round-10 branch](https://github.com/TechEmpower/FrameworkBenchmarks/tree/round-10) created. :+1:
