### ISSUE TITLE
Ruby: Raptor (Phusion Passenger 5) Web Server

### ISSUE THREAD

**Issue by Vikaton** [TechEmpower/FrameworkBenchmarks#1441]
Are you guys using Raptor at all with testing the Ruby frameworks?

http://www.rubyraptor.org/ -> The graph shows a dramatic increase in speed, you should try it out if you arent already, since I didnt see it in the "Tests run with:" list.

**Comment by yunspace** [comment]
from briefly looking over the Ruby code, it seems most of the existing tests are using torqbox. If I wanted to make a new contribution should I start a new TESTDIR project? Or update the existing ones? I'm leaning towards the former.

**Comment by msmith-techempower** [comment]
If the only thing that is changing is the server, then I would suggest the latter - only add a new entry to the appropriate `benchmark_config.json`.

**Comment by nbrady-techempower** [comment]
Added to #1803. Please refer there for language/framework additions/updates.
