### ISSUE TITLE
Update Stale source_code Files

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1458]
Review all source_code files and update them to be accurate. While this information is not yet used, it would be ideal to have it updated so that we can make use of it. This file is used to count lines of code within the project. Each file listed in source_code will have its lines counted (just for reference for now).  We need to verify that all of the files exist and are valid.

**Comment by msmith-techempower** [comment]
Does anyone have any idea if this ever happened?

**Comment by nbrady-techempower** [comment]
It didn't happen completely, but I have it already in https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
