### ISSUE TITLE
Move kernel settings out of benchmarker.py and into install scripts

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1467]
[Currently we modify kernel settings from inside our python code](https://github.com/TechEmpower/FrameworkBenchmarks/blob/495f77eee4aefa00f111d3b378ba87b955d1b652/toolset/benchmark/benchmarker.py#L354). 

We need to pull OS-specific code into the proper installation files, so I'd propose to move `__setup_client`,`__setup_database`,`__setup_server` methods (which all execute code to modify the linux kernel parameters) out of the python code and into `client.sh`, `prerequisites.sh`, and `database.sh`

**Comment by GMLudo** [comment]
+1
It should be a good idea to change also:

1. /etc/security/limits.conf
2. /etc/pam.d/common-session
3. /etc/pam.d/common-session-noninteractive

To be sure that the new limitations in `limits.conf` are correctly applied for all users.
I've some config files examples for that if you're interested in.

**Comment by hamiltont** [comment]
Sure, examples are never bad. How about gist-ing them and providing a link here? 

To be honest, I need to read up on sysctl, limits.conf, and the other bits interact before I could make these changes myself. I've only ever had a hobbyist interest in my kernel settings

**Comment by hamiltont** [comment]
(that's my not-too-subtle way of saying a PR would be most welcome :-P )

**Comment by GMLudo** [comment]
Ok ;-)
I'll do a PR this week-end.

**Comment by hamiltont** [comment]
Awesome, thanks!!
