### ISSUE TITLE
Typo in scala scruffy test

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1481]
Tiny merge typo - don't have time to fix now so creating issue. See [here](https://github.com/TechEmpower/FrameworkBenchmarks/commit/b343d1637675f8876b0d1fc95efa1d16d6f01661#diff-4b23a02ebfb98bf1298a7b3d76405d2cL20) where a `{` was removed without removing a corresponding `}`. Causes this error: 

```
INFO:run-ci:[error] /home/travis/build/TechEmpower/FrameworkBenchmarks/frameworks/Scala/scruffy/src/main/scala/scruffy/examples/Test2Endpoint.scala:26: Unmatched closing brace '}' ignored here
INFO:run-ci:[error]     }
INFO:run-ci:[error]     ^
INFO:run-ci:[error] one error found
INFO:run-ci:[error] (compile:compile) Compilation failed
INFO:run-ci:[error] Total time: 50 s, completed Apr 3, 2015 3:58:58 AM
```

**Comment by LadyMozzarella** [comment]
Whoops -  :-1:  That was my bad. Will send PR tomorrow for that.

**Comment by hamiltont** [comment]
No worries, happens to everyone. Just glad that was the actual cause, thought it was the other issue I was working on :-P
