### ISSUE TITLE
Refactor vagrant bootstrap.sh

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1488]
Based on [this](http://stackoverflow.com/a/19363556/119592) we no longer need to check for firstboot. 

Also, it would be beneficial to [bind mount](https://github.com/hamiltont/FrameworkBenchmarks/commit/ce5220f29f7c199a9518d6721c3e97e7e44a7171) over installs each time vagrant is launched (e.g. even with just plain `vagrant up`), so this code should be exported into the VM by the bootstrap script and executed on each login

**Comment by nbrady-techempower** [comment]
Adding to roadmap: https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
