### ISSUE TITLE
Set JAVA_HOME based on uname

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1499]
As reported [here](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1479#issuecomment-90668052) in #1479 , the java setup depends on usage of `amd64`. This breaks on raspberry pi (and on vagrant if `VB_ARCH` is modified). 

Correct would be to use something like uname to predict where java's installation scripts will install the JVM.

**Comment by msmith-techempower** [comment]
MMMMMMM, I told him to report it there since it feels like being able to specify the install location resolves that problem as a side-effect.

**Comment by hamiltont** [comment]
Hm, I think you'd still need to know the exact path to setup JAVA_HOME, unless we extended 1479 to actually configure an entire environment for each application by resetting stuff like PATH

**Comment by hamiltont** [comment]
fixed in master
