### ISSUE TITLE
Audit framework code to have the correct core count

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1502]
For example, `Ruby/rails/run_thin.sh` does not update `Ruby/rails/config/thin.yml` to have the correct processes count available on a given system. This one defaults to 8, which is okay for our old i7 hardware, but laughable on the 40-core Peak environment.

I suspect MANY tests overlook this configuration tweaking - so we have to audit them accordingly.

**Comment by hamiltont** [comment]
Good point. This information should also be exposed in any solution proposed in #1017

**Comment by nateberkopec** [comment]
Is there any environment variable available that might contain the number of CPU cores on the system?

Or is this simply a matter of replacing "7" with "40"? If so, I am happy to open a PR.

**Comment by msmith-techempower** [comment]
Yes, `$MAX_THREADS` should be what you want.

**Comment by nateberkopec** [comment]
@msmith-techempower Neat. Is there anywhere that documents exactly how that variable is set? A quick project search doesn't seem to turn up anything.

**Comment by msmith-techempower** [comment]
I BELIEVE it is documented in our readthedocs, but I would have to confirm it. Otherwise, you would have to look [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L172) to see what environment variables are provided.

**Comment by nateberkopec** [comment]
Hm, I can't find it in readthedocs (I would expect it to be under Environment, though I looked elsewhere). It's a minor quibble, but it would help when deciding what concurrency settings to use if I knew *exactly* how you decided what MAX_THREADS was.

**Comment by msmith-techempower** [comment]
Ah, it is set via the [config file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/benchmark.cfg.example#L21) in the environment. For instance, on our Peak hardware, there are 40 cores, so that value is set to 40 manually.

We have plans to automatically detect the number, but for now this is how it is done.

**Comment by msmith-techempower** [comment]
Will be resolved by #1701

**Comment by nbrady-techempower** [comment]
Closing this but will add it to the current column in the toolset roadmap
