### ISSUE TITLE
Add testing to TFB toolset

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1511]
Not sure what kind of testing or what library, so any suggestions welcome. Main goal is to improve reliability of TFB toolset, secondary goal would be to help modularlize the toolset in a manner that better enables reuse of the codebase by third-party programs. 

Some python testing frameworks (unsorted, feel free to share more or advocate for any of these): 
- [hypothesis](https://hypothesis.readthedocs.org/en/latest/)

**Comment by LadyMozzarella** [comment]
For Reference: [Python Testing Tools Taxonomy](https://wiki.python.org/moin/PythonTestingToolsTaxonomy)

Looks like there are several options for us and I don't know anything about unit testing in Python. Based on quickly skimming the internet, it appears that [pytest](https://pytest.org/latest/contents.html) is a popular choice.

**Comment by hamiltont** [comment]
[pytest](http://pytest.org/latest/), [unittest](https://docs.python.org/2/library/unittest.html)

**Comment by nbrady-techempower** [comment]
Moved this to the toolset roadmap https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
