### ISSUE TITLE
Remove install.sh files

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1517]
Similar to how we removed the need for `bash_profile.sh` files, we should probably remove the `install.sh` files for each test as well and move that functionality into a combination in the `setup.sh` files.

I propose updating `fw_depends` to do the following:

1. install the given software (such as `java7`) if no 'installed' file exists (such as `$IROOT/java7.installed`)
2. create the 'installed' file (such as `$IROOT/java7.installed` which exports needed variables and updates the path) if it does not exist
3. sources the 'installed' file no matter what (such as `source $IROOT/java7.installed`)

This will help the suite by removing files AND centralizing the installation/execution steps which should make it easier for contributors moving forward.

**Comment by msmith-techempower** [comment]
This might be harder than I imagined since I have been wrestling with ensuring that the `bash_functions.sh` are executed and available to the `setup.sh` scripts. Basically, I cannot get those functions to have the visibility necessary after dropping into the new bash shell and executing `setup.sh`.

**Comment by ebramanti-techempower** [comment]
How are `install.sh` files executed differently from `setup.sh`? That's been a lingering question for me...

**Comment by msmith-techempower** [comment]
The setup scripts are executed via this crazy call:
`sudo -u testrunner -E -H stdbuf -o0 -e0 bash -ex setup.sh`
Which roughly means "run, as testrunner and sending stderr/stdout to the same buffer, this shell script using the existing environment."

The `install.sh` is simply executed... which is part of the problem. This issue requires that the functions declared in `bash_functions.sh`, which is executed right before `install.sh`, be accessible to that new bash shell... and I'm at a loss for how to do this.

**Comment by ebramanti-techempower** [comment]
The `-ex` is important too, which means exit immediately if command exits with non-zero and print commands and args as executed. Since `install.sh` does not catch errors, it can allow broken shell scripts to run.

**Comment by msmith-techempower** [comment]
Presently, `install.sh` should only contain calls to our `bash_functions.sh` so script errors should be nigh impossible

**Comment by ebramanti-techempower** [comment]
[Whoops](https://github.com/ebramanti-techempower/FrameworkBenchmarks/blob/nvm-nodejs/frameworks/JavaScript/nodejs/install.sh). This explains my problem over in #1425.

**Comment by hamiltont** [comment]
> Similar to how we removed the need for bash_profile.sh files, we should probably remove the install.sh files for each test as well and move that functionality into a combination in the setup.sh files.

Works for me. We can also remove `--install` and `--install-only` flag, and I'd really like to see this change happen in tandem with #1224

> This issue requires that the functions declared in bash_functions.sh, which is executed right before install.sh, be accessible to that new bash shell... and I'm at a loss for how to do this.

Bash allows you to export functions in the same way you can export variables to subshells. [Here's a quick primer](http://stackoverflow.com/questions/1885871/exporting-a-function-in-shell). 

> via this crazy call:

If we implement this idea, we'll need to use the same crazy call :-P

**Comment by hamiltont** [comment]
Er, ignore comment about in tandem with. This idea supersedes that one :-p
