### ISSUE TITLE
node.js & MySQL: explain transactional behavior

### ISSUE THREAD

**Issue by denkab** [TechEmpower/FrameworkBenchmarks#1519]
It is unclear if requirement #10 of http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#database-updates is satisfied, since transaction demarcation is implicit and a single connection is reused.

**Comment by nbrady-techempower** [comment]
I don't see where there may be a violation here. Though, both the rule and the framework have been updated since. Closing for now.
