### ISSUE TITLE
Php yaf: Separate install from PHP

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1521]
As mentioned in PR #1516, [yaf is installed inside of the PHP install file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/languages/php.sh#L49). Move this to a separate install file. Keep in mind that other frameworks may depend on yaf.

```bash
# yaf.so
 printf "\n" | $IROOT/php-${VERSION}/bin/pecl -q install -f yaf
```

**Comment by msmith-techempower** [comment]
I will probably be addressing this in my PR that removes `install.sh` files.

**Comment by LadyMozzarella** [comment]
Okay. Will assign to you then.
