### ISSUE TITLE
Remove ringojs-convenient

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1536]
It does not appear to have ever worked, it is extremely stale at this point, and it looks like the main file `ringo-main.js` does not actually attempt to implement anything.

Should we remove this since `ringojs` works?

**Comment by grob** [comment]
what makes you think ringojs-convenient never worked? ringojs-conv is part of the benchmark since round 7 (same as ringojs), works and passed every round of the benchmark since up to the latest preview of round 10. neither is it (resp. the modules it uses) _extremely stale_ nor does `ringo-main.js` _implement anything_, so i don't see any reason to remove it (if something in ringojs-conv doesn't work i'd be happy to help or fix it).

**Comment by msmith-techempower** [comment]
Must be my misunderstanding, then. I will review, thanks for the quick response.

**Comment by msmith-techempower** [comment]
I am trying to convert all tests away from `install.sh` scripts and instead relying more on their `setup.sh` files in conjunction with `fw_depends`.

The specific error I'm seeing when trying to run ringojs-conv is the following:

```
INFO:root:Sleeping 15 seconds to ensure framework is ready
Server ringojs-convenient: Wrapped java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
Server ringojs-convenient:      at ringo-sqlstore/lib/sqlstore/connection/pool.js:50 (anonymous)
Server ringojs-convenient:      at ringo-sqlstore/lib/sqlstore/connection/pool.js:186 (anonymous)
Server ringojs-convenient:      at ringo-sqlstore/lib/sqlstore/store.js:23 (anonymous)
Server ringojs-convenient:      at ringo-sqlstore/lib/sqlstore/store.js:51 (anonymous)
Server ringojs-convenient:      at /home/techempower/FrameworkBenchmarks/frameworks/JavaScript/ringojs-convenient/app/models.js:17
Server ringojs-convenient:      at /home/techempower/FrameworkBenchmarks/frameworks/JavaScript/ringojs-convenient/app/views.js:4
Server ringojs-convenient:      at /home/techempower/FrameworkBenchmarks/frameworks/JavaScript/ringojs-convenient/ringo-main.js:5
Server ringojs-convenient:
```

Any help would be great.

**Comment by grob** [comment]
this error indicates that the mysql.jar is missing. it's copied in [setup.sh](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/ringojs-convenient/setup.sh#L12), so something must be wrong therein. which branch should i check, `master` or `round-10`?

**Comment by msmith-techempower** [comment]
Actually, neither: `remove-install-scripts`

**Comment by grob** [comment]
ah, i see. the command copying the mysql.jar file is missing in the `setup.sh` file in `remove-install-scripts` (compare [master](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/ringojs-convenient/setup.sh#L12) and [remove-install-scripts](https://github.com/TechEmpower/FrameworkBenchmarks/blob/remove-install-scripts/frameworks/JavaScript/ringojs-convenient/setup.sh)). i can try to fix that 'til monday.

just to be sure: which branch is/will be used for round 10?

**Comment by hamiltont** [comment]
> which branch is/will be used for round 10?

The `round10

**Comment by hamiltont** [comment]
ugh, early enter. 

The `round10` branch will be used. Master is going forward and will be used for round 11.

**Comment by grob** [comment]
thanks for clarification, setup.sh in `round-10` looks ok. i'll provide a pull request to fix the `remove-install-scripts` version of it (btw.: there's also a [pending pull request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1354) by @oberhamsi)

**Comment by hamiltont** [comment]
FYI, [looks to me](https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-24-peak-final) like ringojs-convenient [worked fine in R10](https://www.techempower.com/benchmarks/previews/round10/#section=data-r10&hw=peak&test=json). @msmith-techempower - we've gotta get you on the default vagrant setup :-P

@grob If you're up for being pinged when there's an issue we cannot solve internally, I'd love if you could add your github handle to the README for any/all of `JavaScript/ringojs/README.me,JavaScript/ringojs-convenient/README.md, or JavaScript/README.md` (whatever you're interested in being notified about). That could help going forward

**Comment by msmith-techempower** [comment]
This was entirely my fault for being bone-headed; thanks so much for your help @grob
