### ISSUE TITLE
Nodejs: Update all tests to v0.12.x

### ISSUE THREAD

**Issue by ebramanti-techempower** [TechEmpower/FrameworkBenchmarks#1537]
Now that my addition of `nvm` for versioning has been merged into master, I want to begin work on updating the Node tests to the most recent version 0.12.x (even Koa is only running on 0.11.x, which I just implemented). The MySQL driver, [node-mysql-libmysqlclient](https://github.com/Sannis/node-mysql-libmysqlclient), might need to be updated as well. It has very particular compatibility requirements, so the tests might have to be switched over to a new driver (might pertain/fix #1519 & #1520, but not exactly sure yet).

Either way, wanted to open this issue since all of the Node frameworks will be audited/updated.

**Comment by ebramanti-techempower** [comment]
Also, I'll work on updating the warns since the Node frameworks have not been updated with the necessary response headers.

**Comment by mhart** [comment]
Would be great to add io.js to the mix too – it's a more modern, up-to-date fork of Node.js and should be pretty much a drop-in replacement

https://iojs.org

**Comment by ebramanti-techempower** [comment]
@mhart I've been keeping up with io.js, it will be much easier to figure out a solution for this now that we are employing `nvm`. For the moment, these tests **need** to be updated before we consider adding this as an option.

**Comment by mhart** [comment]
Funny you say that – just playing with it on my machine now :+1:

**Comment by ebramanti-techempower** [comment]
@mhart Sweet! What frameworks are you using it with? Right now I'm updating Hapi.js from 1.2 to 8.4, however since io.js is a fork of Node this shouldn't affect it working in io.

**Comment by rayshan** [comment]
May be good to test io.js with this patch or wait for it to land:
https://github.com/iojs/io.js/pull/933

**Comment by ebramanti-techempower** [comment]
I can open an issue to add io.js to the JS framework benchmarks! Thanks for your input!

**Comment by mhart** [comment]
I updated the nodejs benchmark for Node.js v0.10 at least, here: #1563 

The basic JSON/text tests work fine under v0.12 and io.js, and are certainly more stable (not sure how much faster) – but the mysql dependency won't build at all under those versions, and I'm not familiar enough with that code to figure out an alternative.

**Comment by ebramanti-techempower** [comment]
This is done! Onwards to io.js support!
