### ISSUE TITLE
Python: Add historical frameworks

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1540]
Is there any interest in adding these historical frameworks? The most recent ones were updates in late 2013, while the oldest ones are from the 200* age. 

Zope, Quixote, Webware, SkunkWeb, PSO

**Comment by GMLudo** [comment]
Sincerly, I think anyone use that now, except maybe for Zope.
Personally, don't waste your time for that, but it's your time, your decision, not mine ;-)

**Comment by hamiltont** [comment]
My thought is that it could be fun to compare these foundations to the
current state of the art, and might even prove valuable for academics
interested in progress over time

**Comment by zane-techempower** [comment]
I think this is a good idea. It's expected that frameworks improve over time so some older tech is a nice benchmark in a way. Developers might want to know how their current stack compares to stacks they used 10 years ago.

**Comment by hamiltont** [comment]
Cool! @GMLudo is right that someone has to invest the time to code these up, but once that's done I kind of doubt they will need maintenance :-P I'd personally be fascinated to see results like "In 10 years, peak performance has improved 25%" or similar ridiculousness. I'm sure some researchers would be interested in oddball stuff like comparing framework source code LOC count to framework performance over time

**Comment by knewmanTE** [comment]
I'll take a stab at Zope 2.

**Comment by hamiltont** [comment]
Sweet. How about this: we lump them all under Python/historical and use the
benchmark_config.json to declare one configuration per old framework?

**Comment by knewmanTE** [comment]
That works for me!

**Comment by GMLudo** [comment]
@hamiltont: With theses arguments, I recognise that it's interesting to see the potential evolutions. Maybe you'll find that in fact, old frameworks are more efficient that actual Web frameworks ;-) Nevertheless, even if you implement that on with Python 2.7 only (not 3), not sure that theses frameworks will start.

**Comment by hamiltont** [comment]
@GMLudo great! BTW, good point...these may be python 1.x only! If they are hard at all to setup/maintain then it's probably not worth it; we will know soon enough if knewmanTE was able to setup something up easily

**Comment by knewmanTE** [comment]
I spent a good couple of hours trying to get Zope setup with no success. I have a Webware app that seems promising. The only concern there will be getting it configured within the benchmark structure.

**Comment by knewmanTE** [comment]
Within the Webware documentation, they point to [MiddleKit](http://webware.sourceforge.net/Webware/MiddleKit/Docs/Intro.html) for database interactions. However, since these docs were written, a number of newer ORMs have been released (notably SQLAlchemy, which we use for about half of our current Python frameworks).

What do you guys think about using MiddleKit vs SQLAlchemy for the database tests? SQLAlchemy is much easier to setup, but would using it defeat the "historical" goals of these tests?
