### ISSUE TITLE
Mark tests as success only if results were grabbed

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1542]
Currently we mark tests as succeed too early. We should wait until we see the expected numbers e.g. "totalRequests" and other keys. For example, [here](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-24-peak-final/latest/results.json) we list beego as succeed, while if you look at the output more closely you will see that wrk apparently failed to run, and the only result data we have in the `results.json` is 

```
{'results': [{'endTime': 1427218357, 'startTime': 1427218357},
   {'endTime': 1427218359, 'startTime': 1427218359},
   {'endTime': 1427218361, 'startTime': 1427218361},
   {'endTime': 1427218363, 'startTime': 1427218363}]}
```

which is missing the actual benchmarking result data

**Comment by msmith-techempower** [comment]
Did `wrk` really fail to run?

**Comment by hamiltont** [comment]
I really don't know. The only clue we have is the lines saying "connection refused" which appear to be from wrk. So..did the server crash *after* we verified? Seems unlikely

[Here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/R10/toolset/benchmark/framework_test.py#L354) is where we called to work, and we get output from that entire script *but* from the wrk part of it, so perhaps this is somehow not properly capturing stderr? It looks right to me, but maybe we should echo to stdout and to stderr at the top of those templates, just so we can look at the files after the fact and ensure that our echo to the various file descriptors made it into the final stored files. That's just debugging help though, I really don't know what happened here. If it couldn't find wrk bash would have complained.

**Comment by nbrady-techempower** [comment]
I'm adding this to the toolset. One thing I noticed when working on diffing results in-house is that sometimes a framework will pass the verify stage and then not return results. I'm not quite sure how this happens yet, but am going to add it to the TODO's in the toolset roadmap for investigation.
