### ISSUE TITLE
Javascript: add io.js to Node tests

### ISSUE THREAD

**Issue by ebramanti-techempower** [TechEmpower/FrameworkBenchmarks#1546]
We've been getting a bunch of requests in #1537 to add io.js tests to the Javascript frameworks to see if there is any performance difference. As soon as #1537 is closed, I'll begin work on this.

**Comment by branning** [comment]
The decision to merge io.js and node.js and form the Node Foundation elminates the need to do this.

**Comment by Sinewyk** [comment]
How can we help if we want the next benchmark to run on node v4 (being the LTS) and node v5 (stable) ?

**Comment by asilvas** [comment]
+1 for using latest stable. This benchmark has nothing to do with LTS releases, so should be more than reasonable to use latest release.

**Comment by nbrady-techempower** [comment]
We are up to v5, should be v6 soon!

**Comment by Sinewyk** [comment]
I still see 0.12 here https://github.com/TechEmpower/FrameworkBenchmarks/blob/bfc1f5088798d561e71e95d23d0467b1974886c7/toolset/setup/linux/languages/nodejs.sh#L8.

You can probably go straight up to 6.2.2, it's going in LTS in October.

**Comment by nbrady-techempower** [comment]
@Sinewyk the current node version for round 14 is in the round-14 branch. Feel free to submit a pull request to the round-14 branch for further upgrades!
