### ISSUE TITLE
No PHPixie in round 10

### ISSUE THREAD

**Issue by ghost** [TechEmpower/FrameworkBenchmarks#1555]
PHPixie was there in round 9 but is not present in round 10. Why is that?

**Comment by msmith-techempower** [comment]
From the [logs](https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-24-peak-final/latest/logs/php-phpixie/err.txt) it seems like there was an error with installing the software required.

**Comment by cjnething** [comment]
From the latest (Round 12) [logs](http://tfb-logs.techempower.com/round-12/peak/linux/2016-02-22-final/latest/results.json), it looks like phpixie was present and passing (as shown below), so this issue is resolved.
```
"php-phpixie": {
      "fortune": "pass", 
      "plaintext": "warn", 
      "db": "pass", 
      "update": "pass", 
      "json": "pass", 
      "query": "pass"
},
```
