### ISSUE TITLE
No Zend Framework's in round 10

### ISSUE THREAD

**Issue by gerardroche** [TechEmpower/FrameworkBenchmarks#1558]
v1 errors: https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-24-peak-final/latest/logs/zendframework1/err.txt

The same goes for v2: https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-24-peak-final/latest/logs/zendframework/err.txt

Pretty disappointed about this. I contributed v1 and worked on v2 of these benchmarks. They were both working when I last worked on them. Feels like a slap in the face. Thanks TechEmpower.

**Comment by msmith-techempower** [comment]
There seemed to be an issue with a few tests not having access to composer (for reasons unknown). We are going to address this, but as no one noticed during the month and a half of preview runs we had, it slipped through.

As for a slap in the face, I think you are being overly dramatic. Obviously, it is a bummer that this happened, but we only have so many hours in the day and without the community's help in auditing the previews things are bound to fall through the cracks.

It's on our radar for round 11 and we should have it addressed soon.

**Comment by msmith-techempower** [comment]
This seems to have been resolved as there were `zend` results in round 11.
