### ISSUE TITLE
LOC count not making it into final results.json

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1562]
Not sure what's happening, but [20150324072137/results.json](https://raw.githubusercontent.com/TechEmpower/TFB-Round-10/master/peak/linux/results-2015-03-24-peak-final/20150324072137/results.json) has the "slocCounts" keys present and [latest/results.json](https://raw.githubusercontent.com/TechEmpower/TFB-Round-10/master/peak/linux/results-2015-03-24-peak-final/latest/results.json) does not

**Comment by nbrady-techempower** [comment]
fixed with #2018
