### ISSUE TITLE
PHP: Optimize laravel class loader

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1564]
Using `artisan optimize` described [here](http://laravel-recipes.com/recipes/60/optimizing-the-framework-for-better-performance) - Recommended [here](https://www.reddit.com/r/PHP/comments/33evlz/techempower_web_framework_benchmarks_round_10/cqkub4z)

**Comment by bratao** [comment]
Don't forget to use php artisan optimize --force

**Comment by hamiltont** [comment]
Closed by #1571
