### ISSUE TITLE
Python: Add config for greenlet-based workers to gunicorn based tests

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1567]
Perhaps I'm missing something here, but it seems that tests like flask, which are using gunicorn, are currently only using meinheld for their worker classes. Can we add configurations to also test using other worker classes, such as sync workers and greenlet-based workers via either eventlet or gevent

See https://gunicorn-docs.readthedocs.org/en/latest/design.html for info

**Comment by GMLudo** [comment]
You can test others, nevertheless, from my experience, Meinheld is the best with Gunicorn.
If you propose that as scientific approach to be sure it's always the case, it's a good idea.

**Comment by hamiltont** [comment]
@GMLudo Good to have a second pair of eyes, thought I was just getting confused. Python has so many approaches to concurrency, and with the wsgi a lot of frameworks are mixed and matched, so it's quite confusing when you first start reading up on "how to run a webserver using python". 

I'd personally like to know how much worse the greenlet-based approaches are, so if I'll leave this open as a request for a second configuration that uses gevent or eventlet instead of meinheld

**Comment by methane** [comment]
Random notes about greenlet+monkeypatch based concurrency libraries:

I think gevent is most popular for greenlet based concurrent server for now.
But gevent development has been stalled.  It doesn't release versions supporting Python 3 and Python 2.7.9.
veegee/guv looks better for me. But it is not so popular as gevent for now.
eventlet is another choice.  OpenStack uses it.

gevent (or similar) are easy way to solve C10K problem.
But Monkeypatching in them is dirty idea.  It may cause unexpected problems.
And monkeypatched socket is much slower than normal synchronous sockets.
So I recommend to split async service and normal sync worker, and multiplex them in front nginx.

For performance point of view, I think fastest way is gevent+PyPy.
But it's not stable for now. (gevent/gevent#248).

**Comment by methane** [comment]
In my opinion, we should wait until C10K test is added.

**Comment by GMLudo** [comment]
> veegee/guv looks better for me. But it is not so popular as gevent for now.

Very interesting, thanks for this link. Maybe `aiouv` should more interesting than expected.

> eventlet is another choice. OpenStack uses it.

To my knowledge, OpenStack uses several async framework, at least eventlet, gevent and twisted, because you have plenty of daemons inside OpenStack.

> But Monkeypatching in them is dirty idea. It may cause unexpected problems.

Clearly, I'd some stories from production field about that.

> And monkeypatched socket is much slower than normal synchronous sockets.

Good to know.

> So I recommend to split async service and normal sync worker, and multiplex them in front nginx.

I've no better idea, I'm agree with you.

**Comment by hamiltont** [comment]
Great information! Sounds like waiting until c10k is a good idea. I think there would be some value in a "naive" PR that used something like gevent (w/o monkey patch hopefully) and py2, just to see what happens when it is setup in the simplistic way. It would be really great to see a "proof in the results" that multiplexing sync and async offered advantages, although the benefit might *only* show up with a C10k test

**Comment by methane** [comment]
Just adding gunicorn+gevent configuration to Flask or Bottle is easy.
One problem is DB access.

1. Use current stack (fast, but not gevent friendly).
2. Use monkeypatched PyMySQL (slow, but gevent friendly).
3. Use threadpool to offload blocking database access.
4. Use gevent friendly PostgreSQL. (But I'm not inexperienced about PostgreSQL).

Since gevent is tool for special case, there are no common architecture.

**Comment by methane** [comment]
gevent 1.1 was released recently.  It supports Python 3 and PyPy.
PyPy + gunicorn + gevent + PyMySQL is interesting stack.

**Comment by GMLudo** [comment]
Interesting, we'll see the results ;-)

**Comment by msmith-techempower** [comment]
This issue is a year-and-a-half old and appears to be resolved by #2560
