### ISSUE TITLE
Replace curl with python requests library

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1568]
Or something similar.  See http://docs.python-requests.org/en/latest/

Avoids having to have curl installed on host, which will be a barrier to entry for windows

**Comment by zane-techempower** [comment]
I'm using requests on a side project. It's great! Don't know of any better options.

**Comment by GMLudo** [comment]
Personally, I use aiohttp.client for concurrency support with Requests-like API. If you don't need to launch several HTTP requests in the same time, requests is enough.

**Comment by zane-techempower** [comment]
That's really good to know. From what I know, these requests are just used to assert that responses look at certain way i.e. unit test them. The load-testing requests are done by wrk.

**Comment by GMLudo** [comment]
@zane-techempower: Then, Requests it's enough.
Unless you want to speed-up the unit-tests and launch concurrently all requests at the same time for one framework, but it must be benchmarked.
If you had a lot of URLs to validate at the same time, `aiohttp.client` is clearly a winner compare to Requests, I've made a CouchDB crawler and I've benchmarked that.
But, for only 5 requests, especially if the HTTP client is executed on the same machine as the HTTP server, Requests should be quicker.
If you're interested in that I'm explore that, or you want some others tips, don't hesitate to contact me, it's my main day job to optimize Python applications.

**Comment by msmith-techempower** [comment]
We aren't really interested in speeding up the verification process, which is where `curl` is used, and doing the requests in parallel doesn't really get us much more than that.

I suspect that `requests` (or similar) will be a fine replacement.
