### ISSUE TITLE
Wrong 32/64 bits message: "WARNING: FrameworkBenchmarks only officially supports a 64-bit virtual machine, which your current system may not be able to support. Use `TFB_SHOW_VM=true vagrant up` to watch the VM launch"

### ISSUE THREAD

**Issue by jarnix** [TechEmpower/FrameworkBenchmarks#1587]
I'm using Win 8.1 64 bits, I get this error message. The line responsible for this false warning is in vagrant-common/checks.rb

```
if OS.windows? and ARCH.is32?
    puts warning
end
```

PS: please kill me I hate markdown.

**Comment by hamiltont** [comment]
Hmm, do you know how to output the value of `RUBY_PLATFORM`? That would be useful. [This thread](https://www.ruby-forum.com/topic/202173) claims there is no reliable way in ruby to know 32vs64, but suggests a number of guessing-based approached including the method we use now.

**Comment by yunspace** [comment]
I'm also getting the same error on my Windows 10 64bit running VirtualBox 5.0.1. 
The output of `RUBY_PLATFORM` is:

```
irb(main):003:0* RUBY_PLATFORM
=> "x86_64-linux"
```

**Comment by nbrady-techempower** [comment]
I believe this is a problem with mingw64. If you puts RUBY_PLATFORM before the warning message, even in mingw64, I'm getting i386-mingw32.

**Comment by nbrady-techempower** [comment]
I don't see a direct fix for this right now. It's not causing any issues other than displaying that warning, and I still believe it was a mingw64 thing. Closing for now.
