### ISSUE TITLE
Crystal: add Moonshine

### ISSUE THREAD

**Issue by Vikaton** [TechEmpower/FrameworkBenchmarks#1594]
Could you guys maybe add Crystal and the Moonshine web framework?

https://gist.github.com/Vikaton/3102c16ee14ef3d76244

https://github.com/manastech/crystal

https://github.com/dhruvrajvanshi/Moonshine

Need any help with it also?

**Comment by hamiltont** [comment]
> Need any help with it also?

That would be great! [here](https://frameworkbenchmarks.readthedocs.org/en/latest/Development/Add-Frameworks-or-Tests/) is the how-to for adding a new framework if it helps

**Comment by zane-techempower** [comment]
Interested in this one, will start building out today

**Comment by Vikaton** [comment]
Yeah I've been meaning to to to do this but I have lots of School work to do, This will be interesting!

**Comment by will** [comment]
I took a stab at this in #1623

**Comment by Vikaton** [comment]
When will round 11 experimental be available?

**Comment by msmith-techempower** [comment]
Soon™
