### ISSUE TITLE
Unchanged Fortune.py appears modified on case insensitive file systems

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#1603]
Right after cloning the project repository `git status` reports the following on Mac OS X 10.10.3:

```
~/FrameworkBenchmarks (master ✘)✹ ᐅ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   frameworks/Python/historical/webware/app/Context/Fortune.py

no changes added to commit (use "git add" and/or "git commit -a")
```

This happens because Mac OS X Yosemite (10.10) default HFS+ file system treats file names in a case insensitive manner and hence confuses the `fortune.py` and `Fortune.py` files in the same directory.

This may occur on other systems with case insensitive file systems (e.g. Windows).

**Comment by marko-asplund** [comment]
@knewmanTE This issue seems to have gotten introduced in commit 0b4d040532369035c0225846030293ecc388a87b.

Very annoying file system, HFS+ :-(

**Comment by msmith-techempower** [comment]
This annoyed me, too. I've resolved this on master (stupid Windows and other OSs with case-insensitive file systems) via: ec0eeea70c816e323219c94807dd79ddffabd719
