### ISSUE TITLE
MongoDB often does not work properly on Travis-CI

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1604]
Related to the comment by @hamiltont on #1577

**Comment by hamiltont** [comment]
If anyone is interested, [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/run-ci.py#L341) is where I configure mongo in travis ci. It's basic stuff, but I'm not the most experienced with mongodb. Maybe someone can figure out if there is a way to avoid all our mongo issues. 

Two major issues - the keyserver appears to occasionally fail to respond and we do not get the keys for mongodb, and sometimes the server just fails to start.

**Comment by methane** [comment]
Does this issue happen for now?

**Comment by msmith-techempower** [comment]
I believe this one is addressed.

**Comment by nbrady-techempower** [comment]
Haven't seen any more issues with this. Closing for now
