### ISSUE TITLE
RPS for high req/sec bench

### ISSUE THREAD

**Issue by methane** [TechEmpower/FrameworkBenchmarks#1608]
While I haven't used PEAK hosting, I suggest these configuration may improve scalability.

``` console
# echo 32768 > /proc/sys/net/core/rps_sock_flow_entries
# for i in /sys/class/net/eth*/queues/rx-?/rps_flow_cnt; do echo $i; echo 32768 > $i; done
# for i in /sys/class/net/eth*/queues/rx-?/rps_cpus; do echo $i; echo 'ffff' > $i; done
```

See https://www.kernel.org/doc/Documentation/networking/scaling.txt

**Comment by msmith-techempower** [comment]
What would this do, exactly?

**Comment by msmith-techempower** [comment]
This is nearly a year old - can you provide some explanation on the purpose of these tweaks, @methane ?
