### ISSUE TITLE
Benchmark > Getting Started > Installing the Framework Benchmark App Server

### ISSUE THREAD

**Issue by greg-hellings** [TechEmpower/FrameworkBenchmarks#1609]
In this section of the docs we are told to invoke run-tests.py with the argument "--install-software", which is an invalid argument to that script. Perhaps this should be --install-only?

The same error is duplicated in the sections about setting up the database and load servers.

There is no step that indicates to create a testrunner user or where that user ought to be created.

**Comment by hamiltont** [comment]
closed in favor of same issue on docs project

> Perhaps this should be --install-only?

It should ;-)
