### ISSUE TITLE
amd64: Add asmttpd

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1618]
Someone please do this. I legit want to know if it's faster than the C/C++ implementations :-D

https://github.com/nemasu/asmttpd

**Comment by msmith-techempower** [comment]
It does not serve json or plaintext (except as html). I'm not sure how it would fit into our benchmarks any more than a vanilla nginx would, or apache2 without plugins.

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
