### ISSUE TITLE
Nim 0.12.0

### ISSUE THREAD

**Issue by Vikaton** [TechEmpower/FrameworkBenchmarks#1621]
Nim has increased it's performance with this release in their http modules, and multi-threading is coming soon for Jester, since it's single core at the moment.

I heard maybe there will be some wait for updating Nim in techempower until one of the libs for Nim is updated, but it's something to look out for.

**Comment by mfirry** [comment]
+1

**Comment by Vikaton** [comment]
make that Nim 0.12

**Comment by nbrady-techempower** [comment]
Added to #1803. Please refer there for language/framework additions/updates.
