### ISSUE TITLE
Beego: tests returns 0 rps

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#1659]
Beego results in Round 10 are showing 0 rps, but the implementation is apparently passing the validation checks since it is not being marked as did-not-complete.  The implementation should be reviewed/audited to determine why it is validating but measuring at zero requests completed.

The validation logs confirm success:

https://github.com/TechEmpower/TFB-Round-10/tree/master/peak/linux/results-2015-03-24-peak-final/latest/logs/beego

But the wrk logs are curiously missing wrk output:

https://github.com/TechEmpower/TFB-Round-10/blob/master/peak/linux/results-2015-03-24-peak-final/20150324072137/plaintext/beego/raw

**Comment by bhauer** [comment]
Also see issue #1542.

**Comment by msmith-techempower** [comment]
This is "resolved" in that Beego is now properly failing validation.
