### ISSUE TITLE
Prod setup doesn't configure somaxconn properly.

### ISSUE THREAD

**Issue by methane** [TechEmpower/FrameworkBenchmarks#1668]
All nginx-uwsgi tests are failed.
Message says

> Server bottle-nginx-uwsgi: Listen queue size is greater than the system max net.core.somaxconn (128).

https://github.com/TechEmpower/TFB-Round-11/blob/master/peak/linux/latest/logs/bottle-nginx-uwsgi/out.txt

**Comment by methane** [comment]
uWSGI exits immediately when configured listen queue size is smaller than somaxconn.
https://github.com/unbit/uwsgi/blob/3de97b9f7e0614bef098b855e36a3c5e3065be37/core/socket.c#L123-L125

**Comment by msmith-techempower** [comment]
To what should `somaxconn` be set (in general)?

**Comment by methane** [comment]
I think recommended way is:
```
sudo cp config/sysctl.conf /etc/sysctl.d/60-tfb.conf
sudo service procps start
```

legacy (and more portable) way is:
```
cat config/sysctl.conf | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

**Comment by methane** [comment]
I realise somaxconn is not set even on Travis-CI.

I fixed it in this commit:
https://github.com/methane/FrameworkBenchmarks/pull/2/commits/d87f0814c5a7a0d2edd0caf8aa111799faee2228

Is this a right place to configure sysctl?

**Comment by msmith-techempower** [comment]
Is this still an issue? The commit to fix it in Travis uses the same line as in `benchmarker.py`.

I think I am going to close this (bookkeeping), but reopen if there is still more to be done.
