### ISSUE TITLE
All tests pass, but Travis returns error

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1690]
Not sure what happened, but [here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/67206092) is the example.

**Comment by hamiltont** [comment]
ouch. does look like a bug somewhere in the code that determines if we return 0 or 1

**Comment by msmith-techempower** [comment]
This hasn't happened since we started using Ubuntu14 with sudo on Travis.
