### ISSUE TITLE
Vert.x 3.0

### ISSUE THREAD

**Issue by rektide** [TechEmpower/FrameworkBenchmarks#1697]
Vert.x 3.0 is released! Huzzah! Would be great to see it tested in FrameworkBenchmarks. It's been quite a while since Vert.x was in the charts- an old version was removed in #846, & was last seen in [round 8](https://www.techempower.com/benchmarks/#section=data-r8&hw=i7&test=json).

cc @purplefox

**Comment by hamiltont** [comment]
Coolio. Does it make sense to update the [vertx 2.x](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/vertx) code we already have?

**Comment by rektide** [comment]
3.2 featured in latest, yay.
