### ISSUE TITLE
Remove config value for threads

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1701]
I have been burnt by this too many times, apparently.
1. Remove config value for threads (only used by wrk)
2. Change `{max_threads}` in wrk call to ``nproc`` (which will get the number of threads available on the load machine)

**Comment by msmith-techempower** [comment]
Just to note - getting the markdown to actually render those backticks on `` `nproc` `` was difficult AND intentional.

**Comment by hamiltont** [comment]
FYI, I don't think nproc will work properly if the load generator is running inside a container (e.g. on a docker-based cloud IaaS, for example). I'm fine with the change, just pointing out one potential pitfall

**Comment by msmith-techempower** [comment]
That's fine - we could capture it with a pipe and return 1 in that case.

**Comment by nbrady-techempower** [comment]
@msmith-techempower thinking this has been done, but if not, let me know and I'll add to roadmap.
