### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1702]
A long time ago in a desk far far away, I made a lot of changes which resulted in a better benchmark suite, but required additional work to implement support for Windows benchmark runs.

Specifically, the scripts which started/stopped tests were changed from Python scripts to Bash scripts to better sandbox each test run so that we could ensure (at least, that is the dream) that processes would end and release their ports (and whatever else they might use).

Obviously, Windows does not support Bash out of the box, and frankly we should be using the same methodology as we do for Ubuntu - use the native shell to start up a sandboxed test application, put it under load, capture that data, and kill that shell.

My initial thinking would be to use PowerShell, but I am not married to the idea if there is something better suited to the task. We would simply split the code to call the Windows code in the appropriate Windows environment and the Bash shell code in the Ubuntu environment.

**Comment by syalachigere** [comment]
@msmith-techempower Mike, what is the status of toolset support for Windows? Is anyone working on it? I am willing to contribute.

Thanks

**Comment by msmith-techempower** [comment]
Currently, no one is working on it as we are trying to get round 11 out the door.

**Comment by nbrady-techempower** [comment]
I think it's safe to say, this is on the way! :fireworks:
