### ISSUE TITLE
results.json contains a "name" attribute that is always "ec2"

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#1704]
Remove the "name" attribute from the results.json *or* make it meaningful.  Presently, it always is set to "ec2", regardless of the test environment, making it meaningless or confusing.

**Comment by msmith-techempower** [comment]
Suggest removing it - it's an arcane holdover.

**Comment by bhauer** [comment]
Yes please. Just remove it.
