### ISSUE TITLE
Jawn needs update

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1707]
The current implementation of Jawn has no capacity for setting the host, so it is always listening to `localhost` and will refuse connections attempted against direct IP hits.

Example:
```
$ curl localhost:8081/db
{"id":7234,"randomNumber":2746}
$
$ curl 10.0.3.2:8081/db
curl: (7) couldn't connect to host
```

Unfortunately, this means that Jawn will not be included in round 11 since this is required by the benchmarks.

I have also created [this issue](https://github.com/MTDdk/jawn/issues/10) on the issue tracker for Jawn to keep us up to date.

**Comment by MTDdk** [comment]
The updates is a part of the pull request #1693

**Comment by msmith-techempower** [comment]
Resolved in [acac7e](https://github.com/TechEmpower/FrameworkBenchmarks/commit/acac7e925019567b3fadf7ce56c1b9f1b80fd664).

**Comment by MTDdk** [comment]
Looks perfect
