### ISSUE TITLE
Klein (and others) MUST NOT update the Fortune table

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1708]
I have had to update the mysql "Fortune" table to be readonly for `benchmarkdbuser` because SOMEONE was writing to it (:cough: @knewmanTE :cough:).

Fix Klein to not attempt to write to the Fortune table.

**Comment by knewmanTE** [comment]
Hmm. Sorry about that! Not entirely sure why Klein is doing that. It implements SQL Alchemy to grab the Fortunes in the same way as many of the other Python frameworks (Bottle, CherryPy, Flask, among some others).

**Comment by msmith-techempower** [comment]
Not a problem - like I said, I set the table to readonly to fix this, but in order to get fortunes working for klein we have to fix it.

Specifically, [this line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/klein/app.py#L118) seems to be actually causing the ORM to attempt an update on every row rather than just the objects in memory. Not sure what can be done there, but we'll capture ideas/tests here.

**Comment by knewmanTE** [comment]
Looks like [TurboGears](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/turbogears/app.py#L86) has the same line. Is that also causing the issue?

**Comment by msmith-techempower** [comment]
I haven't gotten that far - I'll post back when I do.

**Comment by methane** [comment]
bleach is sanitizing library.  It can be used to embed rendered HTML in another HTML.
But for this purpose, simple HTML escaping is better approach.

SQLAlchemy's session is the "Unit of Work".
TG and Klein should close session at end of each request.

**Comment by methane** [comment]
Jinja2 has `autoescape` option.
http://jinja.pocoo.org/docs/dev/api/#jinja2.Environment
I recommend to use `autoreload=False` to avoid searching template file for each request.
