### ISSUE TITLE
Silicon (and others) MUST NOT write to Fortunes table

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1709]
The latest preview run suggests that silicon is failing because it is trying to write something to the fortune table.

I haven't much more on this and could not figure out the code (too much framework magic). Perhaps, I could get a hand from @matt-42

**Comment by msmith-techempower** [comment]
Here are the last few lines from the log:

```
Setup silicon: -- The C compiler identification is GNU
Setup silicon: -- The CXX compiler identification is GNU
Setup silicon: -- Check for working C compiler: /usr/bin/gcc
Setup silicon: -- Check for working C compiler: /usr/bin/gcc -- works
Setup silicon: -- Detecting C compiler ABI info
Setup silicon: -- Detecting C compiler ABI info - done
Setup silicon: -- Check for working CXX compiler: /usr/bin/g++-4.9
Setup silicon: -- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
Setup silicon: -- Detecting CXX compiler ABI info
Setup silicon: -- Detecting CXX compiler ABI info - done
Setup silicon: -- Configuring done
Setup silicon: -- Generating done
Setup silicon: -- Build files have been written to: /home/techempower/FrameworkBenchmarks/frameworks/C++/silicon/build
Setup silicon: Scanning dependencies of target silicon_tpc_mysql
Setup silicon: [100%] Building CXX object CMakeFiles/silicon_tpc_mysql.dir/main.cc.o
Setup silicon: Linking CXX executable silicon_tpc_mysql
Setup silicon: [100%] Built target silicon_tpc_mysql
Setup silicon: mysql_stmt_prepare error: CREATE command denied to user 'benchmarkdbuser'@'10.0.3.2' for table 'fortune'
Setup silicon: Status: Poll: 0, Port 8080 bound: False, Time Left: 1:44:28.613396
```

**Comment by matt-42** [comment]
By default, the silicon ORM creates the mysql table, only if it does not already exists.
To do so, at initialization, it issues a CREATE TABLE IF NOT EXISTS [...]:
https://github.com/matt-42/silicon/blob/cfcf11fde197e9b48534a17972a458a66a6383cf/silicon/middlewares/sql_orm.hh#L173
It does not alter the table if it already exists.

I just fixed the framework to handle error without crashing:
https://github.com/matt-42/silicon/commit/17167fd6065b1fd4e628a81f2327121d9f733298

**Comment by msmith-techempower** [comment]
Ah, that's looking promising - I will check this out tomorrow. Thanks for the help!

**Comment by msmith-techempower** [comment]
Thanks for the help @matt-42 !
This has been resolved in [c0ae47](https://github.com/TechEmpower/FrameworkBenchmarks/commit/c0ae476ab8dad592d9eca3eac7dda2ddbc95d35d)!
