### ISSUE TITLE
Wicket database tests not working

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1710]
Wicket's json and plaintext tests are working fine, but the database tests are not. The web.xml is updated to have the correct connection string, but requests for db/queries/updates/fortunes seem to be timing out.

**Comment by martin-g** [comment]
Duplicate of #1403 ?!
Related to #1703.

**Comment by msmith-techempower** [comment]
Definitely - searching in the morning is hard. Closing in favor of #1403
