### ISSUE TITLE
Wheezyweb (and others) MUST NOT write to the fortunes table

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1712]
I think the same issue as klein and those others, I think.

**Comment by methane** [comment]
I'm start working on this: https://github.com/methane/FrameworkBenchmarks/pull/4
I don't have test env so I run test on Travis.
When all test passes, I'll create PR.

**Comment by nbrady-techempower** [comment]
@msmith-techempower Do you know off-hand of the others that are doing this? I can start fixing those.

**Comment by msmith-techempower** [comment]
@nbrady-techempower I am not sure. I have actually addressed this directly in MySQL, but not the other dbs by making the fortunes table readonly for the user `benchmarkdbuser`

I suppose we could consider this closed if we can verify that `klein` and `wheezyweb` (and any others I call out in open issues) are no longer attempting to write to the table.

**Comment by msmith-techempower** [comment]
Resolved by #1716
