### ISSUE TITLE
Update Go from 1.2

### ISSUE THREAD

**Issue by ikarienator** [TechEmpower/FrameworkBenchmarks#1718]
Go 1.2 is badly outdated. It had severe memory leaks in its runtime and long GC pauses. We should update to Go 1.4 which is the current mainstream runtime.

**Comment by zane-techempower** [comment]
I updated the title for clarity. Go will remain at its current version for the imminent Round 11. For Round 12 I will make sure that Go is updated to 1.5, which was officially released two days ago. If certain frameworks do not play well with 1.5, which is unlikely, then they will be upgraded as much as possible.

**Comment by diegobernardes** [comment]
+1

and i think the frameworks should be upgraded too with the language to the last stable version

**Comment by nbrady-techempower** [comment]
this will be taken care of here #1765 once the travis issue is resolved
