### ISSUE TITLE
HHVM platform attribute inconsistency: hhvm versus hphp

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#1721]
For our hhvm-enabled PHP test implementations, we have inconsistency in the platform attribute field.

For two tests (hhvm proper and symfony2-hhvm), the platform is [specified as "hhvm,"](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/symfony2/benchmark_config.json#L76) which seems proper and correct from my layperson understanding.

For other hhvm-enabled tests (e.g., [codeigniter_hhvm](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/codeigniter/benchmark_config.json#L32) and [laravel_hhvm](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/php-laravel/benchmark_config.json#L54)), the platform is specified as "hphp."  This wasn't familiar to me, but [it's apparently a thing](https://github.com/facebook/hhvm/tree/master/hphp).  Again, as a layperson, I do not know how hhvm compares to hphp.  Am I to understand that hhvm alone is not sufficient to run PHP code?  So "hphp" is more of a correct platform name?

Should we relabel all of our hhvm-enabled tests as "hphp"?  Is that meaningful and clear to people who know and use hhvm with PHP code?  Or is it better to relabel all hhvm-enabled tests as simply "hhvm"?  The latter seems more reasonable to me as an outsider.  I roughly know what hhvm is, but I had never heard of hphp.

It's also possible I'm missing something even more subtle and the present naming fragmentation *is warranted*.  Perhaps our symfony2 on hhvm implementation is in fact using a different platform than our codeigniter on hhvm implementation.

Can any subject matter experts take a closer look at this and help out with platform classification?

**Comment by cjnething** [comment]
It looks like HPHP was discontinued in 2013 and was replaced by HHVM. This was documented [here](http://hhvm.com/blog/575/joining-retirement-testing-and-bankruptcy) and [here](https://www.facebook.com/notes/facebook-engineering/speeding-up-php-based-development-with-hhvm/10151170460698920/). From what I can tell, all the tests are using hhvm.sh which is downloading HHVM, so they should all be up-to-date (HHVM supports both Hack and PHP 5/7).

**Comment by knewmanTE** [comment]
Closing this issue as this appears to have been resolved.
