### ISSUE TITLE
round 10. ImportError: No module named colorama

### ISSUE THREAD

**Issue by cheers00** [TechEmpower/FrameworkBenchmarks#1735]
I am trying to run the round-10 benchmarks  and I cloned round-10 branch and when I run ```nohup python toolset/run-tests.py```, I am getting the following error. 

Clone command: 
```git clone https://github.com/TechEmpower/FrameworkBenchmarks.git --branch=round-10```

Error:
```
tfb@tfb-app:~/FrameworkBenchmarks$ tail nohup.out 
Traceback (most recent call last):
  File "toolset/run-tests.py", line 11, in <module>
    from benchmark.benchmarker import Benchmarker
  File "/home/tfb/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 30, in <module>
    from colorama import Fore, Back, Style
ImportError: No module named colorama
```

**Comment by msmith-techempower** [comment]
http://frameworkbenchmarks.readthedocs.org/en/latest/Development/Getting-Started/

These are all the instructions required to get your environment set up to run the benchmark suite.
