### ISSUE TITLE
wrk command line uses concurrency for timeout

### ISSUE THREAD

**Issue by purplefox** [TechEmpower/FrameworkBenchmarks#1749]
The generated work command lines use the value of concurrency for timeout too:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L65

This can result in a lot of timeouts as it usually results in a value that is too low.

I can't think of a good reason why the timeout should use this value. A more sensible value would be related to duration, or a constant value (e.g. 15s).

**Comment by methane** [comment]
Is 1sec so low on 1 concurrency?
Which benchmark may be heavy?

**Comment by purplefox** [comment]
The generated script omits the "S" to denote seconds, so who knows whether this is seconds, milliseconds or something else - it's ambiguous.

But even if it was seconds, it doesn't make a lot of sense to use concurrency for this value. E.g. running a test with concurrency value of 1024 - would set the timeout to 1024 seconds - but if the test only runs for 15s this is meaningless.

As mentioned above, I don't see why timeout should be related to concurrency - it seems an arbitrary choice. It would be more sensible imo to just use a constant or something related to duration.

**Comment by methane** [comment]
Since this benchmark project measures "throughput".

Attacker (client)'s timeout should be long enough compared with server-side.
Otherwise, server may process requests which already timed-out and benchmark result
doesn't show real throughput.
This is why wrk's timeout should be so long.

I agree 1024sec timeout is meaningless for 15sec test.
But have you been bitten by too long timeout?

**Comment by purplefox** [comment]
The wrk timeout behaviour confuses me.

If I run a test with timeout = 16 and duration of 15 seconds, I get the following results

wrk/wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 1024 --timeout 16 -t 2 http://127.0.0.1:8080/plaintext -s pipeline.lua -- 100
Running 15s test @ http://127.0.0.1:8080/plaintext
  2 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    55.70ms   35.51ms 461.63ms   77.80%
    Req/Sec     0.87M    37.50k    1.00M    69.03%
  Latency Distribution
     50%   48.12ms
     75%   71.47ms
     90%   99.52ms
     99%  179.74ms
  25803100 requests in 15.00s, 3.17GB read
  Socket errors: connect 0, read 0, write 0, timeout 241
Requests/sec: 1720668.49
Transfer/sec:    216.61MB

As you can see there are some timeouts. This implies to me that the timeout value when "S" is omitted cannot be in seconds. How can you get timeouts on a 15 second test if the timeout value was 16 seconds?

So I'm guessing that, if you omit the "S" then timeout is interpreted as milliseconds, and is way too low. Either that, or wrk is buggy.

**Comment by methane** [comment]
Which version of wrk do you use?

**Comment by methane** [comment]
And could you try without `-s pipeline.lua`?
It makes hard to investigate.

**Comment by purplefox** [comment]
I am using whatever version of wrk that techempower benchmarks uses (I just copied the binary from the VM that it setup).

Here's some more evidence of strange wrk timeout behaviour:

wrk/wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 60s -c 1024 --timeout 160s -t 2 http://127.0.0.1:8080/plaintext -s pipeline.lua -- 100
Running 1m test @ http://127.0.0.1:8080/plaintext
  2 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    62.75ms   36.90ms 512.16ms   72.54%
    Req/Sec   821.81k    85.68k    1.04M    67.03%
  Latency Distribution
     50%   55.34ms
     75%   80.28ms
     90%  107.70ms
     99%  188.47ms
  98105700 requests in 1.00m, 12.06GB read
Requests/sec: 1635038.56
Transfer/sec:    205.83MB

As you can see here the duration of the test is 60 seconds and I set timeout to 160 seconds (and this time I included the "s" so it's unambiguously seconds), and I still get timeouts!

This makes no sense to me.

I will try without pipelining too.

**Comment by purplefox** [comment]
Sorry, I pasted the wrong one, here's the one showing the timeouts:

wrk/wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 60s -c 1024 --timeout 160s -t 2 http://127.0.0.1:8080/plaintext -s pipeline.lua -- 100
Running 1m test @ http://127.0.0.1:8080/plaintext
  2 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    95.76ms  167.26ms   2.54s    96.79%
    Req/Sec   680.36k   164.28k  784.06k    91.74%
  Latency Distribution
     50%   66.68ms
     75%   97.58ms
     90%  141.16ms
     99%  848.11ms
  80817000 requests in 1.00m, 9.94GB read
  Socket errors: connect 0, read 102, write 0, timeout 214
Requests/sec: 1346981.32
Transfer/sec:    169.56MB

**Comment by purplefox** [comment]
And here's one without pipelining, also showing timeouts even though test duration is 60s and timeout value=160s:

wrk/wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 60s -c 1024 --timeout 160s -t 2 http://127.0.0.1:8080/plaintext
Running 1m test @ http://127.0.0.1:8080/plaintext
  2 threads and 1024 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.67ms    1.22ms 410.75ms   89.87%
    Req/Sec   165.22k    25.99k  337.67k    79.20%
  Latency Distribution
     50%    1.57ms
     75%    1.75ms
     90%    2.25ms
     99%    3.87ms
  18685907 requests in 1.00m, 2.30GB read
  Socket errors: connect 0, read 0, write 0, timeout 1644
Requests/sec: 311433.25
Transfer/sec:     39.20MB

**Comment by methane** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/client.sh#L26
TE/FB uses wg/wrk@205a1960

After the version, wrk fixes the timeout issue via wg/wrk@5158fc1.

**Comment by purplefox** [comment]
Thanks for the detective work @methane !

**Comment by msmith-techempower** [comment]
> I am using whatever version of wrk that techempower benchmarks uses (I just copied the binary from the VM that it setup).

We provide a VM?

Glad to see that the confusion with wrk seems to have been resolved by @methane but if we provide a VM, it should have the correct versions of the software we use.

**Comment by purplefox** [comment]
My understanding of the situation:

1. benchmarks are currently using a buggy version of wrk that reports timeouts incorrectly. That should be upgraded as pointed out by @methane 
2. The version of wrk I was using was the one by used by the benchmarks - I just copied it

**Comment by msmith-techempower** [comment]
Got it, thanks @purplefox and @methane

**Comment by purplefox** [comment]
VM: If you follow the instructions on the README to startup using vagrant. It appears to set up a VM in order to run the tests (at least I can see VirtualBox whirring into action on my laptop) and provisions it with stuff including wrk.
That's the wrk I copied.

**Comment by msmith-techempower** [comment]
Ah, the vagrant work is pretty out-dated at this point. @hamiltont initiated that push to make it simpler for people, but as his availability is much less these days, it has fallen by the wayside. I almost always recommend contributors set up their environment manually following the instructions on the ReadTheDocs pages.

I will spend some time and try to get `wrk` updated in a PR later.

**Comment by purplefox** [comment]
That's good to know.
But if it's the case then it might be a good idea to remove the getting started instructions on the README that use vagrant, as that's what most ppl will try first probably :)

**Comment by msmith-techempower** [comment]
Wow, I never got to this, but it definitely needs to be done prior to Round 12.

**Comment by msmith-techempower** [comment]
Sigh, still haven't gotten to this.

**Comment by methane** [comment]
Now this project uses wrk 4.0.1.  This bug has been fixed in 4.0.0.

**Comment by msmith-techempower** [comment]
I do not believe that is true; we are still passing the concurrency with the timeout flag `--timeout $c` https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L66

**Comment by methane** [comment]
@msmith-techempower Original issue is a lot of timeout.  Using concurrency for timeout was not an issue.

See #855 for why I chose concurrency for timeout.  Constant timeout is worse than concurrency.

**Comment by msmith-techempower** [comment]
Understood; closing.
