### ISSUE TITLE
NodeJS json handler doesn't instatiate the result object map

### ISSUE THREAD

**Issue by DamianEdwards** [TechEmpower/FrameworkBenchmarks#1750]
It appears that the NodeJS json handler isn't quite following the stated requirements as it doesn't instantiate a new result object on each request, rather it stringifies a shared object.

See https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/helper.js#L4

**Comment by msmith-techempower** [comment]
Hmm, fair point (maybe). I'm not NodeJS expert, but if this were PHP, for example, then that script (and that variable) would be re-executed on every request; does NodeJS handle these scripts similarly?

**Comment by DamianEdwards** [comment]
I believe not. This script (helper.js) is "required" in by the routing script, which is in turn required by the create-server script. These are all run just once during application start. You can pretty easily tell what runs per request because it's encased in a `function (req, res)`

**Comment by msmith-techempower** [comment]
Then it might be cheating. I suppose an easy test would be to add something like a counter and on request-N update the value of that object, and if request-N+M have that updated object, then NodeJS is cheating; if not, then it's probably the scenario I described.

**Comment by DamianEdwards** [comment]
I did that just and verified that the same object is being used.

**Comment by msmith-techempower** [comment]
Perfect, going to ping @bhauer to see what we should do for publishing round 11 results.

**Comment by DamianEdwards** [comment]
FWIW it doesn't appear to change the results on my rig here, but of course we should correct the test anyway.

**Comment by msmith-techempower** [comment]
I agree - if it's technically cheating, then we should fix it (potentially other nodejs tests are also doing this, as well).

**Comment by bhauer** [comment]
Let's roll with Round 11 results as is, based on Damian's input that the results don't notably differ in a spot check.  But let's definitely get the implementation changed so that Round 12 captures results that are correct.

@msmith-techempower Let's chat to see if we can make someone available here to help with checking the other JavaScript tests.

**Comment by zapov** [comment]
Better solution would be to fix your test and pass in an argument to be returned.
UrWeb too doesn't instantiate objects and why should it? Fix your test so you don't need to manually check every implementation if it's behaving "correctly"

**Comment by msmith-techempower** [comment]
@bhauer I am inclined to close this and allow this type of implementation for now; thoughts?

**Comment by nbrady-techempower** [comment]
I've solved this issue in part of my PR #1835
The object is now being instantiated at the time of the json request, within the callback function.
