### ISSUE TITLE
NODE_ENV variable

### ISSUE THREAD

**Issue by comprehendreality** [TechEmpower/FrameworkBenchmarks#1764]
can someone confirm the node (and various node frameworks) environment variable is set to production for these benchmarks? there is a huge performance penalty when this variable is not set or set to something other than 'production'. i took a look around the code and couldnt find anything which indicated the environment variables used. can someone confirm this is being set?

for reference on the correct setting:

http://apmblog.dynatrace.com/2015/07/22/the-drastic-effects-of-omitting-node_env-in-your-express-js-applications/

**Comment by hamiltont** [comment]
Yes, it is. See https://github.com/TechEmpower/FrameworkBenchmarks/blob/6594d32db618c6ca65e0106c5adf2671f7b63654/toolset/setup/linux/languages/nodejs.sh

For context, a framework that depends on nodejs will declare an `fw_depends nodejs` (see https://github.com/TechEmpower/FrameworkBenchmarks/blob/6594d32db618c6ca65e0106c5adf2671f7b63654/frameworks/JavaScript/nodejs/setup.sh#L3 for example). This will eventually invoke that nodejs.sh script, which will always call `source $IROOT/node.installed`
