### ISSUE TITLE
Node.js not using clustering?

### ISSUE THREAD

**Issue by asilvas** [TechEmpower/FrameworkBenchmarks#1774]
Unless I'm missing something, it appears the Node.js tests do not leverage the available cores via the `cluster` module, which is how Node.js by design scales (it can do the same via other proxy layers, but this one is built-in). Happy to do a PR, but wanted to verify.

**Comment by Sinewyk** [comment]
[forking here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/app.js#L7)

**Comment by asilvas** [comment]
Thanks @Sinewyk
