### ISSUE TITLE
PyPy should not use python-mysqldb

### ISSUE THREAD

**Issue by Dith3r** [TechEmpower/FrameworkBenchmarks#1779]
Hi,

I've done some benchmarks of mysql libraries with pypy 4.0.1:

Lib |	Version	| Queries per second
----|---------------|---------------------------
PyMySQL|0.6.7|13590
MySQL connector|2.1.3|10688
MySQLdb|1.2.5|5841

I've seen yours explanation for not trying different libs for databases access, but i think that this need to be reconsidered one more time.

**Comment by methane** [comment]
I've intended to not use MySQL-python on PyPy.  But it was used accidentally.
Thank you for pointing it out.

**Comment by methane** [comment]
There are two PyPy + MySQL frameworks: Flask and Bottle.
Bottle used PyMySQL correctly.  I fixed Flask-pypy vai #1783.
