### ISSUE TITLE
CodeIgniter 2 should be updated

### ISSUE THREAD

**Issue by DevotionGeo** [TechEmpower/FrameworkBenchmarks#1790]
CodeIgniter 2 with mysql driver is used, it would be better to use CodeIgniter 3 with mysqli or pdo driver.

**Comment by DevotionGeo** [comment]
The real change will come when you use PDO or mysqli, where the huge difference between CI and PHP (no framework) for single query will decrease.

**Comment by nbrady-techempower** [comment]
Added to #1803. Please refer there for language/framework additions/updates.
