### ISSUE TITLE
New Frameworks / Languages

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#1803]
In an effort to keep the issues from becoming too cluttered, the following is a list of suggested frameworks and languages for future rounds of The Framework Benchmarks. If there is a language or framework you would like to see added in the future, you may submit a pull request with your test or leave a suggestion in the comments below.
##### C
H2O

##### C++
Casablanca
CppCMS
ffead
Pion
Proxygen

##### C#
Akka

##### Erlang
Mochiweb
Nitrogen
Zotonic

##### Gallina
Pluto

##### Haskell
Happstack

##### Java
Grails (Update to 3.0.x)
Stripes

##### PHP
Aura
CodeIgniter (Update to 3)
Drupal
Phalcon (Update to 2.0) 
Smce
Smce2
Swool
ThinkPHP

##### Ruby
Cuba
Goliath
Lotus
Raptor (Phusion Passenger 5)
Reel
Webmachine

### Languages

Nim (Update)
R

**Comment by harikt** [comment]
A wiki page would have been fine, so people can come add.

There are lots of newer versions of the framework. Probably the version also appended would be nice.

Eg : Slim 2, 3 . Zend Expressive , Radar.

**Comment by nbrady-techempower** [comment]
@harikt :+1: 
https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features

**Comment by harikt** [comment]
Thank you.

**Comment by mfirry** [comment]
Should I just edit the list?

**Comment by RenaudParis** [comment]
Hi,

Could you please add PHP 7 whenever you get the chance? For now it is still a bit recent, but it will become relevant very soon.

Thank you,

**Comment by msmith-techempower** [comment]
PHP 7 was included in Round 12 results.

**Comment by RenaudParis** [comment]
I'm sorry, if I asked it is because I saw "php5-raw", so I guessed it was PHP 5. Is "php5-raw" actually PHP 7?

**Comment by msmith-techempower** [comment]
`PHP` is php7, `PHP5` is php5

**Comment by RenaudParis** [comment]
Ooooh, okay, I did not see this distinction! Forgive my mistake!
But how come PHP 7 is slower than PHP 5, whereas it is commonly accepted that it is significantly (up to twice) faster? It baffles me...
Thanks anyway for precising it for me!

**Comment by methane** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/php/benchmark_config.json#L68

Both of php-raw and php5-raw were php7.
php5-raw should use `setup_php5` instead of `setup`.

**Comment by msmith-techempower** [comment]
> Both of php-raw and php5-raw were php7.
> php5-raw should use setup_php5 instead of setup.

Good catch.

@nbrady-techempower Can you get a PR for this?

**Comment by RenaudParis** [comment]
Ok that's why they are almost at the same performance then! Dying to see the new updated charts :)
