### ISSUE TITLE
Enable gcServer for asp.net and .net

### ISSUE THREAD

**Issue by ashotmuradian** [TechEmpower/FrameworkBenchmarks#1809]
There is a need to enable gcServer garbage collection mode for asp.net and .net projects in general. It is significant configuration parameter for .net benchmarking and it need to be enabled manually by defining it in app.config configuration file in sources. The only case gcServer garbage collection mode is enabled by default is when it is hosted in IIS.

**Comment by nbrady-techempower** [comment]
Hi @ashotmuradian. If this is still relevant we would love it if you opened a pull request for it. Next round previews are starting soon. Thanks!
