### ISSUE TITLE
Travis CI is inconsistent.

### ISSUE THREAD

**Issue by blee-techempower** [TechEmpower/FrameworkBenchmarks#1859]
Base on what I experienced last couple weeks, I found some problems of travis-ci.
Travis-ci test takes long time to finish, but sometimes it gives incorrect result. Travis-ci test result looks inconsistent sometimes.

Please consider these cases.

## Case 1 : “Travis-ci returns incorrect result sometimes ; result is not consistent.”

First of all there is no major changes between these two snapshots. I just rollback the code.(re allowing sudo to few statements.) My change only affect to CSharp related frameworks That’s all.

Please compare these two. Pay attention to D/vibed, Dart/dart-raw, Dart/redstone.

[snapshot1](https://travis-ci.org/blee-techempower/FrameworkBenchmarks/builds/100199022)
vs.
[snapshot2](https://travis-ci.org/blee-techempower/FrameworkBenchmarks/builds/100408200)

My change only affect to CSharp related frameworks because I only modified ‘mono.sh’ and ‘xsp.sh’ file. So those three test result must be same on both snapshot. But it’s not same. 

To verify this, I repeated same test several times myself. I often got inconsistent result.

Here is another evidence from #1852.

I only change Python/flask related file. I did not touch config files.

You can see what I changed here.
[file change](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1852/files)

Here is the travis-ci result.
[test result](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/100259881)

That travis-ci test failed because of Go/fasthttp.

Well, doesn’t make sense. Right?

My conclusion is Travis-CI is not stable. So my suggestion is we need to look at those pull requests which fail travis-ci test more carefully.

I can repeat the failed test until I get correct result just making dummy changes. But travis-ci test is time consuming and I don’t want to see so many pull requests are in travis-ci queue.

In addition, please consider this case also.

## Case 2 : “Modification of config file causes travis-ci to test every single framework.”

If above case happens, test result of that pull request is always error unless requester did not disable unrelated frameworks on “.travis.yml” file.

What I experienced is if this case happens, most of time those requests are ignored because of error marks. 

So it just stays there for a while.

So please consider this case also.

**Comment by msmith-techempower** [comment]
I believe you are seeing another reason why we want to get away from `apt-get`.

When I check `vibed` from your tests, I see the one that failed did so because of:
```
Setup vibed: ERROR: /toolset/setup/linux/prerequisites.sh: Command 'sudo apt-get -yq update' exited with status 100 (dependency=dlang) (cwd=$FWROOT/installs)
```

Unfortunately, I don't think there is much we can do about this.

The second case is on my radar and I have some ideas for how to resolve it, but for now we just have to deal with it.

**Comment by blee-techempower** [comment]
@msmith-techempower 
In that case, the vibed, it seems apt-get causes trouble. 
What about this case? please look at go/fasthttp
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/100259881

**Comment by msmith-techempower** [comment]
This happens occasionally, but we really don't know what the issue is here. Our script claims there are no tests to run, and it fails instead of returning successfully. It's a false-positive, but probably not worth much time investigating as long as it happens rarely.
