### ISSUE TITLE
An idea how to make the build faster

### ISSUE THREAD

**Issue by kostya-sh** [TechEmpower/FrameworkBenchmarks#1880]
Currently packages like mysql, redis, postgresql are installed and set up even before a travis job checks if any tests need to run. As result an empty build that skips all tests takes 1-2 minutes, while it should only take 10-15 seconds (time for git clone and git log).

BTW not using 3-rd party libraries (colorama, progressbar and requests) in the script that decides if a job needs to run will save another 5 seconds per build ;)

**Comment by msmith-techempower** [comment]
We are definitely aware of this (and other) potential speed-up.

We essentially relied on travis to provide many of the software you mentioned back when we couldn't use `sudo`. Now that we can, we have been working on improving things, but it has been an admittedly slow journey.

**Comment by methane** [comment]
Caching `~/.cache/pip` makes installing python libs fast.
https://github.com/msgpack/msgpack-python/blob/master/.travis.yml#L2-L4

**Comment by methane** [comment]
How about `fw_get` caches downloaded file to `~/.cache/tfb/download` or somewhere,
and setting the directory to travis cache?

**Comment by nbrady-techempower** [comment]
> Currently packages like mysql, redis, postgresql are installed and set up even before a travis job checks if any tests need to run. As result an empty build that skips all tests takes 1-2 minutes, while it should only take 10-15 seconds (time for git clone and git log).

I've done some research on this recently. Unfortunately the services section of travis is run before any scripts, including the before_install scripts so there's not much of a way around that for mongodb, postgres, and mysql. The dream scenario would be to build a matrix dynamically with `git diff` or the like ahead of time and has been brought up with the travis people; they simply don't have it in their roadmap. Caching installs might be a way to go but for now we want to make sure each framework installs everything correctly on its own. Going to close this, noting that work on travis is ongoing.
