### ISSUE TITLE
Luminus performance drop between Rounds 10 and 11?

### ISSUE THREAD

**Issue by k-r-g** [TechEmpower/FrameworkBenchmarks#1889]
In Round 10, Luminus had similar performance numbers to Compojure, as expected since they are both Clojure frameworks. However, in Round 11 it seems like Luminus performance decreased significantly in comparison.

* JSON R10: 91,373; R11: 28,701
* Single query R10: 41,898; R11: 7,288
* Multiple queries R10: 1,187; R11: 483
* Fortunes R10: 23,313; R11: 8,813
* Plaintext R10: 91,584; R11: 29,645

I'm concerned that perhaps one of the changes in #1591 left something in development mode. For example, is logging fully disabled?

While Luminus is getting attention, I think it is also worth changing the database connection pool from c3p0 to HikariCP, as was done for Compojure and others. The performance improvement is striking.

@yogthos Is this something you have interest in investigating? I have only the most basic Clojure knowledge and feel out of my depth here.

**Comment by yogthos** [comment]
Yeah, I think the benchmark is quite a bit out of date now. Luminus has gone through a few revisions since and it would make sense to bring it up to the latest version. I'll take a look at doing a PR for that.

**Comment by k-r-g** [comment]
Excellent!

**Comment by yogthos** [comment]
just made a PR that should update to the latest version https://github.com/TechEmpower/FrameworkBenchmarks/pull/1890

**Comment by k-r-g** [comment]
Woo! Thanks @yogthos for updating things. I'm looking forward to seeing the performance in the next round.

**Comment by yogthos** [comment]
yeah, hopefully it should run better now :)
