### ISSUE TITLE
python: ideas for round 13

### ISSUE THREAD

**Issue by methane** [TechEmpower/FrameworkBenchmarks#1908]
I don't have time before round 12, so these ideas will be implemented before round 13.
cc: @GMLudo 
- [ ] PyPy should use uWSGI instead of gunicorn:
  I use Python/C API based fast HTTP workers (meinheld) on gunicorn.
  But Python/C API is slow on PyPy.  So I use pure Python worker (tornado) + gunicorn.
  Now PyPy provides shared library and uWSGI support CFFI based approach.
  So we should switch to uWSGI in the case of PyPy.
- [ ] Use PGO
  Now we use standard Python build.  It's slower than binary provided by Debian / Ubuntu about 10%.
  Most important difference between standard build and distribution's build is PGO (Profile Guided Optimization).
  On Python 3.5, we can use PGO easily.  Just use `make profile-opt` instead of `make`.
  But it takes about 30 minutes to build.  It's too slow to build on Travis.
  We should try portable binary distribution like miniconda.
- [ ] DB connection via threadpool vs asyncio
  When using asyncio, there are two approach to interact with database: async or threadpool.
  Overhead of async programming in Python is larger than overhead of thread switching [1].
  I want to compare two approaches in this benchmark project.

[1]  http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/

**Comment by methane** [comment]
I tried uWSGI/PyPy behind nginx setup.
It's performance is far poor when compared with current gunicorn/tornado setup.

CPU usage of nginx is high since uwsgi protocol doesn't support keep-alive.
nginx opens unix socket for each request.
uWSGI 2.1 (not released yet) has `--http11-socket` option. So I'll switch to uWSGI 2.1 when it is released.
For round 13, I keep current gunicorn/tornado setup.

**Comment by methane** [comment]
https://github.com/methane/FrameworkBenchmarks/pull/2

Using PGO requires long building time.
Building both of Python 2 and 3 with PGO is not acceptable.
Travis timed out.

**Comment by Dith3r** [comment]
Hi,

Up to uWSGI and PyPy - did you try using [native http](http://uwsgi-docs.readthedocs.org/en/latest/HTTP.html) support from uWSGI? Also best option for python environment is just to update PyPy and python to latest stables releases and change usage mysqldb to pymysql if applications is run on JIT.

**Comment by methane** [comment]
@Dith3r There is test using uWSGI without nginx.
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/uwsgi/setup.sh

Generally speaking, uWSGI should be behind reverse proxy like nginx.  So I don't use the setup for many frameworks.
http://uwsgi-docs.readthedocs.org/en/latest/HTTP.html#can-i-use-uwsgi-s-http-capabilities-in-production

But your comment reminds me that I can use HTTP keep-alive behind nginx.  I'll try it later.

**Comment by GMLudo** [comment]
> Overhead of async programming in Python is larger than overhead of thread switching

Since this article, several things are moved, like the benchmark script used at the first time of this article ;-)

Anyway, it's a very good idea to test that.
Even, it should be strange, it should be interesting to test also with mysql+asyncio.run_in_executor, because pure asyncio mysql driver is in pure python only.
I shouldn't be surprised that asyncio.run_in_executor could be faster in this case.

**Comment by methane** [comment]
> because pure asyncio mysql driver is in pure python only.
> I shouldn't be surprised that asyncio.run_in_executor could be faster in this case.

Yes, lack of extension modules is the biggest overhead of async programming in Python.

**Comment by msmith-techempower** [comment]
This hasn't been touched in almost a year; can this be closed or is this on-going?

**Comment by nbrady-techempower** [comment]
I think this can be closed for now since there does t seem to be any work on it or new conversation. The eventual move to ubuntu 16.04 and python 3 for the toolset might inspire more conversation.

**Comment by GMLudo** [comment]
Hi,

I'm not dead ;-), I've planned to contribute for round 14, especially because we have several improvements now with Python 3.6, uvloop, sanic...
I've made some branches, I'll plan to create PRs before FOSDEM.

Have a nice week.

**Comment by nbrady-techempower** [comment]
Hey @GMLudo! We've made some recent changes to the toolset as well and cleaned up some things so if you need anything please let us know!

**Comment by GMLudo** [comment]
Awesome ! I'll check that soon :-)
