### ISSUE TITLE
Upgrade to MongoDB 3.2

### ISSUE THREAD

**Issue by andregmoeller** [TechEmpower/FrameworkBenchmarks#1930]
The Framework benchmark project is currently using MongoDB 2.6.X, which is relatively 
"old" and doesn't include the WiredTiger storage engine. Starting in 3.2, MongoDB uses the WiredTiger storage engine as the default storage engine (see [WiredTiger as Default](https://docs.mongodb.org/manual/release-notes/3.2/#wiredtiger-as-default)). Therefore I expect that most new MongoDB-projects will use the WiredTiger storage engine.

So, I would like to suggest to upgrade to MongoDB 3.2.

**Comment by nbrady-techempower** [comment]
Captured in the Wiki, thanks!
