### ISSUE TITLE
Problem with '--clean' option of toolset/run-tests.py

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#1934]
This functionality is quite new (https://github.com/TechEmpower/FrameworkBenchmarks/commit/34b79546ea7405a9876332894e5b1269ec246b15#diff-f92ef1689e8d44a3ba6ded6ba5ee3853).
The problem is that looking at the description I expect it just to clear the `results directory`. But when I call it like this './toolset/run-tests.py --clean' it starts to execute tests.
I'm using the `vagrant-development` virtual machine.
Am I missing something? Has any one observed the same behavior?

**Comment by nbrady-techempower** [comment]
Thanks for bringing this to our attention. The functionality was working for me in my test environment, but I will spin it a new box and try it again.

**Comment by nbrady-techempower** [comment]
Also i think I misunderstood what you were saying before, but the whole point of running the 'run-tests' script is to actually run or verify tests. The option is provided for the purpose of removing the results directory before tests are run.

`./toolset/run-tests.py --mode verify --test gemini --clean`

if all you want to do is remove the results directory, just `rm -rf results`

**Comment by zloster** [comment]
Thank you very much for you time and the provided clarification.
