### ISSUE TITLE
When will the next round (round-12) release ?

### ISSUE THREAD

**Issue by DevotionGeo** [TechEmpower/FrameworkBenchmarks#1936]

**Comment by warmchang** [comment]
From past experience, I think will not be completed until the middle of 2016.

**Comment by zloster** [comment]
TFB team usually announces when they will do the next round in the Google group.
This is [the thread](https://groups.google.com/forum/?fromgroups=#!topic/framework-benchmarks/Hq4qxj0TL9o) for the next round. According to the text there tomorrow 22nd February we should see the _first preview_ results.

**Comment by warmchang** [comment]
@zloster , so fast, aha.

**Comment by zloster** [comment]
@warmchang There is some news about this with _important information_. Check the Google group.

**Comment by bhauer** [comment]
Echoing something I just [posted on the Google Group](https://groups.google.com/d/msg/framework-benchmarks/Hq4qxj0TL9o/oOE_eCYbCAAJ), we have data for Round 12 that we're working to post soon.

Our physical hardware environment will be permanently shut down imminently and are rushing to conclude Round 12 as soon as possible.  For Rounds 13 and beyond, we will need to set up a new hardware environment.
