### ISSUE TITLE
Publish TFB-Round-12 data

### ISSUE THREAD

**Issue by valyala** [TechEmpower/FrameworkBenchmarks#1951]
It would be great to have TFB-Round-12 repository with raw data and logs for the Round 12. This repository should look like [TFB-Round-11](https://github.com/TechEmpower/TFB-Round-11). I need this data for investigating the root cause of failing `fasthttp-mysql-prefork` and `fasthttp-postgresql-prefork` benchmarks.

**Comment by nbrady-techempower** [comment]
@valyala They are up and ready for you to view https://github.com/TechEmpower/TFB-Round-12

**Comment by valyala** [comment]
Thanks!

**Comment by nbrady-techempower** [comment]
They're going to end up having a permanent location here because of the file size restrictions on github and not really needing version control for them. http://tfb-logs.techempower.com/

**Comment by valyala** [comment]
Nice! So fasthttp in 'prefork' mode failed due to the following error - see [the corresponding log file](http://tfb-logs.techempower.com/round-12/peak/linux/2016-02-22-final/latest/logs/fasthttp-postgresql-prefork/out.txt):

> The OS doesn't support SO_REUSEPORT: protocol not available

This looks strange, since SO_REUSEPORT has been added to [linux kernel 3.9](https://lwn.net/Articles/542629/), while the OS is running on 3.14 according to [logs](http://tfb-logs.techempower.com/round-12/peak/linux/2016-02-22-final/latest/logs/fasthttp-postgresql-prefork/out.txt):

> GNU/Linux 3.13.0-30-generic x86_64

**Comment by nbrady-techempower** [comment]
Interesting, I would open that as another issue though the next round of testing will not be using those environments.
