### ISSUE TITLE
FastHTTP Should be only 1 directory

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1996]
Currently, there are two directories (mysql and postgresql), but these should be one dir with separate test/code as necessary. The current implementation has JSON/Plaintext tests implemented by both, but without any difference.

@valyala Could you give a hand refactoring these?

**Comment by valyala** [comment]
@msmith-techempower , I'll look into it.

**Comment by nbrady-techempower** [comment]
Can be closed once #2112 is merged

**Comment by valyala** [comment]
@nbrady-techempower , now it can be closed :)

**Comment by nbrady-techempower** [comment]
Thanks @valyala !
