### ISSUE TITLE
Revel should be one directory

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1998]
Currently, there are three directories (revel, revel-jet, and revel-qbs), but these should be one dir with separate test/code as necessary.

My understanding is that `revel` (the framework) is the same for both, but `jet` is used as the ORM for `revel-jet` whereas standard database stuff is done in Golang for `revel`. The same is true for `qbs`

**Comment by nbrady-techempower** [comment]
resolved with #2003 and #2114
