### ISSUE TITLE
PHP: Use new Slim 3, not Slim 2.2.0

### ISSUE THREAD

**Issue by adambro** [TechEmpower/FrameworkBenchmarks#2024]
Slim 3 is the current version, but tests are still done with Slim 2. Not to mention that they are failing im many tests in Round 12 (Fortunes, Queries, only JSON worked).

I can contribute Slim 3 example. Should it be as a separate directory (slim3) or rather update of exisiting Slim 2.x code?

**Comment by nbrady-techempower** [comment]
@adambro If it's easy for you to update the Slim 2.x code, you're more than welcome to do so with a pull request. If you think you're better off starting from the ground up, if Slim 3 has lots of breaking changes, you can create a new directory and we will probably scratch the Slim 2.x code if all goes well.

**Comment by adambro** [comment]
Question about DB classification: I'm using PDO, which is PHP's equivalent of JDBC. For that should I use DB=raw or maybe DB=Micro? Asking because PDO can create PHP objects directly out of result set.

**Comment by msmith-techempower** [comment]
`database` should be one of MySQL, Postgres, MongoDB, Cassandra, Elasticsearch, Redis, SQLite, SQLServer, or None as defined [here](http://frameworkbenchmarks.readthedocs.org/en/latest/Codebase/Framework-Files/?highlight=benchmark_config#benchmark-config-file).

`orm` is to what you are referring when talking about Full, Micro, or Raw. In this case, it looks like it is 'micro' in that it does some abstraction after you write a full query.

**Comment by adambro** [comment]
I've created PR #2030 just now. The `orm=raw` attribute, because it is the same for raw PHP.

**Comment by nbrady-techempower** [comment]
Can be closed once #2101 is merged
