### ISSUE TITLE
Why is perwendel - Spark not shown in the results

### ISSUE THREAD

**Issue by tchoulihan** [TechEmpower/FrameworkBenchmarks#2025]
Is spark failing the tests or something? I don't see it in the results.

**Comment by nbrady-techempower** [comment]
@tchoulihan I see Spark in the [Official Round-12 results](https://www.techempower.com/benchmarks/#section=data-r12&hw=peak&test=json)

**Comment by tchoulihan** [comment]
Yep that's true, sorry about that.
