### ISSUE TITLE
Please specify the number of cores in the published charts

### ISSUE THREAD

**Issue by amichair** [TechEmpower/FrameworkBenchmarks#2034]
For many servers, the number of cores makes a huge difference in performance under high load, probably more than any other factor. However in the published reports/charts this info is not readily apparent. The hardware is specified in the small bar on top of the charts, or in the tooltip over the hardware tab, but they don't actually specify this vital piece of information - that requires quite a bit of further digging for casual observers.

It would be great if those two places would explicitly mention the number of cores on the test hardware, and possibly the number of hyperthreads and core frequency. That would make the results and differences in hardware much easier to relate to.

**Comment by zloster** [comment]
@amichair There is a [special section](https://www.techempower.com/benchmarks/#section=environment) in the website with this information. Also [my comment here](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1768#issuecomment-189443298) adds some clarifications about Amazon `vCPUs`. Note that I haven't check if Amazon haven't changed their definition of `vCPU`.

**Comment by amichair** [comment]
In the environment section, for peak it says "40 HT cores" which is good. For i7 it doesn't say anything. For EC2 it says "2 vCPU each" but doesn't mention how many cores/HT a vCPU is. That's exactly my point - it requires digging in the site, open issues like the one you linked to, Intel specs, Amazon specs, etc.

It would be nice if you just wrote this info right there in the environment page specs, and even better, also on the results page bar/tooltip etc. A tiny change on the website can save people lots of time.

**Comment by nbrady-techempower** [comment]
Nothing wrong with this. Probably won't be any big updates to the current results website but I've got a TODOs going in the roadmap for a new results page. We may end up with some patches to the current results site in the meantime. 
https://github.com/TechEmpower/FrameworkBenchmarks/projects
