### ISSUE TITLE
What is source_code?

### ISSUE THREAD

**Issue by amichair** [TechEmpower/FrameworkBenchmarks#2035]
Looking at http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Add-Frameworks-or-Tests/ I can't find any mention of the source_code file - did I miss it?

I did find it mentioned in this issue tracker, and understood that it's used for SLOC stats. However, it is still unclear what should go in there - e.g., do build files (e.g. pom.xml) count? Some projects include it, others don't. How about the shell scripts (setup.sh etc.)? If one adds the project base directory, this gets included in the count. Also, for some reason most projects I've looked at have in source_code what looks like the complete directory tree, explicitly including all parent paths as well as all files in them. Why is all this necessary? It seems like adding only the root source directory is sufficient and the SLOC count is performed recursively anyway.

Please add a mention of the source_code file in the documentation, and clarify exactly what should and what shouldn't go in it. Or better yet, just remove this file and figure out automatically what the source code directory is and/or any other standard build files if they should be included (there are only so many options which you can gather from the existing projects). That would be much less error-prone and would provide you with more meaningful and consistent statistics with the same rules covering everyone. Maybe allow source_code as an override in special non-standard cases.

What do you think?

**Comment by msmith-techempower** [comment]
`source_code` is a file for specifying which files for a framework are source files.

This was largely added because PHP frameworks would include the entire bootstrap source code for their framework as a part of the directory structure and were penalized for having **way** more sloc than anyone else.

We MAY have addressed this in large part with our dependency management stuff in the suite, and this file can probably go away in favor of using sloc more simply.

**Comment by amichair** [comment]
I see this was closed, but what is the answer/resolution?

It's still not in the docs. Should all projects delete it? Are you deleting it for them? If it should still exist, then the questions above still have to be answered, here and somewhere in the docs...

**Comment by nbrady-techempower** [comment]
> source_code is a file for specifying which files for a framework are source files.

Probably going to move away from this altogether, however, if you'd like to see it in the docs while it remains, they are also open source. Please feel free to submit a PR.

**Comment by amichair** [comment]
When adding a new framework I followed https://frameworkbenchmarks.readthedocs.io/en/latest/Development/Add-Frameworks-or-Tests/ , where I still don't see any mention of adding the source_code file - am I missing it? I'm not sure how the link you just specified relates to it, I've never seen it before. So now I have another level of confusion about the documentation, unrelated to this issue :-)

In any case, this link doesn't answer the questions that were originally raised either, e.g. whether scripts and/or build files should be included (at the time some projects did and some didn't - I haven't checked it now to see if it's more consistent), whether adding only the root directory is enough (I got the answer above, but it's not in the docs, and again looking at other projects gives inconsistent usage).

Also it is unclear from the MAY above if this is now automated and so the file is redundant and no longer needed, or if it still needs to be manually maintained per project... I hope for the later.

You can do with this what you will, I just raised the confusion I myself encountered when adding a new project and following the docs, in case clarifying the docs can make it easier for newcomers.

**Comment by nbrady-techempower** [comment]
The link specified is in the documentation: http://frameworkbenchmarks.readthedocs.io/en/latest/Codebase/?highlight=source_code

Also, if you search for `source_code` in the search bar on the documentation site it is the first link. So though we may not have everything where people might expect to see it, we'd hope they'd at least use the search functionality.

It's not automated yet. I'll add a link in the Add-Frameworks-or-Tests section pointing to this file. As far as the other questions about it, it's not 100% spec'd out, and can change from framework to framework. Don't include the build scripts.

`source_code` isn't a big deal and shouldn't be a blocker to you submitting a test. We can help you along in the Pull Request.

We would love it if people contributed to the documentation as well as their own personal projects.
