### ISSUE TITLE
Running nodejs framework on windows

### ISSUE THREAD

**Issue by kunalspathak** [TechEmpower/FrameworkBenchmarks#2037]
I am trying to get [node+chakracore](https://github.com/nodejs/node-chakracore) framework for windows running with existing `nodejs` benchmarks. However running the benchmarks need `wrk` tool that is not available on windows. 
I went through documentation, but didn't find satisfactory instructions on how to setup things on windows. Can someone help me with instructions on how to setup and populate database, run load server on windows?

**Comment by msmith-techempower** [comment]
We do not currently support windows - use VirtualBox (or similar) to spin up an Ubuntu instance.
