### ISSUE TITLE
Source code for Rapidoid benchmark should resemble real world application

### ISSUE THREAD

**Issue by edudar** [TechEmpower/FrameworkBenchmarks#2041]
Existing source code for this benchmark is written with low-level operations that are far from what Rapidoid advertises as one-liners in their docs. It seems natural to expect something like this
```
On.get("/").html(req -> {
    Resp resp = req.response();
    resp.contentType(MediaType.JSON_UTF_8);
    resp.content("hello");
    return resp;
});
```
instead of custom protocol implementation with very remote proximity to real world use cases. Or at least there should be two entries then: consumer optimized and byte-to-byte one.

**Comment by knewmanTE** [comment]
Resolved with #2193
