### ISSUE TITLE
Bump Hapi to at least 13.x

### ISSUE THREAD

**Issue by taoeffect** [TechEmpower/FrameworkBenchmarks#2046]
The benchmarks appear [to be using Hapi 8.6.0](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/hapi/package.json#L9), but Hapi is all the way up to 13.x now. They also pointed me to this JSON related PR that was recently merged: https://github.com/hapijs/hapi/pull/3014

**Comment by nbrady-techempower** [comment]
@taoeffect Thanks for pointing this out. Feel free to create a pull request for this update and target it toward the round-14 branch. I'll put it here https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features for now. Thanks!
