### ISSUE TITLE
Upgrade Elasticsearch to latest stable version

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#2054]
Currently version 2.3.3.

**Comment by nbrady-techempower** [comment]
Added here, thank you! If you'd like you're more than welcome to submit a pull request against the round-14 branch for this upgrade.

https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features
