### ISSUE TITLE
Ruby dependency gems versions are missing due to Gemfile.lock is not checked in to repository

### ISSUE THREAD

**Issue by Zloy** [TechEmpower/FrameworkBenchmarks#2077]
You set main gems versions in Gemfile - that's ok, These main gems, like sinatra, active-record, puma depend on a big number of dependency gems, which versions become fixed to certain values when you perform `bundle install` or simple bundle. This fixation is written in Gemfile.lock.

As you excluded Gemfile.lock from the repo, If  I try to reprodice your tests half a year later you did, my dependency gems would differ from yours significantly. That is bad.

Here is a quote of Yehuda Katz - the well known ruby blogger and also a contributor of bundler project:  
>    After bundling, always check your Gemfile.lock into version control. If you do this, you do not need to specify exact versions of gems in your Gemfile. Bundler will take care of ensuring that all systems use the same versions.

Please refer to http://yehudakatz.com/2011/05/30/gem-versioning-and-bundler-doing-it-right/

**Comment by nbrady-techempower** [comment]
@Zloy Could you help me understand this a little better? I'm not super familiar with how ruby does dependency management. The Gemfile in each framework that specifies the exact version number is *not* sufficient enough to ensure that those dependencies will be correct?

**Comment by Zloy** [comment]
> The Gemfile in each framework that specifies the exact version number is not sufficient enough to ensure that those dependencies will be correct

That is correct! 

Have a look at my **Gemfile.lock** generated in sinatra folder of TFB:

```
vagrant@TFB-all:~/FrameworkBenchmarks$ cat ./frameworks/Ruby/sinatra/Gemfile.lock
GEM
  remote: http://rubygems.org/
  specs:
    activemodel (4.1.4)
      activesupport (= 4.1.4)
      builder (~> 3.1)
    activerecord (4.1.4)
      activemodel (= 4.1.4)
      activesupport (= 4.1.4)
      arel (~> 5.0.0)
    activerecord-import (0.5.0)
      activerecord (>= 3.0)
    activesupport (4.1.4)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    arel (5.0.1.20140414130214)
    backports (3.6.8)
    builder (3.2.2)
    daemons (1.2.3)
    eventmachine (1.2.0.1)
    i18n (0.7.0)
    json (1.8.3)
    kgio (2.10.0)
    minitest (5.9.0)
    multi_json (1.12.1)
    mysql2 (0.3.16)
    puma (2.9.0)
      rack (>= 1.1, < 2.0)
    rack (1.6.4)
    rack-protection (1.5.3)
      tilt (~> 1.3, >= 1.3.4)
    sinatra-activerecord (2.0.2)
      activerecord (>= 3.2)
      sinatra (~> 1.0)
    sinatra-contrib (1.4.2)
      backports (>= 2.0)
      multi_json
      rack-protection
      rack-test
      sinatra (~> 1.4.0)
      tilt (~> 1.3)
    slim (2.0.3)
      temple (~> 0.6.6)
      tilt (>= 1.3.3, < 2.1)
    temple (0.6.10)
    thin (1.6.2)
      daemons (>= 1.0.9)
      eventmachine (>= 1.0.0)
      rack (>= 1.0.0)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    unicorn (4.8.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord (= 4.1.4)
  activerecord-import (= 0.5.0)
  activerecord-jdbcmysql-adapter (~> 1.3.9)
```

All these gems are dependencies. If someone runs `bundle` say 6 months ago many of these dependencies would change their versions to newer ones. And my Gemfile.lock would differ from his Gemfile.lock. 

Thus Gemfile contains the main gems you use directly in your code with their versions constraints. While Gemfile.lock contains the whole solution with all dependencies versions contraints in the verifiable and stable state.

**Comment by nbrady-techempower** [comment]
@zloy excellent! So we need to make sure each ruby framework has a working Gemfile.lock? Great stuff! Thank you!

**Comment by Zloy** [comment]
That's right, just remove Gemfile.lock from .gitignore, then run bundle and check in generated Gemfile.lock in the repo. It was my pleasure)

**Comment by nbrady-techempower** [comment]
I've mostly taken care of this while fixing the Ruby frameworks.

**Comment by Zloy** [comment]
OK, it's time to close that issue
