### ISSUE TITLE
prerequisites.sh needs fw_exists loaded

### ISSUE THREAD

**Issue by gmile** [TechEmpower/FrameworkBenchmarks#2092]
At the time `prerequisites.sh` is executed, `fw_exists` is not available (see the screenshot).

![image](https://cloud.githubusercontent.com/assets/207112/16179731/489a526c-3677-11e6-9f75-58fbe59982a0.png)

Above picture was taken when running vanilla `vagrant up`.

**Comment by nbrady-techempower** [comment]
@gmile `prequisites.sh` doesn't rely on `fw_exists`. If it does exist, it will exit because the prerequisites would have already been installed.

**Comment by nbrady-techempower** [comment]
oh I misunderstood, sorry. Good catch!

**Comment by LadyMozzarella** [comment]
See #2111
