### ISSUE TITLE
Wrong folder `toolset/deployment` in READMEs and shell scripts

### ISSUE THREAD

**Issue by Zloy** [TechEmpower/FrameworkBenchmarks#2100]
There is no such folder `toolset/deployment`. But there is `deployment` at the same level as `toolset`.
This wrong folder is referenced not only in Readme (which is just confusing), but also in shell scripts, which is ridiculuos 'cause scripts seem to work properly. Perhaps environment variables which contain wrong folders are not used anymore. 

[There are 13 occurences, check it out here](https://github.com/TechEmpower/FrameworkBenchmarks/search?utf8=%E2%9C%93&q=toolset%2Fdeployment&type=Code)

**Comment by nbrady-techempower** [comment]
@Zloy thanks for pointing that out. A lot of these files are windows related and have gone untouched for some time. The microsoft team is actually working on a new toolset for windows. That part of the toolset is obsolete and will be removed in round-14 or 15. The few others are also not being used, and will all be cleaned up moving forward. Thanks!

**Comment by Zloy** [comment]
Ok, I see. 

I've just destroyed my vagrant box and have built it from scratch. I haven't found any error messages like "This script must be run from the FrameworkBenchmarks directory" which should be echoed e.g. in [deployment/common/deployment.sh](https://github.com/TechEmpower/FrameworkBenchmarks/search?utf8=%E2%9C%93&q=toolset%2Fdeployment&type=Code)

Also `grep -Rl "This script must be run from" .` doesn't show any log file except of shell scripts. So, I guessed that e.g. [deployment/common/deployment.sh](https://github.com/TechEmpower/FrameworkBenchmarks/search?utf8=%E2%9C%93&q=toolset%2Fdeployment&type=Code) script wasn't run. Hmmm, strange. Its name implyes that it should be executed when vagrant builds Ubuntu box. Btw, probably we should not close that issue to not to forget fixing it.

**Comment by nbrady-techempower** [comment]
@Zloy agreed. I will leave this open.
