### ISSUE TITLE
Please unlist vertx-web results from round 12

### ISSUE THREAD

**Issue by pmlopes** [TechEmpower/FrameworkBenchmarks#2117]
I've implemented the benchmark and run it locally and got really different numbers than the ones listed on the website. Like many other frameworks I do believe that something went wrong during round 12 and would like that `vertx-web`, please note that I'm not referring to `vert.x`, to be unlisted.

I've updated the code in the mean time (with new commits) and would like to see it on round 13 though.

**Comment by nbrady-techempower** [comment]
@pmlopes I will see what I can do about getting that removal up the chain. Note that our testing environments will probably differ greatly from your local environment, but that all frameworks are tested in that same environment. Was there something specifically in the round-12 logs that caught your attention?

Can you point me to the new commits you're speaking of? I don't see that you've made any recent pull requests. Round-13 has been frozen and we're only accepting pull requests on round-14 for framework enhancements.

**Comment by pmlopes** [comment]
@nbrady-techempower one thing that is hard to explain are the huge differences between json/text benchmarks between vertx and vertx-web. The second performs about 5% from the base which is hard to believe since the code is give or take the same, and there should be a small penalty for vertx-web since it matches routes using regular expressions and does some wrapping of core classes. On development vagrant i see than i get around 8% performance penalty which i understand and think is correct, while the main benchmark shown a penalty of 500%.

If round 13 is already frozen I'd like it too to exclude vertx-web since I did not had a proper chance to run it with the updates environments
