### ISSUE TITLE
Tests failing in Vagrant with permissions denied errors

### ISSUE THREAD

**Issue by ryanlath** [TechEmpower/FrameworkBenchmarks#2156]
I haven't been able to successfully run any of the tests that I've tried (gemini, beego, echo, flask).  I don't think it's framework specific.

Example errors:
Gemini:
`Setup gemini: sed: couldn't open temporary file Docroot/WEB-INF/sed755m9x: Permission denied
Setup gemini: Setup has terminated`
Echo:
`Setup echo: ++ sed -i 's|tcp(.*:3306)|tcp(127.0.0.1:3306)|g' server.go
Setup echo: sed: couldn't open temporary file ./sed7ujaW7: Permission denied`
Flask:
`Server flask:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
Server flask:     fd = _os.open(file, flags, 0600)
Server flask: OSError: [Errno 13] Permission denied: 'tmpHUegMQ'
Server flask: Framework processes have terminated`

Example command:
`toolset/run-tests.py --install server --test gemini`

Genimi log attached:
[out.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/355841/out.txt)

I've tried making some of the Vagrant dirs and the host machine dirs world writeable...that got me a little farther, but not all the way.  Doesn't seem like I should have to, though.

**Comment by nbrady-techempower** [comment]
@ryanlath You said you figured it out after upgrading vagrant correct? Let me know. Closing for now.

**Comment by ryanlath** [comment]
I upgraded the vagrant box.  But I also ran a provision command (it was sort of suggested in an motd/output).  I was just trying anything, really.  I don't know vagrant.  Just want to run benchmarks.

**Comment by ryanlath** [comment]
For future reference, I believe it was running `vagrant provision` that actually fixed this error.
