### ISSUE TITLE
Systematic way of notifying framework partisans

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#2170]
Fairly often, some larger change in the benchmarks infrastructure breaks particular frameworks' execution, in a way that can't really be called a bug in any framework's original code.  I and others don't try to pay close attention to general progress on the benchmarks, but we want e-mail notification when our favorite frameworks break.  As an example, I missed #2074 for a few weeks, so the trivial fix for urweb was delayed.

I don't want to be notified by e-mail for each new issue opened here, but is there a way to, for instance, take advantage of metadata on which frameworks are involved in an issue and e-mail the appropriate people?  A coarse-grained but automatic method would, say, e-mail everyone who committed changes to that framework's files in the last 2 years.

The credibility of the results is really helped by knowing that the fans of each framework are kept up-to-date on when the code they contributed isn't working anymore, and it's unrealistic, I think, to expect everyone interested in one framework to watch carefully for all changes project-wide.

**Comment by msmith-techempower** [comment]
We MAY be able to leverage some of the love we get from Travis-CI to, say, e-mail recent contributors when a test goes from passing->fail.

That said, I feel like a LOT of the pain we experience from contributors stems from using dependency management in a poor way (though, not in your case, Adam). Small soap box rant: when using a dependency manager on a project with a handful of libraries, it is important to remember that a contribution to our suite should be considered a snapshot of time and it should run as-is until the end. Very often, contributors will include dependencies by simply naming them and not locking down the version used, which leads to a few months/years going by fine until the next version breaks the API upon which their tests relied and seemingly inexplicably their tests start failing out the blue.

This is a VERY hard bug for us (TE folk) to track down and fix as we are not experts in all of the frameworks/languages/stacks/etc in our suite and rely on the community for so much.

Getting off my soap-box, I agree; we do make changes to the toolset that occasionally causes unintended breakages of tests (like yours, Adam). We try to keep these as infrequent as possible, but having an alarm system like discussed here would go a long way.

**Comment by achlipala** [comment]
Another approach would be to make judgment calls about which breakages are serious enough, and then e-mailing the Google Group about each one.

**Comment by msmith-techempower** [comment]
We do a lot of git-fu as a part of our Travis-CI work; we can [according to the Travis-CI docs](https://docs.travis-ci.com/user/notifications/) notify people via e-mail when a build fails. This MAY not work exactly as we need it to simply because it looks like a project-wide list, rather than a specific contributor list.

**Comment by msmith-techempower** [comment]
It seems that we could also leverage another python script (a la [run_ci.py](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/run-ci.py)) to the [.travis.yml](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml) in the `after_failure` block. We would have to do more git-fu to figure out recent contributors, but that should not be all that difficult.

I do not know if we can do "passing->failing sends an alert", but we should be able to pretty easily do "failing sends an alert".

**Comment by nbrady-techempower** [comment]
@msmith-techempower I could look into setting this up on Monday, but I think we'd need to discuss it in more detail, like is this opt-in or opt-out, frequency, etc.

**Comment by steveklabnik** [comment]
I am also feeling this; I just noticed https://github.com/TechEmpower/FrameworkBenchmarks/issues/2074 says Rust stuff is broken!

**Comment by nbrady-techempower** [comment]
We should revisit this now. Since continuous benchmarking is in our very near future, we might be able to cultivate a mailing list of folks and pair them to a framework/language to receive notifications after a run. It might be possible to build something into a webapp that allows people to sign up/disable notifications for such things.

@ashawnbandy-te-tfb @knewmanTE

**Comment by msmith-techempower** [comment]
Agreed; try and get some traction from contributors.

**Comment by steveklabnik** [comment]
>  Since continuous benchmarking is in our very near future

:eyes: :heart_eyes:

**Comment by martin-g** [comment]
java/Wicket -> @martin-g

**Comment by nbrady-techempower** [comment]
I'm going to close this for now but add it to the roadmap. The addition of `mention-bot` and our updates to travis have had a significant impact on reaching out to the community. We're able to quickly identify if a framework suddenly starts failing and ping the contributor, and any changes made to a framework via pull request will ping the contributor with `mention-bot`.
