### ISSUE TITLE
iris, the new Golang framework

### ISSUE THREAD

**Issue by taggedboy** [TechEmpower/FrameworkBenchmarks#2171]
When would you people include the [iris framework](https://github.com/kataras/iris) for golang, its the fastest web framework after the fasthttp library for golang.
You can immediately start by using the [official book](https://kataras.gitbooks.io/iris/content/install.html).

**Comment by martin-g** [comment]
As soon as you, or someone else from the community, sends a Pull Request with the implementation.
The implementations are provided and maintained by the community. TechEmpower just provides the hardware and the tooling.

**Comment by nbrady-techempower** [comment]
@taggedboy: exactly as @martin-g says. when we have time it's fun to add new frameworks, but these are better added by those more familiar with the frameworks. Maintaining the tooling, running the previews and rounds, and ensuring that frameworks comply with the rules of the tests keep us fairly busy. If you're interested in submitting this framework and have not done any work with tfb before, please see the [TFB Development Guide](http://frameworkbenchmarks.readthedocs.io/en/latest/Development/). In the meantime, I'm going to close this and add the framework to the wiki.
