### ISSUE TITLE
Is it worth keeping PHP/micromvc?

### ISSUE THREAD

**Issue by knewmanTE** [TechEmpower/FrameworkBenchmarks#2174]
What the title says. For the PHP framework [micromvc](https://github.com/Xeoncross/micromvc), I am seeing that:
- It is no longer maintained
- Hasn't been updated in 3-5 years
- Is only compatible with PHP 5
- Its [website ](http://micromvc.com/)is defunct. You can find a [cached version](https://web.archive.org/web/20110201124701/http://micromvc.com/) of the site on the Web Archive, but there isn't a ton of info there
- The framework doesn't have a full test suite (only JSON, DB, and Queries are implemented)

Given these factors, it might make sense to remove the framework, as I don't imagine its results are particularly meaningful to anyone who might want to build with a PHP framework or compare different PHP frameworks.

That being said, it did perform decently well against other PHP frameworks on Round 12 (5th/31 on JSON, 7th/30 on DB, 17th/27 on Queries), but I don't know if that is reason enough to keep it in our suite.

**Comment by LadyMozzarella** [comment]
+1 for removing it. If the framework is no longer maintained, it isn't really relevant anymore. It may be best left performing well in the history of TFB rounds.
