### ISSUE TITLE
Missing Tests

### ISSUE THREAD

**Issue by knewmanTE** [TechEmpower/FrameworkBenchmarks#2178]
**Last updated: 1/27/2017**

I've noticed that there are a bunch of frameworks that are in our test suite, but are missing 1 or more of the 6 core tests (Plaintext, JSON, DB, Queries, Update, Fortune). Here is a compiled list of missing tests. For people looking to contribute to the project, this could be a great place to start off!

This _should_ be a comprehensive list, but if I missed something feel free to add it or let me know!

| LANGUAGE | FRAMEWORK | TESTS | NOTES |
| --- | :-: | --: | --: |
| C++ | poco | JSON |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| C | duda | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | haywire | JSON |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | libreactor | Update |  |
|  | lwan | Update |  |
|  | onion | Plaintext |  |
|  |  | Update |  |
| C# | evhttp-sharp | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | nancy | Update |  |
|  |  | Fortune |  |
| Clojure | aleph | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Crystal | crystal-raw | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Elixer | cowboy | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Erlang | chicagoboss | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | cowboy | Update |  |
|  |  | Fortune |  |
|  | elli | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | mochiweb | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Go | beego | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | webgo | Plaintext |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Haskell | snap | Update |  |
|  |  | Fortune |  |
|  | wai | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | yesod (mongodb-raw) | Update|  |
|  |  | Fortune |  |
| Java | activeweb (jackson) | Fortune |  |
|  | baratine | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | bayou | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | comsat-servlet | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | comsat-webactors | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | curacao | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | grizzly-bm | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | grizzley-jersey | Update |  |
|  | jetty-servlet | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | jetty | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | jlhttp | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | jooby | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | netty | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | play1 | Plaintext |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | rapidoid | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  | restexpress | Update |  |
|  |  | Fortune |  |
|  | tapestry | Update |  |
|  | undertow-jersey-c3p0 | Update |  |
|  | undertow-jersey-hikaricp | Update |  |
|  | vertx | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Lua | openresty | Update |  |
| Nim | jester | Plaintext |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| PHP | phalcon-micro | Plaintext |  |
|  |  |Update |  |
|  | zend | Fortune|  |
| Perl | dancer | Plaintext |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | plack | Plaintext |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | web-simple | Plaintext |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Python | falcon | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | tornado | Update |  |
|  |  | Fortune |  |
|  | uwsgi | Plaintext |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | wsgi | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Racket | racket-ws | Plaintext |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Ruby | grape | Fortune |  |
|  | ngx_mruby | Update |  |
|  |  | Fortune |  |
|  | rack | Fortune |  |
|  | rails-stripped | Plaintext |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Rust | hyper | JSON |  |
|  |  | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | iron | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | nickel | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | tokio-minihttp | DB |  |
|  |  | Update |  |
|  |  | Fortune |  |
| Scala | colossus | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | finagle | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | finatra | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | finch | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | s-server | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | scruffy | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |
|  | spray | DB |  |
|  |  | Queries |  |
|  |  | Update |  |
|  |  | Fortune |  |

**Comment by zloster** [comment]
@knewmanTE Could you update the table about the Fortune test: `servlet (postgre-raw)`. My merge request is accepted (#2326).

**Comment by knewmanTE** [comment]
@zloster: done!

**Comment by zloster** [comment]
@knewmanTE The combination `activeweb-jackson` and `Fortune` test is not applicable: there is no JSON serialization involved in this test. The difference between the two test implementations of `activeweb` is the usage of Jackson as JSON serialization library.

**Comment by nbrady-techempower** [comment]
Thanks @zloster 

This list needs to be updated and would now include the cached queries test. I'm going to close this for now and add writing a script to generate this output to the project roadmap.
