### ISSUE TITLE
Change rapidoid from a Realistic IA to a Stripped IA

### ISSUE THREAD

**Issue by mooman219** [TechEmpower/FrameworkBenchmarks#2194]
I feel as though the Rapidoid results are deceptive in their results, the implementation for their approach is very specific, hand writing the byte arrays and creating a specialized protocol. https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/rapidoid/src/main/java/hello/SimpleHttpProtocol.java

Idiomatic Rapidoid as described on their website ( http://www.rapidoid.org/ ) differs extremely from the "realistic" approach used in the benchmark. A simple json implementation as per recommendation is simply `On.get("/x").json("x");`, while the actual implementation in the benchmark goes as hand writing line endings.

I would like the IA (Implementation Approach) column to be changed from "Realistic" To "Stripped" to reflect this.

**Comment by mooman219** [comment]
It seems I'm not the only one having this opinion, see https://github.com/TechEmpower/FrameworkBenchmarks/pull/2193

**Comment by knewmanTE** [comment]
@mooman219 #2193 has been merged in! #2192 actually came up as the result of an internal discussion we had about the Rapidoid implementation.
