### ISSUE TITLE
Multiple servers tests

### ISSUE THREAD

**Issue by robertoestivill** [TechEmpower/FrameworkBenchmarks#2195]
Hello everyone,
I'm working on the [Pippo](https://github.com/decebals/pippo) micro framework benchmarks and I have a question regarding how to structure the tests. 
[Pippo supports multiple](http://www.pippo.ro/doc/server.html) Java servers (Undertow, Tomcat, Jetty, TJWS) and would like the benchmark to be run on all of them. 
However, I am not convince about what would be the correct approach to implement benchmarks for all of them, as apparently every [folder in the benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java) code base corresponds to a single server test. 
The "problem" is that the benchmark source code is exactly the same for all servers, as switching servers is as easy as switching dependencies or setting the server class in the `main()` method. I say this is a problem, because I do not want to have the tests source code multiplied by the amounts of supported servers on the benchmark repository.

So I see several ways of solving this:

----
**1)** The benchmark source code goes to one artifact (pippo-benchmark). Hosted on a repository (maven) and we have 4 folders in the benchmark repo (1 per server) that will pull the pippo-benchmark as a dependency and just add the correct server dependency.

- benchmark-base (common code, server agnostic) -> Maven repo

- benchmark-undertow (depends on benchmark-base and adds pippo-undertow) - Benchmark Repo
- benchmark-tomcat (depends on benchmark-base and adds pippo-tomcat) - Benchmark Repo
- benchmark-jetty (depends on benchmark-base and adds pippo-jetty) - Benchmark Repo
- benchmark-twjs (depends on benchmark-base and adds pippo-twjs) - Benchmark Repo

**Pros**: no code duplication, easy to setup
**Cons**: external source repository and dependency hosting

----

**2)** The benchmark runs all supported servers, and have `benchmark_config.json` configure each server on a different port, and declare all tests for each server. 

```
{
    "framework": "pippo",
    "tests": [
        {
            "tomcat_default": {
                "port": 8080,
                "webserver": "Tomcat",
                ...
            },
            // All tomcat tests       
            ...
            "undertow_default": {
                "port": 8081,
                "webserver": "Undertow",
                ...
            }
           // All Undertow tests
           ...
        }
    ]
}
```

**Pros**: all tests on same folder
**Cons**: all servers running at the same time

----
**3)** Different "setups" 
I saw that one of the fields in `benchmark_config` corresponds to the name of the test setup script. As far as I understand, it would be possible to have multiple different `setups` for different servers or configs of the runtime, but I do not know how exactly they will be executed, as they are all in the same "benchmark artifact"

**Pros**: everything!
**Cons**: harder to setup?

----

This was a long write up, I hope is clear and I can use your experience to setup this benchmark correctly.
Cheers

**Comment by robertoestivill** [comment]
I guess I will start answering myself based on trial and error.

Option 2) and 3) are a no go. The toolset expects a `default` named test. This kills the option of specifying all tests combinations in a single `benchmark_config.json` as we can not have a `jetty_default`, `tomcat_default`, etc.

Looks like option 1) is the only way to go.

```
WARNING:root:Framework pippo does not define a default test in benchmark_config.json
Traceback (most recent call last):
  File "toolset/run-tests.py", line 214, in <module>
    sys.exit(main())
  File "toolset/run-tests.py", line 199, in main
    benchmarker = Benchmarker(vars(args))
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 997, in __init__
    self.results['frameworks'] = [t.name for t in self.__gather_tests]
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 338, in __gather_tests
    benchmarker=self)
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/utils.py", line 81, in gather_tests
    os.path.dirname(config_file_name), benchmarker)
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 1025, in parse_config
    validate_test(test_name, test_keys, directory)
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 998, in validate_test
    raise Exception(fullerr)
```

**Comment by msmith-techempower** [comment]
The actual naming of the tests in `benchmark_config.json` is largely irrelevant, though you are correct that we expect exactly one `default` test (again, it does not really matter, so just pick one to be the default). The results website will use the metadata present in `benchmark_config.json` to distinguish the tests from one another.

We prefer that all implementations of a given framework (in this case, a framework on multiple platforms) to exist in a single unified directory. In this case, we expect `frameworks/Java/pippo` to house a `benchmark_config.json` with all the implementations.

**Comment by robertoestivill** [comment]
So what would be the `default` test mean then? 
My plan was to have 4 default tests, one per supported webserver. 
If I understood correctly, you are saying that If I rename one of those to `default`, the results will still consider the server/platform declared on that test?

**Comment by msmith-techempower** [comment]
`default` is a legacy way of running a single test. For example, when we started the suite, `gemini` only had a `default` test type that ran all of the tests. This allowed us to run the tool via `toolset/run-tests.py --test gemini` and it would use the `default` test in the `gemini` directory as the target.

If you want to run any test except `default`, you need to specify it with hyphens. For example, there is now a `mysql` test for gemini, but the entry in `benchmark_config.json` is just "mysql". To run that, we issue `toolset/run-tests.py --test gemini-mysql`. The tool finds the `gemini` directory and looks for a `mysql` test to run.

I admit that this is all a bit arcane now, but it made a lot of sense back when it was built.

You are correct -- if you have one of your tests labeled as `default`, the results website will still use `displayName` to show `Pippo`, and the rest of the metadata (platform, framework, language, database, etc) will be used to differentiate each `Pippo` result from one another. There are several examples of this on the round-12 results website currently (`undertow`, for example).

**Comment by robertoestivill** [comment]
Ok, makes sense now.
However, I don't think undertow is a good example of what you are trying to explain here.
There are 4 directories with different undertow configs. The first two (`undertow` and `undertow-edge`) have the exact same source code duplicated (with slightly different dependencies), exactly what I was trying to avoid to keep the tests maintainable.
Also, because there are on different directories, the tests on `benchmark_config.json` are named always `default`, `mysql`, etc because they don't have to preffix/suffix with the server/framework configuration.

**Comment by nbrady-techempower** [comment]
I'm going to close this for now since we're currently doing work on the benchmark_config
