### ISSUE TITLE
Upgrade Node.js version

### ISSUE THREAD

**Issue by LinusU** [TechEmpower/FrameworkBenchmarks#2196]
Node.js version 0.12.2 is very old, I think it's time to upgrade to the latest version, 6.3.1. I didn't see the Node.js installation as part of the repository though so I don't know how to submit a pull request for this...

Happy to help out :)

**Comment by cjnething** [comment]
Hi @LinusU, not sure where you're seeing 0.12.2, but we recently upgraded to 6.3.0 [here](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2163). Closing for now, if I misunderstood and there's a different issue then please feel free to re-open!

**Comment by LinusU** [comment]
Nice, this readme should probably be updated then:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/README.md#infrastructure-software-versions

Submitting PR now

**Comment by cjnething** [comment]
Ok thanks!

**Comment by nbrady-techempower** [comment]
Merged in, thanks @LinusU

**Comment by LinusU** [comment]
No problem 👌
