### ISSUE TITLE
Phalcon micro ORM

### ISSUE THREAD

**Issue by Jurigag** [TechEmpower/FrameworkBenchmarks#2248]
According to Round 12 phalcon micro is using full ORM while here in code - https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/phalcon-micro/public/index.php it's using `db` object which is not ORM, it should be RAW, it's actually just wrapper on php pdo object.

**Comment by knewmanTE** [comment]
Good catch! Would you mind opening up a merge request with the fix in Phalcon's `benchmark_config.json` file?

**Comment by Jurigag** [comment]
Oh okay, no problem, wasn't sure what needs to be changed.

**Comment by msmith-techempower** [comment]
I'm touching up all the `benchmark_config.json` files and have addressed this directly.
