### ISSUE TITLE
Clojure Pedestal benchmark is not implemented correctly

### ISSUE THREAD

**Issue by yogthos** [TechEmpower/FrameworkBenchmarks#2250]
@msmith-techempower

The update benchmark [uses a `for`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/2e8402fec98296e28e141a8135abff70c7da62bf/frameworks/Clojure/pedestal/src/pedestal/service.clj#L143) where the result is never consumed. Since `for` is lazy, it never actually runs. This is related to [this fix](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2026) for the Compojure benchmark.

**Comment by msmith-techempower** [comment]
@yogthos Thanks for the note.

Ping @k-r-g

**Comment by k-r-g** [comment]
@yogthos I believe I have addressed this in PR #2253. Does this look okay to you? My intention was to make it match what Compojure and http-kit are doing.

**Comment by yogthos** [comment]
Yeah that looks great, and definitely agree that it makes sense for all three to have the same code.

**Comment by k-r-g** [comment]
Excellent. Thanks for finding this!
