### ISSUE TITLE
overhead for Python frameworks?

### ISSUE THREAD

**Issue by anarcat** [TechEmpower/FrameworkBenchmarks#2294]
it seems that the "framework overhead" tab does not yield any results for Python framework. i assume this is because there is no "python-raw" framework.. is that accurate?

if that is so, it seems to me a basic `python-raw` would be pretty useful. i am guessing those are just not implemented for:
- single query
- multiple query
- fortunes
- data updates

is that correct?

**Comment by nbrady-techempower** [comment]
Sorry this took so long to respond to. A basic `python` test would be something that frameworks could compare to. Certainly feel free to open a PR for that at any time. Right now, the overhead tab compares frameworks to whatever they put in the "versus" property of their `benchmark_config.json`
