### ISSUE TITLE
FastHTTP Benchmark Config 

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#2300]
This file includes urls for DB/etc for the default when only `json`/`plaintext` should be exercised, and the actual db implementations include `json`/`plaintext` when they should not.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Go/fasthttp/benchmark_config.json

**Comment by nbrady-techempower** [comment]
@msmith-techempower I'm guessing it is ok though for a "default" test to include db tests? Just doesn't make sense for the json/plaintext test in db only  tests?
