### ISSUE TITLE
Build and install Ubuntu Tuned as part of suite set-up.

### ISSUE THREAD

**Issue by ashawnbandy-te-tfb** [TechEmpower/FrameworkBenchmarks#2318]
We are currently using [Ubuntu's Tuned](https://github.com/edwardbadboy/tuned-ubuntu)  in our production environment, in particular the `latency-performance` profile is active.  We should make this a part of the suite.  The setup process should download, compile, install and configure (if possible) tuned.

Additionally, we shoud check for the correct active profile at the beginning of the run.

**Comment by nbrady-techempower** [comment]
moved this to the roadmap: https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
