### ISSUE TITLE
OpenResty result in Round 13 is not sane

### ISSUE THREAD

**Issue by spacewander** [TechEmpower/FrameworkBenchmarks#2325]
The default value of `worker_process` in [`nginx.conf`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Lua/openresty/nginx.conf) is only one process.

Obversely, run just one process in multicore machine is wasteful. It explains why the result of OpenResty is terrible in Round 13.

Other web frameworks depend on nginx.conf also suffer from the same problem(PHP etc.).

**Comment by methane** [comment]
> Obversely, run just one process in multicore machine is wasteful. It explains why the result of OpenResty is terrible in Round 13.

See here:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Lua/openresty/setup.sh#L10

> Other web frameworks depend on nginx.conf also suffer from the same problem(PHP etc.).

In many case, nginx is not bottleneck.  PHP uses most of CPU time and nginx won't use so much
CPU time. Increasing number of nginx processes just increases number of context swich.

There may be some exception, especially on machine having massive (16~) CPU cores.
But current setting is good for default.  Each web frameworks can adjust nginx processes like OpenResty.
But it should by adjusted by benchmark result, not just by guessing.

**Comment by spacewander** [comment]
Thanks! I get it now.
