### ISSUE TITLE
Spring/Java test metadata clarification

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2338]
Currently the [data states](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/spring/benchmark_config.json#L21): `"platform": "Servlet", "webserver": "Tomcat"`
But actually it is configured to use [`undertow`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/spring/src/main/java/com/techempower/spring/SampleApplication.java#L32-L48). The [README.md](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/spring/README.md) correctly states that.
I've checked how `undertow` projects are defined:

- [undertow](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/undertow/benchmark_config.json) -  `"platform": "Undertow", "webserver": "None"`

- [undertow-jersey-c3p0](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/undertow-jersey-c3p0/benchmark_config.json) - `"platform": "JAX-RS", "webserver": "None"`

How the metadata should look like?

**Comment by msmith-techempower** [comment]
If spring uses Undertow, then its platform should be Undertow.
