### ISSUE TITLE
Improve dstat usage

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#2358]
Currently, we use `dstat` to capture system specifics during every test's benchmarking.

Improve our implementation to separate `dstat` invocations and save for each test type. That is, separate `dstat` for `json`/`db`/etc and stored along side the `raw` file as such.

**Comment by nbrady-techempower** [comment]
Moved to a new project: https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
