### ISSUE TITLE
Environment section of the results website

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2366]
I noticed the following problems:

- There is a difference between [the documentation repository](https://github.com/TechEmpower/TFB-Documentation/blob/master/docs/Project-Information/Environment.md) and the [current data](https://www.techempower.com/benchmarks/#section=environment);

- The Intel Xeon processor model cited for the DB server seems to be mistyped: it doesn't exist according to [Intel data sheets](http://ark.intel.com/products/series/64580/Intel-Xeon-Processor-E5-2400-Product-Family#@Server). I suspect that it's either Е5-2403 оr Е5-2407. Here is the original announcement in the [Google news group](https://groups.google.com/d/msg/framework-benchmarks/nePDNY9jp-4/Y8bw-XM5AAAJ).

**Comment by knewmanTE** [comment]
Good catch @zloster! I will update the docs with our current environment information.

**Comment by knewmanTE** [comment]
Also, on the [TFB Site](https://www.techempower.com/benchmarks/#section=environment) there is a link to the [Xeon processor model](http://ark.intel.com/products/75272).

**Comment by knewmanTE** [comment]
Addressed in [this pull request](https://github.com/TechEmpower/TFB-Documentation/pull/49). Closing this Issue as I consider it resolved.
