### ISSUE TITLE
"None" framework has a line count?

### ISSUE THREAD

**Issue by ubershmekel** [TechEmpower/FrameworkBenchmarks#2367]
In `results.json` under `commitCounts` and `slocCounts` there is a benchmark called `None` though the `test_metadata.json` has no framework named as such.

https://tfb-logs.techempower.com/round-13/final/azure/results.json

It may be a slip of the Python `None` into either `self.test` or `gather_tests`, or perhaps a framework losing its name along the way.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/65003b61fc3c7605e0fb7ed898800317eb946182/toolset/benchmark/benchmarker.py#L780

**Comment by nbrady-techempower** [comment]
This appears to be collecting lines from tests that have the framework listed as None in its `benchmark_config.json`. We are working on cleaning up the `results.json` now. Thanks for pointing it out!
