### ISSUE TITLE
Spring + Thymeleaf

### ISSUE THREAD

**Issue by javieradorno** [TechEmpower/FrameworkBenchmarks#2368]
Why have you chosen Thymeleaf as the templating model for the Spring tests?
JSP or Freemarker are up to 41x faster than Thymeleaf.
I can contribute to a test if you like me to.

**Comment by LadyMozzarella** [comment]
TechEmpower doesn't actively maintain each framework implementation and relies on the community to help keep each one up to date. Contributions are very welcome.

**Comment by nbrady-techempower** [comment]
PR is definitely welcome! Maybe as an additional test so you can prove out the 41x faster statement!

**Comment by javieradorno** [comment]
OK, I'll get my hands on it!
