### ISSUE TITLE
Where is the kernel tuning configuration file?

### ISSUE THREAD

**Issue by kokizzu** [TechEmpower/FrameworkBenchmarks#2375]
Is there exists? or the benchmark done without any kernel tuning?

**Comment by zloster** [comment]
@kokizzu https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/benchmarker.py#L335-L421
Also see https://github.com/TechEmpower/FrameworkBenchmarks/issues/1408.
