### ISSUE TITLE
Unable to run the Benchmark Suite Deployment commands

### ISSUE THREAD

**Issue by rkraman** [TechEmpower/FrameworkBenchmarks#2400]
Hello 
I am trying to install the TechEmpower benchmark suite following the guide
http://frameworkbenchmarks.readthedocs.io/en/latest/Benchmarking/Getting-Started-Benchmarking/#benchmark-suite-deployment

To keep it simple I am starting with a single Virtual Box VM (Ubuntu 14.04 LTS 64-bit) and planned to install all 3 (DB, app server and client).

After getting the Ubuntu VM ready ran the command

nohup python toolset/run-tests.py -s <server hostname/ip> -c <client hostname/ip> -u tfb --install-software --install server --list-tests &
E.g nohup python toolset/run-tests.py -s 127.0.0.1 -c 127.0.0.1 -u tfb --install-software --install server --list-tests &

Got the error message: unrecognized arguments: --install-software

![image](https://cloud.githubusercontent.com/assets/24415607/20935617/22319ff0-bba5-11e6-8efe-b3119f6ce237.png)

It looks like there is also no argument named --list-tests

Is there an updated document or am I missing something?
Any help would be appreciated.

-RR

**Comment by msmith-techempower** [comment]
That is terribly out of date; use [this](http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/) instead.

**Comment by rkraman** [comment]
That is the exact link I have.  Once you go to the above link I click on the "Benchmark Overview" and use the Benchmark Suite Setup.  Is that wrong? Should I use only "Installation Guide" instead of "Benchmark Overview" section?

**Comment by msmith-techempower** [comment]
You should only refer to the "Installation Basics" section I linked you - it will get you set up correctly and able to run a framework test.
