### ISSUE TITLE
AWS Deployment error

### ISSUE THREAD

**Issue by rkraman** [TechEmpower/FrameworkBenchmarks#2404]
I want to setup the benchmark development environment in AWS.  I installed vagrant 1.9.1 and installed the aws plugin.  Later from the vagrant-development directory ran the command
**_vagrant up --provider aws_**

I got the following error message:

![image](https://cloud.githubusercontent.com/assets/24415607/21038836/9bde6554-bd9e-11e6-888f-f9ad86949d52.png)

I am not sure where it gets the ami-f6bf659e value.  I even edited the Vagrant file and changed the line
**_ENV['TFB_AWS_EC2_TYPE'] = ENV.fetch('TFB_AWS_EC2_TYPE', 'm3.medium')_**

Still getting the same **ami-f6bf6h9e** not found error.

PS:  The original file had 'm1.small' and in AWS I did not see such a EC2 type

Any help would be appreciated
Thanks
~RR

**Comment by rkraman** [comment]
I even tried the previous generation instances (m1.medium, m1.large) etc.  Still getting the same **_ami-f6bf6h9e_** not found error.
https://aws.amazon.com/ec2/previous-generation/

**Comment by nbrady-techempower** [comment]
@rkraman we're going through a bit of a transition with the toolset and vagrant. If you want to get up and running on aws (I just tested this recently), spin up an ubuntu 14.04 instance and follow the instructions here: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/

If you run in to any issues installing let me know and I can help you through that. I'm finishing up a single script that will do all the steps in this installation guide for a single vm instance.

**Comment by nbrady-techempower** [comment]
I've also added following up on Vagrant deployments to the roadmap here. https://github.com/TechEmpower/FrameworkBenchmarks/projects/1

If you don't have an aws account (you can make one and do the t2.micro free for several months) you can use vagrant/virtual box on windows. That setup currently works.

**Comment by rkraman** [comment]
**@nbrady-techempower** Thanks for your response.
I did not understand what you mentioned above.  I will explain in detail my setup and ask my questions.
Created a bare metal server [Windows 2012 Server]
Installed VirtualBox 5.1.10
Installed Vagrant 1.9.0
Installed Git
Downloaded the TechEmpower framework from github
From the vagrant-development directory, ran the command **vagrant-up**

All the installation went well and one single VM was created.  Able to do **vagrant ssh**.
Ran a sample test 
e.g toolset/run-tests.py —install server —test nodejs
Test ran successfully and was able to see the results.

**Question:  How to interpret the result and make a chart or graph out of it.  Are there any tool or do I have to write my own and parse the JSON results.**
-------------------------------------
Now that I am able to create a vagrant VM and run the test successfully, I tried to setup in AWS.  I want to actually do a production like environment, but before doing that I wanted to try with a single VM on AWS.  So followed these steps.

1.  In the same bare metal Windows box, created a new Ubuntu 16.04.1 VM.
2.  Inside that VM, installed, Vagrant 1.9.1 (python and git was already installed, had to install pip)
3.  Installed vagrant-aws plugin
4.  Downloaded the TechemPower framework using git
5.  Got all my credentials for AWS and exported that as environment variables
6.  From vagrant-aws directory ran **python setup_aws.ph**.  It was successful and checked AWS  security groups were created.  Using aws-cli even created a KeyPair and added that to the env variable
7.  From vagrant-development directory ran **vagrant up --provider aws**
8. That is when I got the above errors, that **ami-f6bf6h9e** is not found.

**Question:  As of now is it even possible to create AWS vagrant setup for development and/or production?  If yes I need the instruction for that.**
-----------------------------
Creating my own Virtual Box and setting up environment (not using Vagrant)
I tried to follow the instruction and created 3 VMs and did the password less ssh and was able to ssh from server to db to client.  Ran the install db, install client commands successfully (from server).  Unfortunately from server when I ran a test (gemini) it failed saying Java not installed and while trying to run the prereq.  Did not bother to debug further.

I can try to do a single VM instead of 3 and see if that works.
------------------------------
Hope this long note explains exactly my environment and I would be grateful if you could assist me in setting up my environment in AWS and also helping me in interpreting the result.  The plan is our team is developing a new benchmark and before submitting to TechEmpower we wanted to test it and make sure our performance is good enough to submit for the real test :)

Thanks
RR

**Comment by nbrady-techempower** [comment]
@rkraman I noticed the the apt sources list was different on aws than it was for most ubuntu installs that I had been working with. In other words, any `apt-get installs or updates` were grabbing from a slightly different source. To fix this, I replaced `/etc/apt/sources.list` with one from a machine I knew was working. I might try and copy the file from your successful vagrant box, to aws and try running the test again. I would also start with a single vm on aws. That will probably be easier to troubleshoot. Feel free to pastebin/sprunge any logs if you need help debugging.

**Comment by rkraman** [comment]
@nbrady-techempower 
I tried to run a sample test in my vagrant VM box and got the result
**toolset/run-tests.py --install server --test nodejs-postgres --type query**

I wanted to know how to view the results using a GUI.  I got the info that I can paste the results.json data in the below URL.  I did that and nothing happened.  The screen did not show any error message either.
 https://www.techempower.com/benchmarks/#section=test

**_Note:  I just renamed the results.json file to results.json.txt so that I can upload to this website._**
[results.json.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/656312/results.json.txt)

Please advice.

Thanks
RR
