### ISSUE TITLE
Successive fw_depends calls break reporting

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#2411]
If you have `foo` which calls `fw_depends bar`, and in `bar` there is `fw_depends baz`, the logging/reporting all bubbles up to `bar` as the dependency.

Specifically, this is a problem in that any errors are reported incorrectly as `bar` failing when it could be `baz` that is failing.

**Comment by nbrady-techempower** [comment]
@msmith-techempower Do you have a specific example where this happened? Assuming I understand the problem correctly I tried to reproduce as such:

in `postgresql.sh` i made an `fw_depends somenonsense` and then ran `gemini-postgres` which does and `fw_depends postgresql`. `fw_depends somenonsense` reported the error.

**Comment by msmith-techempower** [comment]
No longer relevant as `fw_depends` has been removed in favor of Docker implementations.
