### ISSUE TITLE
Benchmark Development environment setup not working

### ISSUE THREAD

**Issue by rkraman** [TechEmpower/FrameworkBenchmarks#2418]
Hello

I am trying to follow the development environment setup script as per the instructions given in the URL
**http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/#installation-basics**

After pulling the latest Framework code from Github found that the 
run-tests.py file under toolset has significantly changed.

I compared with what I had in my vagrant development box with the latest one and found the difference is significant.  To start with the vagrant box has the file size as 11680 bytes and the latest one has a file size of 10393 bytes.

Also under the Install options section (line number: 138) in the run-tests.py file --install option is completely missing.  In the image it will be clear that the vagrant window (top) has that and the custom dev VM (bottom) does not have that option.  Unable to run tests on my custom dev VM.

![image](https://cloud.githubusercontent.com/assets/24415607/21409941/fd2a821c-c7a2-11e6-92ba-3a9d28e37b21.png)

From Github looks like this file was changed recently (6 days ago) for issue #2403 

-RR

**Comment by nbrady-techempower** [comment]
@rkraman This was addressed yesterday. Please pull from the latest master and do a `vagrant up` from the `vagrant-development` directory. Should be good to go! Let me know if you have any other issues. :)

**Comment by rkraman** [comment]
@nbrady-techempower Thanks for the update.  Yes I was tracing the Github updates and looks like #2409 removed that option.
The documentation still says that I need to setup load server and database
Guess I can ignore those steps and directly run the test.
______________________________________
![image](https://cloud.githubusercontent.com/assets/24415607/21430186/a9bf2a94-c827-11e6-898e-058e3defb003.png)
______________________________________
Thanks for your time and help.

**Comment by nbrady-techempower** [comment]
@rkraman Yes you can ignore those instructions. I will be updating the documentation this week. Thanks for pointing those out.
