### ISSUE TITLE
Install databases based on benchmark_config.json

### ISSUE THREAD

**Issue by dantti** [TechEmpower/FrameworkBenchmarks#2473]
Currently one needs to explicit tells which database software it needs `fw_depends mysql postgres mongo`, this information is duplicated with **benchmark_config.json**.
Some frameworks including mine installed all required databases and depending on the URL called one or the other, this is bad since more databases means more resources, means it's more complex to use the testing framework on other OSes, and also means if in future one DB test is removed things would break.
Since this is complex and require to each framework test to handle one db at time it would be interesting to first have support from the test framework so fw_depends is not required and automatically installed depending on the JSON file and then we can go changing frameworks to handle this.

**Comment by msmith-techempower** [comment]
A simple short-term fix for this is to have nearly identical duplicated setup files, each containing only the database upon which they require.

The `fw_depends` database stuff should not impact any particular framework in terms of performance, so I don't really see this as an issue.

**Comment by msmith-techempower** [comment]
That said, it would be pretty slick to no longer require `fw_depends mysql` and instead that be called automatically be the suite based on the `benchmark_config.json` entry being run; if the suite sees 'MySQL', it would invoke `fw_depends mysql` prior to entry of the setup file.

**Comment by nbrady-techempower** [comment]
I'll add this to the toolset roadmap project: ideas. I agree it would be slick, but a few other things would have to change. For instance, the travis diff tool looks at the fw_depends line when determining which frameworks need to be run. This could also be changed to look at the benchmark_config.json, but not a priority.
