### ISSUE TITLE
Remove run-tests.py arguments

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#2494]
1. ~~`run-tests.py` accepts a number of command line arguments which serve the same purpose as keys in `benchmark.cfg`; remove those arguments from `run-tests.py` and leave only arguments which augment the running of the application (clean, test, mode, etc).~~

2. ~~Add argument to run all tests in a framework directory (e.g. `tfb --framework gemini` will be functionally equivalent to `tfb --test gemini gemini-mysql gemini-postgresql` etc)~~

3. ~~Drop `--list-test-metadata` and instead just always output this file to the results timestamp dir for every run.~~

4. `--parse` is probably broken since we have done so many directory changes; rename this to `--merge` and give it the implementation and description that it will merge all results timestamp directories. This will involve the difficulty in merging `results.json` files and `metadata.json` files (as well as `dstat` and whatnot), so it will be difficult.

**Comment by nbrady-techempower** [comment]
@msmith-techempower We can probably close this after you review and merge #2502 and maybe hold off on `--parse` until the `results.json` structure is done.

**Comment by msmith-techempower** [comment]
Agreed

**Comment by nbrady-techempower** [comment]
So these are all done. Would love to work on a new `results.json` structure soon!
