### ISSUE TITLE
Latency benchmarks seem to display wrong numbers

### ISSUE THREAD

**Issue by ubershmekel** [TechEmpower/FrameworkBenchmarks#2499]
In designing a real time system - I only really care about latency maximum. There's no way to link directly to the latency table but if you click to it yourself here: https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext

* The sort order seems random and the numbers themselves seem wrong too. Even though you cite the error counts - it doesn't add up. It's definitely not average latency but a sampling of sorts.
* How can many of these frameworks have a maximum latency of over 8 seconds? That just looks like the calculation is broken or some OS related blockage is happening.
* It looks as though it's all wrong - average latency, max latency and error count.

Looking at:
https://github.com/TechEmpower/FrameworkBenchmarks/issues/117

I see the value of latency is put into question. Believe me that it's the only thing I care about in my application. If there needs to be more sampling to get an accurate representation, then why not sample more?

**Comment by msmith-techempower** [comment]
I don't know that I can answer this question satisfactorily for your needs, but I would point you to the raw `wrk` captures when you need to see what we get from latency.

[Here](https://tfb-logs.techempower.com/round-13/final/servercentral/results/20161111185139/plaintext/echo-prefork/) is one pretty much picked at random that is a top performer; take look at the `raw` file (it's plaintext, no idea why it doesn't have an extension; issue to follow) and you will see what the suite is exercising and the results we gather.

**Comment by methane** [comment]
@ubershmekel You shouldn't compare of latency when request/sec is different.
Currently, we use wrk to measure throughput.
To measure latency, you should use tool making constant load, and choose load rate carefully
to avoid measuring (wait queue length / throughput).

* https://github.com/rakyll/hey
* https://github.com/tsenart/vegeta

> How can many of these frameworks have a maximum latency of over 8 seconds? That just looks like the calculation is broken or some OS related blockage is happening.

When wrk generates too high load than application can accepts, it can happens.
It means just concurrency is too high.

**Comment by methane** [comment]
Plaintext benchmark is worst case for measuring latency.  It uses pipelined request.
It uses too large concurrency than number of CPU cores.

**Comment by ubershmekel** [comment]
Interesting info @msmith-techempower and @methane. Thank you. It seems the latency data is only broken for the plaintext benchmark because of the network saturation. Perhaps the measurement for plaintext latency needs to be done only at a low level of concurrency.

I can make do with the other benchmark latency numbers. Perhaps until a fix is in place the latency numbers for `Plaintext` should get a disclaimer. I'm content with closing this issue if you guys are.

**Comment by methane** [comment]
When throughput is 10req/sec and concurrency is 100, latency of steady state is 100 / 10 = 10 [sec].

If you want to measure latency, concurrency should be smaller than number of CPU cores.
Latency is meaningful only when load doesn't saturate throughput.

In other words, latency of other benchmarks are bad information too.
It may be better than plaintext's latency, but it's still bad information.

**Comment by methane** [comment]
While website shows latency of max concurrency (which I dislike), raw file contains
data for low concurrency.  For example, flask-py3:

```
Running 15s test @ http://204.93.249.212:8080/json
  8 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   598.13us  164.48us   8.61ms   99.68%
    Req/Sec     1.69k    49.08     1.79k    69.70%
  Latency Distribution
     50%  595.00us
     75%  601.00us
     90%  610.00us
     99%  628.00us
  203189 requests in 15.10s, 35.65MB read
Requests/sec:  13456.25

Running 15s test @ http://204.93.249.212:8080/json
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.07ms    6.44ms 330.09ms   88.45%
    Req/Sec     3.37k     0.98k    7.97k    70.87%
  Latency Distribution
     50%    1.52ms
     75%    4.44ms
     90%   11.42ms
     99%   22.63ms
  1606484 requests in 15.10s, 281.90MB read
Requests/sec: 106393.91
```

I like 90% and 99% latency of concurrency=8.

**Comment by ubershmekel** [comment]
@methane I agree that average throughput is equivalent to average latency. That's a good reason why the  `latency` tab should not sort by `average latency` because it wouldn't add information.

I think it would make sense to first measure the peak throughput of every stack and then measure the latency at half that rate. That would guarantee a non-saturated measurement appropriate for each stack. Then I would sort based on the maximum latency or 99th percentile.

Then it might make sense to rename the latency tab. You already have a `Best` tab. Why not have a `Worst` tab?

**Comment by nbrady-techempower** [comment]
This was also discussed in the [Google Group](https://groups.google.com/forum/#!forum/framework-benchmarks) and the plan is to leave as is for now. Certainly we welcome anyone who wants to build a different visualization tool from the publicly available `results.json` files.
