### ISSUE TITLE
Go: Add Go with mgo MongoDB driver

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#250]
This is just a marker that I've seen a request for a Go implementation that connects to MongoDB using a driver named "mgo".

**Comment by ebramanti-techempower** [comment]
gonna take a crack at this

**Comment by hamiltont** [comment]
@ebramanti-techempower feel free to mark yourself as the Assignee

**Comment by LadyMozzarella** [comment]
Closing. #1418 merged.
