### ISSUE TITLE
rust/tokio-minihttp framework failing

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#2503]
@gkbrk Wanted to ping you for this. Looks like the fw is failing here all of a sudden. Is the `revision` portion of the `Cargo.toml` working correctly or is it pulling from `latest`?

**Comment by gkbrk** [comment]
Oh I think it might be pulling from latest. I probably wrote the wrong thing, I will compile it and commit the Cargo.lock so every single dependency is locked.

**Comment by gkbrk** [comment]
@nbrady-techempower It should be fixed now.
