### ISSUE TITLE
Include Ratpack

### ISSUE THREAD

**Issue by KangoV** [TechEmpower/FrameworkBenchmarks#2526]
It would be nice to have [Ratpack](http://ratpack.io) included in these tests.

**Comment by martin-g** [comment]
Hey @KangoV,

The community contributes and maintains the test implementations.
TechEmpower develops and runs the infrastructure.
Feel free to send a pull request with Ratpack implementation of the tests!

**Comment by KangoV** [comment]
Ahh, I see. Thanks. I'll have a look and see what I can do.
