### ISSUE TITLE
RIP Redis benchmarks, or maybe not?

### ISSUE THREAD

**Issue by samuelcolvin** [TechEmpower/FrameworkBenchmarks#2534]
I was just wondering about adding redis as a "database" to some of the python frameworks, but searching "redis" in this repo most of the recent activity seems to be removing redis and associated benchmarks?

Is redis still considered a valid database to use?

What was that? "What do I think?" Thanks for asking. I'm a massive fan of redis, I feel slightly odd calling it a database but I think that's illogical. Not only does it have first rate persistence and failover, but I know of large companies using it in production to serve customers. If you setup redis  properly (or use it hosted) it's as reliable as any other database and generally much more performant.

I'd be happy to add redis as a database backend for a couple of python benchmarks if redis is being kept. My (totally unscientific) suspicion is it would outperform all other databases.

**Comment by nbrady-techempower** [comment]
I don't think we were pleased with the previous implementation of redis, as it wasn't always reliable. (Is that true of redis by nature? not sure.) Nonetheless, if you want to give it a shot we can certainly review it and provide some feedback. I can't make any guarantees that we'll want to display redis results, but I think we're all open to a debate on that.

**Comment by nbrady-techempower** [comment]
Let me know if you need anything during the process, if you decide to take it on.
