### ISSUE TITLE
Test implementations should live within the FrameworkBenchmarks repo

### ISSUE THREAD

**Issue by knewmanTE** [TechEmpower/FrameworkBenchmarks#2554]
I've noticed recently that there are a handful of frameworks that only have a few files living on this repo and then maintain their actual test implementations on a separate repo (often as a subdirectory of the framework itself).

I'd really like to avoid this as much as possible for the following reasons:

1. It makes it difficult/impossible for anyone other than the framework's maintainers to update their implementation, regardless of how small a change needs to be made. 
2. In some cases, no version or tag is being specified, allowing the maintainer to make changes that don't go through the Pull Request process.
3. It feels a bit contradictory to the spirit of the Framework Benchmarks project, where I would love for everyone to have full access to inspect and improve the code wherever they see a place that could be enhanced.

Frameworks I've noticed so far:

- [C++/ffead-cpp](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C%2B%2B/ffead-cpp) (ping @sumeetchhetri)
- [C/haywire](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C/haywire) (ping @kellabyte)
- [C/libreactor](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C/libreactor) (ping @fredrikwidlund)
- [C/lwan](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C/lwan) (ping @lpereira)

If you're one of those maintainers, or if you implemented a different framework using this methodology, please try to shift your code over so it's living on our repo!

Thanks!

**Comment by lpereira** [comment]
Hi, @knewmanTE! I'm working on Lwan's first release, and that will enable me to move the benchmark code to the FB repository. I know this has been promised for a long time, but life got in the way.

**Comment by knewmanTE** [comment]
@lpereira no worries! Thanks for the update, and best of luck as you move towards your release!

**Comment by nbrady-techempower** [comment]
@lpereira Great news!

**Comment by fredrikwidlund** [comment]
Hi, @knewmanTE. Duly noted! I'm fairly new here so I simply followed some existing patterns. I'll move the project as soon as possible, but it might take a few weeks before I find some time to work on this. Is this something that will disqualify the framework for the next round?

Kind regards,
Fredrik

**Comment by knewmanTE** [comment]
Hey @fredrikwidlund! Thanks for the response! And that's fine if it takes you a bit of time, the most important thing is that it gets done in the long run. As long as the current implementation is still PASSing, it will be included in the next round!
