### ISSUE TITLE
Python: tornado with asyncio(uvloop(libuv))

### ISSUE THREAD

**Issue by westurner** [TechEmpower/FrameworkBenchmarks#2560]
Here's a probably pretty fast stack: Tornado with asyncio with uvloop (libuv; (Node, ))

- tornado with asyncio:
  - src: https://github.com/tornadoweb/tornado
  - src: https://github.com/tornadoweb/tornado/blob/master/tornado/ioloop.py (epoll, kqueue, select)
  - src: https://github.com/tornadoweb/tornado/blob/master/tornado/platform/asyncio.py (asyncio(...))
  - docs: http://www.tornadoweb.org/en/stable/asyncio.html
  - docs: http://www.tornadoweb.org/en/stable/wsgi.html#tornado.wsgi.WSGIAdapter
- asyncio:
  - src: https://github.com/python/cpython/tree/master/Lib/asyncio
  - src: https://hg.python.org/cpython/file/tip/Lib/asyncio
  - docs: https://docs.python.org/3/library/asyncio.html
- uvloop
  - src: https://github.com/MagicStack/uvloop
  - docs: https://uvloop.readthedocs.io/
- libuv
  - src: https://github.com/libuv/libuv
  - docs: http://docs.libuv.org/en/v1.x/

**Comment by westurner** [comment]
See: #1567 (REQ: Gunicorn w/ greenlets)

**Comment by westurner** [comment]
uvloop w/ httptools looks pretty fast (compared with nodejs and golang, for example) in these charts:
https://magic.io/blog/uvloop-blazing-fast-python-networking/

![asyncio, uvloop, nodejs, go, etc requests/s benchmarks](http://i.imgur.com/0iMUePy.png)

... 

- sanic
  - src: https://github.com/channelcat/sanic/
  - pypi: https://pypi.python.org/pypi/Sanic
  - docs: https://sanic.readthedocs.io/en/latest/
  - sanic is built on asyncio, uvloop (libuv (node,)), and httptools (node)

- httptools
  - src: https://github.com/MagicStack/httptools
  - src: https://github.com/MagicStack/httptools/blob/master/tests/test_parser.py
  - pypi: https://pypi.python.org/pypi/httptools
  - desc: "httptools is a Python binding for nodejs HTTP parser. [...]"
  - httptools.HttpRequestParser, httptools.HttpResponseParser, httptools.parse_url
  -

**Comment by westurner** [comment]
Japronto and Meinheld look pretty fast for this "Hello World" benchmark: 

https://medium.freecodecamp.com/million-requests-per-second-with-python-95c137af319

> Most of the servers execute requests from pipelining clients in the same fashion they would from non-pipelining clients. They don’t try to optimize it. (In fact Sanic and Meinheld will also silently drop requests from pipelining clients, which is a violation of HTTP 1.1 protocol.)

.

> ![japronto benchmark](https://cdn-images-1.medium.com/max/800/1*FThTeS_kxx3j7AkTgmMKNw.png)

- japronto
  - src: https://github.com/squeaky-pl/japronto
  - docs: https://github.com/squeaky-pl/japronto/blob/master/README.md
  - uvloop, picohttpparser

- picohttpparser
  - src: https://github.com/h2o/picohttpparser
  - src: https://github.com/h2o/picohttpparser/blob/master/picohttpparser.c
  - docs: https://github.com/h2o/picohttpparser/blob/master/README.md

**Comment by westurner** [comment]
See: https://github.com/TechEmpower/FrameworkBenchmarks/pull/2311#issuecomment-259327909 (re: Python performance)

**Comment by cjnething** [comment]
Hi @westurner,
We are not experts on every language/framework, so we rely on the community to make updates and add new frameworks. If you see areas of improvement, we encourage you to make a pull request! Thanks!

**Comment by nbrady-techempower** [comment]
what @cjnething said. Thanks for the well thought out issue/resources. Would love to see how some of these implementations would fair in the benchmarks.

**Comment by westurner** [comment]
https://morepypy.blogspot.com/2017/03/async-http-benchmarks-on-pypy3.html

![Async HTTP benchmarks on PyPy3](https://1.bp.blogspot.com/-cjlKx06ZBaY/WLb_S3TBWuI/AAAAAAAAAmI/s2fsZ-SaJiwS2B-nAmyTheJfMQrKFHuQACK4B/s640/graphs.png)

**Comment by GMLudo** [comment]
Hello people,

I'm working to integrate all of these new tools in FrameworkBenchmarks.
Too late for round 14, it should be good for round 15.

Have a nice week-end.

**Comment by westurner** [comment]
:+1:
