### ISSUE TITLE
ulimit and erlang based applications

### ISSUE THREAD

**Issue by peterromfeldhk** [TechEmpower/FrameworkBenchmarks#2576]
Erlang based applications (like phoenixframework) usual bottleneck is number of open files configured.

I believe you use 65535 for your tests. Consider to have at least 200000 and you can try turning it up until your benchmark results doesnt change anymore.

**Comment by nbrady-techempower** [comment]
it's been changed to 200,000 for upcoming round 15, and I'll be making changes to the toolset shortly to make it configurable.
