### ISSUE TITLE
[Java/revenj-jvm] Benchmark requirement violation(s)

### ISSUE THREAD

**Issue by mwpastore** [TechEmpower/FrameworkBenchmarks#2581]
The `doGet()` method in `UpdatesServlet.java` [appears](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/revenj-jvm/src/main/java/hello/UpdatesServlet.java#L27) to do a batch update of the "changed" World instances. The tip-off is that the collection is being sorted first (ostensibly to prevent deadlock during a mass-update). The revenj framework is somewhat inscrutable (at least to this Java neophyte) so it's not clear what that `update()` method is doing exactly.

**Comment by nbrady-techempower** [comment]
@mwpastore If this is a batch update, and not a transaction, it doesn't violate the rules. (See rules 9 & 10)[http://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#database-updates]

**Comment by mwpastore** [comment]
It looks like the RevenJ framework automatically wraps non-read-only queries in a transaction? https://github.com/ngs-doo/revenj/blob/master/java/revenj-servlet/src/main/java/org/revenj/server/ProcessingEngine.java#L91-L93

**Comment by zapov** [comment]
@mwpastore revenj-servlet is not used in this benchmark. It doesn't pass through that part. https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/revenj-jvm/pom.xml#L16

**Comment by nbrady-techempower** [comment]
Ok, this looks resolved then? Let me know if there are any other concerns.

**Comment by mwpastore** [comment]
@zapov Thank you for the clarification! Can you help us understand whether the updates are performed within no transaction, a single transaction, or one transaction per record?

**Comment by zapov** [comment]
No transactions are used in the current setup.
It's faster than vanilla jdbc driver because it does a different query to perform the update.

**Comment by mwpastore** [comment]
@zapov Thanks again! Appreciate the explanation.

@nbrady-techempower Sorry for the false alarm!
