### ISSUE TITLE
How about this nice promising line 

### ISSUE THREAD

**Issue by NinoFloris** [TechEmpower/FrameworkBenchmarks#2588]
So as it is quite silent now again for a while I was revisiting the round 13 benchmarks and the blogs and found this little line

> Continuous Benchmarking begins now, which is good news for future rounds

Did anything come of this?

**Comment by nbrady-techempower** [comment]
Hi @NinoFloris 
In the past 2 months we have made several breaking changes to the toolset in an attempt to greatly simplify the process both for future development and for those newbies looking to get started quickly. That temporarily broke our CB implementation. We're almost back up and running with that but we did complete a preview data run which will be up for review shortly.
