### ISSUE TITLE
Async Java servlet tests lost

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2598]
This commit: https://github.com/TechEmpower/FrameworkBenchmarks/pull/2409/commits/b405d2060643b88ea5cfd6053768a2082f760025 has removed `Cassandra` project due to problems with `Cassandra` installation. And the `servlet3-cass` project is removed as consequence.
Unfortunately the tests with database access were the only ones having `async servlet` (Servlet 3.1) implementation.

This issue is created so the lack of Servlet 3.1 test implementations not to go unnoticed. I think it will be useful to have the base line for async servlet results against the plain-old servlets. I have plans to implement them but in the meanwhile someone other could decide to do it.

**Comment by msmith-techempower** [comment]
I have no problem with the underlying goal of this issue, but I'm closing it for now as it does not appear to have any effort against it since March of last year.

Feel free to reopen if development effort begins.

**Comment by zloster** [comment]
The initial implementation for Plaintext and JSON is in #3319.
