### ISSUE TITLE
Consider "Runtime" attribute

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#260]
A reader has suggested the addition of a framework attribute named "Runtime."  This would be distinct from Platform and roughly assigned as follows:
- Ruby frameworks would be either MRI Ruby or JRuby.
- Python frameworks would be Python or PyPy.
- PHP frameworks would be characterized as PHP-FPM, which overlaps
  with platform.
- Perl frameworks would be Perl, I think, which overlaps with language.
- JVM frameworks could be labeled "JVM" as a runtime, which would be a
  nice addition allowing the hiding of all JVM frameworks in one click.
- However, JRuby as a distinct option alongside JVM would be unexpected.
- Go would once again be "Go," meaning it would be represented as such
  in four attributes now (Language, Platform, Runtime, and Framework).
- JavaScript would be V8.
- Lua would be LuaJIT.

Our original intent with the Platform attribute was to consolidate all of the intricacies like this into one umbrella attribute.  But the introduction of a Runtime attribute seems like a good idea to me.

Please contribute to this issue if you have any opinions.  Does this add value?  How would you recommend addressing JRuby versus JVM in the above list?  If you're a Go user, does it really matter to you that Go shows up in so many of these attributes?

**Comment by msmith-techempower** [comment]
Kicking this one down the road.

**Comment by msmith-techempower** [comment]
This was basically done via `flavor` in the metadata.

Reopen if I'm wrong.
