### ISSUE TITLE
Consider separating "Front-end" into "Application Server" and "Web Server"

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#261]
A reader has also recommended that we separate "Front-end Server" into two attributes: "Application Server" and "Web Server."

As with the Platform attribute, our objective in consolidating these two into a single attribute was to reduce confusion.  However, it is possible that we have added confusion instead.

In some cases, the web server will be equivalent to the application server (e.g., nginx and Resin).

Again, I would appreciate any opinions.  Do you feel it add value and/or reduce confusion to separate these?  Or would you prefer to leave them unified?

**Comment by msmith-techempower** [comment]
Kicking this one down the road.

**Comment by msmith-techempower** [comment]
Closing as it has had no traction for five years.
