### ISSUE TITLE
sudo: argument list too long

### ISSUE THREAD

**Issue by oberhamsi** [TechEmpower/FrameworkBenchmarks#2613]
the ringojs and ringojs-convenient tests are failing and i am a bit at loss where in the benchmark toolset the `sudo` is coming from. after successful install and start of the framework, the sudo error appears. relevant log snippet below.

if anyone knows where i should start looking, i'd be thankful.

```
Setup ringojs-convenient: 1535 [main] INFO  org.eclipse.jetty.server.Server  - jetty-9.4.1.v20170120
Setup ringojs-convenient: Status: Poll: None, Port 8080 bound: True, Time Left: 1:44:47.267612
Setup ringojs-convenient: Bound port detected on 8080
Server ringojs-convenient: 1560 [main] INFO  org.eclipse.jetty.server.session  - DefaultSessionIdManager workerName=node0
Server ringojs-convenient: 1562 [main] INFO  org.eclipse.jetty.server.session  - Scavenging every 660000ms
Server ringojs-convenient: 1603 [main] INFO  org.eclipse.jetty.server.handler.ContextHandler  - Started o.e.j.s.ServletContextHandler@16612a51{/,null,AVAILABLE}
Server ringojs-convenient: 1619 [main] INFO  org.eclipse.jetty.server.AbstractConnector  - Started ServerConnector@13bc8645{HTTP/1.1,[http/1.1]}{127.0.0.1:8080}
Server ringojs-convenient: 1619 [main] INFO  org.eclipse.jetty.server.Server  - Started @3671ms
Server ringojs-convenient: 1620 [main] INFO  ringo.httpserver  - Server on http://127.0.0.1:8080 started.
/bin/sh: 1: sudo: Argument list too long
```
http://tfb-logs.techempower.com/round-14/preview-1/ringojs-convenient/out.txt

cc @grob

**Comment by michaelhixson** [comment]
I notice when I remove the `&` from the final line in `setup.sh` and run the test, it prints this:

```
Server ringojs: 492  [main] INFO  ringo.httpserver  - Server on http://127.0.0.1:8080 started.
```

...which makes me think it is only accepting connections from localhost.  While the test is running it does seem like I can curl for `/json` from the same machine, but if I try it from the load-generating machine I get a "Connection refused".

Do you know how to tell it to accept connections from `0.0.0.0` or `::` instead of `127.0.0.1`?

**Comment by michaelhixson** [comment]
ok it looks like we can add `--host 0.0.0.0` to that last line in `setup.sh` and that solves the problem.  I'll put together a PR for this tomorrow.
