### ISSUE TITLE
Frameworks using gzip encoding which is prohibited by the rules

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2646]
**Update 1**: pull request for `Dropwizard` submitted by me
**Update 2**: pull request for `hapi` submitted by nbrady-techempower
**Update 3**: pull request for most of the `PHP` frameworks submitted by joanhey
**Update 4**: pull request for `Tapestry` submitted by me

**Update**: I've a quick look at the PR by joanhey. I think only `yii2-hhvm` is not covered by it and it will be the last one left. The other `php` frameworks seems to be covered.

It will be good someone else to check this information also.
It is possible I've missed something and/or to have false positives but here are the steps how I've checked.

I've downloaded the R14 preview 2 logs:

> wget \
>      --recursive \
>      --no-clobber \
>      --page-requisites \
>      --html-extension \
>      --convert-links \
>      --restrict-file-names=windows \
>      --domains tfb-logs.techempower.com \
>      --no-parent \
>          http://tfb-logs.techempower.com/round-14/preview-2/

Using grep: `~/tmp/r14p2$ grep -rl --include="verification.txt" "'content-encoding': 'gzip'" | sort`.
Results are:

> zloster@box:~ /tmp/r14p2$ grep -rl --include="verification.txt" "'content-encoding': 'gzip'" | sort
> tfb-logs.techempower.com/round-14/preview-2/codeigniter-raw_hhvm/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/codeigniter-raw_hhvm/query/verification.txt
> ~~tfb-logs.techempower.com/round-14/preview-2/dropwizard/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-mongodb/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-mongodb/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-mongodb/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-postgres/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-postgres/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard-postgres/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/dropwizard/update/verification.txt~~
> ~~tfb-logs.techempower.com/round-14/preview-2/hapi/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi/json/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-mysql/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-mysql/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-mysql/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-mysql/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi/plaintext/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-postgres/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-postgres/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-postgres/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi-postgres/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hapi/update/verification.txt~~
> tfb-logs.techempower.com/round-14/preview-2/hhvm/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hhvm/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/hhvm/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/laravel-hhvm-raw/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/laravel-hhvm-raw/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress/json/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress-mysql-raw/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress-mysql-raw/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress/plaintext/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/restexpress/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/slim-hhvm/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/slim-hhvm/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/slim-hhvm/update/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/snap/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/snap/json/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/snap/plaintext/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/snap/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/symfony2-hhvm/db/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/symfony2-hhvm/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/symfony2-hhvm/json/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/symfony2-hhvm/plaintext/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/symfony2-hhvm/query/verification.txt
> ~~tfb-logs.techempower.com/round-14/preview-2/tapestry/fortune/verification.txt~~
> tfb-logs.techempower.com/round-14/preview-2/yii2-hhvm/fortune/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/yii2-hhvm/query/verification.txt
> tfb-logs.techempower.com/round-14/preview-2/yii2-hhvm/update/verification.txt
> zloster@box:~/tmp/r14p2$

**Comment by zloster** [comment]
@nbrady-techempower IMO this issue should stay open since not all frameworks are fixed

**Comment by nbrady-techempower** [comment]
@zloster that's fine. it was closed automatically because of the commit message in the PR that addressed it

**Comment by nbrady-techempower** [comment]
@zloster #2736 will solve all of the `hapi` items
