### ISSUE TITLE
Configuration validation routine references dead url

### ISSUE THREAD

**Issue by KevinBrogan** [TechEmpower/FrameworkBenchmarks#2665]
./FrameworkBenchmarks/toolset/benchmark/framework_test.py : line 908
`  windows_url = "https://github.com/TechEmpower/FrameworkBenchmarks/milestones/Windows%%20Compatibility"`

This url does not exist, and it is referenced in line 959 and line 965 of the same file, as help text for the os and database_os test config options.

**Comment by nbrady-techempower** [comment]
Thanks for pointing this out. I've replaced that reference with the issue containing work towards getting windows compatibility. Unfortunately, still probably a ways away.
