### ISSUE TITLE
Clarification request - Fortune test implementation in most JavaScript frameworks

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2672]
I was looking at the Fortune test implementations for some of the JavaScript frameworks and I've found this:

```
// File A
const self = module.exports = {

  ADDITIONAL_FORTUNE: {
    id: 0,
    message: 'Additional fortune added at request time.'
  },
```
combined with this:

```
// File B
    Fortunes: (req, res) => {
    mongodbGetAllFortunes((err, fortunes) => {
      if (err) { return process.exit(1) }

      fortunes.push(h.ADDITIONAL_FORTUNE);
```

The [first one is here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/helper.js#L7-L10), the [second one is here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/mongodb-raw.js#L67).

What is the problem? IMO the `fortunes.push(h.ADDITIONAL_FORTUNE)` is not newly instantiated object. I'm not an expert in Node.js but I've searched for more information about the subject and found this: http://fredkschott.com/post/2014/06/require-and-the-module-system/. If the information there is correct and I've understood it correctly, than the `h.ADDITIONAL_FORTUNE` is in fact something like a cached field in a long live singleton object.

[The rules for the Fortune test, number 6](http://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#fortunes) require to construct a new object during the request time and adding it to the data structure.

The list of frameworks that seem to create new object:

- [JavaScript/express](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/express/app.js#L160-L170)
- [JavaScript/koa](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/koa/app.js#L104-L107)
- [JavaScript/ringojs](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/ringojs/app/views.js#L34-L38)

The list of frameworks that are using `h.ADDITIONAL_FORTUNE`:

- JavaScript/nodejs - [mongodb-raw.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/mongodb-raw.js#L67), [mongoose.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/mongoose.js#L60),  [mysql-raw.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/mysql-raw.js#L72), [sequelize-postgres.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/sequelize-postgres.js#L64), [sequelize.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/nodejs/handlers/sequelize.js#L66)
- JavaScript/hapi - [mongoose.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/hapi/handlers/mongoose.js#L72), [sequelize-postgres.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/hapi/handlers/sequelize-postgres.js#L60), [sequelize.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/hapi/handlers/sequelize.js#L65)
- JavaScript/sailsjs - [RedisController.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/sailsjs/api/controllers/RedisController.js#L103), [SequelizeMySQLController.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/sailsjs/api/controllers/SequelizeMySQLController.js#L123), [SequelizePostgresController.js](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/sailsjs/api/controllers/SequelizePostgresController.js#L124)
- Also the Node.js/Mitol which is in PR #2671 

Am I correct or I'm missing something?

**Comment by Helidium** [comment]
You are correct.

**Comment by nbrady-techempower** [comment]
@zolster I recently changed all of these frameworks over to use es6 when I updated node and completely missed this. You are 100% correct.

**Comment by zloster** [comment]
@nbrady-techempower I've played recently with the new 2.2.0 release of GNU Guile (which is implementation of Scheme). Probably I've got a high sensitivity to brackets "()" :)
