### ISSUE TITLE
NodeJs mysql-raw benchmark seems to select the same row over and over

### ISSUE THREAD

**Issue by karldcampbell** [TechEmpower/FrameworkBenchmarks#2685]
Maybe I'm missing something, I'm by no means a JS expert.

In mysql-raw.js,

> const queries = {
> RANDOM_WORLD: "SELECT * FROM world WHERE id = " + h.randomTfbNumber(),

> const mysqlRandomWorld = (callback) =>
>   connection.query(queries.RANDOM_WORLD, (err, rows, fields) => {
>     callback(err, rows[0]);
> });

What this seems to do is initialize `id` at the beginning of the test, and then never update it.  This would result in the *same* row being selected over and over, instead of a different row for each query. 

Am I missing something?

**Comment by michaelhixson** [comment]
I think you're right.  You can see the impact of this in the verification log:
http://tfb-logs.techempower.com/round-14/preview-3/nodejs/query/verification.txt

It's supposed to look more like this other log (from a different, well-behaved test):
http://tfb-logs.techempower.com/round-14/preview-3/nodejs-postgres/query/verification.txt

**Comment by nbrady-techempower** [comment]
Thanks @karldcampbell , Submitted a fix.
