### ISSUE TITLE
Error during database setup on Travis

### ISSUE THREAD

**Issue by DEGoodmanWilson** [TechEmpower/FrameworkBenchmarks#2687]
Hello,

I have a fork of the benchmarks for adding a new framework. Everything runs great when I run the following in a Vagrant virtual machine:

```
tfb --mode verify --test-dir C++/luna
```

But when Travis runs, the setup process hangs just here:

```
================================================================================
  Preparing Server, Database, and Client ...
================================================================================

net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
kernel.shmmax = 134217728
kernel.shmall = 2097152
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.docker0.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
vagrant@tfb-database's password: 
```

I am having a hard time understanding where I might have gone wrong.

Travis link: https://travis-ci.org/DEGoodmanWilson/FrameworkBenchmarks/jobs/221784297

GitHub link: https://github.com/DEGoodmanWilson/FrameworkBenchmarks/tree/luna

**Comment by nbrady-techempower** [comment]
Hi @DEGoodmanWilson!

Please rebase from our master branch. You should not have a `benchmark.cfg` file in your repo, just the `benchmark.cfg.example`. That should be for local testing only.

**Comment by nbrady-techempower** [comment]
This will resolve that issue. Let me know if you have any other problems.

**Comment by DEGoodmanWilson** [comment]
I'm not at all sure how the `benchmark.cfg` file got commited. Thank you for noticing that, as it did the trick.
