### ISSUE TITLE
Fix environment-level timezone issue with mysql-connector-java 6

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#2708]
When Java frameworks try to use `mysql-connector-java` 6.x (as opposed to 5.x), they will fail to run in our ServerCentral environment because of exceptions like this:

```
java.sql.SQLException: The server time zone value 'PDT' is
unrecognized or represents more than one time zone. You must
configure either the server or JDBC driver (via the
serverTimezone configuration property) to use a more specifc
time zone value if you want to utilize time zone support.
```

I put off dealing with this problem for Round 14 by changing all the implementations to use `mysql-connector-java` 5.x instead.

As the exception message says, frameworks can use 6.x and work around this problem by setting the `serverTimezone` property in their implementation.  Setting it to `America/Los_Angeles` "works"...

...but they shouldn't have to do this.  There should be an environment-level fix.  This exception does not happen when Travis runs the tests or (apparently) when the contributors run these tests in their own environments.

This exception does occur in our (TechEmpower's) in-house environment as well, so we should be able to test and verify fixes without disrupting ServerCentral's continuous benchmarks.

What's the right way to fix this?

**Comment by zloster** [comment]
IMO there are two approaches to the problem:

1. Add explicit setting for the MySQL server in which timezone it will operate - https://dev.mysql.com/doc/refman/5.5/en/time-zone-support.html. Maybe it will be a good idea to do the same for the other databases - PostgreSQL have [similar setting](https://www.postgresql.org/docs/current/static/runtime-config-client.html#GUC-TIMEZONE), I don't know about MondoDB.

1. The computers that are running the benchmarks should be configured to use `America/Los_Angeles` as timezone id. Why? - see below.

This particular timezone `PDT/PST` has two abbreviation depending on daylight saving - [Wikipedia](https://en.wikipedia.org/wiki/Pacific_Time_Zone). That is also noted in the [Java 8 java docs](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#of-java.lang.String-java.util.Map-):
> Many users of time-zones use short abbreviations, such as PST for 'Pacific Standard Time' and PDT for 'Pacific Daylight Time'. These abbreviations are not unique, and so cannot be used as IDs. This method allows a map of string to time-zone to be setup and reused within an application.

Also here is a [question from stackoverflow.com](http://stackoverflow.com/questions/31151764/java-timezone-gettimezonepdt-not-working).

**Comment by nbrady-techempower** [comment]
Thanks @zloster - After discussing internally on Friday, we're going to explicitly set the timezone in MySQL on the server. I'll be adding that to the installation script on Monday.
