### ISSUE TITLE
Verify the PHP results

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#2717]
In round 13, php is more than 4 times slower. I thought it was a problem of configuration in that round, but in the preview 14 it is the same.

| test | round 11 | round 12 | round 13 | preview 14 |
| --- | --: | --: | --: | --: |
| Plaintext php5 | 177,281 | 195,136 | 44,445 | 45,857 |
| Plaintext php7 | | 163,769 | 45,616 | 44,019 |
| Json php5 | 171,149 | 176,469 | 43,570 | 44,893 |
| Json php7 | | 172,469 | | 42,678 | 42,237 |
| Single query php5-raw | | 116,628 | 40,046 | 39,088 |
| Fortunes php5-raw | | 97,373 | 41,580 | 38,357 |

## How is this possible ?
We are not talking about 10-20% difference, it is 4.4 times slower, with faster servers.
There is a bug in round 11-12 or in round 13-14.

Have you found any bug ?  that explain this difference
What changed in php from round 12 to 13 ?

**Comment by nbrady-techempower** [comment]
Hi @joanhey,

Thanks for preparing this. If you look at the diffs between rounds, you'll see that there were a lot of code changes to the php implementations. Tests broke (for whatever reason) between round 12 and round 13, and there were also some test requirements that were being followed properly. What we on the team did was simply make sure that all the tests were working again, but we certainly didn't optimize the code. 

In other words, this could very well be a php configuration issue, an optimization issue, or a few other things. It's doubtful it's an overall toolset bug as that dip in performance wasn't consistent with other frameworks. 

It's important to note, though we try and help with performance issues for particular languages/frameworks, our core focus is on the toolset and delivering results. We rely on the community to provide and keep up with implementations. The php tests could definitely use a once over from some php experts.

**Comment by zloster** [comment]
@joanhey

> What changed in php from round 12 to 13 ?

The short answer is the hardware environment. Note that all frameworks have reduced results.

More information here: https://groups.google.com/d/msg/framework-benchmarks/nePDNY9jp-4/Y8bw-XM5AAAJ and here: https://github.com/TechEmpower/FrameworkBenchmarks/issues/2366

**Comment by nbrady-techempower** [comment]
Good point by @zloster 
In my mind, that happened between 11 and 12 and thought @joanhey had singled those php tests out for a reason. Thanks!
