### ISSUE TITLE
Add --mode dev to tfb

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#2740]
```
-m {benchmark,verify}, --mode {benchmark,verify}
                        verify mode will only start up the tests, curl the
                        urls and shutdown (default: benchmark)

```
The `dev` mode will be like the verify, but without shutdown.
So will be easier to debug problems

**Comment by nbrady-techempower** [comment]
I like this idea. I've added it to the toolset roadmap. https://github.com/TechEmpower/FrameworkBenchmarks/projects/1

**Comment by nbrady-techempower** [comment]
@joanhey There is now a `--mode debug` Thanks for the idea. :)
