### ISSUE TITLE
C++/Luna Failing

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#2747]
@DEGoodmanWilson Luna seems to be failing recently while trying to grab a dependency https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/227115651#L1856

**Comment by DEGoodmanWilson** [comment]
Interesting. http://gmplib.org seems to be down at the moment, will have a look on Sunday morning.

**Comment by DEGoodmanWilson** [comment]
OK, I've updated the dependency to look at a mirror instead of gmplib.org. @nbrady-techempower can you try running the test again?

**Comment by nbrady-techempower** [comment]
@DEGoodmanWilson Looks like some other issues. No need to worry about it now though, enjoy your weekend! https://api.travis-ci.org/jobs/227200626/log.txt?deansi=true

**Comment by DEGoodmanWilson** [comment]
There were a couple of issues surrounding libmicrohttpd, and the way I was importing pthreads in the configuration file here. I've fixed the package dependencies upstream, those should get imported here automatically. The remainder has gone into a PR. All of this was triggered by some changes in the way an upstream package dependency was configured to handle libpthread. All should be good now, but we'll see if the tests pass now.

**Comment by nbrady-techempower** [comment]
Looks like it's working now. Thanks @DEGoodmanWilson !

**Comment by DEGoodmanWilson** [comment]
🙇
