### ISSUE TITLE
go-std mysql marked as stripped

### ISSUE THREAD

**Issue by egonelbre** [TechEmpower/FrameworkBenchmarks#2774]
While going over the Round 14 (awesome job as usual) results, I noticed that go-std mysql is marked as stripped.

The critical-path presented in that code is entirely realistic for a simple server and similar approach is recommended as the starting point for a web application -- unless there's a good reason not to. _I would even consider not using automatic routing, because for this server, seems unnecessary._

The only issue I can see production-wise is database error handling -- usually you would want to respond with 503 to the end-user... Although, depending on the requirements, responding with an empty answer would be acceptable as well.

As proof for my statements: https://golang.org/doc/articles/wiki/

Also, "framework" field for "default" config should be probably set to "None" as well.

**Comment by nbrady-techempower** [comment]
@egonelbre Thanks for pointing that out. If you'd like to open up a PR to make those changes, I'll gladly get them in. If not, I can review some time next week.
