### ISSUE TITLE
Upgrade nodejs

### ISSUE THREAD

**Issue by scttcper** [TechEmpower/FrameworkBenchmarks#2777]
Current version used is 7.5.0. I think it still had a memory leak issue with async/await and its still locked behind harmony flag. This is no longer the case with > 7.6.0. v7.10.0 is current version. Could wait until node v8.x comes out at the end of the month which brings v8 5.7. https://v8project.blogspot.com/2017/02/v8-release-57.html

**Comment by nbrady-techempower** [comment]
@scttcper Thanks Scott. I've actually been paying close attention to this for other projects. Node v8 was bumped back a couple of weeks, but as soon as it drops I will be making that upgrade.
