### ISSUE TITLE
Add PHP-PM

### ISSUE THREAD

**Issue by Jurigag** [TechEmpower/FrameworkBenchmarks#2794]
I would like to see symfony/laravel tested on php-pm project https://github.com/php-pm/php-pm

It simply turns application to be daemon, bootstrapped once, kind of event based. Not sure if it should be added as platform or new front-end server.

**Comment by nbrady-techempower** [comment]
From their docs:
> Why using PPM as development server instead of vagrant, nginx or apache?

So it looks like it would be classified as `webserver` in the `benchmark_config.json` within the scope of our benchmarks, though I don't really know much about it.

I've added it here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features

If you'd like to try adding it to symfony or laravel, feel free to open up a Pull Request and I'd be happy to help guide you.
