### ISSUE TITLE
Nodejs Pm2

### ISSUE THREAD

**Issue by Talento90** [TechEmpower/FrameworkBenchmarks#2798]
First of all, I would like to say good job maintaining this project! 👍 

My question: Is it possible to run node.js tests using PM2 or Cluster module?

Cheers!

**Comment by RX14** [comment]
Looks like most of the nodejs tests run using the cluster module already.

**Comment by nbrady-techempower** [comment]
Hey, thanks for the comment! Yeah, most of the javascript frameworks running on node are taking advantage of clusters. Feel free to open pull requests if you see further optimizations. :)
