### ISSUE TITLE
HTTP HOST request header for wrk

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2802]
I've noticed that all `wrk` requests are using `localhost` for the `Host` HTTP header.
Example:
```
---------------------------------------------------------
 Running Primer dropwizard
 wrk -H 'Host: localhost' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 5 -c 8 --timeout 8 -t 8 http://TFB-server:9090/json
---------------------------------------------------------
```

IMO the command should include `-H:tbf-server` instead.

**Comment by bhauer** [comment]
That seems reasonable.  If we change this, let's keep an eye on the next continuous run results to ensure that no implementations have broken as a result.  Theoretically, we might have some implementations that are *expecting* to see localhost.  I'm hopeful that none do this in practice.
