### ISSUE TITLE
Available RAM on ServerCentral?

### ISSUE THREAD

**Issue by nateberkopec** [TechEmpower/FrameworkBenchmarks#2810]
[It's not documented](https://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Environment/).

**Comment by zloster** [comment]
@nateberkopec Some time ago in the IRC chat https://botbot.me/freenode/techempower-fwbm/2017-04-03/?msg=83393402&page=1

**Comment by nbrady-techempower** [comment]
528gb on the app server and 16gb on the db server. I'll update the docs today. Thanks to both.

**Comment by nbrady-techempower** [comment]
This will appear live momentarily https://github.com/TechEmpower/TFB-Documentation/blob/master/docs/Project-Information/Environment.md

**Comment by nateberkopec** [comment]
@nbrady-techempower Sorry to be pedantic, but isn't it 40 cores, 80 threads (on app server)? Probably worth getting specific because someone might assume it's actually 160 threads b/c it's an Intel box.

**Comment by bhauer** [comment]
That is correct.  40 physical cores, 80 HT cores.

**Comment by nbrady-techempower** [comment]
Updated the docs to state HT cores. Thanks!

**Comment by RX14** [comment]
I think something like "40 cores 80 threads" would be a lot clearer. I'd assume 160 threads of I read the docs.
