### ISSUE TITLE
Vagrant development is not working currently 

### ISSUE THREAD

**Issue by jeevatkm** [TechEmpower/FrameworkBenchmarks#2854]
Vagrant development is not working currently. I have followed the [latest guide](http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/#vagrant-development-environment) 

When I run `tfb --mode verify --test gemini`

I have master branch as of `Jun 06, 2017` sha `c4a1bee9486785d34b8133415e09c63c192da11c`.

_Please Note: travis build is working_

### OS (Please include kernel version)
Vagrant: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-87-generic x86_64)
My OS: Mac OS Sierra

### Expected Behavior
* Expected to run test verify for the framework/test

### Actual Behavior
* Failling to run the tests

### Steps to reproduce behavior
* Just follow the latest guide and run the `tfb --mode verify --test gemini`

### Other details and logs
```bash
vagrant@TFB-all:~/FrameworkBenchmarks$ tfb --mode verify --test gemini
FWROOT is /home/vagrant/FrameworkBenchmarks.
WARNING:root:results.json for test not found.
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
================================================================================
  Preparing Server, Database, and Client ...
================================================================================


net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
kernel.shmmax = 134217728
kernel.shmall = 2097152
Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant
Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant
================================================================================
  Running Tests...
================================================================================


--------------------------------------------------------------------------------                                                                                                  | Rough ETA:  --:--:--
  Running Test: gemini
--------------------------------------------------------------------------------


Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant


INSTALL: Installing client software




INSTALL: ssh -T -o StrictHostKeyChecking=no vagrant@TFB-client -i /home/vagrant/.ssh/id_rsa
Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant
AttributeError: _FrameworkTest__install_error not a member of FrameworkTest or Benchmarker
This is probably a bug
Process Test Runner (gemini):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 565, in __run_test
    result, process = test.start(out)
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 206, in start
    self.__install_error("status code %s running subprocess '%s'." % (returncode, self.benchmarker.client_ssh_string))
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 756, in __getattr__
    x = getattr(self.benchmarker, name)
AttributeError: Benchmarker instance has no attribute '_FrameworkTest__install_error'
verify: 100% |####################################################################################################################################################################| Rough Time: 00:00:00
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
================================================================================
  Verification Summary


| Test: gemini
|      NO RESULTS (Did framework launch?)
================================================================================


Time to complete: 1 seconds
Results are saved in /home/vagrant/FrameworkBenchmarks/results/20170607231610
```

**Comment by nbrady-techempower** [comment]
Hi @jeevatkm Is this a vagrant vm that's been up for a while and you're pulling the latest master? I've just tested the current master with a new vagrant up. We've done some work on the vagrant scripts that might require you spinning up from scratch.

**Comment by jeevatkm** [comment]
@nbrady-techempower Thanks for quick response.

I have forked master on Jun 6, 2017 last commit msg is`TFBReaper Improvements (#2847)`, 

Do I have to fork it again? please let me know.

**Comment by nbrady-techempower** [comment]
@jeevatkm That fork is fine. Do a new `vagrant up` from `deployment/vagrant` Make sure the other vm has been removed and it's files deleted.

**Comment by jeevatkm** [comment]
@nbrady-techempower Got it, let me give it try and get back.

**Comment by msmith-techempower** [comment]
Gave this issue a +1 based on the initial write-up.

**Comment by jeevatkm** [comment]
I have followed these steps, still facing the same issue. 
* Deleted the existing vagrant vm from virtual box
* Executed the `vagrant up`
* Ran the test `tfb --mode verify --test gemini`

I'm attaching two logs for your analysis.
* [vagrant-up-logs.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/1062492/vagrant-up-logs.txt)
* [tfb-test-logs.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/1062494/tfb-test-logs.txt)

_PS: http://sprunge.us is unavailable so attached the files._

**Comment by nbrady-techempower** [comment]
The `Too many authentication failures for vagrant` seems to be the issue. Within the VM can you try the following to make sure they all work:

```
ssh TFB-database
ssh TFB-server
ssh TFB-client
```

Also, can you give me the contents of `/etc/hosts`

I just tried from scratch and had no issues again, so I'm wondering if this is OS-specific.

**Comment by jeevatkm** [comment]
All three ssh doesn't work. It ends up with 
```
Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant.
```

/etc/hosts
```
vagrant@TFB-all:~$ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
127.0.1.1 TFB-all TFB-all
127.0.0.1 TFB-database
127.0.0.1 TFB-client
127.0.0.1 TFB-server
```

**Comment by nbrady-techempower** [comment]
Ok, from the vagrant up logs you sent, it looks like the script should have worked to set you up. On the vagrant machine can you also give me the output of:

`~/.ssh/config`

It should have:

`NoHostAuthenticationForLocalhost yes`

Also the output of `/etc/ssh/sshd_config`

**Comment by jeevatkm** [comment]
Please find the details -

~/.ssh/config
```
vagrant@TFB-all:~$ cat ~/.ssh/config
NoHostAuthenticationForLocalhost yes
```

/etc/ssh/sshd_config - [sshd_config.txt](https://github.com/TechEmpower/FrameworkBenchmarks/files/1065065/sshd_config.txt)

**Comment by nbrady-techempower** [comment]
The ssh config for vagrant looks correct. We're wondering if you're hitting your own ssh server from vagrant. Can you check your host machine for authentication failures? (I'm not sure where those logs are on Mac OS)

**Comment by jeevatkm** [comment]
I will verify and get back. Thanks for your response.

**Comment by jeevatkm** [comment]
@nbrady-techempower You're correct. Took a while to debug it. My ssh server was standing in the way because my ssh config has forward agent yes. 

```
vagrant ssh -- -o ForwardAgent=no
```

Like you said, everything is working fine. Thank you for your time.

**Comment by jeevatkm** [comment]
I would like to know, when is the freeze date for Round 15?

**Comment by nbrady-techempower** [comment]
That's great news! No problem!

So there's no freeze date set right now. However there is a preview (first) currently running and we're going to try to do 4 or 5 previews. So you have some time

**Comment by jeevatkm** [comment]
Nice, sorry I'm introducing late. I'm the author of [aah framework](https://aahframework.org), once I'm done with benchmark test. I will submit my PR. So that I can get feedback from preview run.

**Comment by nbrady-techempower** [comment]
Fantastic! Please let us know if there's anything else we can help with.

**Comment by jeevatkm** [comment]
No, thank you. You have already helped me. If I get stuck somewhere I will reach out to you.
