### ISSUE TITLE
Trouble with Vagrant/PostgreSQL install in fresh VM

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2879]
### OS (Please include kernel version)

Vagrant: Ubuntu 14.04.5 LTS (GNU/Linux  3.13.0-119-generic)
Host: Ubuntu 12.04, kernel 3.13.0

### Expected Behaviour

`tfb -m verify --test servlet-postgres-raw` to pass. Example:
```
================================================================================
  Verification Summary

| Test: servlet-postgres-raw
|       query         : WARN
|       db            : PASS
|       update        : PASS
|       fortune       : PASS
================================================================================

Time to complete: 190 seconds
```

### Actual Behaviour

When executing `tfb -m verify --test servlet-postgres-raw` in the logs I see the following:

```
Setup servlet-postgres-raw: Use 'apt-get autoremove' to remove it.
Setup servlet-postgres-raw: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Setup servlet-postgres-raw: mv: cannot move ‘postgresql.conf’ to ‘/etc/postgresql/9.3/main/postgresql.conf’: No such file or directory
Setup servlet-postgres-raw: mv: cannot move ‘pg_hba.conf’ to ‘/etc/postgresql/9.3/main/pg_hba.conf’: No such file or directory
Setup servlet-postgres-raw: cp: cannot stat ‘/var/lib/postgresql/9.3/main’: No such file or directory
Setup servlet-postgres-raw: Pseudo-terminal will not be allocated because stdin is not a terminal.
Setup servlet-postgres-raw: Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-119-generic x86_64)

```
And at the end:
```
verify: 100% |################################################################################################| Rough Time: 00:01:51
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
================================================================================
  Verification Summary

| Test: servlet-postgres-raw
|       query         : FAIL
|       db            : FAIL
|       update        : FAIL
|       fortune       : FAIL
================================================================================

Time to complete: 120 seconds
```

### Steps to reproduce behaviour

1. Update the `master` to [latest](https://github.com/TechEmpower/FrameworkBenchmarks/commit/bf4c1320ed9fddfa3ff7db1f9482ee2e585febc6)
1. Update the Ubuntu basebox to latest
1. Delete the old Vagrant VM
1. Execute `vagrant up`
1. Execute `vagrant ssh`
1. Execute `tfb -m verify --test servlet-postgres-raw`

### Other details and logs

For a workaround execute the following in Vagrant:
```
vagrant@tfb-all:~/FrameworkBenchmarks$ sudo pg_createcluster 9.3 main
Creating new cluster 9.3/main ...
  config /etc/postgresql/9.3/main
  data   /var/lib/postgresql/9.3/main
  locale en_US.UTF-8
  port   5432
vagrant@tfb-all:~/FrameworkBenchmarks$ rm installs/postgresql.installed 
vagrant@tfb-all:~/FrameworkBenchmarks$ tfb -m verify --test servlet-postgres-raw
```
This creates a PostgreSQL cluster (i.e. data directories and configuration) named `main` which according to the `man pg_createcluster` is the default name.

**Comment by nbrady-techempower** [comment]
@zloster I just ran a fresh install and this worked fine for me.

```
Setup servlet-postgres-raw: mv: cannot move ‘postgresql.conf’ to ‘/etc/postgresql/9.3/main/postgresql.conf’: No such file or directory
Setup servlet-postgres-raw: mv: cannot move ‘pg_hba.conf’ to ‘/etc/postgresql/9.3/main/pg_hba.conf’: No such file or directory
Setup servlet-postgres-raw: cp: cannot stat ‘/var/lib/postgresql/9.3/main’: No such file or directory
```

The above suggests there may have been a problem copying the conf file we have in the toolset over.

**Comment by zloster** [comment]
@nbrady-techempower I just had an _aha-moment_:
There were errors in the log about the `locale`:
```
Setup dropwizard: perl: warning: Setting locale failed.
Setup dropwizard: perl: warning: Please check that your locale settings:
Setup dropwizard:       LANGUAGE = (unset),
Setup dropwizard:       LC_ALL = (unset),
Setup dropwizard:       LC_TIME = "bg_BG.UTF-8",
Setup dropwizard:       LC_MONETARY = "bg_BG.UTF-8",
Setup dropwizard:       LC_ADDRESS = "bg_BG.UTF-8",
Setup dropwizard:       LC_TELEPHONE = "bg_BG.UTF-8",
Setup dropwizard:       LC_NAME = "bg_BG.UTF-8",
Setup dropwizard:       LC_MEASUREMENT = "bg_BG.UTF-8",
Setup dropwizard:       LC_IDENTIFICATION = "bg_BG.UTF-8",
Setup dropwizard:       LC_NUMERIC = "bg_BG.UTF-8",
Setup dropwizard:       LC_PAPER = "bg_BG.UTF-8",
Setup dropwizard:       LANG = "en_US.UTF-8"
Setup dropwizard:     are supported and installed on your system.
Setup dropwizard: perl: warning: Falling back to the standard locale ("C").
Setup dropwizard: locale: Cannot set LC_ALL to default locale: No such file or directory
```
The PostgreSQL commands and installer depend on `perl`. The `pg_createcluster` was failing before I've fixed the locale. Something have changed in the default configuration of the SSH server in the Vagrant box (probably) - my connection chain at that moment was Ubuntu12.04-->SSH-->Ubuntu14.04-->SSH-->Vagrant. The Ubuntu12.04 is using a mix of `bg_BG.UTF-8` and `en_US.UTF-8`. So the `bg_BG.UTF-8` was request from the SSH server when logging into a session. But the Vagrant box didn't have `bg_BG.UTF-8` generated. So I've just generated it and everything started to work. The other options are to set the locale explicitly in the remote account or reconfigure the SSH server not to honour locales requests.

I'm closing this now. My apologies for taking your time.

**Comment by flip111** [comment]
@zloster can you reopen this issue please? I'm also getting errors about locale from a fresh install.

**Comment by zloster** [comment]
@flip111 The options to remedy this kind of problem are described in my last message.
Which option have you tried?

**Comment by flip111** [comment]
@zloster i'd like to see this fixed in tfb itself so i can just clone and run again. Perhaps set the locale to english utf8 by default if that is a solution

**Comment by zloster** [comment]
I don't think there is something to be fixed in TFB itself. Why?
We have the following components involved:

1. the _OS_ install (the Vagrant image)
2. the _SSH_ server and it configuration
3. the _locale_ configuration of the computer we are using to connect to TFB Vagrant environment

The defaults are:

1. the OS configuration is "LANG=en_US.UTF-8"
2. the SSH server will use the default if the SSH client is not requesting some particular _locale_

Here the problem was:
the _locale_ and _SSH_ configuration of the user's computer are not under control of TFB environment. **And it should not be**. If my SSH client is requesting locale that is not configured on the server **it is a problem at my end**. So I just issued the appropriate commands on the server and I'm able to use the TFB environment the way I like - for example when I run `ls -al` the dates are in my native language. If the SSH is not using the default configuration I will not be able to do this.

If we want to

> just clone and run again

(and we are using some Deutsch, Cantonese or Bulgarian locale by default) what is stopping us from using:
`LC_ALL=C vagrant ssh` instead of `vagrant ssh` or [tweaking the SSH options for Vagrant](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html)?

@nbrady-techempower Please, could you take a look. I've tried to summarise why IMHO the problem here is not something TFB should act on.
