### ISSUE TITLE
Upgrade Grails to 3.x

### ISSUE THREAD

**Issue by donald-jackson** [TechEmpower/FrameworkBenchmarks#2915]
Grails framework 2.x has been officially deprecated as of 1 June 2017, would it be possible for the tests to be upgraded to 3.x ?

**Comment by cjnething** [comment]
Hi @donald-jackson, we are not experts on every language/framework, so we rely on the community to make updates and add new frameworks. If you'd like to see Grails upgraded, we encourage you to make a pull request! Thanks!

**Comment by cjnething** [comment]
Whoops, didn't mean to close it. If someone ends up making a pull request, they can reference this issue.

**Comment by donald-jackson** [comment]
I'll make an attempt at this and submit a pull request when ready

**Comment by riktimmondal** [comment]
I would like to contribute can you provide some resource to get started on this since i am a beginner

**Comment by nbrady-techempower** [comment]
Thanks @donald-jackson Let us know if you need anything.

@riktimmondal Have you checked out the docs at http://frameworkbenchmarks.readthedocs.io/en/latest/
