### ISSUE TITLE
Default pool size for JavaScript benchmarks

### ISSUE THREAD

**Issue by corporatepiyush** [TechEmpower/FrameworkBenchmarks#2931]
For most JavaScript frameworks, test suite uses default size of db connection thread pool, which is incorrect.
Perf testing must be done by mentioning db client max thread pool size to value say 256.

WHERE

Db clients include
1. Mongoose (for mongodb)
2. Sequelize ORM (for postgres)
3. Redis

**Comment by nbrady-techempower** [comment]
Feel free to make a PR for these changes. Closing this as it's not really a problem with our suite. Issues relating to specific framework test implementations can be opened on their repo, or ping the folks that added the test.
