### ISSUE TITLE
Move TFB components into containers progressively

### ISSUE THREAD

**Issue by jaguililla** [TechEmpower/FrameworkBenchmarks#2943]
First of all, this project is OUTSTANDING I can't thank you enough for allowing me to test the performance of my framework this good and also free. You folks are great!

I've been using your project for some rounds and along this time, some good technologies have gone mainstream (containers and microservices tools). As I learned these tools, I've seen a chance to use them inside your benchmark.

By using standard tools, the code base would be reduced and the development speed could be improved.

Will it be possible to use any of the following technologies inside the benchmark?

### Docker
* Create base images for languages (e.g. JDK 8) or servers (e.g. Resin, MySQL...). Though there are already pre-made ones at [hub.docker.com](hub.docker.com).
* Frameworks will define a `Dockerfile` using a Docker base image and building the code inside it.
* PROS:
  - No need for scripts in definitions in the frameworks.
  - Easy of development for framework benchmarks.
* CONS:
  - Windows containers for Docker are not mainstream.
  - Bare metal servers should be provisioned with Docker infrastructure.

### Docker Compose
* Move DBs and servers to containers inside a Docker Compose file.
* Each framework should create a Docker Compose file inheriting the common one, and linking to its used dependencies.
* A container can be used for each permutation.
* PROS:
  - Isolation between components.
  - Deleting containers do not leave any state in the machine.

### Kubernetes
* Can be used to scale the load generators.
* Allows to test framework scalability.

### JMeter
* Extract more information from requests.
* Allows the definition of assertions (they can be included in the warm up, and omitted in benchmark).
* CONS: Performance lost.

### Elastic Search / Kibana
* Allows to generate reports from raw data. A lot of reports can be generated without coding.

I've implemented something along those lines (smaller in scope, of course) in Hexagon's benchmark. You can check the details here:

* [docker-compose.yml](https://github.com/hexagonkt/hexagon/blob/master/docker-compose.yaml)
* [test.jmx](https://github.com/hexagonkt/hexagon/blob/master/hexagon_benchmark/load_test.jmx)

Thanks again for allowing us to test our frameworks and letting us compare the performance between them.

**Comment by RX14** [comment]
I think there are quite a few seperate projects here. I'd be :+1: for putting benchmark targets in containers, but obviously the opinion which matters most is that of the techempower guys. I think it would be good to refactor the benchmarks in pieces, not just rewrite. 

Regarding performance, docker does have an overhead, although I'm not sure if it's significant. IIRC there's some syscall overhead and probably some network overhead from the added routing.

**Comment by jaguililla** [comment]
Docker probably has some overhead, It is a matter of balancing the pros and cons... and as you say, that is a decision to be made by TechEmpower people.

Thanks for your thoughts 👍

**Comment by nbrady-techempower** [comment]
Hey @jaguililla!

Thanks for the well thought out post. We've discussed moving to a container based solution like Docker internally quite a few times. I don't think any of us is really against the idea, it's mostly about the amount of work that comes with something like that. Not only does it require a lot of work on our end to make sure we continue with the same process: documentation, continuous integration testing, etc, but also remember that most of the tests here are submitted by members of the community and would require all of them to move their tests over.

As @RX14 mentioned, there are some other issues that would have to be vetted thoroughly before making a decision like that.
 
I'm certainly in favor of ways that would help improve the benchmark's modularity and will leave this open for anyone who wants to contribute to the discussion.

**Comment by jaguililla** [comment]
Ok, I knew that under a project with a lot of moving parts like this, this change could not be taken lightly. I will participate in this discussion to see if it can be done in some parts or not at all.

**Comment by Dith3r** [comment]
Up to using Jmeter why not try Gatling? it would easily add possibility to put some alternations to requests like params, more complex work flow (maybe something similar to TODO app).

**Comment by jaguililla** [comment]
@Dith3r If load generation is going to be changed (and that is something TE must decide) it would be great to list all available options and note their pros and cons. To me, Gatling.io seems a great tool (I do not know if all features are open though).

Regarding this discussion, I would split the proposal in smaller parts and see if they can be added to the road map one by one (and discussing each of them's details when the time comes).

What do you think?

**Comment by rmohta** [comment]
Wrt Docker and other container based deployments - we're seeing increased adoption of containers and microservice based architecture. Running these test in those settings (along with physical??) can give a sense of overhead, calculated in a scientific fashion.

I am more than happy to help out with this, if that helps :-)

**Comment by RX14** [comment]
@rmohta I think such a test is more likely to show a constant overhead on top of all the frameworks. Doing that for all the suite of frameworks and every round seems like a lot of work - a benchmark like you describe is most likely to be interesting as a benchmark done once and written up into a long blog post.

**Comment by msmith-techempower** [comment]
I am working on investigating Docker for primary replacement to the `fw_depends` and `setup.sh` implementation we have currently.

**Comment by msmith-techempower** [comment]
I'm going to consider this issue closed since everything is in a Docker container now.
