### ISSUE TITLE
Travis MySQL DB Config

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#2944]
It looks like travis mysql installation is broken. Similar to what happened in our testing environment, it looks like the version of mysql being installed on travis isn't compatible with the config we are pushing to it. This is causing a lot of failures on travis where there shouldn't be.

**Comment by mwpastore** [comment]
I have some updates I'd like to push but this is blocking my testing. Any ETA on a fix?

**Comment by nbrady-techempower** [comment]
@mwpastore sadly no immediate ETA. Resources here are tied up at the moment. This is only with the travis config however. Local testing with the vm setup we provide in the docs, or in your own environments should work fine, and then we can pull and test locally for now as a workaround to the travis issue.
