### ISSUE TITLE
ffead-cpp is not a part of the Round 15 Preview 2

### ISSUE THREAD

**Issue by sumeetchhetri** [TechEmpower/FrameworkBenchmarks#2949]
Am unable to see any of the 54 tests for the ffead-cpp framework,

ffead-cpp 
ffead-cpp-mysql
ffead-cpp-postgresql

ffead-cpp-apache2-mongo
ffead-cpp-apache2-mysql
ffead-cpp-apache2-postgresql

ffead-cpp-nginx-mongo
ffead-cpp-nginx-mysql
ffead-cpp-nginx-postgresql

Every test version has 6 tests each, cannot find even one of my framework tests in the Round 15 preview 2 results, am I missing anything here?

**Comment by nbrady-techempower** [comment]
That is strange. I will look in to that for you this week @sumeetchhetri and get back to you

**Comment by nbrady-techempower** [comment]
@sumeetchhetri Looks like your tests are showing up now for us in our current run. It's possible the run we posted finished around the time ffead was merged back in, but you should be in R15-P3.

All of your apache tests are failing though. Looks like you're just missing a `apache` in your `fw_depends` line in those setup files: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/ffead-cpp/setup-apache-mongo.sh#L3

**Comment by sumeetchhetri** [comment]
@nbrady-techempower, If you have a look at the recent changes being done for the ffead-cpp tests you will see that I no longer use the apache2 core pacakage instead I do a complete build from apache sources (https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/frameworks/ffead-cpp-httpd.sh) and refer these as
fw_depends ffead-cpp-httpd
in all of the ffead-cpp-apache-* tests

**Comment by nbrady-techempower** [comment]
@sumeetchhetri Understood. I did not dig that deep. Please check your setup files for broken sources. This is not correct: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/frameworks/ffead-cpp-httpd.sh#L9

**Comment by sumeetchhetri** [comment]
Fixed it - https://github.com/TechEmpower/FrameworkBenchmarks/pull/2967

**Comment by msmith-techempower** [comment]
Resolved with #2967
