### ISSUE TITLE
Pypy2 issues in round 15 preview 2 

### ISSUE THREAD

**Issue by Dith3r** [TechEmpower/FrameworkBenchmarks#2950]
Each framework setup with pypy2 failed with same error:

```
Setup *-pypy2:     creating /site-packages
Setup *-pypy2:     error: could not create '/site-packages': Permission denied
```

**Comment by methane** [comment]
Curious.  What is permission of these directories?

**Comment by Dith3r** [comment]
After first install of Pypy2 path to environment was written as PYPY_ROOT instead of PYPY2_ROOT. In result second test which required Pypy2 tried to use / as path.
