### ISSUE TITLE
dotnet-sdk package breaking apt

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#2962]
@mikeharder @dougbu 

It appears that `dotnet-sdk-2.0.0` package is breaking on apt. It causes a `100 error` for all other packages in our continuous run with the following result:

` dotnet-sdk-2.0.0 : Depends: aspnetcore-store-2.0.0 but it is not going to be installed`

**Comment by dougbu** [comment]
@nbrady-techempower do you have a link to the rest of the log?

**Comment by nbrady-techempower** [comment]
@dougbu http://sprunge.us/SQCY

I may have my head down in another project today. If you need me, feel free to email nbrady@techempower.com

**Comment by mikeharder** [comment]
@nbrady-techempower: Thanks for letting us know, we will investigate today.
