### ISSUE TITLE
Dart raw parallel server is broken

### ISSUE THREAD

**Issue by costajob** [TechEmpower/FrameworkBenchmarks#2981]
### OS (Please include kernel version)
System Version: macOS 10.12 (16A323)
Kernel Version: Darwin 16.0.0

### Expected Behavior
Dart VM should run [the server](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Dart/dart-raw/server.dart) without breaking. 

### Actual Behavior
I've got the following error:
```shell
Unhandled exception:
NoSuchMethodError: Class '_ServerSocket' has no instance getter 'reference'.
Receiver: Instance of '_ServerSocket'
Tried calling: reference
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
...
```

### Steps to reproduce behavior
Just run the Dart VM.

### Other details and logs
The `reference` method does not appear to be supported anymore by the Dart standard library. I suspect you should use the new `ReceivePort` to communicate within the spawned isolates.

**Comment by thosakwe** [comment]
It's because the samples here use a very outdated version of the Dart VM. I'm working on benchmarks for [Angel](https://angel-dart.github.io), a server framework in Dart, so I'll see if I can also get to correcting `dart-raw`.

**Comment by msmith-techempower** [comment]
This issue appears to [have been resolved](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/315014587).

@nbrady-techempower Can you test this locally and close if it is fixed?

**Comment by nbrady-techempower** [comment]
Looks like this is all set
