### ISSUE TITLE
rust - tokio-minihttp - Zap is faster than minihttp

### ISSUE THREAD

**Issue by oldaniel** [TechEmpower/FrameworkBenchmarks#3042]
So I developed a web framework _(Still in development, currently working on speeding up request parsing)_ called `zap` (https://github.com/oldaniel/zap) and it is faster than `tokio-minihttp`. I used it as inspiration but speeded up sending a response and parsing the requests.

Maybe someone can tell me if I should open a pull request on it.

**Comment by nbrady-techempower** [comment]
@oldaniel Sure, part of the reason we created these benchmarking tests was to help framework developers find ways to improve and to create a dialogue with others. If you plan on maintaining this framework by all means, open up a pull request for it. Thanks for checking it out and let us know if you have any questions going forward.
