### ISSUE TITLE
Duplicate SQL statements in `create-postgres.sql` file

### ISSUE THREAD

**Issue by marksiemers** [TechEmpower/FrameworkBenchmarks#3046]
Is it intentional that the SQL statements are duplicated in this file?
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/databases/postgresql/create-postgres.sql

The tables are dropped and created, the data is inserted...then the same thing happens again.

I looked at mysql, and it doesn't appear to have the duplication.

If the duplication isn't necessary, removing it may save a little time while running benchmarks.

**Comment by nbrady-techempower** [comment]
They create differently cased tables, `world` and `World`. I'm not sure what the reason behind this was, other than confusion with postgres originally that `CREATE TABLE World` was creating a table called `world`. So a number of different frameworks use different casing when dealing with Postgres. It'd be nice to be on the same page, but if some of the ORMs/Frameworks innately choose one case over the other, it's not a big deal to leave this as is. An effort to normalize this would involve digging in to each postgres test.

**Comment by msmith-techempower** [comment]
> They create differently cased tables, world and World. I'm not sure what the reason behind this was

The reason behind this is that some ORMs enforce cased queries via back-ticks:
```
SELECT * FROM `World`;
/* or */
SELECT * FROM `world`;
```

It turns out that not all database engines agree on what to do when you disable case sensitivity. If I recall correctly (and I probably do not), PostgreSQL will fail the first query if lower case is forced and only `world` exists.
