### ISSUE TITLE
Realistic tests using common hostings

### ISSUE THREAD

**Issue by faustinoaq** [TechEmpower/FrameworkBenchmarks#3106]
Hi @nbrady-techempower 

Currently TFB are running on super servers with many cores and a huge amount of RAM.

Would be nice to add more common use case like using a $ 20.00 hosting on Digital Ocean to run TFB, is this possible? 🤔

**Comment by nbrady-techempower** [comment]
Servers with different specifications is on our roadmap. Busy time of year for us at the moment, man hours, dollars, etc. But this is definitely being discussed internally. 👍

**Comment by msmith-techempower** [comment]
We are working toward getting some Azure servers added to the round15 run.

I'm going to close this task for now as it is on our roadmap.

**Comment by faustinoaq** [comment]
BTW, https://www.digitalocean.com/community/tutorials/how-to-benchmark-http-latency-with-wrk-on-ubuntu-14-04 is a nice guide to benchmark in DO
