### ISSUE TITLE
Show more information about FortuneHTMLParser error

### ISSUE THREAD

**Issue by flip111** [TechEmpower/FrameworkBenchmarks#3155]
Right now it shows a message
```
Accessing URL http://TFB-server:8000/fortunes:
  Response (trimmed to 40 bytes): "<!DOCTYPE html>
<html><head><title>Fortu"
   FAIL for http://TFB-server:8000/fortunes

     Invalid according to FortuneHTMLParser
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

Would be great if it could point to a line number, column, html tag or anything else more specific.

**Comment by msmith-techempower** [comment]
@nbrady-techempower Does the `--verbose` tag give more output on `fortunes` than just the 40 bytes we normally give?

**Comment by flip111** [comment]
I will still have to test the `--verbose` flag. Would it be possible to show a diff ?

**Comment by nbrady-techempower** [comment]
The diff is actually shown in the results at `/results/<time>/<framework>/fortune/verification.txt` but I've also added #3273 to print to std out as well
