### ISSUE TITLE
Control over stopping process after test

### ISSUE THREAD

**Issue by flip111** [TechEmpower/FrameworkBenchmarks#3158]
Is there any way to control how the main (program under test) process is stopped? I'm not sure how it's being done now, but i tried to install a sigINT handler but hat didn't seem to work. What i'm trying to achieve is get some profiling done of cost centres for a single test, but haskell ghc doesn't write out the `.prof` file when the process is just killed. I think the other way would be to add a REST endpoint for the server to shut itself down, but i think a signal handler is better. Another option altogether would be to recreate the request that the test is doing, is there a way to make the request & check for the response without the bootup/shutdown stuff around it?

**Comment by nbrady-techempower** [comment]
`--mode debug` will leave the server up so you can test/make requests against it. Is that something you're looking for?

**Comment by msmith-techempower** [comment]
Oh @flip111 ... you have run into [my reaper](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/TFBReaper.c).

As @nbrady-techempower suggests, `--mode debug` will PROBABLY get you what you need, but if not, I will have to do some somersaults to update the script to run without the reaper.

Please report whether `--mode debug` gets you what you need.

**Comment by flip111** [comment]
Hi guys. `--mode debug` partially gives me what i need. I just like to make sure that i'm doing the requests in the same way the benchmark does them. For the moment i'm using `wrk` as substitute. Is there any way i can fire off the request part of the benchmark in another tab?

**Comment by msmith-techempower** [comment]
(I'm back from vacation; sorry for the slow reply)

@flip111 That's an interesting use case - so you want the toolset to support starting up the server normally, then as a separate process running the benchmarks against it properly, but not shutting down the original process.

This is possible, but I wonder what purpose it would serve. Can you explain to me why you think this is necessary in the toolset? What is your use-case?

**Comment by flip111** [comment]
I wanted to profile the program (see where time is spend in each function). But i think it will be too much effort for you guys to change the toolset (that's why i will close this issue now). I will just guess the requests that are being made .. i think that is good enough for the moment. Thanks for support.
