### ISSUE TITLE
Add Sugar Framework (Elixir).

### ISSUE THREAD

**Issue by DevotionGeo** [TechEmpower/FrameworkBenchmarks#3185]
I'd love to see [Sugar Framework](https://sugar-framework.github.io/) added to the benchmarks.

**Comment by nbrady-techempower** [comment]
You are welcome to add it @DevotionGeo 

Try cloning the repo and using the `tfb --new` command. Meanwhile I'll add it to the wiki of requested frameworks. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features
