### ISSUE TITLE
Dropwizard/Hibernate combo not commiting updates to the database

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#3224]
This problem was reported by @greenlaw110 on the mailing-list. 
I've done some exploration of the topic. There is a problem when Hibernate 5.2.12 is running without transactions - it will happily close the session without bothering to flush the changes and report 0 flushes.
There is a [new setting since 5.2](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/cfg/AvailableSettings.html#ALLOW_UPDATE_OUTSIDE_TRANSACTION) which should enable the issuing updates outside a transaction. When enabled **and** there is a call to `flush()` than the data is committed. Without `flush()` there is no automatic flush at the end. I'll provide the test code tomorrow.

I'm having problems to make it work with Dropwizard. The hibernate session is reporting the flush operation but the change is not reflected in the database.

So the results for the update test of Dropwizard/Hibernate/MySQL (and PostgreSQL) combo should not be published. Also if other frameworks are using Hibernate 5.2 without transactions their update code should be inspected.

**Comment by nbrady-techempower** [comment]
This is confirmed in #3210 which includes improved verification for the update test.

Going to have to look at #3227 since their updates are persisting but probably using a single transaction

**Comment by zloster** [comment]
Addressed here:#3232

**Comment by greenlaw110** [comment]
@zloster when I am doing dropwizard mysql test I found 75% of requests are Non-2xx or 3xx, is this normal?

```
luog@luog-Satellite-P50-A:~/act/TEB$ wrk -H 'Host: TFB-server' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 256 --timeout 8 -t 8 http://TFB-server:9090/db/update?queries=20
Running 15s test @ http://TFB-server:9090/db/update?queries=20
  8 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   261.10ms  282.58ms   2.36s    85.16%
    Req/Sec   170.40     99.98   848.00     73.95%
  Latency Distribution
     50%  160.69ms
     75%  399.94ms
     90%  657.34ms
     99%    1.23s 
  18888 requests in 15.10s, 7.04MB read
  Non-2xx or 3xx responses: 14347
Requests/sec:   1251.20
Transfer/sec:    477.80KB
```

**Comment by zloster** [comment]
@greenlaw110 That's not normal - maybe it is related to a configuration change for Jetty that I've made for the MySQL variant. I will revert it because the performance is worse.

**Comment by greenlaw110** [comment]
@zloster I am also experiencing bad performance on hibernate updates test when batch updates plus transaction, especially on postgresql, I think it due to the row level lock of postgresql, but not sure why other framework doesn't have the issue...

**Comment by zloster** [comment]
@greenlaw110 The official results are not showing a problem with database updates: [Round 15](https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=update&l=hra0e7&f=zik0zj-ziimf3-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-cn3) and [Round 14](https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=update&l=hra0e7&f=zik0zj-ziimf3-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-cn3)
`dropwizard-postgre`@ 20 update queries:
Round 15: 3,243 RPS 
Round 14: 1,715 RPS

Another note about the first problem: note the result in Round 15 of `dropwizard-mongodb` in the "Data updates" test - 17 000+ errors/44% success rate and "Multiple queries" test - 15 000+ errors/63% success rate. Many errors but the recorded performance is about the same. However its configuration was not changed/tweaked the same way as the MySQL one. So **there is** some problem but it is not related with my Jetty configuration change.
Also important to note is the big drop of RPS between Round 15 and 14 in the "Multiple queries" test at all queries counts except 1.

**Comment by greenlaw110** [comment]
@zloster yes I know, I am not talking about R15, but the test after that...
