### ISSUE TITLE
Updates test: Grails might not commiting data into database separately

### ISSUE THREAD

**Issue by greenlaw110** [TechEmpower/FrameworkBenchmarks#3227]
From the [source code of grails implementation](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Groovy/grails/hello/grails-app/controllers/hello/HelloController.groovy#L52), we can clearly see that it is not commiting each update separately:

```groovy
            World.withSession { Session session ->
                for (int id : worldIds) {
                    World world = World.get(id)
                    world.randomNumber = random.nextInt(10000) + 1
                    worlds.add(world)
                    // flush changes
                    session.flush()
                    session.clear()
                }
            }
```

Note `session.flush()` will **NOT** commit the data, and never will `session.clear()` do the job. I am not a grail person but the `session` come from Hibernate. I think it worth to check into the code and evaluate if it follows the rule

**Comment by nbrady-techempower** [comment]
closing see #3254
