### ISSUE TITLE
Add PHP-PM in toolset

### ISSUE THREAD

**Issue by raziel057** [TechEmpower/FrameworkBenchmarks#3252]
Hi,

What about having PHP-PM (https://github.com/php-pm/php-pm) available in the toolset in order to be able to just use it as dependency for some existing frameworks (symfony, laravel, zf, ...) ?

**Comment by nbrady-techempower** [comment]
Hi @raziel057 

If you want to use PHP-PM, simply add a setup file for it like `toolset/setup/linux/systools/php-pm.sh` so any framework that wants to use it can `fw_depends php-pm`
