### ISSUE TITLE
Updates test - minijax not commiting data into database separately

### ISSUE THREAD

**Issue by greenlaw110** [TechEmpower/FrameworkBenchmarks#3254]
From the [source code of minijax](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/minijax/src/main/java/com/techempower/minijax/Dao.java#L34), clearly the updates is doing batch commit to database in one transaction:

```java
    public void batchUpdate(final List<World> worlds) {
        final EntityTransaction tx = em.getTransaction();
        tx.begin();
        for (final World world : worlds) {
            em.merge(world);
        }
        tx.commit();
    }
```

**Comment by nbrady-techempower** [comment]
Thanks @greenlaw110 Will address on Monday

**Comment by greenlaw110** [comment]
@nbrady-techempower [Dropwizard source code](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/dropwizard/src/main/java/com/example/helloworld/db/hibernate/WorldHibernateImpl.java#L36) has the same issue:

```java
	@Override
	public World[] updatesQueries(int totalQueries) {
		final World[] worlds = new World[totalQueries];
		Transaction txn = null;

		try {
			txn = currentSession().beginTransaction();

			// using write batching. See the data source properties provided in the configuration .yml file
			for (int i = 0; i < totalQueries; i++) {
				worlds[i] = findAndModify(Helper.randomWorld(), Helper.randomWorld());
			}
			currentSession().flush();
			currentSession().clear();
			txn.commit();
		} catch (RuntimeException e) {
			if (txn != null && txn.isActive())
				txn.rollback();
			throw e;
		}
		// The cleaning of the session should happen in the dropwizard provided aspect code

		return worlds;
	}
```

**Comment by nbrady-techempower** [comment]
@zloster can you speak to this? i see some annotations where `transactional` is false.

**Comment by zloster** [comment]
`dropwizard` is using Hibernate 5.2, `minijax` is using `Eclipselink` as ORM library. I have only checked how the Hibernate is working - i.e. what SQL query it generates. It should be easy to be done also with Eclipselink.
So a manual DB transaction is started, each row is fetched from the DB and the `randomNumber` field is modified in memory. When the `currentSession().flush()` is called Hibernate will issue a batch SQL statement which will contain all the update queries.

I've added [screenshots from VisualVM and the used configuration file](https://github.com/zloster/logs/tree/master/FrameworkBenchmarks/dropwizard-hibernate-batch-updates).
You can see 20 selects and one batch statement with all the updates.

Hibernate needs some settings in order achieve this. They are available here:
- [hello-world-mysql.yml](https://github.com/TechEmpower/FrameworkBenchmarks/pull/3232/files#diff-da6509d4c057ada418cd1669123768d1)
- [hello-world-postgres.yml](https://github.com/TechEmpower/FrameworkBenchmarks/pull/3232/files#diff-e97d738efb72e7faa2f2d6ecce83055d)
- The third and fourth settings are enabled by default from [dropwizard](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java#L78-L79)

For reference I've used this article: https://vladmihalcea.com/how-to-batch-insert-and-update-statements-with-hibernate/

If Eclipse link will issue the same SQL statements than I don't see a problem. Here are some issues where this matter is discussed:
- https://github.com/TechEmpower/FrameworkBenchmarks/issues/1622
- https://github.com/TechEmpower/FrameworkBenchmarks/issues/2204
- https://github.com/TechEmpower/FrameworkBenchmarks/issues/2581
- https://github.com/TechEmpower/FrameworkBenchmarks/issues/2579 - executing SQL batch update statement in transaction

**Comment by greenlaw110** [comment]
@zloster I think the [requirement](https://www.techempower.com/benchmarks/#section=code) we are talking is not about batch update, but transactions:
> Use of transactions is acceptable but not required. If transactions are used, a transaction should only encapsulate a single iteration, composed of a single read and single write. Transactions should not be used to consolidate multiple iterations into a single operation.

So my understanding is the code above should be something like:

```java
	@Override
	public World[] updatesQueries(int totalQueries) {
		final World[] worlds = new World[totalQueries];
		Transaction txn = null;

		try {
			for (int i = 0; i < totalQueries; i++) {
				txn = currentSession().beginTransaction();
				worlds[i] = findAndModify(Helper.randomWorld(), Helper.randomWorld());
				txn.commit();
			}
		} catch (RuntimeException e) {
			if (txn != null && txn.isActive())
				txn.rollback();
			throw e;
		}
		// The cleaning of the session should happen in the dropwizard provided aspect code

		return worlds;
	}
```

Or I have some misunderstanding about the transaction requirement?

**Comment by greenlaw110** [comment]
This is to @nbrady-techempower, actually I don't quite understand why do we have the requirement about transaction and the batch update at the sametime, as these 2 requirements looks conflict to each other:

About batch update:
> Use of batch updates is acceptable but not required. To be clear: batches are not permissible for selecting/reading the rows, but batches are acceptable for writing the updates.

About transaction:
> Use of transactions is acceptable but not required. If transactions are used, a transaction should only encapsulate a single iteration, composed of a single read and single write. Transactions should not be used to consolidate multiple iterations into a single operation.

**Comment by zloster** [comment]
@greenlaw110 See the linked issues (particularly #2579 where exactly the same situation is discussed).
IMO wrapping a batch update with transaction don't give some unfair advantage to any particular implementation: on the wire you have to send some additional commands to the DB. When transactions are not used - the code doesn't need to send this commands.
The code needs to do this because of the Hibernate 5.2 problem I've described on the mailing list.

**Comment by greenlaw110** [comment]
@zloster 
1. Once a Rule is defined it shall not be violated, both Go/fasthttp and dropwizard updates implementation should be rectified to make them comply to the rule. Unless TEB take the rule out.
2. It does make it unfair to other implementation that comply to rule 10, as commit multiple times definitely require more resource on both app server and the database including the transferred data. For single transaction commit, your data already committed into the database from the wire for each iteration. You can simply do the test on your own machine to compare the current dropwizard impl and the impl I proposed above.

**Comment by greenlaw110** [comment]
@nbrady-techempower Actually I suspect gemini's implementation violate rule 10 as well:

```java
  @PathSegment
  public boolean update()
  {
    final Random random = ThreadLocalRandom.current();
    final int queries = query().getInt("queries", 1, 1, 500);
    final World[] worlds = new World[queries];

    for (int i = 0; i < queries; i++)
    {
      worlds[i] = store.get(World.class, random.nextInt(DB_ROWS) + 1);
      worlds[i].setRandomNumber(random.nextInt(DB_ROWS) + 1);
    }

    store.putAll(Arrays.asList(worlds));
    
    return json(worlds);
  }
```

**Comment by nbrady-techempower** [comment]
@greenlaw110 Gemini doesn't use transactions.

> It does make it unfair to other implementation that comply to rule 10, as commit multiple times definitely require more resource on both app server.

Rule 10 allows batch updates. The confusing contradiction is "batch updates with transactions." After an internal discussion I believe were going to allow batch updates with transactions. I don't think there's really a good case against this. I will let you guys know here, and will update the documentation if it changes. To be clear, batch updates are allowed right now, this change would also allow batch updates with transactions.

**Comment by msmith-techempower** [comment]
Batch **updates** and transactions is allowed (though, the transaction will surely only make performance worse if any difference is appreciated at all); we will updated our rules accordingly.
