### ISSUE TITLE
Frameworks Failing for not passing Update Test Verification

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#3262]
From #3210 & #2027 we are now verifying to make sure that database entries have changed after the Updates test runs. There are still a few framework tests that need to be addressed. If I pinged you here, it's because you might be able to help, or you were the core contributor for these tests. Note that these are failures and the results of their update tests will no longer be captured.

ffead-cpp
ffead-cpp-apache-mongo
~~macchiato~~
~~koa-postgres~~
~~sailsjs~~
~~sailsjs-postgres~~
~~play2-scala-reactivemongo~~
~~play2-scala-reactivemongo-netty~~
~~web2py-optimized~~

@sumeetchhetri @methane @mkurz @ilvalle 

Some things to look for that I've already fixed in other tests are:

Using the queries handler that doesn't update the db at all
Not having the proper database name in the `benchmark_config.json`: MySQL, Postgres or Mongodb
Returning a response before the updates are done writing to the db

**Comment by methane** [comment]
Sorry, web2py is so special than other typical frameworks and I don't have motivation for it.
fwd: @ilvalle, @abastardi

**Comment by abastardi** [comment]
I submitted a pull request that I believe should fix the problem for web2py-optimized.

**Comment by nbrady-techempower** [comment]
All have been updated

**Comment by sumeetchhetri** [comment]
Thanks a lot Nate
