### ISSUE TITLE
Dropwizard updates - mongodb implementation

### ISSUE THREAD

**Issue by greenlaw110** [TechEmpower/FrameworkBenchmarks#3285]
The [mongodb implementation of dropwizard updates test](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/dropwizard/src/main/java/com/example/helloworld/db/mongo/WorldMongoImpl.java#L25) uses mongodb's update operation, instead of read the data into memory and then persist into database:

```java
    @Override
    public World findAndModify(int worldId, int newRandomNumber) {
        World theOne = findById(worldId);
        theOne.setRandomNumber(newRandomNumber);
        worldCollection.updateById(theOne.getId(), DBUpdate.set("randomNumber", theOne.getRandomNumber()));
        return theOne;

    }
```

I think we have talked about this before and the agreement is NOT to use mongodb's update operation in this test.

**Comment by nbrady-techempower** [comment]
Of course you can use update, you can't use findAndModify. This writes it's own findAndModify, reads the value from the database, sets the random number, and then updates.

**Comment by greenlaw110** [comment]
Ah, you are right. silly issue...
