### ISSUE TITLE
Resolve mongodb errors for JVM + MongoDB frameworks in R15

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#3314]
@zloster pointed out on the mailing list that some of the frameworks using the JVM and MongoDB have a large number of errors in round 15.

https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=query&l=fjd9bz&d=e6

I believe undertow-mongodb is fixed with commit 7f3d8a1335da3103a7a07ce01f7771a9ed0abfff.

How about dropwizard and hexagon?  Apparently they are using the same underlying mongodb-driver library for connecting to the database, though they are not customizing the Mongo client settings in the same way the undertow code is.

Maybe that means they are inheriting default settings that are not good for TFB's expected 512 concurrent client requests.  Looking at the mongodb-driver code on GitHub, I suspect the default settings support only 500 (not 512) concurrent queries.

https://github.com/mongodb/mongo-java-driver/blob/05b7ca07c648adff63ccce309cadac053b71baf1/driver-legacy/src/main/com/mongodb/MongoClientOptions.java#L148

https://github.com/mongodb/mongo-java-driver/blob/05b7ca07c648adff63ccce309cadac053b71baf1/driver-legacy/src/main/com/mongodb/MongoClientOptions.java#L964-L965

**Comment by zloster** [comment]
@michaelhixson 
The recent results seems to confirm that `undertow-mongodb` is fixed:

- https://tfb-status.techempower.com/results/a1110174-a3af-4c2e-a4e1-bfcdca8bd8eb
- https://tfb-status.techempower.com/results/0cf97d5a-86b1-4ebe-b53a-485a6532dae9
