### ISSUE TITLE
Investigate nginx keepalive settings

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#332]
For the frameworks that run on nginx, we should review whether their nginx configurations have the right settings for enabling keepalive connections.  It seems to disable them by default.  I saw a large improvement in the Dart tests from just a small tweak.

http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_keep_conn

> By default, a FastCGI server will close a connection right after sending the response. When set to the value on, nginx will instruct a FastCGI server to keep connections open. This in particular is necessary for keepalive connections to FastCGI servers to function.

http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive

> Activates cache of connections to upstream servers.
> 
> The connections parameter sets the maximum number of idle keepalive connections to upstream servers that are retained in the cache per one worker process. When this number is exceeded, the least recently used connections are closed.

...

> For HTTP, the proxy_http_version directive should be set to “1.1” and the “Connection” header field should be cleared

**Comment by LadyMozzarella** [comment]
documentation tag: Add bugs to PHP README as suggested by @hamiltont,
implementation review tag: Check/review status of keepalive settings for all frameworks using nginx.
