### ISSUE TITLE
TravisCI - Build matrix exceeds 200 jobs

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#3324]
Currently in the `master` branch there are [exactly 200 build jobs](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/344929209) (scroll to the bottom). TravisCI refuses to build the project when new framework is added. So currently adding a new framework will halt builds executions.

Short term mitigation (NOT fix) is some clean up of the framework projects. In the Java directory there are several candidates that could be merged in single framework/build job:

- [x] `comsat-servlet` and `comsat-webactors`
- [x] `grizzly-bm` and `grizzly-jersey`
- [x] `undertow-jersey-c3p0` and `undertow-jersey-hikaricp`

I'll start with the `grizzly`-based projects because I have some knowledge about them. Each merge will free one build job slot.

For a long term solution - I don't know.

**Comment by cjnething** [comment]
Interesting, looks like other projects are having this issue too https://github.com/aschn/drf-tracking/issues/97

**Comment by joanhey** [comment]
And remember that a job on travis-ci.org is limited by 50 minutes.
https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

**Comment by zloster** [comment]
There should not be a problem with the build timeout at least in the Java directory. Check here where a rebuild of the Java frameworks happens: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/341133956.

The longest builds are:
1. Java/act - ~29 min. - 2 database configurations with 3 ORM frameworks plus MongoDB variant
1. Java/play2-java - ~21 min.
1. Java/dropwizard - ~11 min.
1. Java/undertow - ~10 min.
1. Java/servlet - ~9 min.

**Comment by nbrady-techempower** [comment]
If push comes to shove, we may group some of the lesser worked on languages together in travis, like Erlang and Elixir. This would also speed up full runs because shared dependencies won't have to be reinstalled.

**Comment by zloster** [comment]
Now there are 3 (three) free jobs in the `master` branch and a flexible solution in the `docker` branch. Added bonus: a little less code in the source repository and a little faster full runs.
Thank you all.

@nbrady-techempower Feel free to close this.

**Comment by nbrady-techempower** [comment]
Thanks again for your help here!
