### ISSUE TITLE
should disable proxy_cache of resin

### ISSUE THREAD

**Issue by smallnest** [TechEmpower/FrameworkBenchmarks#3325]
When I have seen  the benchmark of [round 15](https://www.techempower.com/benchmarks/#section=data-r15&hw=ph&test=fortune), I am surprised Java frameworks (servlet, servlet-cjs) have so much good result for dynamic requests except plaintext.

I check the [resin configuraton](https://github.com/TechEmpower/FrameworkBenchmarks/search?utf8=✓&q=resin+proxy-cache&type=) and found "proxy_cache" has been set to **true**:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/70a2dac6639cf731dc7c5730333d2ce4116c39b5/toolset/setup/linux/webservers/resin/resin.properties#L115

```
# Enable the proxy-cache - for caching static content in memory
proxy_cache_enable : true
```

It says it is only for static content but official document says it is for dynamic content:

> http://www.caucho.com/resin-4.0/admin/http-proxy-cache.xtp#Configuration
>
> <proxy-cache> configures the proxy cache (requires Resin Professional). The proxy cache improves performance by caching the output of servlets, jsp and php pages. For database-heavy pages, this caching can improve performance and reduce database load by several orders of magnitude.

If my thought is right, the benchmarks  for java frameworks with resin actually is testing the cache of response of servlets. The option should be set false.

_I am not familiar with resin so may be my guess is wrong._

**Comment by zloster** [comment]
The project is using the [_normal_ Resin version](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/webservers/resin/resin.sh#L12-L13), not the _Pro_ version.
