### ISSUE TITLE
Single transaction for all updates?

### ISSUE THREAD

**Issue by fafhrd91** [TechEmpower/FrameworkBenchmarks#3446]
i dont really know Go, but this looks like on transaction for all update queries?

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Go/fasthttp/src/server-postgresql/server.go#L114

also h2o seems uses one update query

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/h2o/src/database.h#L43

so my question are this cases allowed?

**Comment by nbrady-techempower** [comment]
Yes, there was a thread about this recently in the issues. We were allowing batch updates, but not batch updates with transactions. We do allow that now. See #9 and #10 here http://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#database-updates

**Comment by fafhrd91** [comment]
thanks

**Comment by zloster** [comment]
@fafhrd91 Most of the details are here: https://github.com/TechEmpower/FrameworkBenchmarks/issues/3254
