### ISSUE TITLE
Use .gitattributes instead of requiring autocrlf=false

### ISSUE THREAD

**Issue by jongalloway** [TechEmpower/FrameworkBenchmarks#3527]
Per #3504, it's necessary to specify `git config --global core.autocrlf false` on Windows. This is a global setting that's the opposite of GitHub's recommendations.

It would be better to use `.gitattributes` to set this per-repo, as per these docs: https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

This would then work out of the box on all operating systems without requiring anyone to change global git config.

**Comment by msmith-techempower** [comment]
[Added](https://github.com/TechEmpower/FrameworkBenchmarks/pull/3526/commits/3924aab6a21cf7c9ac411e2fc2be7d26e847abd5)

I will update the documentation to no longer state that requirement.
