### ISSUE TITLE
Add a link to the github id

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#3587]
In the continuous benchmarking https://tfb-status.techempower.com/

### Expected Behavior
 Citrine
Run ID: 3f5e1eca-f530-403c-ab0a-39769ff7c8da

https://github.com/TechEmpower/FrameworkBenchmarks/tree/f2f177b4061660a7b580cfc720e1e38f661cf0b3/
### Actual Behavior
 Citrine
Run ID: 3f5e1eca-f530-403c-ab0a-39769ff7c8da

TFB git commit ID
    f2f177b4061660a7b580cfc720e1e38f661cf0b3
TFB git repository URL
    https://github.com/TechEmpower/FrameworkBenchmarks.git 
TFB git branch name
    master

**Comment by nbrady-techempower** [comment]
I've opened a PR to address this https://github.com/TechEmpower/tfb-status/pull/3

**Comment by joanhey** [comment]
Nate I asked a link to the tree in that point.
Not to the last commit.
From one round to another there may be 50 commits.

Tree:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/id

Last commit:
https://github.com/TechEmpower/FrameworkBenchmarks/commit/id

**Comment by nbrady-techempower** [comment]
That makes sense, all set.

**Comment by nbrady-techempower** [comment]
I'll close this issue here, if you have any other requests feel free to open an issue on https://github.com/TechEmpower/tfb-status
