### ISSUE TITLE
Highlighting options for individual frameworks

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#359]
User Historiopode from Hacker News suggests a highlight option, which would be useful for reference and sharing.

> it would be nice if you could select one or more frameworks and have them highlighted in the result listings, so as to be able to notice their relative position at a glance.

**Comment by msmith-techempower** [comment]
Okay, I'm going to close this issue - it is five years old and still not added.

Hopefully, we can get our results view to be in a better place where issue tracking can be captured against it (read: not here).
