### ISSUE TITLE
Vagrant docker permissions

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#3682]
The first time work correctly.

After stop vagrant `vagrant halt` and start later `vagrant up` and execute `tfb` show:
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`

If you execute `sudo usermod -aG docker ${USER}`  the first time, the permissions problem disappear.
Only add the user `vagrant` or better `${USER}` to the docker group.

**Comment by nbrady-techempower** [comment]
Thanks @joanhey. I'll take care of this tomorrow.
