### ISSUE TITLE
How create a compiling time benchmarking?

### ISSUE THREAD

**Issue by MatheusRV** [TechEmpower/FrameworkBenchmarks#3726]
As I start at https://github.com/netlify/staticgen/issues/371 talking about static site generator compiling time, I'm using this Framework to create a Fork https://github.com/MatheusRV/StaticSiteGeneratorBenchmarks, but I need mensure diferente build time on diferente frameworks on many programaing languages. But i dont know here start, could some one help? I look at toolset/beanchmark/test_types.

**Comment by MatheusRV** [comment]
Could some one give me the idea how to implement a compiling time benchmarking over TFB?

**Comment by nbrady-techempower** [comment]
It sounds like you're trying to compare the build times for static site generators across multiple languages? Though we provide some simple time logging output for the dockerfile builds, this isn't the focus of these benchmarks. Good luck with your project!
