### ISSUE TITLE
WSL Error calling canonicalize_path

### ISSUE THREAD

**Issue by MatheusRV** [TechEmpower/FrameworkBenchmarks#3728]
Is this able to run on WSL?

### OS (Please include kernel version)
Windows Linux Subsystem (Ubuntu 16.04.4 LTS | Linux DESKTOP-TKI46T0 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux | Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014)

### Expected Behavior
TFB Run

### Actual Behavior
`$ ./tfb --mode verify --test gemini
: not found/tfb:
: not found./tfb:
: not found./tfb:
./tfb: 28: ./tfb: resolve_symlinks: not found
./tfb: 28: ./tfb: canonicalize_path: not found
: not found./tfb: }
: not found./tfb:
./tfb: 32: ./tfb: _resolve_symlinks: not found
: not found./tfb: }
: not found./tfb:
./tfb: 36: ./tfb: _assert_no_path_cycles: not found
: not found./tfb: return
: not found./tfb:
./tfb: 38: local: not in a function`

### Steps to reproduce behavior
`git clone https://github.com/TechEmpower/FrameworkBenchmarks.git
./tfb --mode verify --test gemini`

**Comment by programingjd** [comment]
I had the same error.
I replaced the shebang to use #!/usr/bin/env bash instead of #!/bin/sh and it resolved the issue.

**Comment by MatheusRV** [comment]
Tks this works well
