### ISSUE TITLE
Average latency displayed not Best's latency

### ISSUE THREAD

**Issue by benaadams** [TechEmpower/FrameworkBenchmarks#3754]
### Expected Behavior

Average latency on the Latency section matches the latency for the result shown under "Best performance"

### Actual Behavior

Average latency on the Latency section always matches the latency for the 16,384 connection result.

### Steps to reproduce behavior

Compare the latency in results.2018-05-14-23-53-34-327.json to the version shown on website https://www.techempower.com/benchmarks/#section=test&runid=7571f049-a396-49cb-ad05-20d971a6538d for that run

**Comment by bhauer** [comment]
This should be addressed.
