### ISSUE TITLE
Odd results regarding Node vs ASP.NET Core in Round 15

### ISSUE THREAD

**Issue by jtheisen** [TechEmpower/FrameworkBenchmarks#3769]
I'm struggling to understand those results from Round 15: It appears that Node is much faster on Dells and ASP.NET Core is much faster on Azure, but why should that be the case?

![image](https://user-images.githubusercontent.com/1516294/40297937-c12e8b84-5ce1-11e8-9e0d-3e1c3da0859a.png)

What's going on here?

**Comment by sebastienros** [comment]
I am part of the ASP.NET team and will try to explain our understanding, and how we fixed it. 

The way we saw it when Round 15 was out is that ASP.NET did not scale with the number of cores. So ASP.NET would not look competitive on higher numbers of cores. From this point we started to work on understanding why and found some locking contention in our database drivers. It happens that most benchmarks that were done on each driver where on raw latency, and not concurrent load. We replicated these numbers internally with different environments and we could see the RPS hit a ceiling even with more cores. With Node I assume scaling is more natural as it only needs to tune the number of processes.

So for that past 6 months we have worked in collaboration with the ADO.NET driver developers to improve the performance and you can see that ASP.NET does much better in the latest round preview. We are very grateful we got @roji for the PostgreSql driver and @bgrainger for the MySql one to acknowledge this point and improve the drivers. And we know there are still some improvements to get on MySql.

**Comment by msmith-techempower** [comment]
I think this answers the questions sufficiently; closing.

**Comment by jtheisen** [comment]
@sebastienros Can you also drop a note on what's the situation on Sql Server?
