### ISSUE TITLE
Clarify that pipelining to the database is allowed

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#3772]
We decided to allow pipelining between the application and database like vertx-postgres is currently doing.  We should specifically call this out as allowed in the requirements.  The current requirements kind of imply that pipelining would be disallowed.

In particular, I suggest that we change General Requirement 7, which currently reads:
> Except where noted, all database queries should be delivered to the database servers as-is and not coalesced or deduplicated at the database driver. In all cases where a database query is required, it is expected that the query will reach and execute on the database server—that is, the full round-trip effort of a query will be part of the workload.

And although this kind of pipelining may be used in all database tests, I think we should change Multi-query Requirement 6, which currently reads:
> This test is designed to exercise multiple queries, each requiring a round-trip to the database server, and with each resulting row selected individually. It is not acceptable to use batches. It is not acceptable to execute multiple SELECTs within a single statement. It is not acceptable to retrieve all required rows using a SELECT ... WHERE id IN (...) clause.

Related discussion on our google group:
https://groups.google.com/d/msg/framework-benchmarks/A78HrYsz4AQ/_zneyvo2CwAJ

**Comment by bhauer** [comment]
I am going to apply these changes momentarily.

**Comment by bhauer** [comment]
This is posted.
