### ISSUE TITLE
Cached queries: number of queries not being set

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#3773]
We got a report on our google group that cached queries test isn't passing along the number of queries correctly:
> More importantly, I would like to report another issue - the cached queries test type seems to be currently broken because the parameter specifying the number of queries is not set, i.e. the URL ends with "?queries=". The last good run is 8de314d3-b970-4295-a3ca-3682f3905a3b ( https://tfb-status.techempower.com/results/8de314d3-b970-4295-a3ca-3682f3905a3b ).

https://groups.google.com/d/msg/framework-benchmarks/A78HrYsz4AQ/Dpd7ZdUwBwAJ

**Comment by msmith-techempower** [comment]
I biffed this on the `wrk` image. I'll fix it.
