### ISSUE TITLE
No way to edit wiki

### ISSUE THREAD

**Issue by rektide** [TechEmpower/FrameworkBenchmarks#3776]
Hello. I wanted to add a new framework to the suggested items list on the wiki.

Editing however appears disabled. I tried pulling down the wiki repo, [adding the Java Armeria framework there](https://github.com/rektide/techempower-framework-benchmarks-wiki/commit/ae6bc05829ca01f13cf330ccb6c9d5f2e21ce3a0), but I have no permissions to push.

In your issue template, you say,

> If this is a request for a new language/framework, please check/add to the wiki at
> https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks,-Languages-and-Features

However this is presently not possible. What can I do to get this framework onto the wiki?

**Comment by cjnething** [comment]
Hi @rektide, sorry about that. It looks like [GitHub doesn't support pull requests to Wikis](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). I just added it to the Wiki. Thanks for your contribution!
