### ISSUE TITLE
Test type 3: Multiple database queries (doc/action disagreement?)

### ISSUE THREAD

**Issue by benaadams** [TechEmpower/FrameworkBenchmarks#3783]
> Test type 3: Multiple database queries
> 
> **17. The request handler will be exercised at 256 concurrency only.**

However when running the test locally it outputs
```
---------------------------------------------------------
 Queries: 20 for query
 wrk -H 'Host: tfb-server' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive'
 --latency -d 15 -c 512 --timeout 8 -t 8 "http://tfb-server:8080/queries?queries=20"
---------------------------------------------------------
Running 15s test @ http://tfb-server:8080/queries?queries=20
  8 threads and 512 connections
```
So its running it at 512 concurrency?

**Comment by sebastienros** [comment]
When testing aspnetcore on Citrine with 256 connections with count=20 we see 24K instead of 20K.

**Comment by benaadams** [comment]
> When testing aspnetcore on Citrine with 256 connections with count=20 we see 24K instead of 20K.

You mean a 512 connections match the actual TE runs; whereas 256 connections (as in docs) is faster?

**Comment by sebastienros** [comment]
Yes, thank you for clarifying.

**Comment by nbrady-techempower** [comment]
Sorry this got lost in the noise, but is reflected in the docs.
