### ISSUE TITLE
Dockerization of the Ruby benchmarks

### ISSUE THREAD

**Issue by mwpastore** [TechEmpower/FrameworkBenchmarks#3834]
The Dockerization of the Ruby benchmarks is... incomplete. ~~Most of them are missing the commands that actually launch the web server, and~~ there are quite a few bugs (for example, shell parameter expansion in `CMD` statements, which will not work). Is someone working on finishing these, or are you looking for assistance from the community?

**Comment by mwpastore** [comment]
Let me take back what I said about missing run commands; I was looking at the "base" dockerfiles. But that raises a new question: why aren't the non-base dockerfiles FROM base? 

> for example, shell parameter expansion in CMD statements, which will not work

https://github.com/TechEmpower/FrameworkBenchmarks/blob/57d89df8ef6b1a7ece50af9f4f471e7248e6240a/frameworks/Ruby/sinatra-sequel/sinatra-sequel-passenger-mri.dockerfile#L15

https://github.com/TechEmpower/FrameworkBenchmarks/blob/57d89df8ef6b1a7ece50af9f4f471e7248e6240a/frameworks/Ruby/sinatra-sequel/sinatra-sequel-postgres-torquebox-jruby.dockerfile#L11

**Comment by mwpastore** [comment]
Hrrm. Does that work? Let me actually try it before I start making wild statements.

**Comment by mwpastore** [comment]
Okay, I'm full of nonsense. 😆I'll close this issue. Sorry for the noise.

**Comment by bhauer** [comment]
Thanks @mwpastore! Glad it was a false alarm, but we really appreciate people like yourself who help with double checking.
