### ISSUE TITLE
Feature Request: specify dockerfile in benchmark_config.json

### ISSUE THREAD

**Issue by mwpastore** [TechEmpower/FrameworkBenchmarks#3835]
I'd like the ability to specify the dockerfile for each test in benchmark_config.json, with it defaulting to {test-name}.dockerfile. I think this would make the benchmark directories with lots of tests much more manageable. It would also make it easier to group together test-specific files. For example, I would submit a PR to restructure sinatra-sequel like so:

```
sinatra-sequel/
  Gemfile
  benchmark_config.json
  boot.rb
  config/
  config.ru
  hello_world.rb
  tests/
    default/
      Dockerfile
    postgres/
      Dockerfile
    (et cetera)
  views/
```

And in benchmark_config.json:

```
{
  "framework": "sinatra-sequel",
  "tests": [
    {
      "default": {
        "dockerfile": "tests/default/Dockerfile"
      },
      "postgres": {
        "dockerfile": "tests/postgres/Dockerfile"
      },
      (et cetera)
    ]
}
```

**Comment by michaelhixson** [comment]
Related: #3717, which also lets you override the `CMD` in the dockerfile so that multiple variants of the framework can share the same build steps but then launch the application differently.

**Comment by nbrady-techempower** [comment]
This feature was added in #4543 and the docs have been updated

**Comment by mwpastore** [comment]
AWESOME. Thanks @nbrady-techempower!
