### ISSUE TITLE
Continuous test results json is not compressed

### ISSUE THREAD

**Issue by amichair** [TechEmpower/FrameworkBenchmarks#3869]
The ~1.5M json resource is being served uncompressed by the HTTP server... dunno if you care about this, but I just noticed it and thought I'd let you know :-)

**Comment by michaelhixson** [comment]
We fixed this with a change to the nginx proxy in front of tfb-status.techempower.com.  Before, it was gzipping HTML but nothing else.  I guess that's the default behavior unless you specify more content types it should gzip.
