### ISSUE TITLE
Discourage code not used in the benchmarks

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#3911]
Contributors sometimes include source code in their PRs that isn't required for the benchmarks.  The most common forms of this are:
* Functional tests, such as JUnit tests in a `src/test` directory in Java frameworks.
* Startup scripts for launching the framework's application directly without going through TFB.
* Local development configs used on the developer's workstation but not in TFB.

We don't want that code in this repository.  Maintaining that code is a burden for us and we don't think that burden is worthwhile.  Contributors are free to maintain that code elsewhere outside of this repository.

However, I don't think contributors know this until we tell them so in the PR.  We should do more to make this clear.  I especially don't want contributors to spend a lot of time writing functional tests and then feel like that time was wasted when we say "please remove that".

Options:
* Add a blurb about this in the pull request template.
* Add a bullet point about this in our contribution guide.
* Add some sort of automated check / bot that gives warnings in PRs when it sees suspicious files?  For example, if it sees a directory named `test` anywhere it could comment on the PR like "Hey, I see this directory named `some_framework/src/test` that looks like it contains functional tests.  We don't want to maintain this code, see (link to docs) for an explanation."

**Comment by nbrady-techempower** [comment]
Added this to the PR Template and also the general contributing guidelines https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Contributing-Guide#general-guidelines
