### ISSUE TITLE
Please, include memory footprint results

### ISSUE THREAD

**Issue by andrcmdr** [TechEmpower/FrameworkBenchmarks#3940]
Guys, can you please share not just only results about RPS, but also results about memory footprint, along with RPS, for each framework in continuous benchmarking iterations (https://tfb-status.techempower.com).

This measurements will be more interesting, especially for choosing frameworks to develop micro/nano services in cloud native environments and FaaS platforms.

**Comment by msmith-techempower** [comment]
We do capture that [type of data](http://tfb-logs.techempower.com/round-16/final/gemini/plaintext/stats.txt), but have no mechanism (at present) for visualizing it. This is on the roadmap.

**Comment by andrcmdr** [comment]
Thanks!
This measurements can be very helpful (I think even more helpful than RPS)!
I already grep memory footprint data for some framework benchmarks through parsing output of `time` tool (something like `/usr/bin/time -v -o ./run-time.log bash ./wrapper-on-benchmark.sh 2>&1 | tee ./output.log & disown`).
