### ISSUE TITLE
Measuring time in milliseconds is required

### ISSUE THREAD

**Issue by plokhotnyuk** [TechEmpower/FrameworkBenchmarks#3947]
Currently time is measured in seconds and it leads up to ~6.7% error in calculation of avg. throughput rate.

**Comment by msmith-techempower** [comment]
I do not believe that time is actually measured in seconds; rather, it is displayed in seconds for human consumption.

[This example](http://tfb-logs.techempower.com/round-16/final/act/plaintext/raw.txt) illustrates that, when appropriate, measurements are made in milli, and even micro, seconds.

**Comment by plokhotnyuk** [comment]
I mean start and end times, which are reported as result of raw output and then used in subsequent calculations:
```
STARTTIME 1527785236
ENDTIME 1527785251
```
