### ISSUE TITLE
Dart Redstone Implementation has error for Postgres flavor

### ISSUE THREAD

**Issue by shriharip** [TechEmpower/FrameworkBenchmarks#4056]
### Other details and logs

I see the line 120 in the "server.dart"  file is 
static const worldQuery = 'SELECT id, randomnumber FROM world WHERE id = @id;';

should have been 
static const worldQuery = 'SELECT id, randomnumber FROM @world WHERE id = @id;';

**Comment by nbrady-techempower** [comment]
I think you're mistaken. It's selecting from the table `world`. We're not replacing `world` in this statement.
