### ISSUE TITLE
rust/actix: not reading randomNumber from db during updates test

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#4067]
It looks like rust/actix's updates test implementation is violating one of the requirements, which is:

> 6. At least the `randomNumber` field must be read from the database result set.

I doubt this will affect its performance too much, but it's notable because actix is currently first place in the updates test in the latest continuous benchmarks.

I noticed this before in a PR but forgot about it until now:  https://github.com/TechEmpower/FrameworkBenchmarks/pull/3987/files/130d43eada44b27c4113783ba09b9698443c7d97#diff-13fc77611ee2c9c89dc86928e08c94e2

That `SELECT id FROM world WHERE id=$1` query is still in the latest code:  https://github.com/TechEmpower/FrameworkBenchmarks/blob/07ce7d5b6956ef886e65367be23b88eb175fd94e/frameworks/Rust/actix/src/db_pg_direct.rs#L32

**Edit: I suggested a fix here at first, but the suggestion was wrong, so I've removed it.**

Pinging @fafhrd91 since he maintains the actix code.

**Comment by fafhrd91** [comment]
I might misunderstood specs. I'll fix it.
