### ISSUE TITLE
Update Docker-Py

### ISSUE THREAD

**Issue by MatheusRV** [TechEmpower/FrameworkBenchmarks#4118]
I'm trying to implement a simpler way to do tasks inside Dockers, but because Docker-Py is in version 0.3.5 I'm having some bizarre errors, for example, it's not possible to find /bin/bash when running the [docker_helper.py #L177](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/utils/docker_helper.py#L177) It returns me that the file does not exist even though it is there. I already ran several tests and the error persists as https://github.com/docker/docker-py/issues/2149 . How to proceed to update Docker-Py, it usually breaks not closing Docker after RUN, so the next execution will return that it is still running and can not access it.

Last version is 3.5.0 as seen: https://github.com/docker/docker-py/releases/latest

**Comment by nbrady-techempower** [comment]
I'm not sure what you mean by 

> Docker-Py is in version 0.3.5

I'm also not sure what you're trying to do?

**Comment by MatheusRV** [comment]
> I'm not sure what you mean by
> 
> > Docker-Py is in version 0.3.5
> 
> I'm also not sure what you're trying to do?

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/Dockerfile#L17 This code is using Docker 3.1.0 not Docker 3.5.0.

**Comment by msmith-techempower** [comment]
Is there a specific need to use a newer version of the Docker Python SDK?
