### ISSUE TITLE
Test with HipHop VM (hhvm) for PHP frameworks

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#413]
It would be very interesting to test at least a subset of the PHP frameworks on Facebook's HipHop VM (hhvm).

https://github.com/facebook/hiphop-php

**Comment by bhauer** [comment]
I am curious: do we have any HHVM tests that actually include the use of a framework or are all of our HHVM tests analogous to our "plain PHP" test?

Since HHVM is more an alternative *platform* than a framework, I'd really like to see HHVM with a few high-profile frameworks.  Maybe Laravel, Cake, and Zend?

**Comment by msmith-techempower** [comment]
The latter - HHVM is analogous to our "plain PHP" test.

**Comment by bhauer** [comment]
Do we have an issue that captures an intent to get some mainstream frameworks tested with HHVM?  I don't think we need a mirror of all PHP frameworks on HHVM, but a small subset would be nice in order to establish how well HHVM scales with additional framework code size versus PHP.

**Comment by msmith-techempower** [comment]
Is this issue not precisely what you described?

**Comment by bhauer** [comment]
Yes, but it's closed.

**Comment by msmith-techempower** [comment]
Reopened - what @bhauer said.

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
