### ISSUE TITLE
Frontend framework benchmark from TechEmpower

### ISSUE THREAD

**Issue by McFlat** [TechEmpower/FrameworkBenchmarks#4134]
This is a feature request. I would like to request a frontend framework benchmark, I've been using these benchmarks for years to know what to use in production and what to learn next as part of future developments. It would be awesome if you guys also did a frontend framework benchmark. So people can see how jQuery performs compared to vanilla JavaScript, or VueJS or ReactJS or Angular or BackboneJS or Marionette etc. That would be really awesome because then developers of these frontend frameworks could use these benchmarks to know what to improve, just like ASP.Net did with their results(895 times improvement, wow!) and so on. Right now we have a backend benchmarks, but it would be great if we also had a frontend benchmarks that would allow us to see results of TypeScript versus CoffeeScript or ES2015 versus ES2016, and not only languages but the frameworks that use these languages. I understand that this is not an easy task to accomplish and I congratulate you guys on the current progress you've made, may the future bring more good fortune.

<img width="1017" alt="screen shot 2018-10-18 at 9 10 38 am" src="https://user-images.githubusercontent.com/43896676/47160898-85794c00-d2b6-11e8-9d5f-2ab555fea42b.png">

**Comment by MatheusRV** [comment]
I believe that this is not the purpose of this repository. There are several other repositories that perform workload testing in frontend frameworks. To create this change would have to modify several parts of the benchmark.

**Comment by nbrady-techempower** [comment]
Thanks for making a request @McFlat 

Unfortunately this isn't something that we'd take on in this particular project.

**Comment by bhauer** [comment]
Hi @McFlat. I really appreciate the kind words you have for the project and it is very rewarding to hear that it has been of use to you!

We work on this project as time permits between the work that "keeps the lights on" as they say, so the short answer is that we don't have the human hours necessary to take on that additional effort.  As much as I agree with you (believe me, I want faster front-end applications too!), it's beyond our reach for the moment.

All that said, @krausest's work looks very relevant and appears to be the go-to for front-end performance benchmarking.  Take a look: https://stefankrause.net/js-frameworks-benchmark8/table.html
