### ISSUE TITLE
MySQL log flushing configuration change

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#414]
Consider setting the following MySQL configuration option for log flushing based on input from someone more experienced with InnoDB tuning at Hacker News:

    innodb_log_flush_at_trx_commit = 2

See thread at https://news.ycombinator.com/item?id=6195747

**Comment by LadyMozzarella** [comment]
Closing - Looks like this was completed at [commit #b4e0d7ca516e2cf2017a069dd9493b85536122c3](https://github.com/TechEmpower/FrameworkBenchmarks/commit/b4e0d7ca516e2cf2017a069dd9493b85536122c3) on June 28, 2014.
