### ISSUE TITLE
Why import io.vertx.core.Vertx in the configuration of spring webflux?

### ISSUE THREAD

**Issue by jabrena** [TechEmpower/FrameworkBenchmarks#4140]
Hi,

Why in this Configuration class:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/spring-webflux/src/main/java/benchmark/config/PgClientConfig.java

Are you using a Vertx object?

Juan Antonio

**Comment by nbrady-techempower** [comment]
That may be an extraneous import. @jringuette is the last person to work on that so he could answer best. You're more than welcome to submit a PR to fix if it is.

**Comment by jringuette** [comment]
Because pg-client is built on vertx. Under the hood, it use a vertx instance in its database driver implementation.

**Comment by jabrena** [comment]
Hi @jringuette, many thanks for the answer. :)
