### ISSUE TITLE
Is it possible to send a PR about Spring Webflux + R2DBC + PostgreSQL

### ISSUE THREAD

**Issue by jabrena** [TechEmpower/FrameworkBenchmarks#4141]
Hi,

I was reviewing the project and it is amazing. I reviewed in detail spring examples:

+ Spring (Servlet API)
+ Spring Webflux (PostgreSQL)
+ Spring Webflux (MongoDB)

I would like to contribute with a new example using the new Reactive library for relational databases.
https://github.com/r2dbc

Is it possible?

Juan Antonio

**Comment by nbrady-techempower** [comment]
@jabrena Thanks for checking out TechEmpower's Framework Benchmarks! You're more than welcome to submit a Pull Request for any implementation. We'll try to review it or ping folks who may have worked on the implementation last.
