### ISSUE TITLE
NO RESULTS (Did framework launch?)  What do I need to do?

### ISSUE THREAD

**Issue by IKende** [TechEmpower/FrameworkBenchmarks#4179]
log display server started!
```
beetlex-fasthttpapi: [Info:11/07/2018 12:10:34] server start@:::8080
beetlex-fasthttpapi: [Info:11/07/2018 12:10:34] FastHttpApi Server started!
beetlex-fasthttpapi: ServerGC:True
beetlex-fasthttpapi: BeetleX Http Server Listen :::8080
```
i tested successfully with wrk4.1.0 on the local server

_Originally posted by @IKende in https://github.com/TechEmpower/FrameworkBenchmarks/pull/4178#issuecomment-436606687_

**Comment by nbrady-techempower** [comment]
We'll try and help you troubleshoot within the PR. I'll close this to keep it in one place.
