### ISSUE TITLE
Docker Image Failing to Build

### ISSUE THREAD

**Issue by codylerum** [TechEmpower/FrameworkBenchmarks#4217]
```wildfly-ee: Step 1/14 : FROM maven:3.6.0-jdk-11-slim as maven
wildfly-ee: Docker build failed; terminating
wildfly-ee: Traceback (most recent call last):
wildfly-ee:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 51, in __build
wildfly-ee:     raise Exception(token['errorDetail']['message'])
wildfly-ee: Exception: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
wildfly-ee: Build time: 1s
```

Is there something that needs to be white listed? I updated this to use `maven:3.6.0-jdk-11-slim` which worked fine in CI but seems to be failing @ tfb-status

https://tfb-status.techempower.com/unzip/results.2018-11-24-07-16-09-874.zip/results/20181121114424/wildfly-ee/build/wildfly-ee.log

**Comment by nbrady-techempower** [comment]
Dockerhub has been having intermittent issues the last couple of days; nothing to do on our end. However, we could parse that error better.

**Comment by codylerum** [comment]
Thanks. Normally wouldn't have worried but just waiting on the first clean run after an update. I'll keep monitoring it. I'll leave this issue open for now in case others see the same problem.
