### ISSUE TITLE
Responses including cached Date header

### ISSUE THREAD

**Issue by an-tao** [TechEmpower/FrameworkBenchmarks#4291]
I did some testing in the benchmark project and I found that in the tests 'Json' and 'Plaintext', the response 'Date' header of some frameworks is always the same as the first response. It hints that the response entire text string including headers and the body is cached in memory for every request. According to the benchmark document, this seems to be illegal. But the framework that uses caching occupies a high position in the rankings. Am I wrong with the test rules? Does the test client check the Date header to ensure that each response is generated separately?

**Comment by an-tao** [comment]
I think the ulib framework is caching the response, maybe I was wrong, but when I followed it's dockerfile to run the test, I got responses by the curl command as follows:
<img width="821" alt="2018-12-25 9 40 41" src="https://user-images.githubusercontent.com/21002501/50408868-2b05ea00-0829-11e9-956f-b5db5d974f17.png">
As you can see, all the Date headers are the same. Do you think that what I suspect is reasonable? If I am wrong, please correct me. Thank you!

**Comment by dividedbynil** [comment]
@stefanocasazza

**Comment by stefanocasazza** [comment]
I simple follow as other frameworks to not update the Date header for performance reason. So far it is not a requirement to have a Date header timed aligned

**Comment by fafhrd91** [comment]
Rust top performing frameworks do update date header.

**Comment by nbrady-techempower** [comment]
Per the test rules, the response must be composed on the spot. This should include the proper date, though we currently do not check that the date header is different from request to request, just that it's present. I'll look to add this as part of the verification step before the next round, marking tests that don't fix this in the future as failed.

@bhauer @msmith-techempower @michaelhixson Anything to add here?

**Comment by benaadams** [comment]
Date header should be changing every second otherwise it wouldn't meet the "production-grade" requirement?

**Comment by zloster** [comment]
@nbrady-techempower Some test implementation are using time-expiration caching for the date header. They refresh the date header once a second or so. Out my head I can recall:
- https://github.com/TechEmpower/FrameworkBenchmarks/blob/d157dfc58f2cae4c0f57ba6eddfca0b26fd73525/frameworks/Java/netty/src/main/java/hello/HelloServerHandler.java#L78-L87
- https://github.com/TechEmpower/FrameworkBenchmarks/blob/d157dfc58f2cae4c0f57ba6eddfca0b26fd73525/frameworks/Java/spring-webflux/src/main/java/benchmark/DateHandler.java#L11-L19

The HTTP date header is with an 1 second granularity - https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1 So caching for a second should not have any big practical implications. Maybe the rules should be amended if this behaviour is allowed.

**Comment by nbrady-techempower** [comment]
@zloster I think we're probably ok with that but I will double check. Whatever verification we put into the toolset likely wouldn't flag that anyway.

**Comment by zloster** [comment]
@nbrady-techempower I agree.
Just wanted to make sure this fine detail don't get lost.

**Comment by boazsegev** [comment]
F.Y.I,

The facil.io framework also [caches the date string](https://github.com/boazsegev/facil.io/blob/master/lib/facil/http/http.c#L80-L92) using a single second granularity (not the whole header, but still).

I was assuming that's allowed, since the result doesn't effect the response (it should always show the correct date/time)...

**Comment by benaadams** [comment]
I assume the General requirements have been updated for this:

> 5. ... For Date, we expect that the rendered date be accurate. However, it does not need to be rendered from the system clock to a byte buffer for each request. Re-rendering once per second is an acceptable tactical optimization (and is an optimization baked into many frameworks).

**Comment by nbrady-techempower** [comment]
Yeah just to confirm, we're ok with re-rendering/caching just the date header every one second. Date headers that remain unchanged will cause tests to fail in upcoming rounds.

**Comment by nbrady-techempower** [comment]
@helyho Java/voovan needs to be updated, as it will fail before the next round because of this issue.

@smthing Same with Java/smart-socket

**Comment by nbrady-techempower** [comment]
This should be resolved with #4452
