### ISSUE TITLE
ENV variable to identify host environment

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#4336]
Let's talk about setting some kind of environment variable on the host machines that tests can use to identify where the benchmarks are being run like:

`BENCHMARK_ENV=citrine`

This would allow tests to tune to specific environments without necessarily creating multiple test variants. 
 
Per discussion in #4333

**Comment by sebastienros** [comment]
Would it allow conditional statements in Docker images though? Like call `COPY` or `ENV` conditionally based on these settings?

If not then maybe calling a specific bash script before invoking the Docker image would be useful.

**Comment by nbrady-techempower** [comment]
No, but you could check the environment in a `RUN` command and run whichever bash script you wanted

**Comment by msmith-techempower** [comment]
I am not entirely against the notion of using environment variables, but we already have to tweak the run script (our continuous scripts for starting/stopping a run) on each environment manually; so, I think probably adding a simple optional flag to `run-tests.py` like `--env citrine` does the job simply.

**Comment by nbrady-techempower** [comment]
Then to @sebastienros point you could have a dockerfile that runs some setup script like:

`RUN ./${BENCHMARK_ENV}.sh || default.sh`  which would run `./citrine.sh` if you had it or `default.sh` in some other environment if you didnt have a `vagrant.sh` or `travis.sh` or whatever

**Comment by volyrique** [comment]
FYI `h2o` currently detects the environment it is running on, though in a fragile manner - details [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/3f5ae4d173f330cd9a047b9439aa9b3cea84e16b/frameworks/C/h2o/start-servers.sh#L13).

**Comment by mkurz** [comment]
Besides an environment variable that let's you identify on which platform the tests run (cloud vs. citrine) I suggest two more environment variables:

- One for "raw" CPU count - which is the CPU count of the host machine _but without hyper threading threads_.
- One for threads count (that is CPU count _including_ hyper threading threads)

If these two would be available, there wouldn't be a need to switch or customize scripts per environment when the config file syntax of a framework or the app itself can read environment variables (Play2 for example).
E.g. in a Play config file you could just define something like:
```
db.poolsize = ${CPU_COUNT}
// or maybe even (not sure)
db.poolsize = ${CPU_COUNT * 2}
// or
app.workerthreads = ${THREAD_COUNT}
```
The `${...}` variables would be resolved via env variables obviously.

What do you think?

**Comment by mkurz** [comment]
The advantage of having `CPU_COUNT` (without hyper threading threads) and `THREAD_COUNT` (with hyper threading threads) is that even when you change the infrastructure/plattform/server where the tests run on, that wouldn't matter for applications because they would adapt automatically to the cpu/thread counts (because only the TechEmpower guys have to set that value once after changing the server).
If however we only have `BENCHMARK_ENV`, we would always have to adjust the application scripts to update the cpu/thread counts... every time you change the server...

What do you think?

**Comment by nbrady-techempower** [comment]
@mkurz I believe, by default, the container uses all the cpus of the underlying host and you have access to that information in bash as if you were on the host. Some frameworks here already gather that information to do what you're saying, like https://github.com/TechEmpower/FrameworkBenchmarks/blob/498221c13cb76aeae17e2ba9ba5be092b83b52d8/frameworks/Haskell/yesod/yesod.dockerfile#L10

**Comment by mkurz** [comment]
@nbrady-techempower Thanks for your reply - I gave this a try, see #4413

**Comment by nbrady-techempower** [comment]
Going to close this now as `BENCHMARK_ENV` is in and the thread information is already available. Will continue to look at adding more helpful env vars in the future.

**Comment by mkurz** [comment]
So we can expect `BENCHMARK_ENV` set to `citrine` when running on bare metal. What about Azure? Will you set a value or leave it empty?

**Comment by nbrady-techempower** [comment]
We’ll set it to azure for now yeah

On Monday, February 11, 2019, 1:30 PM, Matthias Kurz <notifications@github.com> wrote:


So we can expect BENCHMARK_ENV set to citrine when running on bare metal. What about Azure? Will you set a value or leave it empty?
