### ISSUE TITLE
Discuss on Mofuw (Nim) status?

### ISSUE THREAD

**Issue by proyb6** [TechEmpower/FrameworkBenchmarks#4374]
It’s now a read-only, no longer maintain by the author, should it be remove from the benchmark?

https://github.com/2vg/mofuw

**Comment by nbrady-techempower** [comment]
Yes, feel free to open a PR that removes it. Otherwise someone here will get to it shortly.

**Comment by nbrady-techempower** [comment]
Resolved with #4420
