### ISSUE TITLE
Small error in multiple queries requirements 

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#4376]
Checking the logs and watching the result sets, I found an small error in the concurrency.

## log query/raw.txt 512 concurrency
```
 Queries: 20 for query
 wrk -H 'Host: 10.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28
```

https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=query
## Requirements summary
In this test, each request is processed by fetching multiple rows from a simple database table and serializing these rows as a JSON response. The test is run multiple times: testing 1, 5, 10, 15, and 20 queries per request. All tests are run at **256 concurrency**.

Change the concurrency to **512** in the requirements summary.

**Comment by joanhey** [comment]
Also need to change in 
https://www.techempower.com/benchmarks/#section=code

## Test type 3: Multiple database queries

17. The request handler will be exercised at 256 concurrency only.

**Comment by joanhey** [comment]
Another concurrency error:

## Test type 2: Single database query

17. The request handler will be exercised at concurrency levels ranging **from 8 to 256**.

And is **from 16 to 512**.

**Comment by bhauer** [comment]
Great catch, @joanhey! I've just posted fixes for these.
