### ISSUE TITLE
Dart Angel framework failing

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#4432]
@thosakwe Looks like the framework is no longer building correctly possibly because some of the dependencies in the pubspec were updated. Could you update this if you have the time? If not we can just remove it for now and you can add it back when you're ready. Thanks!

**Comment by thosakwe** [comment]
I should be able to update this within the next few days. I have an exam tomorrow, though, so I won’t be able to fix the error until that’s done. Hopefully that’s fine with you

**Comment by nbrady-techempower** [comment]
@thosakwe Of course! Take your time, just wanted to make you aware.

**Comment by thosakwe** [comment]
Starting work to patch this up today.

**Comment by nbrady-techempower** [comment]
Thanks @thosakwe !

**Comment by nbrady-techempower** [comment]
Hi @thosakwe - Anything I can do to help move this along? Going to start removing broken frameworks next week.

**Comment by thosakwe** [comment]
Finally got it done - https://github.com/TechEmpower/FrameworkBenchmarks/pull/4537

**Comment by thosakwe** [comment]
Noticed that the tests were failing in Round 18 (I've definitely updated a lot since March, so that's probably why).

Getting to work on fixing it.

**Comment by nbrady-techempower** [comment]
Thanks @thosakwe !
