### ISSUE TITLE
Bottle & starlette performance

### ISSUE THREAD

**Issue by agalera** [TechEmpower/FrameworkBenchmarks#4479]
According to the TechEmpower info:
(plaintext)
starlette: 359,988
bottle: 309,756

https://github.com/TechEmpower/FrameworkBenchmarks/blob/7ebc9912b0f570987ec8470281594700ccb70374/frameworks/Python/bottle/gunicorn_conf.py#L8
I have seen that the configuration of gunicorn is different, bottle uses workers * 3, and starlette no, I have tried in my local several configurations:

bottle
workers * 1 = 26,090.86
workers * 2 = 25,852.29
workers * 3 = 25,790.37

starlette
workers * 1 = 8,492.77
workers * 2 = 7,930.71
workers * 3 = 7,778.75

According to TechEmpower, starlette is faster, but I can not even match the performance with the code of your repository (I'm using the dockerfiles that you provide), what am I doing wrong?

I used wrk for testing:
wrk -t4 -c 20 -d10s http://127.0.0.1:8080/plaintext

any ideas? Thanks!
@tomchristie @defnull

**Comment by tomchristie** [comment]
🤷‍♂️ I’d start by reducing the variables. Try plain WSGI (Gunicorn) vs ASGI (Gunicorn with Uvicorn worker class) and see if you’re still seeing a difference. Might help you figure out some environmental difference between what you’re doing in each case.

**Comment by agalera** [comment]
I am now running the tests in the same container docker, and with a more simplified code, to see if I find the reason, I have also reduced the number of workers to 2, since I am on the laptop and so I have 2 free cpus for wrk

starlette + gunicorn + uvicorn
Running 10s test @ http://127.0.0.1:8080/plaintext
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   608.34us  548.21us  13.68ms   98.64%
    Req/Sec     8.62k   401.13     9.32k    74.00%
  171636 requests in 10.00s, 24.06MB read
Requests/sec:  17160.11
Transfer/sec:      2.41MB

Bottle + gunicorn + meinheld
Running 10s test @ http://127.0.0.1:8080/plaintext
  2 threads and 10 connections

  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   488.23us  397.80us  14.25ms   92.17%
    Req/Sec    10.81k     1.33k   13.73k    65.84%
  217091 requests in 10.10s, 36.65MB read
Requests/sec:  21494.20
Transfer/sec:      3.63MB


bottle_app.py
```python
import bottle

app = bottle.Bottle()
@app.get('/plaintext')
def index():
    return 'Hello, world!'
```

starlette_app.py
```python
from starlette.applications import Starlette
from starlette.responses import PlainTextResponse

app = Starlette()


@app.route('/plaintext')
def plaintext(request):
    return PlainTextResponse(b'Hello, world!')
```
bottle_conf.py
```python
workers = 2

bind = "0.0.0.0:8080"
keepalive = 120
errorlog = '-'
pidfile = '/tmp/bottle.pid'
loglevel = 'error'
```

scarlette_conf.py
```python
workers = 2

bind = "0.0.0.0:8080"
keepalive = 120
errorlog = '-'
pidfile = '/tmp/scarlette.pid'
loglevel = 'error'
```

run bottle
```
gunicorn bottle_app:app -k 'egg:meinheld#gunicorn_worker' -c bottle_conf.py 
```

run scarlette
```
gunicorn app:app -k uvicorn.workers.UvicornWorker -c starlette_conf.py
```

```
root@d66250ff7de6:~# uname -a
Linux d66250ff7de6 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 GNU/Linux
root@d66250ff7de6:~# python --version
Python 3.6.6
root@d66250ff7de6:~# pip freeze
asyncpg==0.16.0
bottle==0.12.16
Click==7.0
greenlet==0.4.15
gunicorn==19.9.0
h11==0.8.1
httptools==0.0.11
Jinja2==2.10
MarkupSafe==1.1.1
meinheld==0.6.1
starlette==0.3.0
ujson==1.35
uvicorn==0.3.3
uvloop==0.12.1
websockets==7.0
```

**Comment by agalera** [comment]
I tested directly with the script provided by TechEmpower:
./tfb --mode benchmark --test bottle
./tfb --mode benchmark --test starlette
the percentage is similar, being slower starlette

maybe with more cores scale better starlette? I'll try to test this on some more powerful server

**Comment by nbrady-techempower** [comment]
@agalera Don't forget we're also using a 3 machine set up that introduces some network latency. If you're testing on one machine, your results will vary. Also, of course, there are tons of other variables here. You can keep an eye on https://tfb-status.techempower.com to see if the results you cited from round 17 are still applicable. There have probably been some changes to these tests in the meantime.

**Comment by agalera** [comment]
@nbrady-techempower Thanks a lot!

https://www.techempower.com/benchmarks/#section=test&runid=7464e520-0dc2-473d-bd34-dbdfd7e85911&hw=ph&test=plaintext&l=zijzen-7&a=2

I have seen that there is a build on the 20th of this month, and it gives some results similar to those that it gives me in my environment, maybe some change in bottle or starlette has changed the performance compared with round 17.

**Comment by tomchristie** [comment]
> maybe some change in bottle or starlette

Starlette's requirements are pinned, and hasn't been updated in the TE repo lately, so shouldn't be anything there. But look like Bottle has seen some changes in the repo recently.

One thing to look at might be the JSON tests instead, and see if you're seeing equivelent variances there. (And if the build on the 20th changes metrics there too or not.)

Something to watch out for is that the plaintext tests enable HTTP pipelining, which isn't actually representative of almost any real-world cases since it's disabled on all modern browsers now, and generally unsupported by clients and proxies. Could be related to behavior under pipelining.

**Comment by agalera** [comment]
if it is true that plaintext is not very useful to analyze, json tests are much more interesting, but support for ujson en bottle is not yet in any official release (https://github.com/bottlepy/bottle/pull/933)

That is the reason why I was comparing the performance in plaintext, see if it coincided with TechEmpower and then try the same tests with bottle 0.13-dev in local.

**Comment by nbrady-techempower** [comment]
Going to close this for now; hard to identify the issue unless you can replicate our environment.
