### ISSUE TITLE
Codeigniter framework issues

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#4492]
CodeIgniter is causing some issues in our Azure and Citrine environments, most recently leaving 1026 php-fpm processes open and using 30gb of memory. Though Citrine can handle it, it's causing docker to shutdown on Azure.  The same is not happening for the `codeigniter-hhvm` tests, though those tests are getting several hundred 5xx errors.

@joanhey as my go to for PHP related issues, do you have any time to take a look at this?

Edit: CakePHP also opens 1026 php-fpm processes but only uses 2-3gb of memory

**Comment by joanhey** [comment]
Hi, Nate
I will check it locally now.

But the last round was using 2.048 php-fpm processes without any problem.

**Comment by joanhey** [comment]
Also fail in the vagrant box.

Tried: 
* Update core
* php 7.2
* changes in the config

But the problem is when use db persisten connections, that have a memory leak.
I will create an issue in the codeigniter repo, as no other framework have this problem.

I will disable db persistent connections when using the cloud server.

@nate where is the info or example about the new [BENCHMARK_ENV]

**Comment by nbrady-techempower** [comment]
Thanks for taking a look @joanhey 

I'll update the wiki with benchmark_env stuff.

For now, to get the BENCHMARK_ENV you can use

`ARG BENCHMARK_ENV` in your dockerfile and then you'll have access to `$BENCHMARK_ENV` which will be either `azure` or `citrine` for our two main envs.

**Comment by joanhey** [comment]
And why not another for vagrant or local ??

**Comment by nbrady-techempower** [comment]
Those are for specific tuning for the bigger environments. I don't think we have to name every environment. If the framework is breaking on local or vagrant without some kind of tuning based on environment variables, I think there are other problems. You can check to see if `BENCHMARK_ENV` is empty to know you're in local/vagrant/travis.

**Comment by nbrady-techempower** [comment]
Btw, those are passed in during execution. So when you run `tfb --test codeigniter` you can pass `--benchmark-env local`

**Comment by joanhey** [comment]
The good thing about the local, is that you can test locally that it is working the code.

**Comment by nbrady-techempower** [comment]
Agreed. But like I said, the way we add the `BENCHMARK_ENV` is by adding the `--benchmark-env citrine` flag to the `tfb` command on the citrine environment. So if you'd like a `local` all you have to do is add `--benchmark-env local` to your `tfb` command locally and `$BENCHMARK_ENV` will = `local` for ya! :)

**Comment by nbrady-techempower** [comment]
FYI, we've made a slight change to this and it's been added to the wiki https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-How-To-Add-Frameworks-or-Tests#tuning-by-environment
