### ISSUE TITLE
Documentation and benchmark inconsistencies

### ISSUE THREAD

**Issue by amichair** [TechEmpower/FrameworkBenchmarks#4528]
Hi, I've noticed various inconsistencies between the documentation (on results website and/or docs site) and actual scripts/benchmarks behavior, and a few other glitches (readme, config file etc.):

- [x] 1. The requirements docs (both on results website and in docs page) for the Fortunes test (maybe also others) states that it is run with concurrency levels ranging from 8 to 256, but in practice it also runs with 512.

- [x] 2. The requirements docs (both on results website and in docs page) for the Fortunes test (maybe also others) states that the response content type must be "text/html", however the test verification fails if this content type string is returned. It passes only with "text/html; charset=UTF-8". The requirements should be updated to reflect the real test.

- [x] 3. The docs say that in the benchmark config file, orm should be Full, Micro or Raw. But the script for adding a new framework generates a config with 'None' as well. Also the docs don't specify this as being optional, as it does for some other fields. So is None a valid option or not? And what is the difference between None and Raw? Either the script should be modified to avoid None, or the docs to mention and explain None.

- [x] 4. The docs show a 'flavor' field in the config examples, but don't mention or explain it in the field explanations below the example.

- [x] 5. The auto-generated readme for a new test says to fill in the source_files file, but this file has been removed from the actual codebase as no longer relevant. This should be updated everywhere in docs/readme etc.

- [x] 6. The Java/README.md file seems outdated, and for some reason most of the Java framework readme's link back to it. It should either be updated, or the links to it changed to point to the benchmarks homepage or something else.

- [x] 7. When opening an issue on github (for the main project, not the docs), the issue template says about new frameworks that one should add a readme with info about the framework and a link to its homepage and documentation. However the auto-generated readme when creating a new test, while containing exhaustive steps on what should be in the readme, fails to mention this.

In general, it seems there's an issue with updating info in one place and not in others, perhaps you can have an internal checklist or procedure to make sure that if something changes in the scripts or policy, it should be updated everywhere (results website docs, docs website, scripts, generated readmes/configs, github templates, existing projects, etc.) As a developer/user, I often find myself running around the various sources trying to guess which ones are up to date and which ones are stale and how to resolve conflicts between them so that I know how to do things right. I'm sure organizing this would benefit both you and users/devs/viewers.

**Comment by nbrady-techempower** [comment]
All items have been addressed. Thanks for the attention to detail. The wiki is now the primary source of documentation.
