### ISSUE TITLE
Iris seems to be a questionned framework

### ISSUE THREAD

**Issue by waghanza** [TechEmpower/FrameworkBenchmarks#4591]
Hi,

I can see that `iris` has been added here.

In an alternative project https://github.com/the-benchmarker/web-frameworks/issues/1129, it has been raised a legal question about this framework.

When this framework, was added here, do you have the same questionning ?

Regards,

**Comment by nbrady-techempower** [comment]
Since the maintainer of the framework isn't the one that submitted the implementation, and there seems to be issues regarding licensing, etc... and way too much drama for me to follow/care about, I'll remove it.
