### ISSUE TITLE
Question: how to tune GC for test environments

### ISSUE THREAD

**Issue by flip111** [TechEmpower/FrameworkBenchmarks#4592]
I noticed that tuning some params on the haskell runtime system can make a big difference in the transfer/sec achieved. I did some [measurements](https://github.com/TechEmpower/FrameworkBenchmarks/pull/4571). I think it would be fair to tune these parameters because in production you also get to tune it for your application/workload. I have not found an "intuitive way" to find the optimal parameters (please drop a line if you know). Testing combinations of params takes a long time, but this seems to be the traditional [way to do it](https://hackage.haskell.org/package/ghc-gc-tune). My question is how and when (during test? / before test? / between rounds?) can this tuning be done for the different environments (Physical / Cloud) ?

Perhaps related issue: https://github.com/TechEmpower/FrameworkBenchmarks/issues/1433

**Comment by nbrady-techempower** [comment]
Hi @flip111 -

We recently introduced a new `ARG` called `BENCHMARK_ENV` that you can pull into your docker container to find out which testing environment you're in https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/utils/metadata.py#L285

Tests run continuously off the master branch of this repo and you can see those results on https://tfb-status.techempower.com

So you can make pull requests with different tuning parameters and when the next run kicks off it will pull the latest code from this master branch. You can continue to tweak as needed and we'll try and get those PR's in ASAP so you can monitor results.
