### ISSUE TITLE
[php-ngx] Multiple queries test regression

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4612]
The #4596 is separating `single query` and `multiple queries` tests in the PHP frameworks. However there is a missed configuration about the `php-ngx`:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/4596/files#diff-d064e3038c12f323a8ab7749aa0d07e3R136

I guess that @joanhey will fix this easily.

IMO there is _also a problem with the verification code_. Check the build output in Travis:
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/489982007#L1256-L1285

It only issues `warnings` but doesn't fail the verification. _It should fail because the code is always returning a single result_. https://github.com/TechEmpower/FrameworkBenchmarks/blob/ba86c0d71263d5ddd5253007a1d1ffa24736b37e/frameworks/PHP/php/dbraw.php#L10-L15

The other related configurations:

- https://github.com/TechEmpower/FrameworkBenchmarks/blob/ba86c0d71263d5ddd5253007a1d1ffa24736b37e/frameworks/PHP/php/deploy/nginx_php.conf#L54-L60
 - https://github.com/TechEmpower/FrameworkBenchmarks/blob/ba86c0d71263d5ddd5253007a1d1ffa24736b37e/frameworks/PHP/php/php-ngx.dockerfile#L29

**Comment by joanhey** [comment]
The code is fixed.

But the test should fail, and not show only warnings.

**Comment by nbrady-techempower** [comment]
The PR closed this, but leaving open until I make the toolset change to mark those warnings as failures.
