### ISSUE TITLE
Continuous benchmark stalled

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#4634]
https://tfb-status.techempower.com/

**Comment by michaelhixson** [comment]
I don't think it is stalled.  Right now it is going through the four variants of vibed, which each [timeout after one hour of building](https://github.com/TechEmpower/FrameworkBenchmarks/issues/4568).  Hopefully we'll see new results in a half hour or so after it gets through the last variant of vibed.

From the current run's `benchmark.log` file:
```
--------------------------------------------------------------------------------
Benchmarking vertx-web-susom-postgres
--------------------------------------------------------------------------------
BENCHMARKING DB ...
Benchmark results:
Complete
BENCHMARKING QUERY ...
Benchmark results:
Complete
BENCHMARKING UPDATE ...
Benchmark results:
Complete
BENCHMARKING FORTUNE ...
Benchmark results:
Complete
vertx-web-susom-postgres: Benchmarking time: 8m 18s
vertx-web-susom-postgres: Build time: 1s
vertx-web-susom-postgres: Time starting database: 1s
vertx-web-susom-postgres: Time until accepting requests: 1s
vertx-web-susom-postgres: Verify time: 8m 56s
vertx-web-susom-postgres: Total test time: 9m 8s
tfb: Total time building so far: 4h53m 26s
tfb: Total time verifying so far: 81h14m 19s
tfb: Total time benchmarking so far: 76h26m 7s
tfb: Total execution time so far: 89h3m 25s
vibed: ERROR: Problem starting vibed
vibed: Total test time: 1h1m 0s
tfb: Total time building so far: 5h53m 26s
tfb: Total time verifying so far: 81h14m 19s
tfb: Total time benchmarking so far: 76h26m 7s
tfb: Total execution time so far: 90h4m 26s
vibed-dmd-pgsql: ERROR: Problem starting vibed-dmd-pgsql
vibed-dmd-pgsql: Total test time: 1h1s
tfb: Total time building so far: 6h53m 26s
tfb: Total time verifying so far: 81h14m 19s
tfb: Total time benchmarking so far: 76h26m 7s
tfb: Total execution time so far: 91h4m 30s
vibed-ldc: ERROR: Problem starting vibed-ldc
vibed-ldc: Total test time: 1h1m 0s
tfb: Total time building so far: 7h53m 26s
tfb: Total time verifying so far: 81h14m 19s
tfb: Total time benchmarking so far: 76h26m 7s
tfb: Total execution time so far: 92h5m 32s
```

**Comment by joanhey** [comment]
Perhaps will be useful to try #4543, for lower that 4 hours.

**Comment by nbrady-techempower** [comment]
I'm not sure vibed is a good example of re-using the same dockerfile. Most of the differences happen during the build step; compiling with different configurations.

**Comment by michaelhixson** [comment]
The run got past vibed and tfb-status shows new data now, so I'm going to close this issue.  I agree that we should fix vibed at some point, but I see that as part of the always-present meta-issue of "we should fix or remove all failing frameworks".

**Comment by zloster** [comment]
@nbrady-techempower @michaelhixson 
These two runs seem to need cleaning:

- https://tfb-status.techempower.com/results/7005d40e-50d4-4ea4-8506-6010b6494844
- https://tfb-status.techempower.com/results/b9da3281-5254-4581-89eb-fe5933ed1f44

![TFB-status-cleaned](https://user-images.githubusercontent.com/778924/55854867-97a1bc00-5b6e-11e9-874f-b1590c81a9a6.png)
