### ISSUE TITLE
Trouble with #4649 and Travis - always skipping the test execution

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4655]
I've hit a problem with #4649. I have a fresh branch in my cloned repository. The command **fails in Travis** with this:
> export RUN_TESTS=`./toolset/travis/travis_diff.py | tee /dev/tty | grep -oP "travis-run-tests \K(.*)"`
fatal: Not a valid object name FETCH_HEAD
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "./toolset/travis/travis_diff.py", line 68, in <module>
    'git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)'
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '-c', 'git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)']' returned non-zero exit status 128

Here is the actual [Travis log](https://travis-ci.org/zloster/FrameworkBenchmarks/jobs/519727780#L436-L446).

On my workstation `git --no-pager diff --name-only FETCH_HEAD` is working and producing a result.

>XXXX@YYYY:~/source/FrameworkBenchmarks/frameworks/C/octane$  git --no-pager diff --name-only FETCH_HEAD
frameworks/C/octane/README.md
frameworks/C/octane/src/program.c
frameworks/C/octane/src/program.cpp
frameworks/C/octane/src/responders/sds_responder.c
frameworks/C/octane/src/responders/sds_responder.cpp
frameworks/C/octane/src/responders/sds_responder.h
frameworks/C/octane/src/responders/sds_responder.hpp

**Comment by nbrady-techempower** [comment]
Ah, bummer. When it's not a pull request travis is checking out the latest commit hash, when it is a pull request travis is grabbing the PR and naming it `FETCH_HEAD` and then checking out `FETCH HEAD`. I'll update the script early next week to handle that. In the meantime, feel free to open up work-in-progress PRs if you want to take advantage of our travis tests.

**Comment by nbrady-techempower** [comment]
Ok @zloster Looks like this is all set now. As long as you're workflow is creating a feature branch from your master branch, pushes to your branch will compare against your master to find the files that were changed. Also, pushes to your master or merges into your master will trigger a full run. (We want master to always do a full run)
