### ISSUE TITLE
"filters panel" not working anymore

### ISSUE THREAD

**Issue by mkurz** [TechEmpower/FrameworkBenchmarks#4668]
1. Go to https://www.techempower.com/benchmarks/#section=test&runid=d06ed950-3314-47f0-8708-137a9378ffe7
2. Click "Show filters panel"
3. Choose "play2"
4. Click "Apply changes"

**Result:** Changes are not applied :boom: 

Tested with Chrome and Firefox.

**Comment by nbrady-techempower** [comment]
Confirmed this as well, thanks for submitting @mkurz

**Comment by bhauer** [comment]
I'll investigate.  The panel is working for Round 17, but it seems recent changes I made broke support for the continuous runs that come packaged with metadata.  I'll follow up when I have updates.

**Comment by mkurz** [comment]
I used the panel ~ 2 or 3 weeks ago and it was working.

**Comment by bhauer** [comment]
Give it a retry now.

**Comment by mkurz** [comment]
Thanks, it works now.

**Comment by bhauer** [comment]
Thanks for catching that!
