### ISSUE TITLE
Actix-pg should not assume fortunes list size

### ISSUE THREAD

**Issue by sebastienros** [TechEmpower/FrameworkBenchmarks#4672]
From the fortunes requirements:

> The list data structure must be a dynamic-size or equivalent and should not be dimensioned using foreknowledge of the row-count of the database table.

But I think actix-pg is doing it:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/db_pg.rs#L208

Another related question, should new new Fortunes result be added after the database ones have or can it be added to the list before? I might matter based on the list implementation, and also for sorting as it's closer to its final position if added first.

**Comment by fafhrd91** [comment]
forgot about that one, should be fixed

**Comment by fafhrd91** [comment]
regarding additional record, do you think it will make any difference on results?

**Comment by nbrady-techempower** [comment]
> Another related question, should new new Fortunes result be added after the database ones have or can it be added to the list before?

We don't specify and probably wouldn't change/enforce anything new there until after the next round. What matters is that the new Fortune is created within the scope of the request and added to a dynamically sized list.
