### ISSUE TITLE
Incomplete test cases - compairing apples and orranges

### ISSUE THREAD

**Issue by Licenser** [TechEmpower/FrameworkBenchmarks#47]
Hi,
I've worked through some of the tests and noticed that certain framework tests don't implement all tests.
I see a issue with that in the sense that it removes parts of the programs logic and simplifies the case of handling.

Taking the netty test (which did best) as an example I don't see any logic regarding the path in the source which seems a bit like cheating to me.

I'd suggest not to rank frameworks with an incomplete implementation or at least force them to contain the same logic in regards to routing as other tests do.

Cheers,
Heinz

**Comment by LadyMozzarella** [comment]
Closing - summarized a bit in documentation.
