### ISSUE TITLE
Broken link in issue tracker template

### ISSUE THREAD

**Issue by amichair** [TechEmpower/FrameworkBenchmarks#4720]
The new issue template in this issue tracker says:

`If this issue is regarding documentation, please open that issue at our documentation repo at https://github.com/TechEmpower/TFB-Documentation`

but this link results in a 404 error.

**Comment by nbrady-techempower** [comment]
Note to self to use the new template workflow https://help.github.com/en/articles/about-issue-and-pull-request-templates
