### ISSUE TITLE
Add tags for round 16 and 17

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#4756]
Before there were branches R16 and R17.
I understand that they are not necessary.
But tags must exist for R16 and R17.

R17: https://github.com/TechEmpower/FrameworkBenchmarks/tree/b20ac7b1bad9e0e5e629d3d4cf1d5970387bb608

R16:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/724a773096f403d149cfaf59b8257465bbf70103

It would also be useful to add the link in the visualize page. Now there is only one link to the blog.

**Comment by msmith-techempower** [comment]
Yeesh, this is on me.

I'll get those tagged and released.

Thanks for bringing this to my attention.

**Comment by msmith-techempower** [comment]
I'm not going to get to this today (I will eventually), but I wanted to capture what we dug up here so I don't have to look again.

round16: 724a773096f403d149cfaf59b8257465bbf70103
round17: b20ac7b1bad9e0e5e629d3d4cf1d5970387bb608

**Comment by nbrady-techempower** [comment]
I took care of it: https://github.com/TechEmpower/FrameworkBenchmarks/releases
