### ISSUE TITLE
Clarify max-threads and the assumption of homogeneous testing machines

### ISSUE THREAD

**Issue by MalcolmEvershed** [TechEmpower/FrameworkBenchmarks#476]
`toolset/run-tests.py` has:

    parser.add_argument('--max-threads', default=8, help='The max number of threads to run weight at, this should be set to the number of cores for your system.', type=int)

This is passed to `start()` in `setup.py` as `args.max_threads`. But some scripts like `wsgi/setup.py` instead use:

    import multiprocessing
    NCPU = multiprocessing.cpu_count()

I don't mind either style, but what do we want? Proposals:

1. Scripts are fine to call cpu_count(). Change run-tests.py to set the default max_threads to cpu_count().

2. Scripts are fine to call cpu_count(). Don't let --max-threads be set on the command line and always set args.max_threads to cpu_count().

3. Change scripts to use args.max_threads and change run-tests.py to set the default max_threads to cpu_count().

Thoughts?

**Comment by hamiltont** [comment]
Moving to TechEmpower/TFB-Documentation#19
