### ISSUE TITLE
Wizzardo updates don't read randomNumber

### ISSUE THREAD

**Issue by sebastienros** [TechEmpower/FrameworkBenchmarks#4769]
As per https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#database-updates on point .vi `At least the randomNumber field must be read from the database result set.`

From my understanding of the current implementation it seems this value is never read:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/wizzardo-http/src/main/java/com/wizzardo/techempower/DBController.java#L94

It shouldn't impact the overall performance but I think it's necessary for compliance.

**Comment by nbrady-techempower** [comment]
Agreed; I've opened #4770 -- thanks @sebastienros

**Comment by sebastienros** [comment]
I have looked at 3 implementations so far and none read this field. So now I am questioning my understanding of the requirement.

Do we only need to do a  `SELECT id, randomNumber` or does the `randomNumber` field actually needs to be read and also assigned to an actual `World` object?

**Comment by nbrady-techempower** [comment]
@sebastienros Yes, they should. Feel free to open new issues or list them here.

**Comment by sebastienros** [comment]
ok, thanks for confirming, the doubt had grown ...
