### ISSUE TITLE
Reintroduce Tomcat+Servlet, possibly other Servlet containers

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#477]
Prior to publishing the Round 1 results, we had gathered results for Servlet and other Servlet-based frameworks on two Servlet containers: Tomcat and Resin.  Tomcat is popular, but Resin proved slightly faster across the board.  With only rudimentary results rendering at the time, we removed Tomcat from the tests because it was consistently slower and appeared to add no value, just noise.  Leaving it in would have also made the data appear, at least at first glance, too JVM-centric.

However, now that the results site allows filtering and we've long since passed the point of having a huge number of tests, we should reintroduce Tomcat+Servlet.  I was reminded of this in the comments to issue #475 by @MalcolmEvershed.

It would be appealing to me to add the following (and possibly others):
- Tomcat+Servlet
- Jetty+Servlet
- WildFly+Servlet (nee JBoss Application Server 8)

I don't believe it would be valuable to create permutations testing all Servlet-derived frameworks on these other Servlet Containers.  However, showing how each Servlet container performs with the most fundamental case (the Servlet tests) would allow a reader to extrapolate, for example, Compojure+Jetty (by looking at how Jetty+Servlet compares to Resin+Servlet and then how Resin+Compojure compares to Resin+Servlet).

If in the future a higher water mark is established over Resin (e.g., by WildFly), we may gradually want to add more permutations.  For instance, I have been interested in seeing Gemini on Undertow (#370).

**Comment by nbrady-techempower** [comment]
Looks like we have a few of these now
