### ISSUE TITLE
actix-pg doesn't read randomNumber

### ISSUE THREAD

**Issue by sebastienros** [TechEmpower/FrameworkBenchmarks#4771]
As per https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#database-updates on point .vi `At least the randomNumber field must be read from the database result set.`

It looks like `actix-pg` is not doing it.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Rust/actix/src/db_pg.rs#L169

The other rust implementation (`actix-core`) is using __diesel__ which should read all values by itself.

**Comment by nbrady-techempower** [comment]
Resolved by #4777
