### ISSUE TITLE
httpbeast json benchmark

### ISSUE THREAD

**Issue by fafhrd91** [TechEmpower/FrameworkBenchmarks#4794]
httpbeast uses [const expression](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Nim/httpbeast/techempower.nim#L9) for Json generation which violates benchmark rules

I don't know nim, I might be wrong. here is nim docs on [consts](https://nim-lang.github.io/Nim/manual.html#constants-and-constant-expressions)

**Comment by zloster** [comment]
`Nim/jester` is doing the same:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/cbfa2afa090451efda80a1e4abbc5fc7a34633a5/frameworks/Nim/jester/techempower.nim#L10

**Comment by nbrady-techempower** [comment]
I don't think `const` is an issue here. It looks like a regular assignment that's happening on every call to that route. The `%*` operator is serializing json from the `json` package. https://nim-lang.org/docs/json.html#creating-json This seems fine to me.

**Comment by fafhrd91** [comment]
[Nim docs](https://nim-lang.github.io/Nim/manual.html#constants-and-constant-expressions) talks about compile time execution.

**Comment by nbrady-techempower** [comment]
@fafhrd91 oooooh, sorry I missed that. I agree. Those should be `var`s.

**Comment by ynfle** [comment]
I think it should be `let` as is doesn't change
