### ISSUE TITLE
New benchmark type - file upload

### ISSUE THREAD

**Issue by elgunhuseynli** [TechEmpower/FrameworkBenchmarks#4829]
All of the benchmark types are based on download performance of the server. But what about how efficiently frameworks can handle concurrent file uploads?

I'm grateful to add PRs for file upload.

**Comment by bhauer** [comment]
That's a good idea.  I'll get it referenced in #133.

**Comment by nbrady-techempower** [comment]
Closing this now since it's in the additional test types issue
