### ISSUE TITLE
Actix Fortunes; Explanation of results

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#4834]
Actix fortunes are performing miles ahead of the rest of the field. [Check out these results.](https://www.techempower.com/benchmarks/#section=test&runid=5cc1a314-4e0c-4294-b8f1-cb607e0a5440&hw=ph&test=fortune)

@fafhrd91 I imagine that when we post official Round 18 results, there will be a lot of questions about how this was achieved. The framework was already near the top in previous results, but is now performing ~300% better. We suspect that a major contributing factor is a new release of the [rust-postgres driver](https://github.com/sfackler/rust-postgres/commit/0c8ecc024056a226a4496f8e4e4a24b343f1b894#diff-082b5049aa9906798891d9c781d670b4)

We're probably going to bring attention to this in the blog post for Round 18. Would you be able to speak to some of the improvements you made?

**Comment by fafhrd91** [comment]
sure

* new async rust postgres driver. it is rust implementation of psql protocol
* actix is single threaded, it runs in multiple threads but each thread is independent, so no synchronization is needed
* fortunes template uses simd instructions for html escaping
* actix uses generics extensively. compiler is able to use static dispatch for a lot of function calls
* actix uses object pools for requests and responses
* also it uses high performance hash map, based on google's swisstable

**Comment by bhauer** [comment]
> fortunes template uses simd instructions for html escaping

Nice.  I am just guessing, but I suspect this is the first use of SIMD instructions in any test implementation.

**Comment by zloster** [comment]
> 
> 
> > fortunes template uses simd instructions for html escaping
> 
> Nice. I am just guessing, but I suspect this is the first use of SIMD instructions in any test implementation.

The .Net stuff seems to utilize them a lot: [CoreCLR](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+avx) (the runtime) and [CoreFX](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+avx) (the standard library)

**Comment by sebastienros** [comment]
I am surprised you are not mentioning the usage of pipelining with Npgsql as this is what had the most impact AFAIK.
