### ISSUE TITLE
Suspisious log lines in Citrine benchmark.log

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4836]
The [latest available `benchmark.log`](https://tfb-status.techempower.com/unzip/results.2019-06-04-22-21-19-761.zip/results/20190601080432/benchmark.log) has the following lines in it:

```
--------------------------------------------------------------------------------
Benchmarking spring-webflux-rxjdbc
--------------------------------------------------------------------------------
BENCHMARKING DB ... 
Benchmark results:
Complete
BENCHMARKING QUERY ... 
Benchmark results:
Complete
BENCHMARKING UPDATE ... 
Benchmark results:
Complete
BENCHMARKING FORTUNE ... 
Benchmark results:
Complete
spring-webflux-rxjdbc: Benchmarking time: 8m 17s
spring-webflux-rxjdbc: Build time: 2s
spring-webflux-rxjdbc: Time starting database: 1s
spring-webflux-rxjdbc: Time until accepting requests: 4s
spring-webflux-rxjdbc: Verify time: 8m 56s
spring-webflux-rxjdbc: Total test time: 9m 10s
tfb: Total time building so far: 4h36m 25s
tfb: Total time verifying so far: 73h17s
tfb: Total time benchmarking so far: 68h37m 27s
tfb: Total execution time so far: 80h4m 45s
spyne: ERROR: Framework is not accepting requests from client machine
spyne: Total test time: 55s
tfb: Total time building so far: 4h37m 17s
tfb: Total time verifying so far: 73h17s
tfb: Total time benchmarking so far: 68h37m 27s
tfb: Total execution time so far: 80h5m 40s
```

According to the log the framework under test is `spring-webflux-rxjdbc` but there is an error message mentioning the next framework to be run - `spyne`:
```
spyne: ERROR: Framework is not accepting requests from client machine
spyne: Total test time: 55s
```

The data for the run: https://tfb-status.techempower.com/results/52587667-bee1-4b9b-b34d-929b616d5e4c

**Comment by nbrady-techempower** [comment]
It looks like this is happening in a few places where the header for the framework isn't being printed when the framework has a startup error. A couple of other spots it looks like one or two log lines weren't flushed to the benchmark log when a startup error occurred and appear a few lines down in the log. I'll take a look into it, but I don't suspect it's anything major.
