### ISSUE TITLE
onyx multiple queries benchmark violation

### ISSUE THREAD

**Issue by fafhrd91** [TechEmpower/FrameworkBenchmarks#4842]
onyx framework executes one query per request for multiple queries benchmark
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/onyx/src/endpoints/worlds/many.cr#L5

**Comment by nbrady-techempower** [comment]
@vladfaust To you have any time to fix this? We'll have to remove this from any official results.

https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries

**Comment by vladfaust** [comment]
Feel free to remove it for now, I'll re-add it some time later. Thanks!

**Comment by michaelhixson** [comment]
@fafhrd91 Thanks.  Confirmed by enabling postgres query logs locally.

```
Accessing URL http://tfb-server:8080/queries?queries=2:
2019-06-10 19:35:38 GMT LOG:  execute <unnamed>: SELECT * FROM world WHERE (id = ANY($1))
2019-06-10 19:35:38 GMT DETAIL:  parameters: $1 = '{3473,6467}'
```

**Comment by sebastienros** [comment]
Could this be part of the CI tests?

**Comment by msmith-techempower** [comment]
> Could this be part of the CI tests?

That's a great idea.
