### ISSUE TITLE
Retain worst-case latency during warmup?

### ISSUE THREAD

**Issue by foliot** [TechEmpower/FrameworkBenchmarks#4861]
I think it would be really interesting to see the worst-case latency of frameworks before they warm up. It would be even more interesting to see how long each framework takes to warm up, though that would probably be difficult to measure. 

From my professional experience with ASP.NET (not core), warmup costs happen a lot more often than I ever expected, and it has been a difficult problem to solve. You might have dozens of servers that get restarted periodically, and _somebody_ has to be the first person to hit an endpoint, and that person might notice a pretty considerable delay. Warming up each endpoint would be the only good solution to that, but it is infeasible with millions of lines of code and many thousands of endpoints. 

I've also been playing around with ASP.NET Core recently, and it has some unexpected warm-up costs as well. For both Entity Framework and Dapper, it could take hundreds of milliseconds to perform the first query for a trivial tutorial application. Based on EF Core [issue 1906](https://github.com/aspnet/EntityFrameworkCore/issues/1906), I'm not the only person noticing these unexpected performance problems.

This type of problem could be especially bad with cloud hosting that automatically spins up or winds down servers based on system load, such as Google App Engine. Auto-scaling platforms would be great if your application can handle it, but it would be too bad if that introduced a lot of unpredictable latency during peak usage.

I think having more visibility into this would push framework developers to reduce warmup costs and improve worst-case user experiences.

**Comment by zloster** [comment]
> I think it would be really interesting to see the worst-case latency of frameworks before they warm up

This data is currently available in non-structured form. The reported numbers from `wrk` about the `primer` and the `warmup` phases. Here is an example from `Citrine` and about DotNet Core:
https://tfb-status.techempower.com/unzip/results.2019-06-16-15-57-19-945.zip/results/20190613004556/aspcore-mvc-dap-pg/db/raw.txt
```
Running 5s test @ http://10.0.0.1:8080/mvc/db/dapper
  8 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   292.09us    1.03ms  40.09ms   99.62%
---------------------------------------------------------
Running 15s test @ http://10.0.0.1:8080/mvc/db/dapper
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.78ms    6.87ms 657.58ms   96.27%
```

It gets more interesting if you add the data from the `Azure` run:
https://tfb-status.techempower.com/unzip/results.2019-06-08-22-31-25-369.zip/mnt/tfb/FrameworkBenchmarks/results/20190605011349/aspcore-mvc-dap-pg/db/raw.txt
```
Running 5s test @ http://10.0.0.4:8080/mvc/db/dapper
  8 threads and 8 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.10ms    1.95ms  35.45ms   94.77%
---------------------------------------------------------
Running 15s test @ http://10.0.0.4:8080/mvc/db/dapper
  4 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.64ms   17.90ms 444.45ms   89.91%
```
The latency numbers by itself are not very revealing. But adding a comparison with the cloud instances i.e. weaker CPUs and so on starts to show some insights. I've quickly skimmed through some of the results - most results showed better latencies on `Citrine`. But `aspcore-mvc-dap-pg` is exactly the opposite - the max latencies from the two environments are very close to each other. Yes, we could speculate where the max latencies limitation is coming from. But the data suggest there is a bottleneck.

Maybe displaying these values side by side could reveal the framework limitations in the cold start conditions. @foliot What do you think?

**Comment by foliot** [comment]
Hmm, I didn't realize that this was captured in the raw data. I'm not sure why exactly the latency isn't all that bad during the cold start like I see when I work with ASP.NET Core locally. Maybe the test would need larger models to work with or something? I know that a lot of C# libraries do some time-consuming reflection on objects the first time you call a method with a new class, so maybe that isn't really visible here due to the simple data model. 

Since the code used for these benchmarks is pretty small and simple, maybe warmup time isn't the kind of thing you'd really notice in the numbers for a lot of frameworks. Just glancing at a few other frameworks, it didn't really look like the numbers were that insightful. I'm closing this for now, since I'm content with looking through the raw numbers, and there possibly wouldn't be much of a benefit to include them in the visualization or focus on them too much.

**Comment by zloster** [comment]
@foliot There is №17 here: https://github.com/TechEmpower/FrameworkBenchmarks/issues/133#issue-13071709
If/when it is implemented than we will get more revealing data.
