### ISSUE TITLE
Add Benchmarks for Facebook Wangle

### ISSUE THREAD

**Issue by wiineeth** [TechEmpower/FrameworkBenchmarks#4883]
There are no benchmarks for [Facebook Wangle](https://github.com/facebook/wangle) which seems like a good project that integrates Netty + Finagle.

**Comment by nbrady-techempower** [comment]
This is already in https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks-Languages-and-Features

We rely on members of the community to submit and maintain new tests. If you're interested in doing that, check out the documentation in our wiki and open up a PR. We'll be happy to help out along the way.
