### ISSUE TITLE
Scala http4s shown as failed

### ISSUE THREAD

**Issue by sideeffffect** [TechEmpower/FrameworkBenchmarks#4885]
Scala `http4s` is always shown as `failed: fortune update`

https://tfb-status.techempower.com/results/5e176269-0aec-4c98-aab8-114eaece69cf

and is shown as `Did not complete` in the visualization

https://www.techempower.com/benchmarks/#section=test&runid=5e176269-0aec-4c98-aab8-114eaece69cf&hw=ph&test=fortune&l=zijukf-f

even though everything shows that `fortune` is passing OK

https://tfb-status.techempower.com/unzip/results.2019-06-26-03-51-02-855.zip/results/20190622150326/http4s/fortune/verification.txt

https://tfb-status.techempower.com/raw/results.2019-06-22-08-12-48-832.json

**Comment by sideeffffect** [comment]
the reason may be not `fortune`, but transaction deadlock on batch update in `updates`

I've created a PR to fix that: https://github.com/TechEmpower/FrameworkBenchmarks/pull/4886

**Comment by zloster** [comment]
Check the `raw.txt` about `fortune` test:
https://tfb-status.techempower.com/unzip/results.2019-06-26-03-51-02-855.zip/results/20190622150326/http4s/fortune/raw.txt

See that NOT a single request is successful for this test - everything is at zero. Some time ago I've opened https://github.com/TechEmpower/FrameworkBenchmarks/issues/4092. Currently it is closed but there are several problems and similar behaviour is described there. I've send a message to the mailing list requesting for more people to take a look. `spring-webflux` is having exactly the same behaviour. Take a look at this screenshot:

![Screenshot from 2019-06-11 09:48:13](https://user-images.githubusercontent.com/778924/60384716-dd916080-9a89-11e9-8364-c7d3d1d8bb53.png)

The script I've used is very simple:
```
XXX@box:~/sources$  cat stress-http.sh 
#!/bin/bash
for i in {1..100}
  do
  echo "Round $i:"
  wrk -H 'Host: 172.18.0.4' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 120 -c 512 --timeout 8 -t 2 "http://172.18.0.4:8080/fortunes"
  done
```
It is executed from the Vagrant VM development environment when a framework is started in `Debug` mode. The IP 172.18.0.4 corresponds to the Docker container running the framework. The IPs are changing so it should be inspected and adjusted before running it. This is not a good example for shell script - the Ctrl-C is tricky for example.

With this script I can observe that the framework sometimes enters a state where the connections are established but no traffic occurs as shown in the screenshot. Sometimes there are 5-15 steps from the loop without a problem. There could be one step in the loop with the problem, then again several  without. Or sometimes there are several consecutive steps manifesting the problem.

**Comment by sideeffffect** [comment]
I have no idea how to fix it on the side of `http4s`. perhaps somebody from @TechEmpower can chime in

**Comment by sideeffffect** [comment]
`http4s` seems to be working fine in

https://tfb-status.techempower.com/results/299df813-559c-47c3-91eb-96955d8f50d1
