### ISSUE TITLE
Why there is no benchmark for erlang framework?

### ISSUE THREAD

**Issue by SunnyMaximo** [TechEmpower/FrameworkBenchmarks#4914]

**Comment by nbrady-techempower** [comment]
chicagoboss was recorded in [round 18](https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=json&l=zik0z3-f)

looks like the other implementations need some work: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Erlang
Feel free to improve upon them.
