### ISSUE TITLE
Policy on OS / kernel upgrade?

### ISSUE THREAD

**Issue by rvolgers** [TechEmpower/FrameworkBenchmarks#4925]
I've looked through the various Wiki pages but couldn't find an answer, so I'm asking here.

The benchmarks are currently using Ubuntu 16.04 LTS as far as I can tell. This will still be supported until early 2021, but stopped receiving new hardware support upgrades late last year.

Is there any idea about when an OS upgrade may need to happen?

Main reason I'm asking is 20.04 LTS is likely to contain the io_uring functionality merged in Linux 5.1, while 18.04 LTS does not. It would be cool to see if it changes things significantly. If the benchmark switches to 18.04 LTS and then rides that to the end of support that could take until 2027!

This is all rather speculative and not at all urgent, just wondering what the current thinking is.

**Comment by nbrady-techempower** [comment]
Hey @rvolgers; the main test environment is on latest CentOS but the toolset and a lot of frameworks are using ubuntu docker images. We try to keep the test environment up-to-date and there's no policy on updating docker images. Open a pull request to update them, and if they pass travis, they'll get in.

**Comment by zloster** [comment]
@nbrady-techempower When a Docker container runs on a host, it uses the **host's kernel**. I.e. when we start a Ubuntu-based Docker image on a host running CentOS we get the following:

- Ubuntu userland tools compiled with the "Ubuntu" way (organisation of the configuration files, default tools for various tasks, **compilation settings** for all the tools `-О2` vs `something else`;
- All this stuff is using the Linux kernel distributed with the CentOS - mainline version, some **additional patches** applied from the maintainers of the Linux distribution, various **tweaks and compilation settings** for the kernel executables.

Here is some old writing about what could be different in a Linux kernel configuration: https://jwboyer.livejournal.com/47022.html

Given the above the documentation **should be clarified** that in fact the Citrine environment **is not** using the default Ubuntu kernel.

**Comment by zloster** [comment]
@nbrady-techempower No need for apologies. I've just wanted to make clear the separation of kernel and userland machinery that Docker brings. RedHat/CentOS kernel version numbering is not helpful for tracking the feature parity with the Linux mainline kernel.
