### ISSUE TITLE
Some suggestions for wiki clean up - Ubuntu as host operating system

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4935]
This originated here: https://github.com/TechEmpower/FrameworkBenchmarks/issues/4925

I've noticed only two mentions about "Ubuntu":

- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Environment#operating-systems
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Expected-Questions - question №20 "...physical machines running Ubuntu as a non-virtualized comparison..."

**Comment by nbrady-techempower** [comment]
Thanks zloster. I've updated those and included the kernel version in the citrine section on the first page.

**Comment by errantmind** [comment]
Is the kernel listed on the above page still accurate?
