### ISSUE TITLE
Live results interface broken

### ISSUE THREAD

**Issue by jcheron** [TechEmpower/FrameworkBenchmarks#4938]
It seems that the Live Results interface is bugged since a few days.

### OS, Browser
Linux, Windows
Chrome, Opera, Firefox, Chromium

### Expected Behavior
All the elements are selected or unselected after clicking on `Enable` or `Disable all` links

### Actual Behavior
None of the `Enable` or `Disable all` links have any effect.

### Steps to reproduce behavior
- Goto [Live results](https://www.techempower.com/benchmarks/#section=test&runid=036fcd14-bcf8-4758-863f-bacd15faf6b6)
- Click on `Show filters panel` button
- Click on `Enabled` or `Disabled all` links

### Other details and logs
The javascript console displays:

![image](https://user-images.githubusercontent.com/2511052/61585202-b98be100-ab56-11e9-8f68-412a3f83513c.png)

+ I don't know if there's a connection, but the list of the frameworks is not complete (Anyway, I can't find `Ubiquity-swoole` anymore).

**Comment by bhauer** [comment]
Thanks for the report. This one is something I'll need to fix. I'll try to take a look this coming week.

**Comment by joanhey** [comment]
Hi @jcheron 
It's normal that Ubiquity-swoole is not in the Round 18.
The round 18 use the data from this run https://tfb-status.techempower.com/results/52587667-bee1-4b9b-b34d-929b616d5e4c
As explain this comment https://github.com/TechEmpower/FrameworkBenchmarks/issues/4630#issuecomment-508233287

And it's exactly here : https://github.com/TechEmpower/FrameworkBenchmarks/tree/12b68023e5d406680af745d34b2984741bc7c198
And the last commit was in 31 May.
Ubiquity-swoole was added on 12 Jun.

**Comment by bhauer** [comment]
@jcheron I believe the issue with the filters panel when viewing a continuous run from tfb-status should be resolved with a reload.  Give it a try when you get a chance and let me know.

**Comment by jcheron** [comment]
@joanhey 
I wasn't talking about Round18, but only about the intermediate results of the runs (accessible on [tfb-status](https://tfb-status.techempower.com)).
I believe that Ubiquity-Swoole is not the only one concerned: see https://github.com/TechEmpower/FrameworkBenchmarks/issues/4943 and https://github.com/TechEmpower/FrameworkBenchmarks/issues/4941

@bhauer 
It's okay with a reload (CTRL+F5) thanks!

**Comment by pmlopes** [comment]
I observe that newly added frameworks:

* 0http
* restana

Are also missing from the CI UI results although the results are on theb`results.json`

**Comment by bhauer** [comment]
These issues should be addressed. There was a problem with the results viewer not re-initializing itself with framework metadata provided by the continuous results service.
