### ISSUE TITLE
Php make doesn't check if locale is available

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#494]
I receive a ton of these errors when trying to install the server software on my spare computer: 

    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US)

This was easily fixed for my by running `locale-gen en_US`, I'm not sure if that's something that might need to be included in the general release

**Comment by LadyMozzarella** [comment]
@hamiltont - Is this still an issue? Should we add `locale-gen en_US` if the locale is already set, but isn't already set to en_US?

**Comment by hamiltont** [comment]
Actually, let's close this for now. I expect it was my setup at the time causing this, see docker/docker#2424
