### ISSUE TITLE
Website is missing newly added test

### ISSUE THREAD

**Issue by MichalStrehovsky** [TechEmpower/FrameworkBenchmarks#4941]
Run 036fcd14-bcf8-4758-863f-bacd15faf6b6 has a newly added test "aspcore-corert-rhtx" (added in #4924) - I can see it successfuly ran in [results.json](https://tfb-status.techempower.com/raw/results.2019-07-16-05-56-48-290.json), but it's missing in [the visualization](https://www.techempower.com/benchmarks/#section=test&runid=036fcd14-bcf8-4758-863f-bacd15faf6b6&hw=ph&test=plaintext) on the website.

I would expect it to should show up for both plaintext and json.

**Comment by ifduyue** [comment]
racket too is missing from the website visualization
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Racket/racket

**Comment by jcheron** [comment]
It's probably the same issue: [Live results interface broken](https://github.com/TechEmpower/FrameworkBenchmarks/issues/4938)

**Comment by bhauer** [comment]
The viewer was not properly loading the metadata provided by the continuous runner, but it should now be fixed.  You should be able to see `aspcore-corert-rhtx` now.
