### ISSUE TITLE
Let us see results for smaller concurrency level

### ISSUE THREAD

**Issue by ostrolucky** [TechEmpower/FrameworkBenchmarks#4942]
Concurrency levels available on your website: 256, 1024, 4096, 16384. I feel these are unachievable for vast majority of websites.

<img width="876" alt="Screenshot 2019-07-21 at 21 31 01" src="https://user-images.githubusercontent.com/496233/61596056-e98ebf00-abfe-11e9-92e2-af357f91e286.png">

As a developer, I would be interested to see results with lower, more common concurrency level, let's say 8. Some frameworks will achieve a lot better latency results.

**Comment by bhauer** [comment]
High concurrency levels are a attribute specific to the Plaintext test type.  You can read more about the concurrency levels of each test type in [the test requirements](https://www.techempower.com/benchmarks/#section=code).

The Fortunes test, for example, is measured at concurrency levels ranging from 16 to 512.

![image](https://user-images.githubusercontent.com/777068/61599647-cf91b400-abdf-11e9-903e-a4899b0ddb1e.png)
