### ISSUE TITLE
kooby results are not visible from UI

### ISSUE THREAD

**Issue by jknack** [TechEmpower/FrameworkBenchmarks#4943]
Hi,

 [Kooby](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Kotlin/kooby) results are not visible from UI build #[036fcd14-bcf8-4758-863f-bacd15faf6b6](https://www.techempower.com/benchmarks/#section=test&runid=036fcd14-bcf8-4758-863f-bacd15faf6b6&hw=ph&test=fortune), but I can see them in [results.2019-07-16-05-56-48-290.json](https://tfb-status.techempower.com/raw/results.2019-07-16-05-56-48-290.json)

Thanks.

**Comment by jknack** [comment]
I checked Java frameworks and found all these are missing from [web site latest build](https://www.techempower.com/benchmarks/#section=test&runid=66ee924e-3bc2-4bd8-aaf0-2cd8443f65db&hw=ph&test=plaintext&l=xan9tr-f):

- baratine
- javalin
- quarkus
- t-io
- tapestry

**Comment by bhauer** [comment]
This should be fixed! Sorry about that. Please reload the results site to confirm.

**Comment by jknack** [comment]
Confirmed. Thank you
