### ISSUE TITLE
More Wiki cleanup

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4947]
Here they are:
1. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/About-Techempower - here the headings are with broken formatting;
1. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Support-FAQ - Here the first link is dead: "Please also see Expected Questions". "Expected Questions" is leading to "File not found";
1. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Framework-Files - at the end of the first heading ("Benchmark Config File"): "The requirements section explains the ..." is also dead link, but this time I get a error message about trying to edit the wiki;
1. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Overview - the sections: 
  https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Overview#language-readmemd
  https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Overview#framework-readmemd
  https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Codebase-Overview#framework-specific-files
  Each of them is containing a dead link.
5. https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Benchmarking-Getting-Started - the first link "If you're interested in development please visit the getting started guide for development." is leading to the home page of the wiki. The link in the https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Benchmarking-Getting-Started#linux-server-setup section is also leading to the wiki home page.

The above issues cover sthe bottom half of the wiki contents. I'll check the other part in the upcoming days.

**Comment by nbrady-techempower** [comment]
Got 'em all! Thanks as always @zloster!
