### ISSUE TITLE
subprocess.check_call + Rebar in Cowboy and Elli

### ISSUE THREAD

**Issue by ashawnbandy** [TechEmpower/FrameworkBenchmarks#495]
When run-test hits either the Cowboy or Elli test, it will either hang or time-out (depending on the version of benchmarker.py being used).  run-test calls setup_erlang.py#start(args) and successfully executes all lines up to line 9 (see commit #4219cb3441). Line 9 is apparently called but never returns.  This may be an intermittent issue but has persisted for at least the last seven days across several installations of the test harness and also appeared while @michaelhixson was testing a few weeks ago.  

 Additional facts:
1. The command being issued on line 9, "./rebar get-deps" runs successfully on the command line.
2. The code at http://pastebin.com/PptZBHFG runs without error.

**Comment by hamiltont** [comment]
Fixed in master - See [travis](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/56909686). Neither test passes, but it seems to be due to syntax errors and not anything systematic
