### ISSUE TITLE
The wiki - additional notes

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4954]
This is part 2:

- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Readme-Formats#language-readmes - `fw_depends options for the language` should be removed;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Testing-and-Debugging#travis-ci - the link `Read more about TFB and Travis-CI.` is leading to the wiki home page;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-How-To-Add-Frameworks-or-Tests#adding-a-new-test-without-the-installation-wizard - the link `Implement at least one test ` is leading to the wiki home page;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-How-To-Add-Frameworks-or-Tests#additional-information - the link `See Travis CI Tips and Tricks for more details.` is also leading to the wiki home page;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Contributing-Guide#general-guidelines - this link `See the installation guide for specifics.` should link to https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Installation-Guide
Also in the same paragraph the link `Our Vagrant scripts can set up a VM` is leading to the wiki home page;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Contributing-Guide#github-pull-request-procedure - the link `this documentation, see the about documentation page. ` should point to https://github.com/TechEmpower/FrameworkBenchmarks/wiki/About-Documentation;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Contributing-Guide#github-issue-procedure - the link `see the documentation page.` should also point to https://github.com/TechEmpower/FrameworkBenchmarks/wiki/About-Documentation;
- https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Getting-Started - the first link ` visit the getting started guide for benchmarking.` is leading to the wiki home page;
- on the same page - `3. Enable Travis-CI` - the two links a leading to the wiki home page;

This should get the wiki in a top shape.

**Comment by nbrady-techempower** [comment]
Got 'em all! Thanks again for your diligence! 

![](https://media2.giphy.com/media/MUeQeEQaDCjE4/giphy.gif?cid=790b76115d3b5d247267696c513037c0&rid=giphy.gif)
