### ISSUE TITLE
Results are not displayed on the report view?

### ISSUE THREAD

**Issue by IKende** [TechEmpower/FrameworkBenchmarks#4964]
https://tfb-status.techempower.com/results/d995c1ca-2918-4587-b668-2fc66635018a
`results.json` have `beetlex-core` framework test data, but results are not showed on the report view?

**Comment by MichalStrehovsky** [comment]
Also seen in #4943, #4941, and https://github.com/TechEmpower/FrameworkBenchmarks/issues/4938#issuecomment-514685834.

**Comment by bhauer** [comment]
That's my fault.  A recent change I made in the results site for Round 18 seems to have broken support for updated metadata for continuous runs.  I'll investigate and follow up.

**Comment by bhauer** [comment]
This should be fixed!  Sorry about that.  Please reload the results site to confirm.
