### ISSUE TITLE
GPG error when trying to install Postgres

### ISSUE THREAD

**Issue by DestyNova** [TechEmpower/FrameworkBenchmarks#4969]
### OS (Please include kernel version)
Ubuntu Linux 19.04, kernel 5.0.0-23-generic.

### Expected Behavior
Docker image is built and benchmark performed.

### Actual Behavior
Docker build aborts with:
```
techempower/postgres:latest: Step 16/35 : RUN apt-get -y update > /dev/null
techempower/postgres:latest:  ---> Running in e4228eb9068a
techempower/postgres:latest: W: GPG error: http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
techempower/postgres:latest: W: The repository 'http://apt.postgresql.org/pub/repos/apt xenial-pgdg InRelease' is not signed.  
techempower/postgres:latest: Removing intermediate container e4228eb9068a
techempower/postgres:latest:  ---> cc599e6c384f
techempower/postgres:latest: Step 17/35 : RUN apt-get -y install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" postgresql > /dev/null       
techempower/postgres:latest:  ---> Running in 10eaad76b10f
techempower/postgres:latest: E: There were unauthenticated packages and -y was used without --allow-unauthenticated                                                     
techempower/postgres:latest: Removing intermediate container 10eaad76b10f
techempower/postgres:latest: Docker build failed; terminating
```

### Steps to reproduce behavior
```
git clone https://github.com/TechEmpower/FrameworkBenchmarks.git
# last commit: b9cc153dcd1c20e78197b0191536f0d11b8ca554
cd FrameworkBenchmarks
./tfb --mode verify --test urweb
```

### Other details and logs
It seems like the `--allow-unauthenticated` option needs to be used when using `apt-get update` on the Postgres apt source.

By the way, I was trying to run the latest version of the benchmarks for Urweb and compare them against the old one, after noticing that its performance for all tests dropped by a factor of approximately  100x (!) between round 16 and round 17. Any tips on how to investigate that would be much appreciated.

**Comment by DestyNova** [comment]
I can get it to ignore the error and build with the following diff, but I'm not sure if that's the right way.

```
diff --git a/toolset/databases/postgres/postgres.dockerfile b/toolset/databases/postgres/postgres.dockerfile
index 02d1f0f8f..a31c723be 100644
--- a/toolset/databases/postgres/postgres.dockerfile
+++ b/toolset/databases/postgres/postgres.dockerfile
@@ -21,7 +21,7 @@ RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCC4CF8
 
 # install postgresql on database machine
 RUN apt-get -y update > /dev/null
-RUN apt-get -y install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" postgresql > /dev/null
+RUN apt-get -y install --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" postgresql > /dev/null
 
 ENV PG_VERSION 11
```

**Comment by nbrady-techempower** [comment]
@DestyNova I'm going to apply the fix you mentioned for now and look for a better solution. As far as the Urweb benchmarks go, there's not a lot there we can help with. I'd look at all the changes made by the people maintaining the tests and maybe reach out to any of them for help. Do you see those performance differences in the official round results we've posted?

**Comment by DestyNova** [comment]
Thanks @nbrady-techempower! Yes, the official results are affected: for example:

Round 16, "Fortunes": 323,430 responses per second
Round 17 (and 18): 2,544 rps

I had a look at the Dockerfiles for those two versions, and it seems that the Round 16 version used an old tarball from the Urweb site, but round 17 switched to the version available with `apt-get`.
Hard to imagine that this could make things over 100 times slower though :open_mouth:

**Comment by nbrady-techempower** [comment]
@DestyNova Understood; sadly there's not much I can do to help with that. I would try to dig through the logs, maybe there were a lot of errors. (https://tfb-logs.techempower.com) The round 18 logs will be posted this week. Otherwise, your best bet would be to reach out to some of the maintainers and see if they can help. If it's consistent in all the runs on https://tfb-status.techempower.com then my guess is there was some change that introduced the regression and it wasn't just a one off.

**Comment by nbrady-techempower** [comment]
I'm going to close this issue, but if you end up with a little more information and want to ping some of the Urweb folks, feel free to open a new issue to track.

**Comment by DestyNova** [comment]
Cheers @nbrady-techempower, I brought it up on the [Ur/web mailing list](http://www.impredicative.com/pipermail/ur/2019-July/002850.html) but it's not very active there. I was thinking maybe a change to database query caching or something like that may have some influence, but my knowledge is insufficient (about Ur/web and the test harness) to intelligently investigate. Will check out those logs though :smiley:
