### ISSUE TITLE
Cannot run the test

### ISSUE THREAD

**Issue by huangzhhui** [TechEmpower/FrameworkBenchmarks#4975]
### OS (Please include kernel version)
`Linux hyperf-001 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Expected Behavior
Export the result

### Actual Behavior
```
Traceback (most recent call last):
  File "/FrameworkBenchmarks/toolset/run-tests.py", line 6, in <module>
    from toolset.benchmark.benchmarker import Benchmarker
  File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 2, in <module>
    from toolset.utils.docker_helper import DockerHelper
  File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 14, in <module>
    from psutil import virtual_memory
ImportError: No module named psutil
```

### Steps to reproduce behavior
Follow the README of the project, 
1. Clone the project
2. `./tfb --mode verify --test gemini`
3. Execute the command that tfb outputs, `docker run -i -t --rm --network tfb -v /private/var/run/docker.sock:/var/run/docker.sock -v /root/FrameworkBenchmarks:/FrameworkBenchmarks techempower/tfb --mode verify --test gemini`

### Other details and logs

**Comment by nbrady-techempower** [comment]
You most likely don't have the latest version of the toolset. Please pull from master and try again. Re-open if the issue continues.

**Comment by huangzhhui** [comment]
```
[root@hyperf-001 FrameworkBenchmarks]# git remote add upstream https://github.com/TechEmpower/FrameworkBenchmarks
[root@hyperf-001 FrameworkBenchmarks]# git fetch upstream
From https://github.com/TechEmpower/FrameworkBenchmarks
 * [new branch]      master     -> upstream/master
[root@hyperf-001 FrameworkBenchmarks]# git merge upstream/master
Already up-to-date.
[root@hyperf-001 FrameworkBenchmarks]# ./tfb --mode verify --test gemini
docker run -i -t --rm --network tfb -v /private/var/run/docker.sock:/var/run/docker.sock -v /root/FrameworkBenchmarks:/FrameworkBenchmarks techempower/tfb --mode verify --test gemini
[root@hyperf-001 FrameworkBenchmarks]# docker run -i -t --rm --network tfb -v /private/var/run/docker.sock:/var/run/docker.sock -v /root/FrameworkBenchmarks:/FrameworkBenchmarks techempower/tfb --mode verify --test gemini
Traceback (most recent call last):
  File "/FrameworkBenchmarks/toolset/run-tests.py", line 6, in <module>
    from toolset.benchmark.benchmarker import Benchmarker
  File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 2, in <module>
    from toolset.utils.docker_helper import DockerHelper
  File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 14, in <module>
    from psutil import virtual_memory
ImportError: No module named psutil
[root@hyperf-001 FrameworkBenchmarks]# 
```

**Comment by huangzhhui** [comment]
@nbrady-techempower This problem still exists, please re-open this issue.

**Comment by nbrady-techempower** [comment]
@huangzhhui Is this the first time you've tried setting up the benchmarks on that machine? If this is a VM, i'd start from scratch if it's not the first time. We made some changes to the toolset where the techempower/tfb image is being built locally instead of pulled from dockerhub and I think yours is using an old image. First try `docker image rm techempower/tfb:latest` and running again but if it's a VM i'd suggest just wiping and starting again.
