### ISSUE TITLE
Tfb --mode debug never stop

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#4982]
When you are in mode debug, with Ctrl + c you can close it.

But actually never close. Almost when testing a php framework.

**Comment by nbrady-techempower** [comment]
What do you mean by "never closes." Is there a docker container still running? I just tried with `tfb --mode debug --test php` and it worked fine. Is there a framework you were using that I can recreate with?

**Comment by joanhey** [comment]
Sorry my bad.
After update the system, the terminal had a keyboard shorcut to `Ctrl + c`

It's working correct :+1:
