### ISSUE TITLE
Reset database schema/data between frameworks

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#506]
Presently, between each framework's tests we restart the database servers.

For purity, this process should be extended to:
- Drop all tables / database as a whole.
- Recreate database / create tables.
- Repopulate tables with test data.

In other words, give each framework a database that can be used as a playground, allowing for frameworks to make enhancements to the schema as needed (within reason; we don't want to see tricks designed to defeat the purposes of the tests).  See #490.

Are there additional inter-framework environment cleanups that are necessary?  In #404, @pbooth had indicated that we should ensure all sockets are properly closed out.

**Comment by nbrady-techempower** [comment]
Woo, this is almost done! And in the "In Progress" section of the roadmap: https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
