### ISSUE TITLE
Ubiquity-workerman (incredible) results in last run

### ISSUE THREAD

**Issue by jcheron** [TechEmpower/FrameworkBenchmarks#5118]
I wish that were true,
The `Ubiquity-workerman` couple would be the fastest on the Multiple queries test (see [42f65a64-69b2-400d-b24e-20ecec9848bc](https://www.techempower.com/benchmarks/#section=test&runid=42f65a64-69b2-400d-b24e-20ecec9848bc&hw=ph&test=query)).
Ubiquity is fast, and so is Workerman. But it seems more than unlikely that the workerman-raw version will be slower than the one associated with a Framework (even if Ubiquity uses Mysqli, and workerman PDO), and this is not the only point of comparison that can raise suspicion...

I didn't see anything suspicious in the [query raw file](https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/ubiquity-workerman/query/raw.txt).
The [logs](https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/ubiquity-workerman/run/ubiquity-workerman.log) just indicate an error that occurred on 1 worker

I'll try to investigate this on my side...

**Comment by joanhey** [comment]
Well Kumbia-Workerman will be faster :) jeje

**Comment by joanhey** [comment]
We will check #5122 results in the next run in the plain Workerma with Mysqli.
If the results are good, will benefit any framework using Mysqli.

**Comment by jcheron** [comment]
So there was a problem in the **Ubiquity-workerman** tests, not revealed by the initial test phase, nor by the logs in the last run.
A good part of the Db queries were not executed, as soon as the concurrency level increased.

To confirm that, I made a script checking that the number of Db queries executed, and that the number of rows read on the server side corresponds to the executed code, at a given concurrency level.
In principle:
- I store the initial values on the DB side.
- I clear the cache of requests.
- I run a test (ab or wrk) with `xx` requests and a certain level of concurrent access.
- I measure the values again and compare the difference with an expected `yy` number.

For Mysql, my script looks like this:
```php
class QueriesCheck {
	/**
	 * @var Database
	 */
	private $db;
	public function __construct($dbOffset='default'){
		$this->db=Database::start($dbOffset);
	}
	public function run($url,$concurrency=512,$count=15000,$expectedQueries=15000,$expectedRows=15000):void{
		$queries=$this->getQueries();
		$rows=$this->getRows();
		$this->resetCache();
		
		\passthru("ab -c $concurrency -n $count $url");
		
		$queries=$this->getQueries()-$queries;
		$rows=$this->getRows()-$rows;
		$message="queries: $queries/$expectedQueries, rows: $rows/$expectedRows";
		if($rows<$expectedRows || $queries<$expectedQueries){
			throw new \RuntimeException("Problem: ".$message);
		}
		echo $message;
	}
	
	public function getQueries():int{
		return $this->db->queryColumn("Show session status like 'Queries';",1);
	}
	
	public function getRows():int{
		return $this->db->queryColumn("show session status like 'Innodb_rows_read';",1);
	}
	
	public function resetCache():void{
		$this->db->query('RESET QUERY CACHE;');
	}
}
(new QueriesCheck())->run($argv[1],$argv[2]??512,$argv[3]??15000,$argv[4]??15000,$argv[5]??15000);
```
It would be nice if Techempower had a Python equivalent for checking our tests.
I'm not sure that my inglorious test in the last run will raise any suspicion about the results of the runs in the future.
Such a verification (as I have not seen anywhere in the existing code) would give even more credibility to our results.

**Comment by joanhey** [comment]
It's difficult as the benchmark is by time, but it can be done

**Comment by joanhey** [comment]
I find more information, that normally the bench don't check.

Workerman Mysql
https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/workerman/db/raw.txt
```
---------------------------------------------------------
 Concurrency: 512 for db
 wrk -H 'Host: 10.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 "http://10.0.0.1:8080/db"
---------------------------------------------------------
Running 15s test @ http://10.0.0.1:8080/db
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.04ms    1.00ms  25.67ms   68.82%
    Req/Sec     8.94k   789.74    13.83k    70.08%
  Latency Distribution
     50%    1.92ms
     75%    2.61ms
     90%    3.36ms
     99%    4.94ms
  3758506 requests in 15.10s, 676.65MB read
Requests/sec: 248912.94
Transfer/sec:     44.81MB
STARTTIME 1570333962
ENDTIME 1570333977
```

Ubiquity-workerman with Mysqli
https://tfb-status.techempower.com/unzip/results.2019-09-27-18-21-14-704.zip/results/20190923214828/ubiquity-workerman/db/raw.txt
```
---------------------------------------------------------
 Concurrency: 512 for db
 wrk -H 'Host: 10.0.0.1' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 "http://10.0.0.1:8080/WorkerDb"
---------------------------------------------------------
Running 15s test @ http://10.0.0.1:8080/WorkerDb
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    20.02ms   28.53ms 114.31ms   81.56%
    Req/Sec     3.06k   518.41     5.53k    69.69%
  Latency Distribution
     50%    3.35ms
     75%   32.29ms
     90%   70.14ms
     99%  100.32ms
  1283671 requests in 15.10s, 229.88MB read
  Socket errors: connect 0, read 1283659, write 0, timeout 0
Requests/sec:  85012.34
Transfer/sec:     15.22MB
STARTTIME 1569595253
ENDTIME 1569595268
```

**The sockets errors are never show like errors.**

### Comparison db with 512 concurrent. 

| Wrk | Ubiquity-Workerman | Workerman | 
----- |  ------: | -------: |
Socket errors | read 1283659 | 0 | 
Mb read |  229.88 | 676.65 | 
Requests/sec | 85012.34 | 248912.94

### What we see:
![Screenshot_20191008114135](https://user-images.githubusercontent.com/249085/66385470-d4852900-e9c0-11e9-9e22-d06aaa8d8226.png)

https://www.techempower.com/benchmarks/#section=test&runid=42f65a64-69b2-400d-b24e-20ecec9848bc&hw=ph&test=db&p=zik0zj-zik0zj-zik0zj-zik0zj-d

The results are completely different from wrk and what we see.

**Comment by jcheron** [comment]
On the run of the 2019-09-23 where Ubiquity-workerman generated socket errors,
see https://tfb-status.techempower.com/unzip/results.2019-09-27-18-21-14-704.zip/results/20190923214828/ubiquity-workerman/query/raw.txt

The results showed that these errors were present:

![image](https://user-images.githubusercontent.com/2511052/66392514-5892dd00-e9d0-11e9-8b14-e44f5b7a7739.png)

**Comment by jcheron** [comment]
> It's difficult as the benchmark is by time, but it can be done

I'm not talking about doing this check during the benchmark, but beforehand, when using the `verify` mode of the `tfb` script:
```
./tfb --mode verify --test XFramework
```
In the `verify` mode,  we could integrate the checking of the actual number of database queries performed:
We make an `ab` with `10,000` requests, at the desired concurrency level:
```
ab -c 512 -n 10000 $url
```
We then check that the number of queries and the number of lines read from the DB is at least `20*10,000` if the test is multiple queries (`/query/20`).
This is what my php script does.

**Comment by joanhey** [comment]
The visualize only show the >200 errors, never the socket errors.
In the table you see the errors from php:
https://tfb-status.techempower.com/unzip/results.2019-09-27-18-21-14-704.zip/results/20190923214828/ubiquity-workerman/run/ubiquity-workerman.log

If show the socket errors it will be always present for any framework.

I hope that in will be present the socket errors, without errors from the language.

**Comment by jcheron** [comment]
You have the wrong Run, between your table (run of 2019-09-23)
![image](https://user-images.githubusercontent.com/2511052/66402898-f5ac4080-e9e5-11e9-8218-08a86a04224d.png)

And the results table you showed (run of 2019-10-01)

The results of the 2019-09-23 run are in line with the expectations:
![image](https://user-images.githubusercontent.com/2511052/66403164-64899980-e9e6-11e9-88c2-851608047fb8.png)

And this is also the case for the 2019-10-01 run;
**The results are about the same between wrk and what we can see**

**Comment by joanhey** [comment]
Yes, my fault.  (Monday !!)
