### ISSUE TITLE
Why is peachpie categorized as php ?

### ISSUE THREAD

**Issue by waghanza** [TechEmpower/FrameworkBenchmarks#5175]
Hi,

I can see that https://github.com/peachpiecompiler/peachpie is in folder **PHP** in https://github.com/TechEmpower/FrameworkBenchmarks/blob/b4064c3a66de31d368af600b5208f4ba68d444da/frameworks/PHP/peachpie/Server/Program.cs#L1

Should it not be in `CSharp` folder ?

Regards,

**Comment by nbrady-techempower** [comment]
We generally categorize frameworks by what language the test implementations are written in, even if they compile to another language: https://github.com/TechEmpower/FrameworkBenchmarks/blob/b4064c3a66de31d368af600b5208f4ba68d444da/frameworks/PHP/peachpie/Website/fortune.php

This is why TypeScript has its own folder or why es4x is in JavaScript, etc.

**Comment by waghanza** [comment]
Yo sou then that `peachpie` should be in `CSharp` folder, then

**Comment by nbrady-techempower** [comment]
We categorize frameworks by what language the test implementations are written in.

The test implementations for peachpie are written in PHP

Please see all the test implementations here: 

https://github.com/TechEmpower/FrameworkBenchmarks/tree/b4064c3a66de31d368af600b5208f4ba68d444da/frameworks/PHP/peachpie/Website

The are all written in PHP

**Comment by waghanza** [comment]
I see there is a mix of languages :stuck_out_tongue:

**Comment by joanhey** [comment]
https://www.peachpie.io/
