### ISSUE TITLE
PHP frameworks with problems

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#5193]
PHP/hhvm is broken. Now it's disabled from tests.

Phpixie no way to configure persistent connections.

~CakePHP fail the fortunes test after update the version.~

~Codeigniter has disabled persistent connections (memory leak #4493, #4492) use mysqli by default.~

**Comment by jcheron** [comment]
In [last Travis run](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/606443372?utm_source=github_status&utm_medium=notification):
- **php-ngx-async** [Update test](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/606443463#L2571)
- **php-pgsql-raw** [Update test](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/606443461#L2220)
- **symfony** [Update test](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/606443462#L2904)
- **imi** [Update test](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/606443464#L2199)

**Comment by telmodias** [comment]
I would like to leave the suggestion to update the test version of Codeigniter, which according to https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/codeigniter is 2.1.3 , which is very outdated, being the latest stable 3.1.11, and being v4 current in rc.3 (specifically intended for use with PHP7).

**Comment by joanhey** [comment]
The bench use Codeigniter 3.1.10
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/codeigniter/composer.json

But the readme need the changes.

The high error rate it's because don't use persistent db connections, because when use it have a memory leak. #4493 #4492

**Comment by joanhey** [comment]
Updated to codeigniter 3.1.11 
and the readme.

**Comment by joanhey** [comment]
We are now with PHP8
