### ISSUE TITLE
Errors in PHP tests

### ISSUE THREAD

**Issue by dracony** [TechEmpower/FrameworkBenchmarks#520]
Previews show an alarming amoun of errors for most PHP frameworks:
http://www.techempower.com/benchmarks/previews/round7/#section=data-r7&hw=i7&test=plaintext&l=sg

Perhaps there is something wrong with PHP on the server?

**Comment by LadyMozzarella** [comment]
Update: PHP Errors still present in master branch as of 2015 03 03
Results summary (updated): [Travis PHP Test Build](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/builds/52964642) (Run from commit [#f9d9df177b35316e6227957c7a93fdaff36ed8b1](https://github.com/LadyMozzarella/FrameworkBenchmarks/commit/f9d9df177b35316e6227957c7a93fdaff36ed8b1))

Failing PHP Frameworks (specific tests failing listed below) Currently on Master:
* laravel
  * 'laravel-raw':
    * All tests pass/warn on master, locally.
    * Doesn't launch on master according to Travis CI (looks like configuration issue). Error: 
    ERROR:root:[03-Mar-2015 23:10:29] ERROR: unable to bind listening socket for address '127.0.0.1:9001': Address already in use (98)
  [03-Mar-2015 23:10:29] ERROR: FPM initialization failed
* phalcon: 
  * 'php-phalcon-mongodb':
    * All tests fail on master, locally.
    * All fail on master according to Travis CI. 
    * Fix potentially (would need to verify again) within [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (I believe this one is only fixed locally, Failing within Travis for this PR). 
* phpixie:
  * 'php-phpixie': 
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * Fix potentially within [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 
* pimf:
  * 'pimf': 
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * Fix potentially within [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 
  * 'pimf-raw': 
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * Fix potentially within [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 
* silex:
  * 'silex': 
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * All tests warn with [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 
  * 'silex-raw': [Issue #720: Validation Failure – silex-raw](https://github.com/TechEmpower/FrameworkBenchmarks/issues/720)
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * Some tests pass with [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). Passing in PR: plaintext, json. Failing in PR: fortune, db, update, query
* silex-orm:
  * 'silex-orm': 
    * Doesn't launch on master, locally.
    * Doesn't launch on master according to Travis CI. 
    * Some tests pass with [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). Passing in PR: json. Failing in PR: db, query
* php-zend-framework: 
  * 'ZendFramework': 
    * Doesn't launch on master, locally
    * Doesn't launch on master according to Travis CI. 
    * Fix potentially within [Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 
* php-zend-framework1: 
  * 'ZendFramework1': 
    * Doesn't launch on master, locally
    * Doesn't launch on master according to Travis CI. 
    * Fix potentially within [ Pull Request #1314](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1314) (Travis shows as passing on this PR). 

Once PR #1314 gets merged (or if someone could branch off/merge in removeBashProfile), 'silex-raw' and 'silex-orm' could use some assistance with their db tests (db, query, and update). I believe that's all that really needs work right now for PHP. If we could get 'php-phalcon-mongodb' passing Travis that would be cool, too. 'laravel-raw' can also use come TLC.

**Comment by LadyMozzarella** [comment]
Because there are only a handful of PHP tests now failing, I am going to close this issue in favor of raising errors for individual PHP tests.

**Comment by gerardroche** [comment]
The R10 branch says that the zend framework's failed? Someone please tell me this isn't the case. I [worked](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1148) on these and they were working. 

R10 travis build https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/56583930
