### ISSUE TITLE
No sticky socket session in NodeJS frameworks

### ISSUE THREAD

**Issue by corporatepiyush** [TechEmpower/FrameworkBenchmarks#5204]
NodeJS frameworks do not use sticky socket sessions which will drastically degrade the request handling capabilities as it does not divide the socket handling and HTTP parsing across multi-core CPUs

This might help - https://github.com/uqee/sticky-cluster

**Comment by nbrady-techempower** [comment]
The repo you're linking looks like it's pre-production versioning and last updated 3 years ago. You can open a PR trying this out in one of the frameworks if you'd like, but otherwise I don't think this is an issue.
