### ISSUE TITLE
Add mention about https://tfb-logs.techempower.com/ in the documentation

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#5212]
AFAIR https://tfb-logs.techempower.com/ was the place to check for the logs from the official rounds. I'm not able to find mentions about it in the documentation.
I've managed to find only these two references:
1. https://github.com/TechEmpower/FrameworkBenchmarks/issues/3846#issue-330416240
2. https://github.com/TechEmpower/FrameworkBenchmarks/issues/2646#issue-218682513

Currently https://tfb-logs.techempower.com/ is displaying the contents of the main website of Techempower.

**Comment by nbrady-techempower** [comment]
Hey @zloster! This is just a temporary placeholder. We're moving all the logs to a different server. I'll let you know when it's back online.

**Comment by nbrady-techempower** [comment]
In the meantime, the logs from citrine are still available. This was round 18: https://tfb-status.techempower.com/results/9ce91254-04d7-4455-9742-aa6a1f673e86

**Comment by zloster** [comment]
Thank you for the clarification.
I've edited the title. Maybe adding a mention here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/About-Benchmarks-Project will be helpful. Also it seems this page needs formatting fix.

**Comment by bhauer** [comment]
Sorry, accidental close.  I'll check in on this with the people on our side.

**Comment by nbrady-techempower** [comment]
I've added a note about this here https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Results-Website
