### ISSUE TITLE
Increase SetMaxOpenConns in Go?

### ISSUE THREAD

**Issue by createconnect** [TechEmpower/FrameworkBenchmarks#5272]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/104c9695a61053df491bf8f0f6a856f2bb965e4f/frameworks/Go/fasthttp/src/server-mysql/server.go#L44

What will happen if we increase SetMaxOpenConns to 90?

**Comment by zloster** [comment]
Hi @createconnect! Probably you will get more feedback if you [track some of the committers](https://github.com/TechEmpower/FrameworkBenchmarks/commits/master/frameworks/Go/fasthttp).  [The blame (line history)](https://github.com/TechEmpower/FrameworkBenchmarks/blame/104c9695a61053df491bf8f0f6a856f2bb965e4f/frameworks/Go/fasthttp/src/server-mysql/server.go#L44) shows that this comes from `valyala` - the author of the `Go/fasthttp` framework. Given the solid results of `Go/fasthttp` probably this setting is investigated in the past. Maybe the current state have changed and could be reconsidered.

**Comment by nbrady-techempower** [comment]
I'll ping @valyala but I'm sure what @zloster is saying is accurate. Going to close this for now.
