### ISSUE TITLE
ulib incorrectly hardcodes Content-Length in fortune benchmark

### ISSUE THREAD

**Issue by xfix** [TechEmpower/FrameworkBenchmarks#5286]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/ulib/src/fortune.h

While it is currently a subject of discussion (see https://github.com/TechEmpower/FrameworkBenchmarks/issues/5201), I feel like what ulib does is clearly incorrect. Specifically, it hardcodes the `1227` value in Content-Length.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C%2B%2B/ulib/src/fortune.h#L176

Meanwhile, the requirements (https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#fortunes) say this:

> The list data structure must be a dynamic-size or equivalent and should not be dimensioned using foreknowledge of the row-count of the database table.

If you cannot assume the table size, I don't think you can assume how many bytes are stored in a table either.

Unfortunately, I cannot really fix that myself, because the platform looks ridiculous to code in (`U_MULTICHAR_CONSTANT64`, seriously?).

**Comment by nbrady-techempower** [comment]
I agree. @stefanocasazza can you update this please.

**Comment by nbrady-techempower** [comment]
This has been updated somewhat satisfactory for now. I'm going to work on a better fortunes verification process to test hardcoded content-length when I get some time.
