### ISSUE TITLE
The framework "ffead-cpp" always build failed but it cost much time than 1 hour

### ISSUE THREAD

**Issue by wangkaish** [TechEmpower/FrameworkBenchmarks#5299]
See the recent build log [https://tfb-status.techempower.com/unzip/results.2019-12-11-13-12-34-716.zip/results/20191207065330/ffead-cpp/build/ffead-cpp.log](https://tfb-status.techempower.com/unzip/results.2019-12-11-13-12-34-716.zip/results/20191207065330/ffead-cpp/build/ffead-cpp.log)

**Comment by nbrady-techempower** [comment]
I've addressed that here #5300 
Thanks!
