### ISSUE TITLE
Need clarification for the multi-query test

### ISSUE THREAD

**Issue by snluu** [TechEmpower/FrameworkBenchmarks#5368]
For the multi-query test, is the expectation that:
a) The application only fires off the next DB query **after** the previous query returns, or
b) The application is free to fire off the queries in parallel?

Looking through the different frameworks, I noticed that some implement “a” (even though they can do “b”), and some implement “b”. Frameworks that go with the “b” approach definitely has the better competitive edge. 

For example: https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=query&l=zdhf5r-f

Crystal outperforms Dart in the single-query test, but performs significantly slower in the multi-query test because Crystal implements “a” while Dart implements “b”.

**Comment by nbrady-techempower** [comment]
Yes, this is allowed.

https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries

> This test is designed to exercise multiple queries with each resulting row selected individually. It is not acceptable to execute multiple SELECTs within a single complex query. It is not acceptable to retrieve all required rows using a SELECT ... WHERE id IN (...) clause. **_However, note General Requirement #7 which permits pipelining of network traffic between the application and database._**

**Comment by snluu** [comment]
@nbrady-techempower Thanks for the clarification, Nate! I will work on a patch for the Crystal frameworks to run the queries concurrently. Feel free to close this task, or we can close it once my patch is marged.

**Comment by snluu** [comment]
PR here: #5370
