### ISSUE TITLE
Some frameworks don't show up on website

### ISSUE THREAD

**Issue by Fenny** [TechEmpower/FrameworkBenchmarks#5387]
Hi, some frameworks do not show up when I try to visualize the test data:

https://www.techempower.com/benchmarks/#section=test
https://tfb-status.techempower.com/raw/results.2020-01-10-08-20-11-093.json

`cinatra`, `fiber`, `chubbajs` were recently added and are not visible, but are successfully tested in the json file.

`Note: This results web site can only render results for the frameworks it knows about by way of the metadata available for the currently-public Round. Therefore, results for frameworks that are not known by the metadata will not be visible.`

Do we have to wait until a public round before we can see the results on the website?
Or could we add these frameworks to the metadata manually?

Thanks!

**Comment by nbrady-techempower** [comment]
When you copy and paste just the json results into that `section=test` then you won't see new frameworks. However, if you click the `visualize` link when a run has completed from here https://tfb-status.techempower.com/ you should see them. We're working on a number of updates right now to the results website and this is one of the things being addressed.

**Comment by Fenny** [comment]
Thank you!
