### ISSUE TITLE
Yesod results not showing up

### ISSUE THREAD

**Issue by Siltaar** [TechEmpower/FrameworkBenchmarks#5395]
Hi,

I filtered away "yesod" framework but its results are not shown here : 

Nothing indicates that they are missing.

### OS (Please include kernel version)

GNU+Linux Debian Firefox nightly 73

### Expected Behavior

Results of "yesod" framework.

### Actual Behavior

No results displayed for this framework, even when there is only this one selected.
I can load results for a lot of other frameworks.

### Steps to reproduce behavior

Load this page:
https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=fortune&l=zijzcv-f&f=z8kflr-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-e7

**Comment by nbrady-techempower** [comment]
yesod was in a failed state during the Round 18 runs: https://tfb-logs.techempower.com/Round%2018/citrine-results-v1-raw.json

It has been updated since and you can see new visualized results from https://tfb-status.techempower.com

**Comment by Siltaar** [comment]
I just checked but Yesod results are still missing here : 
https://tfb-status.techempower.com/raw/results.2020-01-10-08-20-11-093.json

**Comment by nbrady-techempower** [comment]
@Siltaar That run is still in progress. Yesod is one of the last to be tested. The run before it shows results.

**Comment by Siltaar** [comment]
Well it states : 493/641 frameworks tested for this file, and 642/642 for the previous. I can read results from the previous file:
https://www.techempower.com/benchmarks/#section=test&runid=f317f963-c164-4bd2-9240-9dd9084a0cea
