### ISSUE TITLE
Suggested Frameworks

### ISSUE THREAD

**Issue by mohsenomidi** [TechEmpower/FrameworkBenchmarks#5416]
Hi, 

I would like to ask you to add the [Pistache, An elegant C++ REST framework](https://github.com/oktal/pistache) as Framework, in the test result ranking. 

Regards.

**Comment by nbrady-techempower** [comment]
I've added it here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks-Languages-and-Features

But we would need someone from the community to submit a PR for it. You're more than welcome to.

**Comment by mohsenomidi** [comment]
Thanks, i want to add the point, the Pistache should be under C++ category, it is not C#

Do you have any instructions or manual that describe how to add it as a PR, i mean the development structure.. or how to add new library and what should be develop..
Thanks

**Comment by nbrady-techempower** [comment]
Oh, sorry, I'll fix that. Everything you should need to add a framework is in the wiki https://github.com/TechEmpower/FrameworkBenchmarks/wiki Feel free to open a PR once you're close and we can get you the rest of the way
