### ISSUE TITLE
some jooby results are not visible from latest build

### ISSUE THREAD

**Issue by jknack** [TechEmpower/FrameworkBenchmarks#5440]
We lost jooby-netty/jooby-pgclient tests from latest build: https://www.techempower.com/benchmarks/#section=test&runid=8721f3a4-7b13-4703-9cd8-91b6779668c2&hw=ph&test=fortune&l=xan9tr-1r

They were present in previous build.

**Comment by nbrady-techempower** [comment]
The logs from that build show they had issues starting up https://tfb-status.techempower.com/unzip/results.2020-01-26-14-10-27-480.zip/results/20200122202821

**Comment by jknack** [comment]
sorry, my bad. I pushed a fix: https://github.com/TechEmpower/FrameworkBenchmarks/pull/5441
