### ISSUE TITLE
Consider using HOSTS file for machine roles rather than configuration rewriting

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#545]
Presently, the toolset employs a bit of simple trickery to search configuration files for the word _localhost_ and replace that with the name of the database server provided to the benchmarker as a command line argument.

Trouble is, unless each framework's setup.py is diligent, nothing ever resets the configuration back to _localhost_ when the test completes and it's very easy for deployment-specific configurations to be committed to Git.

Fundamentally, the approach seems untenable.

I'd like to consider requiring that environments rely on three entries in the HOSTS file(s) used by the machines to resolve the three machine roles.  In our own environment, we have used the prefix "tfb" (techempower framework benchmarks) and we have three machine names:
- _tfbapp_ for the web/application server role.
- _tfbdata_ for the database server role.
- _tfbload_ for the load-generator role.

If we adopted these names for all installations of the suite, expecting that any installation used HOSTS (or an actual DNS server properly configured, although that would be entirely optional) to resolve to IPs, we could avoid the configuration rewriting trickery.

E.g., a three-machine configuration

```
# techempower framework benchmarks server roles
192.168.0.1   tfbload
192.168.0.2   tfbapp
192.168.0.3   tfbdata
```

Or a configuration using a single machine for load and data (as we did in previous rounds)

```
# techempower framework benchmarks server roles
192.168.0.1   tfbload
192.168.0.2   tfbapp
192.168.0.1   tfbdata
```

**Comment by msmith-techempower** [comment]
One of the issues facing contributors and we maintainers alike is that it is hard to debug issues with passing the $DBHOST variable (and others) around correctly. Most tests require the use of sed for updating config/source files to have the correct IP address, and very often issues arise by contributors naively using "127.0.0.1" in their code. This works on Travis-CI, we see the green check mark, do a cursory code review, but often merge in as-is only to find out that these are completely broken in our production environment.

SO, we should go through out various scripts and update everything to use hostnames. I can see the following needing to happen:

    Update the --install scripts to set the proper IP addresses on the hostnames on each machine.
    Remove all the calls to sed across all tests (big work)
    Alter all the files that sed used to update to instead use the hostnames
    Remove $DBHOST env variable (have tests that use it at the command line use the hostname instead)

**Comment by nbrady-techempower** [comment]
Looks like there isn't much discussion left surrounding this? Seems like the right thing to do. Moving it to the roadmap: https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
