### ISSUE TITLE
🤔 Benchmark stuck?

### ISSUE THREAD

**Issue by Fenny** [TechEmpower/FrameworkBenchmarks#5464]
https://tfb-status.techempower.com/results/3143715b-1b99-4b58-915e-5944504b8f07

Has been hanging on `607/645` for 3 days now, could it be that something is wrong/stuck?

**Comment by michaelhixson** [comment]
We had a power outage that interrupted that run.  I started a new run a few hours ago today.

**Comment by joanhey** [comment]
The new run too.

21/645 frameworks tested

elapsed time ~41 hours
estimated remaining time ~1,229 hours
