### ISSUE TITLE
Bad results in last run

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#5484]
[Last run](https://www.techempower.com/benchmarks/#section=test&runid=48e28547-3d66-42e2-9a61-11b312e6e173) vs [previous run](https://www.techempower.com/benchmarks/#section=test&runid=350f0783-cc9b-4259-9831-28987799782a)

Almost all frameworks have a big drop in req/s, specially java, but also: php, js, ....

Any change in Citrine ?

Or any information that justify that drop.

Thank you

**Comment by nbrady-techempower** [comment]
Interesting. One of the ports on our switch died after the power outage so we had to change ports, but that shouldn't be the "reason." If there is a reason. I'll poke around and see what I can find.

**Comment by nbrady-techempower** [comment]
We're not 💯 about what happened here, but after some tests a reboot seems to have solved the problem. We're starting a new run now.

![Have you tried turning it off and back on again?](https://media2.giphy.com/media/F7yLXA5fJ5sLC/200.webp?cid=790b76119580cedb8545db76bac353cacc2f847c13a151a4&rid=200.webp)
