### ISSUE TITLE
Doubt about some benchmark results

### ISSUE THREAD

**Issue by panjf2000** [TechEmpower/FrameworkBenchmarks#5498]
Hi,
I've check out some benchmark results on [Continuous Benchmarking results](https://tfb-status.techempower.com/) and it turned out that [gnet](https://github.com/panjf2000/gnet) got an extremely low performance, run id: [79d56671-150b-4653-9513-337cade8b1e1](https://www.techempower.com/benchmarks/#section=test&runid=79d56671-150b-4653-9513-337cade8b1e1&hw=ph&test=plaintext&l=zijocf-1r), which confused me a lot because it is way different from my own benchmarks of [gnet](https://github.com/panjf2000/gnet): https://github.com/panjf2000/gnet_benchmarks and I have no idea why [gnet](https://github.com/panjf2000/gnet) got a benchmark result that low on TechEmpower.

I want to find out the reason about it, so is there any chance that I can see some logs/outputs of the HTTP plaintext benchmarks? Or Can I get some benchmark configurations of 『TechEmpower Framework Benchmarks』? like the number of concurrent connections, benchmark duration, etc.

There must be a root cause that reduces the performance of [gnet](https://github.com/panjf2000/gnet).

**Comment by nbrady-techempower** [comment]
Logs are available from the detail view page https://tfb-status.techempower.com/results/79d56671-150b-4653-9513-337cade8b1e1 Click on **results.zip (browse)**

Environment details are available in the Wiki https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Environment

A quick look at your benchmarks looks like you're using a single machine and hitting localhost to benchmark. This won't come close to mirroring our 3-machine testing environment.

Hope you find what you're looking for, but we can't help results that don't match other benchmarks unless the environments are identical. Good luck and let us know if you need any other info.
