### ISSUE TITLE
Actual run stuck !!

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#5509]
https://tfb-status.techempower.com/results/460201b3-af12-4f5e-80cd-517c6747fd8b

4/649 frameworks tested

elapsed time ~2 hours
estimated remaining time ~360 hours

**Comment by michaelhixson** [comment]
We've been having issues with the client machine's Ethernet connection.  They looked like hardware issues at first (with either the switch or the client network card), but updating the driver for the card seemed to fix things.  We applied the same update to all three machines and started another run.
