### ISSUE TITLE
[Suggested Framework] NestJS

### ISSUE THREAD

**Issue by jchook** [TechEmpower/FrameworkBenchmarks#5520]
[NestJS Homepage](https://nestjs.com/) and [GitHub](https://github.com/nestjs/nest).

> A progressive Node.js framework for building efficient, reliable and scalable server-side applications.

Some reasons why I think it makes a good candidate:

- Well funded
- Already "used by" 20k+ GitHub projects
- Unique approach to routing and code organization (for the node ecosystem)
- Claims efficiency, reliablity, and scalability

**Comment by nbrady-techempower** [comment]
We already have nestJS implementations. Check them out [here](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/TypeScript/nest) and feel free to contribute.
