### ISSUE TITLE
Is the rank of swoole using swoole-server.php or swoole-server-noasync.php in FrameworkBenchmarks/frameworks/PHP/swoole?

### ISSUE THREAD

**Issue by uniqss** [TechEmpower/FrameworkBenchmarks#5563]
### OS (Please include kernel version)
Any
### Expected Behavior
In FrameworkBenchmarks/frameworks/PHP/swoole there is a swoole-server.php and a swoole-server-noasync.php. What's the difference between them?  Is the rank of  https://www.techempower.com/benchmarks/  using swoole-server.php or it is using swoole-server-noasync.php?
### Actual Behavior
Both works.

**Comment by nbrady-techempower** [comment]
Round 18 was based off this commit [12b68023e5d406680af745d34b2984741bc7c198](https://github.com/TechEmpower/FrameworkBenchmarks/tree/12b68023e5d406680af745d34b2984741bc7c198/frameworks/PHP/swoole). There was only one variation of Swoole at that time.

**Comment by uniqss** [comment]
Oh, thanks very much! And when will the Round 19 come? I found out the bench is tested every day, so where can I get the latest rank tested last day?

**Comment by nbrady-techempower** [comment]
You can see the results of continuous tests on https://tfb-status.techempower.com

#4966 will have updates for Rnd 19

**Comment by uniqss** [comment]
Yes, I found this [https://tfb-status.techempower.com](https://tfb-status.techempower.com).  And the result is a json: [https://tfb-status.techempower.com/raw/results.2020-03-28-16-56-34-849.json](https://tfb-status.techempower.com/raw/results.2020-03-28-16-56-34-849.json)
In root.rawData.fortune I can't find swoole. only lumen-swoole/hamlet-swoole/laravel-swoole is found. I just want to see the result of raw swoole, and aspcore-ado-my and php 7 raw, and the latency and TPS(transactions per second) of mysql and postgresql of these frameworks. Could somebody just tell me how to trim this large json and get my answers kindly?

**Comment by uniqss** [comment]
I've just written some code to analyze the fat json to get the rank of every opration.
[https://github.com/uniqss/benchmark_result_analysize](https://github.com/uniqss/benchmark_result_analysize)
