### ISSUE TITLE
JSON Caching allowed?

### ISSUE THREAD

**Issue by Fenny** [TechEmpower/FrameworkBenchmarks#5591]
I noticed that some new frameworks scored high in [latest JSON serialization test](https://www.techempower.com/benchmarks/#section=test&runid=c7013dea3-22c9-44c1-864f-949509d78e0c&hw=ph&test=json), some are caching the JSON responses when looking at the source. I don't want to be that guy, but I think its fair if everybody follows the rules.

[JSON Serialization requirements](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#json-serialization)
**xiv.** _The serialization to JSON must not be cached; the computational effort to serialize an object to JSON must occur within the scope of handling each request._

Maybe the author of [firenio](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/firenio) could example what's going on on the following lines:
[/firenio-http-lite.dockerfile#L23](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/firenio/firenio-http-lite.dockerfile#L23)
[/TestHttpLoadServer.java#L156](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/firenio/src/main/java/hello/TestHttpLoadServer.java#L156)

**Comment by nbrady-techempower** [comment]
Putting a `println` [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/firenio/src/main/java/hello/TestHttpLoadServer.java#L99) gives me output every time i hit the `/json` endpoint, so I'm not sure this does what you think it does but we can ping @wangkaish for clarification.

**Comment by Fenny** [comment]
Yeah sure, maybe @wangkaish could clearify :+1:

**Comment by wangkaish** [comment]
You misunderstood the parameter "cachedurl",  a url string can be cached if the url frequently requested, for example when the request "/json" is coming, it will use the cached string "/json" instead of use 'new String("/json")'.
