### ISSUE TITLE
How should I reproduce or get error messages?

### ISSUE THREAD

**Issue by sy-records** [TechEmpower/FrameworkBenchmarks#5677]
On the new list https://www.techempower.com/benchmarks/#section=test&runid=64be2110-3011-48ae-8416-30c0ac0609c1&hw=ph&test=plaintext&l=zik073-3j , I see that simps has some errors, how should I reproduce them?

![image](https://user-images.githubusercontent.com/33931153/80660675-fcec8600-8abe-11ea-8183-eb3da83ffc2a.png)

Is it because of a response header or concurrency problem?

**Comment by sy-records** [comment]
I found the log.
https://tfb-status.techempower.com/unzip/results.2020-04-29-09-09-18-794.zip/results/20200425045046/simps

**Comment by sy-records** [comment]
I can't find why there are errors, can you tell me?
In the [simps.log](https://tfb-status.techempower.com/unzip/results.2020-04-29-09-09-18-794.zip/results/20200425045046/simps/run/simps.log) file, only the route can't be found, but I've defined all the routes for testing.

**Comment by nbrady-techempower** [comment]
I don't know what other errors you're expecting @sy-records ? The log file you linked is suggesting that this is a problem with your implementation and not something with the benchmarking framework.

**Comment by msmith-techempower** [comment]
```
simps: Fatal error: Uncaught Exception: Router Not Found in /simps/vendor/simple-swoole/simps/src/Server/Protocol/HTTP/SimpleRoute.php:153
simps: Stack trace:
simps: #0 /simps/vendor/simple-swoole/simps/src/Server/Protocol/HTTP/SimpleRoute.php(115): Simps\Server\Protocol\HTTP\SimpleRoute->defaultRouter(Object(Swoole\Server), 33150, Array)
simps: #1 /simps/vendor/simple-swoole/simps/src/Server/Http.php(95): Simps\Server\Protocol\HTTP\SimpleRoute->dispatch(Object(Swoole\Server), 33150, 'ion: keep-alive...')
simps: #2 {main}
```
This seems to suggest that the error is being thrown from a library file rather than the implementation code. Likely, that means that either the calling code is doing something wrong like not registering the router correctly, or there is a bug in the underlying framework library.

**Comment by sy-records** [comment]
I am not sure if this exception will be generated in the request `/plaintext`, please allow me to check again, thanks.

**Comment by joanhey** [comment]
If you need more information, catch the Exception.
`Uncaught Exception: `

Almost all frameworks catch all the exceptions and show informative messages to the developer.

If you catch it (and all other uncaught ) you can show more info: url, client ip, memory used, cpu used, .....

**Comment by sy-records** [comment]
Well, I found that it's not the Exception that's causing the problem, it's the fact that it drops after using the `pipeline.lua` script.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/19b136f3bcc456f5326dd8009d4491a7f501dbf3/toolset/wrk/pipeline.lua#L1-L12

```
 Running Warmup plaintext
 wrk -H 'Host: 10.0.0.1' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 28 http://10.0.0.1:8080/plaintext
---------------------------------------------------------
Running 15s test @ http://10.0.0.1:8080/plaintext
  28 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   380.07us  248.13us  16.66ms   91.82%
    Req/Sec    45.99k     2.43k   72.35k    76.64%
  Latency Distribution
     50%  357.00us
     75%  452.00us
     90%  573.00us
     99%    0.87ms
  19331605 requests in 15.10s, 2.99GB read
Requests/sec: 1280283.51
Transfer/sec:    202.68MB
---------------------------------------------------------
 Concurrency: 256 for plaintext
 wrk -H 'Host: 10.0.0.1' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 256 --timeout 8 -t 28 http://10.0.0.1:8080/plaintext -s pipeline.lua -- 16
---------------------------------------------------------
Running 15s test @ http://10.0.0.1:8080/plaintext
  28 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us    -nan%
    Req/Sec    90.00      0.00    90.00    100.00%
  Latency Distribution
     50%    0.00us
     75%    0.00us
     90%    0.00us
     99%    0.00us
  252 requests in 15.03s, 40.85KB read
Requests/sec:     16.77
Transfer/sec:      2.72KB
STARTTIME 1588099210
ENDTIME 1588099226
```
