### ISSUE TITLE
Update Ubuntu version in Vagrant

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#5688]
Now Citrine and Azure use Ubuntu 18.04.
The databases also use 18.04 in docker.

We need to update Vagrant to use Ubuntu 18.04 too.

![vagrant-up](https://user-images.githubusercontent.com/249085/81989547-bd38a900-963d-11ea-8bb8-9fe5d62e3842.png)

**Comment by nbrady-techempower** [comment]
Updated in #5648 Thanks @joanhey
