### ISSUE TITLE
Replace go-mgo / go-mgo-prefork

### ISSUE THREAD

**Issue by andregmoeller** [TechEmpower/FrameworkBenchmarks#5701]
go-mgo and go-mgo-prework are using [mgo](https://github.com/go-mgo/mgo), which has not been maintained since July, 2018. So, I would not use it for a new project. Instead I would probably use [mongodb/mongo-go-driver](https://github.com/mongodb/mongo-go-driver). [atreugo-mongo-prefork/atreugo-mongo-prefork](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Go/atreugo/src/storage/mongo.go#L8-L11) and [fasthttp-mongo](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Go/fasthttp/src/storage/mongo.go#L8-L11) are already using this driver. So, I suggest to replace go-mgo/go-mgo-prefork by something that uses mongodb/mongo-go-driver.

**Comment by TonyPythoneer** [comment]
@andregmoeller 
If you know how to update, please send PR. Thx.
