### ISSUE TITLE
Windows Java installer script using unofficial link 

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#572]
Currently, the Java requirements (in toolset/setup/windows/installer.ps1) is pointing to http://ghaffarian.net instead of an official Oracle link.

This should be fixed.

**Comment by nbrady-techempower** [comment]
There's still a lot of work to be done for Windows compatibility, if it even happens before we have full bash support on windows. Closing this for now.
