### ISSUE TITLE
Spring on GraalVM Support

### ISSUE THREAD

**Issue by amorenew** [TechEmpower/FrameworkBenchmarks#5732]
I wonder if there will be a support for Spring on GraalVM
Spring Boot App started in **0.078** seconds on GraalVM instead of **1.47** seconds on JVM
More info about Performance on GraalVM
https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/

**Comment by nbrady-techempower** [comment]
Feel free to add this permutation yourself with a PR or reach out to the maintainers. We don't really track startup time as a performance indicator, though. Don't know if there are other benefits.
