### ISSUE TITLE
Terrible warp-rust benchmark?

### ISSUE THREAD

**Issue by except** [TechEmpower/FrameworkBenchmarks#5759]
I know benchmarks aren't really supposed mean much. Shouldn't the`tokio` crate use the `rt-threaded` feature, as by default, tokio spawns a runtime that only uses a single core.

Other people saw this in another [issue](https://github.com/seanmonstar/warp/issues/557).

**Comment by nbrady-techempower** [comment]
> I know benchmarks aren't really supposed mean much

❓

> Shouldn't the tokio crate use the rt-threaded feature, as by default, tokio spawns a runtime that only uses a single core.

We don't necessarily keep tabs on those issues here. We leave it up to the test implementers and maintainers to figure out the best way to improve. To your earlier point, it seems the benchmark was at least useful enough that you recognized this `rt-threaded` feature should be used by default, and that's one of the main goals here; finding ways to improve efficiency and performance.  You're welcome to open a pull request to improve the rust-warp implementation. Thanks! :)
