### ISSUE TITLE
Investigate why Go did not run on EC2

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#577]
As pointed out by Paul Kroll in the Google Group, Go didn't run on EC2.  Let's investigate what caused it to fail and get a separate issue logged to work on that.

[1] https://groups.google.com/d/msg/framework-benchmarks/XYhQdGmR2tE/GpGQ5h6udvkJ

**Comment by LadyMozzarella** [comment]
Closing this issue as Falcore appears to be passing in the latest previews for Round 10.
