### ISSUE TITLE
Use HTTP2 in benchmarks

### ISSUE THREAD

**Issue by abnud1** [TechEmpower/FrameworkBenchmarks#5784]
Current benchmarks use wrk which isn't HTTP2 capable even though many frameworks support HTTP2.

In my opinion not using HTTP2 presents a problem: if X is faster than Y according to the benchmarks, would X be faster than Y if both of them used HTTP2 instead? what if Y was optimized for HTTP2 like h2o for example?.

The obstacle I see besides replacing wrk is that not all frameworks support HTTP2, I suggest we use HTTP2 where possible, benchmarking tool should fallback to HTTP1.1 if server doesn't support it, and last but not least the Results Website should show - preferably in a NEW column - the HTTP Protocol version used in the benchmark.

For the benchmarking tool we can choose from:
1- [Hay](https://github.com/rakyll/hey)
2- [Vageta](https://github.com/tsenart/vegeta)

**Comment by nbrady-techempower** [comment]
We would not remove HTTP1.1 pipelined tests, but we would add HTTP2 tests for comparison. That's already on the list of additional test types we'd like to add when we have time: https://github.com/TechEmpower/FrameworkBenchmarks/issues/133

Feel free to add some comments there, if you'd like.

**Comment by abnud1** [comment]
@nbrady-techempower could you add issue #133 to the Test Types Roadmap project ? in the guidelines for the issues you said I should check that project, I didn't find HTTP2 there so I assumed the Idea hasn't been issued yet. Sorry for this.

**Comment by nbrady-techempower** [comment]
@abnud1 good point! added, thanks
