### ISSUE TITLE
Pass/fail capture and rendering

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#579]
This requires more thought, but we should have some means after a run to know whether each test permutation passed or failed.  Ideally, if the permutation fails, some logging output would be automatically captured.

Then, down the line, it would be nice for this information to flow through to the results charts so that tests that fail to run aren't simply missing.

**Comment by nbrady-techempower** [comment]
Added this to the results website roadmap https://github.com/TechEmpower/FrameworkBenchmarks/projects
