### ISSUE TITLE
TFB-Status Offline

### ISSUE THREAD

**Issue by nbrady-techempower** [TechEmpower/FrameworkBenchmarks#5814]
We're working on it currently and hope to have Citrine / TFB-Status back up shortly.

**Comment by Fenny** [comment]
By any chance, you could merge https://github.com/TechEmpower/FrameworkBenchmarks/pull/5816 before restarting? Thanks ❤️

**Comment by nbrady-techempower** [comment]
Sorry @Fenny, we restarted around noon and before your PR was passing
