### ISSUE TITLE
ubuntu libs 404 Not Found

### ISSUE THREAD

**Issue by xcyl** [TechEmpower/FrameworkBenchmarks#5820]
cuehttp: Step 1/12 : FROM ubuntu:18.04
cuehttp:  ---> c3c304cb4f22
cuehttp: Step 2/12 : RUN apt-get update -yqq
cuehttp:  ---> Using cache
cuehttp:  ---> f0373f38ff20
cuehttp: Step 3/12 : RUN apt-get install -yqq g++-7 cmake git
cuehttp:  ---> Running in 6aeaff20f323
cuehttp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.58.0-2ubuntu3.8_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
cuehttp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-106.107_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
cuehttp: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3-gnutls_7.58.0-2ubuntu3.8_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
cuehttp: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
cuehttp: Removing intermediate container 6aeaff20f323
cuehttp: Docker build failed; terminating
cuehttp: Traceback (most recent call last):
cuehttp:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 57, in __build
cuehttp:     raise Exception(token['errorDetail']['message'])
cuehttp: Exception: The command '/bin/sh -c apt-get install -yqq g++-7 cmake git' returned a non-zero code: 100

**Comment by nbrady-techempower** [comment]
Seems this was just a temporary outage @xcyl; it's working now.
