### ISSUE TITLE
Results: Overhead comparisons missing for some tests

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#584]
Although some tests such as Play and Vertx specify Netty as their "versus" attribute, the results website is not correctly finding a suitable Netty comparison test to render a versus line.

I need to review the code to refresh my memory.  I will investigate why this is.

**Comment by msmith-techempower** [comment]
@bhauer Kicking this into the Round 12 work; any ideas here?

**Comment by msmith-techempower** [comment]
I believe this was resolved in our audit of the `benchmark_config.json` files.
