### ISSUE TITLE
Rust implementations: dependency git crates error

### ISSUE THREAD

**Issue by botika** [TechEmpower/FrameworkBenchmarks#5872]
It seems that the rust bench that use `git crates` return this error. 
```
Updating crates.io index
actix:     Updating git repository `https://github.com/simd-lite/simd-json-derive.git`
actix: error: failed to get `simd-json-derive` as a dependency of package `actix v2.0.0 (/actix)`
actix: Caused by:
actix:   failed to load source for dependency `simd-json-derive`
actix: Caused by:
actix:   Unable to update https://github.com/simd-lite/simd-json-derive.git
```
It is not only in actix it seems to happen in all that use `git crates`. 

Very strange ... sure it has to do with cargo or github.

**Comment by nbrady-techempower** [comment]
This appears to just be a problem with that particular repo, which has been solved in actix / ntex. Other frameworks like hyper and may-minihttp are not having a problem with their git dependencies.
