### ISSUE TITLE
tfb-status server is not running

### ISSUE THREAD

**Issue by itsumura-h** [TechEmpower/FrameworkBenchmarks#5914]
Server [https://tfb-status.techempower.com](https://tfb-status.techempower.com) is not running

**Comment by nbrady-techempower** [comment]
We have an internet outage and are working on resolving the issue, thanks!

**Comment by itsumura-h** [comment]
It is solved!

**Comment by Bogdanp** [comment]
JFYI, the status server was down earlier today and now it's up but it's serving a `hello, world` message.

**Comment by nbrady-techempower** [comment]
@Bogdanp Thanks, we're aware of the issue and working on bringing back up the service.

**Comment by michaelhixson** [comment]
It's back now.
