### ISSUE TITLE
Run last-updated frameworks first in continuous benchmarking to give more time to fix problems before the next run

### ISSUE THREAD

**Issue by matt-42** [TechEmpower/FrameworkBenchmarks#5925]
----- Just an idea:

I think it would be nice to first run tests that were updated recently in the continuous benchmark. 

This will give more time to contributors currently working on updating some frameworks to fix errors or performance problems before the next countinous benchmark run.

Right now there is no way for contributors of the last framework zysocket-v to fix anything before the next run. This would fix this.

---- Another idea but more aggressive:

Run ONLY the tests that were updated since the last run in the continuous benchmark to allow faster iterations of framework contributors, and once or twice a month all the tests.

**Comment by nbrady-techempower** [comment]
The 2nd idea is indeed too aggressive; I wouldn't do that.

The 1st isn't bad, but I'm not sure I want to have code in the toolset that sorts the list of tests to be run by looking for last modified files in each test directory.

**Comment by volyrique** [comment]
The second idea was [previously discussed](https://groups.google.com/forum/?fromgroups=#!topic/framework-benchmarks/5n-eJ924W0U) on the mailing list, where in fact I made the argument that in certain cases it was desirable to run the tests **without** changes several times to aid statistical analysis.

**Comment by matt-42** [comment]
Thanks @volyrique I did not know about this discussion. I understand it's a complex subject. I'll do what I can with the 100h feedback loop then. I'm closing this issue since it's already discussed then.
