### ISSUE TITLE
Grizzly: Review JSON test implementation; instantiate object and then serialize

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#593]
As Daryl Robbins points out in the Google Group [1], the Grizzly JSON serialization test implementation should be audited and modified as needed to reflect the spirit of the test.  Most importantly, the test type asks that a object be instantiated and then serialized, but the Grizzly implementation uses the Jackson streaming API directly to formulate a JSON response without having actually instantiated a Java object.

The implementation should be modified to more closely match the implementation seen in the Servlet test.

[1] https://groups.google.com/d/msg/framework-benchmarks/s3IG2GXVUWQ/gyHYUHgSgh0J

**Comment by zloster** [comment]
This issue should be closed. The current code seems to be fine: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/grizzly-bm/src/main/java/org/glassfish/grizzly/bm/JsonHttpHandler.java#L25-L33

**Comment by nbrady-techempower** [comment]
Looks like this has since been resolved
