### ISSUE TITLE
Tests based on obsolete protocols?

### ISSUE THREAD

**Issue by jcayzac** [TechEmpower/FrameworkBenchmarks#5976]
I noticed Drogon recently came in first place and beat Actix. I didn't know about Drogon so I went to read its documentation a bit. It seems it doesn't support the current version of the HTTP protocol (2).
Shouldn't the tests used for the benchmarks not be based on ancient versions of HTTP?

**Comment by nbrady-techempower** [comment]
>  ancient versions of HTTP?

😆

I guess HTTP/2 was introduced 5 years ago, which is 150 years in tech-speak, so you're not wrong.

However, we don't have a test specifically designed for HTTP/2 and there's no requirement that test implementations must support HTTP/2.
