### ISSUE TITLE
javalin results are not visible from UI

### ISSUE THREAD

**Issue by bensullivan** [TechEmpower/FrameworkBenchmarks#6010]
Hi,

javalin results are not visible from UI build [#ba6c12a4-d54d-4a9e-825b-abde0ef6d6a2](https://www.techempower.com/benchmarks/#section=test&runid=ba6c12a4-d54d-4a9e-825b-abde0ef6d6a2), but I can see them in [results.2020-05-27-07-57-48-450.json](https://tfb-status.techempower.com/raw/results.2020-05-27-07-57-48-450.json)

This seemed to be the closest build to the official Round 19 release date.

Thanks.

**Comment by nbrady-techempower** [comment]
Hi @bensullivan,

This test is marked as a "stripped" test and "stripped" tests are hidden by default. To view the results of those tests, you can go into the filters panel and enable "stripped" and then click "apply changes".

**Comment by bensullivan** [comment]
Ah OK thanks.

Can I ask why it was marked as stripped?

Thanks

**Comment by bensullivan** [comment]
For the 2020 offical round 19 [page](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=fortune&a=2), my filter had stripped enabled by default and javalin was not one of the stripped frameworks...
