### ISSUE TITLE
Why does framework not appear in composite scores

### ISSUE THREAD

**Issue by billywhizz** [TechEmpower/FrameworkBenchmarks#6018]
This is just a query so not sure if this is correct place to raise it. My framework (JavaScript/just) has run on the live benchmark for first time. It scores well overall but does not appear on the composite scores index. Is there something I need to set in the configuration in order to have it appear there?

https://www.techempower.com/benchmarks/#section=test&runid=3e069eac-3b1d-4f77-bb06-2bceb4172dea&hw=ph&test=composite&a=2

From the scores it got it should be scoring about 7588 on the composite index.

This is the config I am using: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/just/benchmark_config.json

**Comment by billywhizz** [comment]
Is it likely because I put the "framework" field in as "None". I am assuming it should be "just"

**Comment by nbrady-techempower** [comment]
@billywhizz Yes, your frameowork name should be "just" and I can look into it the beginning of next week

**Comment by billywhizz** [comment]
@nbrady-techempower thanks! i have created a PR here https://github.com/TechEmpower/FrameworkBenchmarks/pull/6019. feel free to close this issue or i can.

**Comment by billywhizz** [comment]
PR has been merged so i will close this. thank you!
