### ISSUE TITLE
How to integrate tool like Pgbouncer or Odyssey

### ISSUE THREAD

**Issue by ldng** [TechEmpower/FrameworkBenchmarks#6059]
I'm looking at the Python framework and notice that all async framework use SqlAlchemy connection pooling but Django is left with its default config. Personnally I haven't deployed, IRL, a Django without Pgbouncer in 10 years so the benchmark feels a bit unfair in that regard.

So, how do you integrate a third-party connection pooling tool like Pgbouncer or Odyssey into the framework ? In the Django Dockerfile ? In Postgresql's ? In its own docker ?

**Comment by nbrady-techempower** [comment]
I'm not familiar with Pgbouncer but if it's similar to SqlAlchemy then you shouldn't have a problem adding it in the django dockerfile similar to the way SqlAlchemy is done for the other python frameworks. Happy to help out with that if you open a PR and can't get it working right.

**Comment by ldng** [comment]
No, it is not similar to the SqlAlchemy way. PgBouncer and Odyssey are both generic connection pooling tools for Postegresql. Tehy are coded in C and C++ respectively. You have the option to put them "application server" side, "database server" side or on it's own server.  Server here beeing either a physical one or a docker container. Hence my question, how would that fit in the benchmark setup.

**Comment by nbrady-techempower** [comment]
I haven't given this too much thought, but I would say, for starters, try adding it into a script in the django docker container that starts Pgbouncer and the web server. We can see how that performs and talk about ways to improve the setup from there.
