### ISSUE TITLE
[bug] Sometimes got Verifying exception: (2003, "Can't connect to MySQL server on 'tfb-database' (111)")  

### ISSUE THREAD

**Issue by dvaknheo** [TechEmpower/FrameworkBenchmarks#6081]
### OS (Please include kernel version)
centos7 (aliyun)
### Other details and logs

VERIFYING QUERY COUNT FOR http://tfb-server:8080/fortunes
--------------------------------------------------------------------------------

i want to add my framwork  . and sometime found that:
```
Verifying test fortune for duckphp caused an exception: (2003, "Can't connect to MySQL server on 'tfb-database' (111)")
   FAIL for http://tfb-server:8080
```
not only in my framwork ,also in other framework .

most be that (in other framwork its possiblilty is maybe)
```
FAIL for http://tfb-server:8080/fortunes
     `<fieldset><legend>Exception(PDOException:2002)</legend>    SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  
```

it maybe the docker's dns problem ？

one condition maybe the mysql  connection no release ?

how to solute it ?

**Comment by dvaknheo** [comment]
there is  the system framework 'php' 's error output info:
```
php: Stack trace:
php: #0 /php/dbquery.php(7): PDO->__construct('mysql:host=tfb-...', 'benchmarkdbuser', 'benchmarkdbpass', Array)
php: #1 {main}
php: Next PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in /php/dbquery.php:7
php: Stack trace:
```
```
| php
|       fortune       : FAIL
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS
```

**Comment by joanhey** [comment]
Send a PR with your framework and check if pass the travis test.

If it fail, will be easier for us to help you, watching the code.

**Comment by joanhey** [comment]
It's working  #6090 , so can be closed.

**Comment by dvaknheo** [comment]
this  problem must cause by docker host mechine dns .

close on you see this post . think you joanhey    :)
