### ISSUE TITLE
Run finagle benchmark

### ISSUE THREAD

**Issue by huangshiyou** [TechEmpower/FrameworkBenchmarks#6154]
### Usage Issue
This may not be an issue but more like a requirement for usage clarification. I am trying to run the finagle benchmark, but the execution seems to not terminate forever. May I know what is the correct way to run a single benchmark manually? I am using something like this:
`java -jar target/scala-2.12/finagle-benchmark.jar`

**Comment by nbrady-techempower** [comment]
Follow the installation guide here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Development-Installation-Guide

Then you should be able to run:

`./tfb --mode benchmark --test finagle`

**Comment by huangshiyou** [comment]
Thanks for your reply. May I know if there is a way to run w/o docker? Is there a way to run it manually, like java -jar ...? Thanks.

**Comment by nbrady-techempower** [comment]
No, we do not have a way to run the benchmarks without docker.
