### ISSUE TITLE
TFB Status is unavailable for some days

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [TechEmpower/FrameworkBenchmarks#6161]
The [status page](https://tfb-status.techempower.com/) returns a HTTP `502` / `504` for some days.
Are there any current maintenance tasks that I have missed?

**Comment by nbrady-techempower** [comment]
We know about the issue and are working on it. The benchmarks are running as normal, it is just tfb-status that is down. It probably won't be up until Monday when everyone returns. Thanks!

**Comment by Kaliumhexacyanoferrat** [comment]
Perfect, thank you - can't wait for the results next week 😉

**Comment by jknack** [comment]
Status page is back, but builds aren't (seems stuck).

Thank you.

**Comment by nbrady-techempower** [comment]
Thanks for your patience on this. We should be up and running now.

**Comment by nomhoi** [comment]
TFB Status is unavailable now.
