### ISSUE TITLE
Travis CI slow

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#6178]
Travis is migrating repositories to travis-ci.com.
So there are less jobs in .org.

It's time to migrate to .com

Why and complete information:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#q-why-are-some-of-my-queued-jobs-taking-longer-than-usual-to-build

**Comment by nbrady-techempower** [comment]
thanks @joanhey! didn't know about this. i'll look into making the switch.

**Comment by nbrady-techempower** [comment]
This has been completed. Future pull requests should trigger on travis-ci.com. I'll leave this open until we confirm.

**Comment by joanhey** [comment]
My last PR start immediately and run very fast in `travis-ci.com`.

My PRs from yesterday are still in queue and need hours to run in `trvis-ci.org`.

Fixed, Thank you

**Comment by joanhey** [comment]
Closed all PRs from yesterday in queue and resend the PRs.

**Comment by nbrady-techempower** [comment]
Awesome, thanks for the heads up on this!

**Comment by joanhey** [comment]
The PRs resend are waiting still for the run from before.
They all passed the new run. 
Perhaps you can close the runs and merge.

**Comment by joanhey** [comment]
@nbrady-techempower  I think that you need to close the old runs queued, they will need days to finish.

**Comment by joanhey** [comment]
![Captura de pantalla_área-de-selección_20201202141013](https://user-images.githubusercontent.com/249085/100876804-2f70be00-34a8-11eb-95a1-e2cddf74ab87.png)

:thinking:

**Comment by nbrady-techempower** [comment]
@joanhey well, this looks like a fail. we ran through 10k credits and they want $170 / mo. for 2 max concurrent jobs. looking into options but we may go down the self-hosted hole. i get to testing the PRs manually later today.

**Comment by joanhey** [comment]
My PRs are tested locally.
For $170 / mo we have cheaper private servers :), for do the jobs.

Another options is to use the Github actions, that are free for open source.
Or add 1 more server for the tests (3 for the runs +1 for tests).
