### ISSUE TITLE
Ruby: Add Reel, Webmachine

### ISSUE THREAD

**Issue by tarcieri** [TechEmpower/FrameworkBenchmarks#62]
Hi there! I'm the creator of an actor system + I/O framework + web server for Ruby: Celluloid, Celluloid::IO, and Reel respectively.

It seems like you guys have created a pretty interesting framework for performance benchmarking. My only complaint is that I don't think your existing tests of Ruby projects are covering the state-of-the-art and therefore make Ruby look rather bad.

I've recently done some major bottleneck elimination in Celluloid::IO and am getting rather promising numbers on JRuby, especially when InvokeDynamic is enabled. It'd be great to get my web server Reel included in your tests. Reel is also supported by the Webmachine framework, which would give a better indicator of the speed when utilized with a useful web framework as opposed to just a bare bones web server. Your benchmarks seem to run the entire gauntlet in this regard so I think including both makes sense.

I'm definitely willing to help out here however possible, and just wanted to open a tracking ticket to let you know ;)

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new features and languages
