### ISSUE TITLE
Is the CI running?

### ISSUE THREAD

**Issue by sebastienros** [TechEmpower/FrameworkBenchmarks#6210]
Couldn't find CI checks on the recent PRs. Did I miss an announcement?

**Comment by sebastienros** [comment]
Just saw that there was a discussions tab now, next time ;)

**Comment by nbrady-techempower** [comment]
@sebastienros CI isn't running right now. We migrated to travis-ci.com and hit our credits limit. Working on contacting someone from there to see what their Open Source policy is as well as considering some other options.

**Comment by sebastienros** [comment]
Looking at the PR history, it looks like GH actions might work. It supports docker. I use it on a project that has way more activity in terms of PRs and haven't reached the limits. I think it's around 70h per month, and I have not seen it enforced yet. Converting from Travis was easy (same issue with quotas). But I assume you already thought about it ;)

**Comment by nbrady-techempower** [comment]
@sebastienros Yeah, thanks! We're also considering some in-house options. Waiting to hear back from travis and to get some man hours on it

**Comment by waghanza** [comment]
@nbrady-techempower I've implemented GH actions in https://github.com/the-benchmarker/web-frameworks. I've seamlessly created a dynamic pipeline (only test updated frameworks instead of all). Glad if I can help ❤️
