### ISSUE TITLE
How to locally run the benchmark while getting a ranking close to citrine ? 

### ISSUE THREAD

**Issue by matt-42** [TechEmpower/FrameworkBenchmarks#6306]
Does anybody have found a way to locally run the benchmark and get a ranking similar to the ones of citrine?

I'm asking because when I run the benchmarks on my machine, the results does not reflect at all the numbers reported by the citrine environment. It sometimes happens  that  lithium versions running faster on my machine runs slower on citrine. For the cached queries it's even worst : perfs are 10x higher on my 4cores cpu than on citrine.

I have several ideas, like runing the wrk/db/framework on  separate machines, buying a more powerful processors, but it would be nice to have some words from people  who  had success replicating tfb results locally.

**Comment by benaadams** [comment]
> For the cached queries it's even worst : perfs are 10x higher on my 4cores cpu than on citrine.

Aside: cached queries default is 100 queries per request https://github.com/TechEmpower/FrameworkBenchmarks/issues/5858

**Comment by matt-42** [comment]
> > For the cached queries it's even worst : perfs are 10x higher on my 4cores cpu than on citrine.
> 
> Aside: cached queries default is 100 queries per request #5858

Thanks for the info, I think I was benchmarking with 20...

**Comment by billywhizz** [comment]
> Does anybody have found a way to locally run the benchmark and get a ranking similar to the ones of citrine?
> 
> I'm asking because when I run the benchmarks on my machine, the results does not reflect at all the numbers reported by the citrine environment. It sometimes happens that lithium versions running faster on my machine runs slower on citrine. For the cached queries it's even worst : perfs are 10x higher on my 4cores cpu than on citrine.
> 
> I have several ideas, like runing the wrk/db/framework on separate machines, buying a more powerful processors, but it would be nice to have some words from people who had success replicating tfb results locally.

it's entirely possible you will see better per cpu performance locally, especially if running the client, server and db all on the same machine. if the programs gets scheduled on cpus where they can share caches it will make a big difference. you also won't have the tcp overhead going across the network.

if you do want to try testing yourself the best option i have found was the spot instances from [packet/equinix](https://metal.equinix.com/product/servers/) which are cheap to rent for a few hours at a time and are similar spec to citrine servers.

**Comment by matt-42** [comment]
using 100 queries instead of 20 was finally enough to locate the bottleneck of the cached queries test: the standard C rand() function.
