### ISSUE TITLE
All .net core test program errors？

### ISSUE THREAD

**Issue by beetlex-io** [TechEmpower/FrameworkBenchmarks#6326]
[aspcore] had problems starting or stopping
[aspcore-ado-pg] had problems starting or stopping
[aspcore-ado-pg-up] had problems starting or stopping
[aspcore-mono] had problems starting or stopping
[aspcore-mono-mvc] had problems starting or stopping
[aspcore-mono-mvc-my] had problems starting or stopping
[aspcore-mono-mvc-pg] had problems starting or stopping
[aspcore-mono-mw] had problems starting or stopping
[aspcore-mono-mw-my] had problems starting or stopping
[aspcore-mono-mw-pg] had problems starting or stopping
[aspcore-mono-pg] had problems starting or stopping
[aspcore-mvc] had problems starting or stopping
[aspcore-mvc-ado-my] had problems starting or stopping
[aspcore-mvc-ado-pg] had problems starting or stopping
[aspcore-mvc-ado-pg-up] had problems starting or stopping
[aspcore-mvc-dap-my] had problems starting or stopping
[aspcore-mvc-dap-pg] had problems starting or stopping
[aspcore-mvc-dap-pg-up] had problems starting or stopping
[aspcore-mvc-ef-pg] had problems starting or stopping
[aspcore-mvc-ef-pg-up] had problems starting or stopping
[aspcore-mw] had problems starting or stopping
[aspcore-mw-ado-my] had problems starting or stopping
[aspcore-mw-ado-pg] had problems starting or stopping
[aspcore-mw-ado-pg-up] had problems starting or stopping
[aspcore-mw-dap-my] had problems starting or stopping
[aspcore-mw-dap-pg] had problems starting or stopping
[aspcore-mw-dap-pg-up] had problems starting or stopping
[aspcore-mw-ef-pg] had problems starting or stopping
[aspcore-mw-ef-pg-up] had problems starting or stopping
[aspcore-mw-json] had problems starting or stopping
[aspcore-pgo] had problems starting or stopping
[aspcore-pgo-pg] had problems starting or stopping
[aspcore-pgo-pg-up] had problems starting or stopping
[aspcore-vb-mw] had problems starting or stopping
[aspcore-vb-mw-ado-my] had problems starting or stopping
[aspcore-vb-mw-ado-pg] had problems starting or stopping
[beetlex] had problems starting or stopping
[beetlex-core] had problems starting or stopping
[beetlex-core-updb] had problems starting or stopping
[beetlex-debug] had problems starting or stopping

**Comment by nbrady-techempower** [comment]
That is strange. Was there a common dependency that's broken or the package manager down? The logs will be up shortly when the run is completed.

**Comment by beetlex-io** [comment]
The component package download error was found when submitting RP inspection， Update the Docker base image to solve this problem.

**Comment by joanhey** [comment]
It would be possible to see the logs before finishing the run ???

**Comment by nbrady-techempower** [comment]
@joanhey Right now, we push the zip file up when the run is completed. tfb-status is not hosted on citrine, for obvious reasons. The idea of transferring logs after every test completes isn't that appealing to me. It's currently easier outside of the toolset as part of a cleanup step.
