### ISSUE TITLE
Rust short form should be rs

### ISSUE THREAD

**Issue by pickfire** [TechEmpower/FrameworkBenchmarks#6351]
![image](https://user-images.githubusercontent.com/4687791/107168494-80e08080-69f6-11eb-8632-f9fea85e4b04.png)

Rust short form for language should be "rs" rather than "rus" since the file extension used is "rs".

**Comment by bhauer** [comment]
Done!  Rust is now abbreviated as "rs" in the attribute columns.  (You may need to reload to see the change.)
