### ISSUE TITLE
D test results are missing from round 20

### ISSUE THREAD

**Issue by PetarKirov** [TechEmpower/FrameworkBenchmarks#6353]
Of the D language permutations only the `collie` and `collie-ldc` runs [were included](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext&l=zik0zb-sf) in the round 20 results, but not the rest of the D implementations, which can be found e.g. in this preview run: https://www.techempower.com/benchmarks/#section=test&runid=1580dba0-1ac1-4e3c-96f4-5747295d67a6&hw=ph&test=plaintext&l=zik0xr-73&a=2

I tried to look for any clues, but I couldn't find why is that, given that the code is still in the repo: https://github.com/TechEmpower/FrameworkBenchmarks/tree/R20/frameworks/D

What needs to be done to get the D implementations included again?

**Comment by nbrady-techempower** [comment]
Most are tagged as broken for various reasons. They'll be removed entirely unless someone wants to take a crack at fixing them or creating new entries. That preview run is from September of 2019. Feel free to open up a pull request removing the broken tags if you'd like to take a crack at it!
 https://github.com/TechEmpower/FrameworkBenchmarks/blob/R20/frameworks/D/vibed/benchmark_config.json#L26

**Comment by PetarKirov** [comment]
@nbrady-techempower thanks for the answer and pointing me to the json file!
In the future please open an issue and tag relevant people so it can be fixed. Personally, as a contributor and maintainer of various D open-source projects since around 2015 I had no idea that these benchmarks were broken and I had a hard time finding any information about them when someone asked on the D newsgroup about their status.

Perhaps a CODEOWNERS can be added so you guys can now who to ping if some implementation fails. The ping could even be automated via a GitHub action.

> Most are tagged as broken for various reasons.

Are there any logs that I can check? I will run the benchmarks locally, but I hit some errors in the `tfb` script which I need to fix first.

**Comment by nbrady-techempower** [comment]
> In the future please open an issue and tag relevant people so it can be fixed

I appreciate what you're getting at here, but this is why we built https://tfb-status.techempower.com This project has been broken for 2 rounds now, so I'm not sure why the relevant people haven't noticed. We rely on maintainers to track this stuff themselves.

> Perhaps a CODEOWNERS file can be added so you guys can know who to ping if some implementation fails. The ping could even be automated via a GitHub action ;)

We've tried this before and it was just too noisy and most everyone opted out. We can talk about reintroducing it now that we're using GitHub actions.

> Are there any logs that I can check? I will run the benchmarks locally, but I hit some errors in the tfb script which I need to fix first.

You'll probably be able to find some on a search through tfb-status, but if you're having issues that we can help with on the toolset, please open up an issue. If you want to just remove the broken tags in a PR, CI will run and give you some logs there. I'm fine with that.
