### ISSUE TITLE
display_name in benchmark_config.json doesn't appear to work

### ISSUE THREAD

**Issue by bdw429s** [TechEmpower/FrameworkBenchmarks#6408]
Moving this from Discussions at @nbrady-techempower 's request:
https://github.com/TechEmpower/FrameworkBenchmarks/discussions/6381

-----

Per my recent conversation with @nbrady-techempower I renamed the primary name of the Lucee CF engine framework to simply cfml as the "default" configuration and then created the variant (not sure if that's the right word) of cfml-adobe for the Adobe CF engine. I set the display_name property of the "default" block to cfml-lucee in the benchmark config JSON file.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CFML/CFML/benchmark_config.json#L24

However, the display name doesn't appear to be used. When I view the data from the nightly runs

https://www.techempower.com/benchmarks/#section=test&runid=fe267cab-bcfc-4e75-8f4a-9ac08c174b09&hw=ph&test=json&a=2

I expect to see
* cfml-lucee
* cfml-adobe

but instead I see
* cfml
* cfml-adobe

**Comment by bhauer** [comment]
Just posted a change to address this. Please refresh the link above to confirm.

**Comment by nbrady-techempower** [comment]
Confirmed for me.

@bdw429s Thanks for finding and reporting this!

**Comment by bdw429s** [comment]
@nbrady-techempower @bhauer To confirm, I'm NOT seeing the behavior changed in the link above.  

![image](https://user-images.githubusercontent.com/584009/109720067-35da0900-7b6f-11eb-9edd-03bd9a659fb0.png)

The `cfml` framework still shows as `cfml` and is not using the display name of `cfml-lucee`.

**Comment by nbrady-techempower** [comment]
![image](https://user-images.githubusercontent.com/1304934/109720391-dd9b0b00-7b5e-11eb-87e6-a7a2f64112bc.png)

Maybe try clearing your cache / hard refresh?

**Comment by zspitzer** [comment]
![image](https://user-images.githubusercontent.com/426404/109722888-9daf4480-7bad-11eb-9e6b-8e708eea019f.png)

https://www.techempower.com/benchmarks/#section=test&runid=c91833d5-6f63-468e-83e7-cd046dcdbd6a&hw=ph&test=fortune&l=zik0zj-73&a=2

**Comment by bdw429s** [comment]
I cleared my cache and it's all good now.  Thanks!
