### ISSUE TITLE
Server header value can be single char?

### ISSUE THREAD

**Issue by beetlex-io** [TechEmpower/FrameworkBenchmarks#6430]
actix raw
``` rust
const HDR_SERVER: &[u8] = b"Server: A\r\n";
```
aspcore 
``` csharp
 private readonly static AsciiString _headerServer = "Server: K";
```

**Comment by nbrady-techempower** [comment]
No. Check out the discussion here: https://github.com/TechEmpower/FrameworkBenchmarks/discussions/5673#discussioncomment-217279

The new toolset will verify this. Round 21 won't happen until the new toolset is ready (soonish) and those tests will fail.
