### ISSUE TITLE
Framework(s) not showing up on results page

### ISSUE THREAD

**Issue by benaadams** [TechEmpower/FrameworkBenchmarks#6458]
Particularly [`CSharp/ben`](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/ben).

It does look to be happily producing results in the runs [results.2021-03-08-20-18-54-992.json](https://tfb-status.techempower.com/raw/results.2021-03-08-20-18-54-992.json)

![image](https://user-images.githubusercontent.com/1142958/111404188-3d98c200-86c6-11eb-99a2-0cf9f02ba575.png)

However it doesn't show on the [visualize page](https://www.techempower.com/benchmarks/#section=test&runid=aef71fdb-3272-434c-84ec-1a6cffb11fbf); not sure why?

**Comment by n-stefan** [comment]
Isn't it "asp.net core" (Mcr/Mcr, #18)?
Not bad for Micro ORM :)

**Comment by benaadams** [comment]
Oh weird; yes it is showing up there

![image](https://user-images.githubusercontent.com/1142958/111467818-cc382e00-871c-11eb-81a2-0ca43179995c.png)

Which makes it even stranger on Plaintext

![image](https://user-images.githubusercontent.com/1142958/111467999-fdb0f980-871c-11eb-974b-585d91f1026c.png)

As there are two with the same name


Wondering how the config annotates it 🤔

**Comment by nbrady-techempower** [comment]
@benaadams Looks like there might be some confusion with keys because of the framework and display_name keys in the config. https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/CSharp/ben/benchmark_config.json#L13

**Comment by benaadams** [comment]
Cool will fix; thank you
