### ISSUE TITLE
can you add the `goframe` to benchmark

### ISSUE THREAD

**Issue by ayamzh** [TechEmpower/FrameworkBenchmarks#6506]
https://github.com/gogf/gf  this framework is more an more popular

**Comment by nbrady-techempower** [comment]
Added here: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Suggested-Frameworks-Languages-and-Features

We don't add the frameworks ourselves.

**Comment by platipusica** [comment]
Hi Nate, 

could you add Jam.py on Suggested page please? Under Python:
https://github.com/jam-py/jam-py

Thanks in advance.

**Comment by nbrady-techempower** [comment]
@platipusica done
