### ISSUE TITLE
Cinatra github issue

### ISSUE THREAD

**Issue by opakaj** [TechEmpower/FrameworkBenchmarks#6536]
Its clear in the tests that /plaintext resolves to hello world. And it works well. Its just that.. 
Why doesn't it run correctly when I update the main.cpp code. There's something I'm not seeing.
For example, I may change hello world to "hello world 2" for the /plaintext url with a new image tag but no change in output. Yet building the original works. The issue started after removing the comments from main.cpp of example folder in cinatra github home page.

**Comment by nbrady-techempower** [comment]
If you're still having this issue, please re-open with some more details. Are you using the toolset to test the changes? `tfb --mode verify --test cinatra` etc.
