### ISSUE TITLE
Mark ASP.NET Core >platform< benchmark approach as "stripped" instead of "realistic"

### ISSUE THREAD

**Issue by lauxjpn** [TechEmpower/FrameworkBenchmarks#6585]
@roji BTW, shouldn't _all_ platform benchmarks be marked as `stripped` instead of `realistic`?

_(From the info icon tooltip of the filters panel:)_

> **Implementation approach** describes the test's design disposition.
> * A **realistic** implementation approach uses the framework with most out-of-the-box functionality enabled.  We consider this realistic because most applications built with the framework will leave these features enabled.
> * A **stripped** implementation approach removes or outright avoids implementing features that are unnecessary for the particulars of this benchmark exercise.  This might illuminate the marginal improvement available in fine-tuning a framework to your application's use-case.
> **Stripped** implementations are hidden by default.  See the Motivation and Question section for more information.

_Originally posted by @lauxjpn in https://github.com/TechEmpower/FrameworkBenchmarks/issues/6566#issuecomment-840231270_

---

> shouldn't all platform benchmarks be marked as stripped instead of realistic?

I guess it's a matter of interpretation, but I personally don't think so... The same components are being used in the platform as in the non-platform benchmarks - it's the same ASP.NET, Npgsql, rather than versions where functionality has been stripped out. The **benchmark implementation** indeed uses ASP.NET in a way which is very perf-oriented and atypical, but I think that's a different matter.

For example, there are web frameworks out there which don't have MVC at all (or a middleware pipeline), but do expose a low-level API that's similar to how the platform benchmarks are using Kestrel directly. The .NET platform benchmark is about comparing against those, and avoiding using optional web components (e.g. MVC) which aren't strictly-speaking necessary. On the other hand, if I were to produce a version of Npgsql which only supports the code path needed to run Fortunes (no transactions, no parameters, no nothing), that would definitely fall into the definition of "stripped" above, as I understand it.

_Originally posted by @roji in https://github.com/TechEmpower/FrameworkBenchmarks/issues/6566#issuecomment-840461435_

**Comment by lauxjpn** [comment]
According to [Basic Concepts](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Basic-Concepts), a _framework_ is defined as follows:

> **framework**
> We use the word framework loosely to refer to any **HTTP stack** —a full-stack framework, a micro-framework, or even **a web platform** such as Rack, Servlet, or plain PHP. 

So we are primarily focused on ASP.NET Core here, and not backend databases.

With that in mind, taking a look at the definitions of `realistic` and `stripped` again, the _realistic_ approach is about having most out-of-the-box functionality of ASP.NET Core enabled, whether favorable to the ASP.NET Core benchmarks or not, while the _stripped_ approach optimizes as much as possible by removing everything that is not absolutely vital to making the benchmark succeed, in favor of ASP.NET Core benchmark performance.

The _stripped_ definition is exactly what the ASP.NET Core platform benchmarks do. They remove everything possible, and even go so far to manually parse the endpoint URI string character by character in the most efficient way.

@roji confirmed this in https://github.com/TechEmpower/FrameworkBenchmarks/pull/6566#issuecomment-833572837:

> I know it sounds a bit extreme, but the platform benchmarks are extreme (e.g. see the **totally stripped-down ASP.NET, which sane applications generally won't do**).

Therefore, the ASP.NET Core _platform_ benchmarks approach should be marked as `stripped` instead of `realistic`.

**Comment by lauxjpn** [comment]
> (I think a compelling counter argument could potentially be made, if other large competing frameworks do basically the same, either explicitly or implicitly, and are marked as realistic as well. **For example, if PHP does basically no processing, and the PHP script then manually parses the URI itself and then just executes the database queries, it could be argued that this is exactly what the ASP.NET Core platform benchmarks do.**)

That is essentially what the PHP _platform_ benchmarks do. So I guess if other platform benchmarks call themselves `realistic` independent of whether they actually are or not, the ASP.NET ones can do so as well.

**Comment by roji** [comment]
@lauxjpn the following defines the classifications (open the filters panel and hover over the question mark next to "classification":

```
Full-stack, meaning a framework that provides wide feature coverage including server-side templates, database connectivity, form processing, and so on.

Micro, meaning a framework that provides request routing and some simple plumbing.

Platform, meaning a raw server (not actually a framework at all).  Good luck! You're going to need it.
```

That seems to correspond to the reality of the implementations.

**Comment by lauxjpn** [comment]
@roji Yeah, I am not really questioning the classification. I am just questioning, that the `platform` classification can be part of the `realistic` approach. They seem to be mutually exclusive.

But if that is how it is handled across the board, and the benchmarks are therefore all shown by default so that all frameworks (not just ASP.NET Core) can flex, than I guess that's fine with me.
