### ISSUE TITLE
play-activate-mysql: Review multi-query approach

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#659]
The play-activate-mysql test permutation may be ignoring the spirit of the multiple query test.  My understanding is that Activate is an STM implementation and for the purposes of this test, it is effectively an in-memory cache.  This aligns Activate with (future) test type 7 from #133, which is a caching test.

As it is, the existing implementation yields the following outcome on EC2:

![ec2-mysql-multi-query](https://f.cloud.github.com/assets/777068/1717547/54f54cba-61d1-11e3-8ae4-3108b85a640f.png)

This is showing just MySQL tests (Mongo tests are not shown).

Put another way, if one to run a profiler on the MySQL database, all implementations should look the same—each web request should yield 20 database queries.  I suspect that play-activate-mysql is not actually running 20 queries per request, at least not consistently.

**Comment by msmith-techempower** [comment]
play-activate seems to have been removed entirely.
