### ISSUE TITLE
Disable PG log subsystem

### ISSUE THREAD

**Issue by NinoFloris** [TechEmpower/FrameworkBenchmarks#6627]
Locally I've noticed a big difference (in the order of >25% faster) between the default `log_destination='stderr'` and `log_destination=''`.

I'd like to do a run where it's off to see if it has similar effect on a larger machine. 
This would help faster clients widen the gap if they have it in them.

With a destination (note the 19.8% errfinish):
<img width="516" alt="Screenshot 2021-06-10 at 17 08 59" src="https://user-images.githubusercontent.com/4218809/121550146-c5187780-ca0e-11eb-8ad6-f2204c3c1d38.png">

Without (3.7%):
<img width="544" alt="Screenshot 2021-06-10 at 17 08 42" src="https://user-images.githubusercontent.com/4218809/121550189-ce094900-ca0e-11eb-8dbd-415b2779d9bc.png">

Most likely there are other paths in portal run not taken as a result of this being off as well.

**Comment by nbrady-techempower** [comment]
@NinoFloris Sorry about taking so long to look at this; been busy on our end. Discussing with the team now.

**Comment by nbrady-techempower** [comment]
Closing because it didn't look like we were seeing any real positive results from this and some frameworks and alt environments were failing. Thanks again for the test!
