### ISSUE TITLE
Errors - what does this number mean?

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#669]
I don't know what the value in the Errors column on the results website means.  Is it the number of 500-series responses during the "peak" test?

For example, in round 8 bottle-pypy had these requests/second numbers for the plaintext test:

```
concurrency     256     1,024    4,096   16,384
req/s        64,148    88,328   25,402   11,733
```

The errors column says "52".  Where does that number come from?

I think the results website should make this clear.  I wanted to reply to a Reddit comment [1] asking about the plaintext errors with, "The errors are there because we have over 16,000 concurrent clients," but I don't know if that's correct.

[1]http://www.reddit.com/r/programming/comments/1t4brc/framework_benchmarks_round_8/ce57v6k

**Comment by LadyMozzarella** [comment]
Closing - summarized in documentation.
