### ISSUE TITLE
cherrypy - missing from results

### ISSUE THREAD

**Issue by thezoggy** [TechEmpower/FrameworkBenchmarks#6698]
https://www.techempower.com/benchmarks/
cherrypy is not shown but does appear to be in the repo?

**Comment by nbrady-techempower** [comment]
![image](https://user-images.githubusercontent.com/1304934/125371150-00230900-e335-11eb-8dce-29601843afd8.png)


You can view the logs here: https://tfb-status.techempower.com/results/f78282e3-ed37-4e7c-9862-3163de23b23b

It did have some results in plaintext but all the database tests failed.
