### ISSUE TITLE
Consider EC2 c3.large instances instead of m1.large

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#670]
According to Florin Patan in the Google Group, c3.large instances may be cheaper than m1.large instances.

If it's relatively painless to switch over, I'd be willing to do it.  I need to see what the guys who actually do the EC2 work over here think about the idea of rebuilding the instances.  :)

For reference: https://groups.google.com/d/msg/framework-benchmarks/-D6mXi9N5qw/pM1H6jXurcAJ

**Comment by LadyMozzarella** [comment]
We are using c3.large now, closing.
