### ISSUE TITLE
Hyperlinks from boxes in result tables

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#679]
The lovely tables generated from the benchmark results contain a variety of little boxes for languages, frontends, etc.  How about hyperlinking each box to an external page, when appropriate?  For instance, the "language" column could contain links to the official sites for the various languages.  It might also be nice to hyperlink each framework name in the leftmost column to the official site for that framework.

I think this sort of feature gets more useful as more unusual frameworks get included!

**Comment by msmith-techempower** [comment]
Lots of changes to where we save the logs happening; closing this for now as it will be at the forefront of that effort.
