### ISSUE TITLE
Docker image `techempower/postgres:latest` build is failing 

### ISSUE THREAD

**Issue by adam-fowler** [TechEmpower/FrameworkBenchmarks#6841]
### OS (Please include kernel version)
macOS 11.4. This is also being seen on any new PR that requires a test of postgres. See #6838 and #6840

### Expected Behavior
Docker image `techempower/postgres:latest` builds

### Actual Behavior

techempower/postgres:latest fails to build. It generates the following error
```
techempower/postgres:latest: Step 19/35 : RUN mv postgresql.conf /etc/postgresql/${PG_VERSION}/main/postgresql.conf
techempower/postgres:latest:  ---> Running in 6dfeb5297267
techempower/postgres:latest: mv: cannot move 'postgresql.conf' to '/etc/postgresql/13/main/postgresql.conf': No such file or directory
techempower/postgres:latest: Removing intermediate container 6dfeb5297267
techempower/postgres:latest: Docker build failed; terminating
```
### Steps to reproduce behavior
- Ensure you don't have the `techempower/postgres:latest` image installed
- Run `./tfb --mode verify --test hummingbird-postgres`

**Comment by nbrady-techempower** [comment]
This is resolved atm, but want to look at upgrading to 14. thanks!
