### ISSUE TITLE
what's the next time to do benchmark tests? Can add rust framework "axum", which from tokio?

### ISSUE THREAD

**Issue by Athxx** [TechEmpower/FrameworkBenchmarks#6872]
what's the next time to do benchmark tests? Can add rust framework "axum", which from tokio?

**Comment by nbrady-techempower** [comment]
We don't currently have a timeline on the next round. You can open a PR to add axum if you'd like. Tests run continuously with results on https://tfb-status.techempower.com.

**Comment by dragosv** [comment]
Rust axum PR: https://github.com/TechEmpower/FrameworkBenchmarks/pull/6885
