### ISSUE TITLE
When Round 21? 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [TechEmpower/FrameworkBenchmarks#6913]
Am not sure what's the schedule of rounds, nor did I find it somewhere. It's been almost 9 months since Round 20 has published!

So when will Round 21 will be release?

**Comment by nbrady-techempower** [comment]
We will let you know in a pinned issue. There is no scheduled release. Unfortunately our resources are tied up paying the bills with clients. In the meantime, you can follow https://tfb-status.techempower.com for continuous benchmarking. Thanks for checking in.
