### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [TechEmpower/FrameworkBenchmarks#6943]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/91f02af3d2a26b851a2a7c2414bbfe292c773055/frameworks/Java/vertx/src/main/java/vertx/App.java#L408

The program can potentially fail to release a system resource.

**Comment by nbrady-techempower** [comment]
This isn’t a benchmarks issue. If you think there’s a problem with the code, please ping the maintainer or open a PR.
