### ISSUE TITLE
Missing Perl plack benchmarks 

### ISSUE THREAD

**Issue by vandergrafgenerator** [TechEmpower/FrameworkBenchmarks#6953]
plack-gazelle and plack-twiggy are only being benchmarked for Plain Text, Single Query and Multi Query. Why Fortunes and the other benchmarks are not being run?

What about benchmarking more plack servers like Starman, Starlet, Feersum and Corona (async)?

**Comment by nbrady-techempower** [comment]
@vandergrafgenerator We rely on community members like yourself to implement tests.

**Comment by vandergrafgenerator** [comment]
> @vandergrafgenerator We rely on community members like yourself to implement tests.

I will do that. But i am new to Github. I have yet to familiarize to it. I started to work on it to later realize i was pull requesting unfinished work in a messy way. 

As for the already existing Perl Plack benchmarks is there a way to contact the original developers? My nginx.conf performs ~30% better buy maybe they have reasons to keep the current nginx.conf.
