### ISSUE TITLE
Validation Failure - play-activate-mysql

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#707]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/play-activate-mysql/out.txt

<b>DB</b>
Invalid response:
expecting `{"id":3684,"randomNumber":8967}`
saw `[{"id":3684,"randomNumber":8967}]`

**Comment by LadyMozzarella** [comment]
play-activate-mysql is passes/warns on master. Good to close?
![play-activate-mysql](https://cloud.githubusercontent.com/assets/4926965/6472220/ab6ae26e-c1a5-11e4-86da-96c5ab282df7.png)
