### ISSUE TITLE
Validation Failure - play-scala-mongodb

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#710]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/play-scala-mongodb

See `err.txt` for the exact errors present.

**Comment by LadyMozzarella** [comment]
I have play-scala-mongodb as passing on master. Good to close?
![play-scala-mongodb](https://cloud.githubusercontent.com/assets/4926965/6471962/fdcb0d10-c1a3-11e4-870f-b810dd8fc3a6.png)
