### ISSUE TITLE
Some frameworks don't use a JSON serializer

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#7106]
A basic search for `{"message": "Hello, World!"}`, in the repo.

Return 23 files using it.

**Comment by nbrady-techempower** [comment]
@joanhey That's a little misleading, isn't it? That's how you instantiate an object before serialization in many cases? Like: `return web.json_response({"message": "Hello, World!"})`

**Comment by joanhey** [comment]
Yes @nbrady-techempower , my fault

What a week,

Sorry and closed.
