### ISSUE TITLE
Validation Failure - scalatra-raw

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#715]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/scalatra-raw/out.txt

<b>DB</b>
Invalid response:
expecting `{"id":3417,"randomNumber":2133}`
saw `[{"id":3417,"randomNumber":2133}]`

**Comment by LadyMozzarella** [comment]
Appears to be passing in the previews of round 10, closing.
