### ISSUE TITLE
Include memory usage in results

### ISSUE THREAD

**Issue by frmdstryr** [TechEmpower/FrameworkBenchmarks#7151]
Given that memory is often limited on VPS machines, I think it would be beneficial to include peak memory usage in the results. Would it be feasible to add this?

Thank you for hosting these benchmarks!

**Comment by billywhizz** [comment]
you can view the TE results in a nice layout with memory and other stats [here](https://ajdust.github.io/tfbvis/). you can also checkout the [repo](https://github.com/ajdust/tfbvis) for that site and view the results from any TE run locally by downloading the results.zip from the [status page](https://tfb-status.techempower.com/). click on [details](https://tfb-status.techempower.com/results/5871dabb-406e-4bd8-9caf-e8d65ab97888) for the run you want and there should be link for the zipped data.
