### ISSUE TITLE
Validation Failure - servicestack-nginx-postgresql

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#716]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/servicestack-nginx-postgresql

No response bodies are present for any of the tests.

See `out.txt` for the exact errors present.

**Comment by LadyMozzarella** [comment]
[Fixed in master](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/57577406#L4708). Closing.
