### ISSUE TITLE
scala-steward support in techempower

### ISSUE THREAD

**Issue by mosesn** [TechEmpower/FrameworkBenchmarks#7175]
Dependabot is really neat, but it [doesn't support scala](https://github.com/dependabot/dependabot-core/issues/352).  On the other hand, [scala-steward](https://github.com/scala-steward-org/scala-steward) is actively maintained and seems to be the solution embraced by the Scala community.  How would you feel about hooking up scala-steward support, so that we don't need to bump library versions manually anymore?

**Comment by nbrady-techempower** [comment]
@mosesn I don't have a problem with that, but maybe this is a question for the other scala maintainers here. A quick look at the repo makes it seem like it's simply a PR to add this repo and no permissions need to be set on our end? If that's the case, I'm fine with it.
