### ISSUE TITLE
Validation Failure - servicestack-xsp-postgresql

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#719]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/servicestack-xsp-postgresql

No response bodies are present for any of the tests.

See `out.txt` for the exact errors present.

**Comment by hamiltont** [comment]
@msmith-techempower Should we move all the servicestack validation errors from the [R9 milestone](https://github.com/TechEmpower/FrameworkBenchmarks/milestones/Round%209%20Validation) to the R11 milestone? They are all windows only and it may be helpful to close out the R9 milestone and actually focus on the R11 one

**Comment by msmith-techempower** [comment]
@hamiltont Yes, agreed.

**Comment by hamiltont** [comment]
Done
