### ISSUE TITLE
Validation Failure - silex-raw

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#720]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/silex-raw

No response bodies are present for any of the tests.

See `err.txt` for the exact errors present.

**Comment by dracony** [comment]
Totally missed the previous comment. Is help still needed ?

**Comment by msmith-techempower** [comment]
This has been closed and resolved via #1461 by @ssmith-techempower
