### ISSUE TITLE
Automatically bump releases with Dependabot

### ISSUE THREAD

**Issue by Dreamsorcerer** [TechEmpower/FrameworkBenchmarks#7200]
Rather than requiring manual PRs to update dependencies for every project, how about setting up Dependabot to automatically bump new versions across all the benchmarks. They can be tested and auto-merged without any human if tests still pass successfully.

**Comment by nbrady-techempower** [comment]
We just recently added this process but only for vulnerable updates.

**Comment by nbrady-techempower** [comment]
Many of the same reasons as https://github.com/TechEmpower/FrameworkBenchmarks/issues/7240#issuecomment-1085243712
