### ISSUE TITLE
Validation Failure - silica-raw

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#721]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/silica-raw

No response bodies are present for any of the tests.

See `err.txt` for the exact errors present.

**Comment by LadyMozzarella** [comment]
Is this issue good to close now that the Framework has been removed from the project with [Pull Request #1325](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1325)?
