### ISSUE TITLE
Validation Failure - slim

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#724]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/slim/out.txt

<b>DB</b>
Invalid response:
expecting `{"id":"3012","randomNumber":"8050"}`
saw `[{"id":"3012","random_number":"8050"}]`

<b>QUERY</b>
Invalid response:
expecting `[{"id":"9294","randomNumber":"3136"},{"id":"291","randomNumber":"6578"}]`
saw `[{"id":"9294","random_number":"3136"},{"id":"291","random_number":"6578"}]`

**Comment by LadyMozzarella** [comment]
Can we close this issue?

php slim is [passing on master](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/52758514) at [commit #f9d9df177b35316e6227957c7a93fdaff36ed8b1](https://github.com/TechEmpower/FrameworkBenchmarks/commit/f9d9df177b35316e6227957c7a93fdaff36ed8b1) on 2015/03/03.
