### ISSUE TITLE
Dependabot Bug: Invalid Update of Jackson Dependency

### ISSUE THREAD

**Issue by ebarlas** [TechEmpower/FrameworkBenchmarks#7282]
The dependabot bot broke the Microhttp Java test by updating pom.xml with an invalid version of Jackson.

Dependabot updated the version from `2.13.1` to `2.13.2.1`. It should have updated to `2.13.2`.

https://github.com/TechEmpower/FrameworkBenchmarks/commit/2b1ad6d767318e1ebd1e5793edf2935dbc3e7b32

**Comment by nbrady-techempower** [comment]
Oh, that's wild. You should open that bug there if you haven't yet and I'll revert this one.

**Comment by nbrady-techempower** [comment]
Actually, 2.13.2.1 seems fine in other frameworks. Not sure why it couldn't resolve it here.

**Comment by ebarlas** [comment]
I'm not sure how that's possible. It's not in Maven Central: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/
<img width="647" alt="Screen Shot 2022-04-08 at 1 17 37 PM" src="https://user-images.githubusercontent.com/221014/162522868-49e1eb96-8ed6-4b34-8a7d-42cdaf2b46d4.png">

**Comment by ebarlas** [comment]
And another perspective: https://github.com/FasterXML/jackson-core/blob/2.14/release-notes/VERSION-2.x

Simply put, there was no `2.13.2.1` from what I can tell.

**Comment by nbrady-techempower** [comment]
This one passed verification: https://github.com/TechEmpower/FrameworkBenchmarks/pull/7264/files#diff-c030bbee70eadf510d634868974a965290f0bd2cf86c67f2f48e120f241802a4

Wonder if it's possible they accidentally pushed a malformed version and dependabot picked up the latest right away.

**Comment by ebarlas** [comment]
Ah, now we're honing in on the problem.

`jackson-databind` _does_ have a version `2.13.2.1`. So it _is_ a bug with the Dependabot logic.

**Comment by ebarlas** [comment]
I'll avoid using a common property to configure dependency versions.

**Comment by ebarlas** [comment]
I'll submit a PR shortly with the corresponding change to pom.xml for Microhttp test.

**Comment by nbrady-techempower** [comment]
> I'll avoid using a common property to configure dependency versions.

Makes sense.

Thanks!

**Comment by ebarlas** [comment]
@nbrady-techempower, I created the following PR: https://github.com/TechEmpower/FrameworkBenchmarks/pull/7285

**Comment by ebarlas** [comment]
@nbrady-techempower, the following PR is ready for merge: https://github.com/TechEmpower/FrameworkBenchmarks/pull/7286

The inline dependencies ensure compatibility with Dependabot.
