### ISSUE TITLE
Tfb-status no commit and link

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#7317]
This is really useful, and now it's gone.

![image](https://user-images.githubusercontent.com/249085/166065773-3688a962-e4dc-4da2-824a-7cf152796839.png)

**Comment by heixiaoma** [comment]
I also think it's very important. I don't know why the official closed it, or will it release the test in 2022? Multi round test?

**Comment by nbrady-techempower** [comment]
Will look into it on Monday. This wasn't removed on purpose, so just an error somewhere.
