### ISSUE TITLE
Inconsistent NodeJS benchmarks

### ISSUE THREAD

**Issue by NagabhushanS** [TechEmpower/FrameworkBenchmarks#7355]
The NodeJS benchmarks are a bit inconsistent. I noticed that benchmarks for express and koa frameworks with MongoDB as a database are pretty bad (and by a weird margin) compared to the same frameworks with MySQL/PostgreSQL and also worse compared to fastify/polkadot in general. I looked into the code and found that:

1. The "express-mongodb" and "koa" benchmarks make use of Mongoose as a ORM which would degrade the benchmark results. 
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/express/mongodb-app.js
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/koa/models/mongoose.js
2. The polkadot/fastify mongodb benchmarks on the other hand, use the native mongodb driver which would be faster. https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/fastify/db/mongo.js and https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/polkadot/drivers/mongodb.js

I don't see a reason to use Mongoose as an ORM here since the benchmark routes are pretty straightforward and there is no need for an ORM. Also, even if we are using an ORM, it would be nice to make it consistent among the various NodeJS frameworks for unbiased comparison.

If the change from Mongoose to native MongoDB driver seems justifiable, I would be happy to create a PR for the same.

**Comment by nbrady-techempower** [comment]
> I don't see a reason to use Mongoose as an ORM here since the benchmark routes are pretty straightforward and there is no need for an ORM.

I think there's value in leaving an ORM implementation alongside a non-ORM implementation within the same framework to show the difference in speed. Feel free to do that.

We don't force standardization in all tests across a language. The goal isn't necessarily to see which framework "wins" when we strip all the rest of it out. We've talked about this a lot in the past. We love different variations and mutations. When you come here to interpret the results, it's to do exactly as you've done. "What are the reasons why this is faster? What are the tradeoffs in performance for using an ORM?" etc.
