### ISSUE TITLE
Format for passing "queries" parameter to page handlers

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#737]
I brought this issue up on the mailing list, but no one had any responses to share, so I figured I'd add it here, so there's at least a record that someone thought this small spec change would be nice.

Two of the tests require processing of "an integer query string parameter named queries."  However, the way the benchmarking is set up, it seems to be allowed to support any URL scheme that ends in the value of this parameter.  For instance, it looks like http-kit now implements the "db" test on top of the "queries" test with a URI "/http-kit/db/1", which has no query string.

I see two reasonable resolutions of this inconsistency:
1. Update the problem spec to say that the "queries" count can be processed from the end of a URI in whatever way is most natural for the framework.  (This seems to be what is actually implemented now.)
2. Tweak the validation logic to mark implementations as noncompliant when they pass "queries" with anything but the query string method requested in the spec.

I'm very much in favor of option 1!  Ur/Web doesn't usually use query strings, so a bit of ugly and unidiomatic code is required to parse "queries" currently.  A big part of the Ur/Web philosophy to avoid explicit parsing or use of strings for structured data in general, so this is the only place in the implementation now that does anything like parsing or conversion from strings.

I'd also prefer to see this requirement removed:
  "The queries parameter must be bounded to between 1 and 500. If the parameter is missing, is not an integer, or is an integer less than 1, the value should be interpreted as 1; if greater than 500, the value should be interpreted as 500."

The current benchmarking tools seem not to exercise any element of this requirement.  As a result, it seems to make sense to either (1) require that this parameter is always an in-range integer or (2) add validation that implementations actually implement the rules.

From my perspective, a 2nd-best resolution to this last point would be just to remove the requirement to handle missing or noninteger values, keeping the range clipping, which is easy to implement when the parameter begins life as an integer in the framework.

**Comment by LadyMozzarella** [comment]
Closing - summarized in documentation.
