### ISSUE TITLE
how to use the frameworkbenchmark？

### ISSUE THREAD

**Issue by smjbsb** [TechEmpower/FrameworkBenchmarks#7404]
Please tell me how to use the frameworkbenchmark benchmark benchmark pressure measuring tool. Do you have a detailed tutorial？

**Comment by nbrady-techempower** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/wiki

**Comment by smjbsb** [comment]
Using the frameworkbenchmarks tool for benchmarking, the time for a round of testing is about 100 hours, a total of 20 rounds, that is, does it take 2000 hours to complete an accurate test?

**Comment by nbrady-techempower** [comment]
I don't know what you mean by "a total of 20 rounds." 1 round is about 100 hours. That's a complete test. We've posted 20 official rounds on our site over time.

**Comment by smjbsb** [comment]
1. What does 20 official rounds mean? Do I need to test 20 times?
2. Can I perform benchmarking only for server performance? Can you share specific test commands? Because I don't understand the specific official documents, and I don't know which framework is only for server performance testing. Thank you!

**Comment by nbrady-techempower** [comment]
Only for server performance? Please read the wiki and the tests we perform, also in the wiki. I don’t think you understand what this tool is.

**Comment by smjbsb** [comment]
1、Using the frameworkbenchmarks tool for benchmarking, should I choose CentOS 、Ubuntu or Red hat operating system for testing？
2、Can you share specific test commands? Because I don't understand the specific official documents, Thank you!
