### ISSUE TITLE
Can we add Django REST Framework?

### ISSUE THREAD

**Issue by webdevstorage** [TechEmpower/FrameworkBenchmarks#7406]
### Expected Behavior
The benchmark should include Django REST framework. 
https://www.django-rest-framework.org/

### Actual Behavior
The benchmark is missing Django REST.
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/django

**Comment by nbrady-techempower** [comment]
Yes, you are free to add that implementation.
