### ISSUE TITLE
1、Using the frameworkbenchmarks tool for benchmarking, should I choose CentOS 、Ubuntu or Red hat operating system for testing？

### ISSUE THREAD

**Issue by smjbsb** [TechEmpower/FrameworkBenchmarks#7417]
1、Using the frameworkbenchmarks tool for benchmarking, should I choose CentOS 、Ubuntu or Red hat operating system for testing？
2、Can you share specific test commands? Because I don't understand the specific official documents, Thank you!

**Comment by smjbsb** [comment]
Thank you!    But In the test command (tfb --mode verify --test ${your-test-here}), what does this parameter (${your-test-here}) mean?

**Comment by smjbsb** [comment]
In the test command (TFB --mode verify --test ${your-test-here}), what   does     this    parameter    (${your-test-here}) 
 mean?

**Comment by smjbsb** [comment]
In the test command "TFB --mode verify --test   '${your-test-here}'", what does this parameter "${your-test-here}" mean?

**Comment by smjbsb** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/48588113/174424063-e3d77112-365f-4561-82c3-b10225a80f21.png">

**Comment by nbrady-techempower** [comment]
This is not an issue with the benchmarks. I can’t help you with this beyond the wiki.

**Comment by smjbsb** [comment]
What version of the Ubuntu system do you use? 18.04.1?

**Comment by smjbsb** [comment]
During the pressure test with the frameworkbenchmarks tool, after the machine instance runs for several hours, SSH cannot connect to the machine instance. Have you ever encountered such a problem?
