### ISSUE TITLE
Add HTTP/2 category

### ISSUE THREAD

**Issue by nordiauwu** [TechEmpower/FrameworkBenchmarks#7421]
Most frameworks sitting at the top (e.g., lithium, drogon) do not support HTTP/2; therefore, no one interested in performance will use them (in my humble opinion). That said, it is reasonable to introduce the HTTP/2 category.

**Comment by nbrady-techempower** [comment]
Thank you. This is on the list of things that may happen at some point and is in a few other open issues.

**Comment by nordiauwu** [comment]
> Thank you. This is on the list of things that may happen at some point and is in a few other open issues.

Oh, I'm sorry. I searched for other issues but couldn't find any.

**Comment by boohba** [comment]
@nbrady-techempower Any updates on this? Is there another issue specifically dedicated to the introduction of categories for modern HTTP versions? I'm afraid this set of benchmarks has become obsolete and therefore misleading.

![image](https://user-images.githubusercontent.com/58115165/227755425-16867a1f-b74e-48c1-95df-8e49d9b7bcb4.png)

**Comment by fakeshadow** [comment]
> @nbrady-techempower Any updates on this? Is there another issue specifically dedicated to the introduction of categories for modern HTTP versions? I'm afraid this set of benchmarks has become obsolete and therefore misleading.
> 
> ![image](https://user-images.githubusercontent.com/58115165/227755425-16867a1f-b74e-48c1-95df-8e49d9b7bcb4.png)

It would be great to have http/2 and http/3 bench but lacking of them does not make tfb obsolete (yet). There are some points worth consider:
1. people terminating http/2 and http/3 at load balancer and use http/1 locally does not show in your graph. it's still a popular practice.
2. json and database category give you a solid indirect reflection of any framework's http/2 performance(if it supports the spec). http/2 benchmark besides tls always end up benching for (de)serialization and io multiplexing.

**Comment by nouzu** [comment]
> 1. people terminating http/2 and http/3 at load balancer and use http/1 locally does not show in your graph. it's still a popular practice.

Using PHP is also a popular practice, but it's certainly not the best. 

> 2. json and database category give you a solid indirect reflection of any framework's http/2 performance(if it supports the spec). http/2 benchmark besides tls always end up benching for (de)serialization and io multiplexing.

I disagree. If some framework has a fast JSON implementation doesn't mean their TLS and HTTP/2 implementations are fast too.
