### ISSUE TITLE
missing `dart2` result in round 21

### ISSUE THREAD

**Issue by iapicca** [TechEmpower/FrameworkBenchmarks#7480]
[dart2](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Dart/dart2) has been [added to the frameworks](https://github.com/TechEmpower/FrameworkBenchmarks/pull/6549)
but results are not shown in any of the [rankings for round 21](https://www.techempower.com/benchmarks/#section=data-r21)

this is particularly unfortunate because the only other [dart](https://dart.dev) examples are **_seven_** years old
(or `angel` framework with a ranking that matches my personal experience)

is it possible to update the ranking?

cc @kevmoo  @nbrady-techempower

**Comment by nbrady-techempower** [comment]
@iapicca "Stripped" approaches are not shown by default. This is working as intended. To show stripped results, you have to open the filters panel and apply the changes.

![image](https://user-images.githubusercontent.com/1304934/180018800-061219d2-f326-4010-a49c-f51169afe67f.png)

**Comment by iapicca** [comment]
thank you @nbrady-techempower 

not the results I was expecting @kevmoo 

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/45637986/180036191-f92579c0-4e04-4c14-8ad5-a8dc42d612a3.png">
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/45637986/180036325-cd62538a-188c-4590-91e5-038d450984cd.png">

**Comment by kevmoo** [comment]
Totally agree, @iapicca – Dart 2 caused some regressions due to our type system changes.

We have some low hanging fruit to fix here. Just need to get on it!

**Comment by mit-mit** [comment]
@nbrady-techempower what is the definition of a "stripped approach"?

**Comment by kevmoo** [comment]
> @nbrady-techempower what is the definition of a "stripped approach"?

No framework?
