### ISSUE TITLE
Request per second wrongly calculated on the Website

### ISSUE THREAD

**Issue by laupse** [TechEmpower/FrameworkBenchmarks#7486]
It seems that there is an issue with Request per second of the website. 
I was checking the result of round 21 directly with json API, and recalutlating RPS since it is not present it the json response. 

But my result deffer. It seems that on the website the totalrequests is always divided by 15 but sometimes it should be divided by the something else which, i guess, is the result of `endTime - startTime`

example : 
```
# axum-pg 20row multiple query
endTime: 1656650869
latencyAvg: "14.49ms"
latencyMax: "32.49ms"
latencyStdev: "3.19ms"
startTime: 1656650853
totalRequests: 523203
```
`1656650869-1656650853=16 523203/16=32 700,1875`

![image](https://user-images.githubusercontent.com/98523125/180415835-3072b187-29d2-4734-80b1-77c7349136e0.png)

### Expected Behavior
Divide total request by `endTime-startTime`
### Actual Behavior
Divide total request by 15

**Comment by nbrady-techempower** [comment]
The short story on this is that the `startTime`/`endTime` is not an accurate representation. The only requests that get counted here are within 15 seconds, but the `endTIme` is often when the last (uncounted) request is returned.

**Comment by joanhey** [comment]
Check this https://github.com/TechEmpower/FrameworkBenchmarks/issues/7402#issuecomment-1176859459

**Comment by laupse** [comment]
Ok i was expected this response. i'll align on this. Thx for the clarification !
