### ISSUE TITLE
Update spring versions and optimize docker JVM building

### ISSUE THREAD

**Issue by EdminioPerez** [TechEmpower/FrameworkBenchmarks#7497]
### Discussed in https://github.com/TechEmpower/FrameworkBenchmarks/discussions/7496

<div type='discussions-op-text'>

<sup>Originally posted by **EdminioPerez** July 27, 2022</sup>
Hi!!

I would like to make a PR upgrading the spring version to the latest and optimize the building of the Docker using the Eclipse Temuring JRE, that is a JVM optimized for Prod Environments</div>

**Comment by nbrady-techempower** [comment]
You're welcome to do that. We don't track those types of upgrades/updates in issues here.

**Comment by EdminioPerez** [comment]
> You're welcome to do that. We don't track those types of upgrades/updates in issues here.

Hi Nbrady, thanks for your reply, I'll try to push a PR with the changes
