### ISSUE TITLE
dead code in the D postgres code

### ISSUE THREAD

**Issue by SingingBush** [TechEmpower/FrameworkBenchmarks#7515]
I was just looking at the D code and saw this line

https://github.com/TechEmpower/FrameworkBenchmarks/blob/38a10251e5587a4ea038d35a3156bf64208c091b/frameworks/D/vibed/source/postgresql.d#L116

which builds a query string that isn't used. There is a prepared statement defined elsewhere in the code that is being used so that line is redundent

**Comment by nbrady-techempower** [comment]
You can open up a PR if you'd like to fix it, but no need to track that issue here. Thanks!
