### ISSUE TITLE
High Number of frameworks having problems starting

### ISSUE THREAD

**Issue by billywhizz** [TechEmpower/FrameworkBenchmarks#7557]
in the last run and the current one just-js and a number of other frameworks seem to have failed to start. it has never failed before and nothing has changed since round 21.

it seems the number of frameworks failing in same way has increased significantly in last round and the one currently running. is there some environmental issue causing problems maybe?

https://tfb-status.techempower.com/results/15bfed85-1093-485d-b161-5f61b7abd0be

**Comment by nbrady-techempower** [comment]
A few spot checks have me believing it's the postgres upgrade. @joanhey does that seem right to you?

**Comment by joanhey** [comment]
After some research, it seems correct that it affects these fails.
I have had to look at other fws, because Just doesn't give any errors.
The others return `... authentication type: 10`

It's again the problem with the auth encryption. That come from postgresql v10.

New in Postgresql 14:

> Change the default of the [password_encryption](https://www.postgresql.org/docs/14/runtime-config-connection.html#GUC-PASSWORD-ENCRYPTION) server parameter to scram-sha-256 (Peter Eisentraut)
> 
> Previously it was md5. All new passwords will be stored as SHA256 unless this server setting is changed or the password is specified in MD5 format. Also, the legacy (and undocumented) Boolean-like values which were previously synonyms for md5 are no longer accepted.

Now I'll send a PR.

**Comment by billywhizz** [comment]
@joanhey thanks for investigating - so this means all frameworks must support/use scram-sha-256 authentication in their PG driver?

**Comment by joanhey** [comment]
`Scram-sha-256` was introduced in Postgesql v10. (October 5, 2017)
And it's the recommended method for a most secure connection. And any new PG driver need to support it.

I changed the default to md5 again in `postgresql.conf` in the PR.
And Just-js is working again, and the rest.

Historically this bench use md5, because at the time of this change, most pg drivers didn't suppor scram-sha-256.
Something similar happens with Mysql 8.

**Comment by billywhizz** [comment]
thanks @joanhey - i will look at adding scram-sha-256 support to the postgres driver for just-js.

**Comment by joanhey** [comment]
A new think in Postgresql 14 is **pipeline** mode in `libpg`, and also work with older servers versions.

Some fws in this bench use hand made versions.

https://www.postgresql.org/docs/current/libpq-pipeline-mode.html
https://www.percona.com/blog/how-postgresql-pipeline-mode-works/

**Comment by billywhizz** [comment]
> PD I hope that more pg drivers start to add the pipeline mode.

@joanhey i don't understand this comment when a number of frameworks were already doing pipelining on previous postgres protocol but were told it wasn't allowed? somebody needs to clarify this.

**Comment by joanhey** [comment]
@billywhizz 
I was talking about pg drivers, not about the benchmark.

And remember that pipeline is not for use in all apps.

> Since each SQL statement is essentially idempotent it is up to the client logic to make sense of the results. Sending SQL statements and pulling out results that have no relation with each other is one thing but life gets more complicated when working with logical outcomes that have some level of interdependence.
> 
> It is possible to bundle asynchronous SQL statements as a single transaction. But as with all transactions, failure of any one of these asynchronously sent SQL statements will result in a rollback for all the SQL statements.
> 
> Of course, the API does provide error handling in the case of pipeline failures. In the case of a FATAL condition, when the pipeline itself fails, the client connection is informed of the error thus flagging the remaining queued operations as lost. Thereafter normal processing is resumed as if the pipeline was explicitly closed by the client, and the client connection remains active.

**Comment by billywhizz** [comment]
@joanhey i still don't understand the implication of what you are saying. i raised the point that this is officially supported behaviour in postgres wire protocol already [here](https://github.com/TechEmpower/FrameworkBenchmarks/issues/7019#issuecomment-1040727395) 
![Screenshot from 2022-08-22 22-40-01](https://user-images.githubusercontent.com/159073/186023703-11423465-08c1-45e1-b90d-2063fd5c3aba.png) and we were told it is not allowed. 

so, is pipelining allowed or not going forward?
