### ISSUE TITLE
mORMot is breaking the rules

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#7692]
https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#fortunes

![image](https://user-images.githubusercontent.com/249085/201448048-6bece834-c984-4710-9def-11396db69364.png)

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Pascal/mormot/src/raw.pas#L242-L255

:-1:

**Comment by joanhey** [comment]
@pavelmash 
We all know how to do it soo.

**Comment by joanhey** [comment]
![image](https://user-images.githubusercontent.com/249085/201448640-2c1da673-ad38-4c93-a464-902ce86ac1c3.png)

![image](https://user-images.githubusercontent.com/249085/201448674-5f01f507-8661-47fb-8273-c3923d0ee56e.png)

Sorry !!

**Comment by joanhey** [comment]
@nbrady-techempower 
I think that it's necessary to add a test, than any fw that is faster using db vs json will not pass the test.

**Comment by pavelmash** [comment]
Constant with fortunes table content is under {$ifdef USE_SQLITE3} condition - it's used ONLY for filling SQLITE3 database what we use for testing. For TFB  tests app is compiled without -dUSE_SQLITE3, so this lines is not used at all. But you are right - it's confused a little - I will remove it.

JSON serialization is slower compared to db because we spawn threads = 4*CPU count and there is indeed problems with scalability in our HTTP server implementation - we working on it.

**Comment by synopse** [comment]
This is clearly a false positive.
@joanhey is wrong about his/her guess. This fixed array is used for `GenerateDB` below which is NOT for the fortunes test.
The fortunes tests are implemented either in  `TRawAsyncServer.fortunes` or `TRawAsyncServer.rawfortunes` and both use clearly a `TDynArray` dynamic list.
Please look at the exact code, not making wild guesses.

The fact that  /json is somewhat slower than /db or /fortunes is that the HTTP server becomes a bottleneck with a lot of cores, as @pavelmash stated.
Something +/- 10% is not a good indication of being actually slower.

**Comment by synopse** [comment]
> @nbrady-techempower I think that it's necessary to add a test, than any fw that is faster using any db test vs json will not pass the test.

Yes, but with a real margin.

The fact that /json is somewhat slower than /db or /fortunes is that the mormot HTTP server becomes a bottleneck with a lot of cores, as @pavelmash stated.
Something +/- 10% is not a good indication of being actually slower.

**Comment by joanhey** [comment]
I don't know Pascal, like more people.
But I still think that it's better to delete this constant from the code.

And about the difference between json and db, it's not normal.
And naturally looks suspicious, without a clarification.

**Comment by joanhey** [comment]
It's not about 10% difference between json and db.

All frameworks that have ~300K req/s with 1 query, have about ~1 million req/s with json.
But mORMmot is the first fw than have less.

**Comment by joanhey** [comment]
![image](https://user-images.githubusercontent.com/249085/201489832-511e8291-e3b6-4718-a4cb-f14c18b9ab47.png)

With the plaintext 2,333,124 req/s and with json 320,078 req/s.
If the json encoder is slow also will be with the 1 query, because need to be converted to json too.

I like all the fast frameworks from any language, but we try to check suspicious thinks.
To have a fair play in the benchmark. 
And also to help checking strange behaviours to the creators of the frameworks.

**Comment by synopse** [comment]
That is a strange behavior we try to fix, indeed.
But the test code is fair and don't break any rule.
