### ISSUE TITLE
Any concerns with using a pre-built image?

### ISSUE THREAD

**Issue by rbjorklin** [TechEmpower/FrameworkBenchmarks#7742]
I have contributed an implementation for one of the OCaml frameworks and since then more have been added. I see an opportunity to save some time on the test run by pre-baking an image with the OCaml compiler along with all the dependencies across the different frameworks. Another potential benefit of doing this is if dependencies aren't pinned they would still always be the same in the pre-built image leading to more consistent test runs.

Would something like this be well received?

**Comment by nbrady-techempower** [comment]
@rbjorklin I don't have any problems with this, so long as it doesn't obfuscate anything obvious. We of course still need all the test implementation code in this repository.
