### ISSUE TITLE
Doubts about results

### ISSUE THREAD

**Issue by panicoenlaxbox** [TechEmpower/FrameworkBenchmarks#7752]
Hello,

Is there a list of the libraries/frameworks somewhere along with a link to their code repository? For example, in the Plaintext test the best ranker is pico.v, but what is pico.v? A google search gives me several results and I'm not sure what it is.

On the other hand, and just to confirm, for example in Plaintext, pico.v has a value of 7,028,146 in round 21, does that mean that it has been able to process that number of requests per second (specifically for the column 1024 concurrent users )?.

Thanks and regards.

**Comment by nbrady-techempower** [comment]
You can usually find all the links you need in the README for that framework in this repository. In this case: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/V/pico.v

7,028,146 is the total number of requests in the ~15m test time.

**Comment by panicoenlaxbox** [comment]
Thank you so much @nbrady-techempower for your quick response.

It's clear where I can find the source code of each language/framework. Nothing to say, too much to study. 👍 

However, for my second question (and I know it's my fault) I still have a doubt.

You said, "7,028,146 is the total number of requests in the ~15m test time". 

"15m" or "15s" (minutes or seconds)? 

FAQ says the following:

*"How is each test run?" Each test is executed as follows:
Run a 15-second captured test for each of the concurrency levels (or iteration counts) exercised by the test type. Concurrency-variable test types are tested at 16, 32, 64, 128, 256, and 512 client-side concurrency. The high-concurrency plaintext test type is tested at 256, 1,024, 4,096, and 16,384 client-side concurrency."*

I don't find any place where documentation talk about minutes, it's always about seconds.

If I filter to pico.v, I see:

![image](https://user-images.githubusercontent.com/1210159/204617251-b2ec305a-1fab-4463-b78b-7a86961fa75e.png)

For me, it means that requests/per second were these in a test of 15s (no minutes) of duration:

| client-side concurrency | responses per second |
| ----------------------- | -------------------- |
| 256                     | 6,999,305            |
| 1,024                   | 7,028,146            |
| 4,096                   | 6,999,826            |
| 16,384                  | 6,849,922            |

7,028,146 seems to be the best round for pico.v (with 1,024 concurrent users it was able to respond 7,028,146 requests/per second).

I'm sure I am missing something, sorry in advance, but I was discussing with a colleague this morning and we are not able to read properly the results.

Thank you very much and sorry for my insistence.

**Comment by nbrady-techempower** [comment]
Yes, sorry, I misspoke. It's ~15sec and I had the wrong total requests. You can see more raw data on https://tfb-status.techempower.com.

So you would see something like this in the `results.json`:

```
      "ffead-cpp-v-picov-raw-profiled": [
        {
          "latencyAvg": "327.65us", 
          "latencyMax": "13.76ms", 
          "latencyStdev": "225.28us", 
          "totalRequests": 104959792, 
          "startTime": 1670078943, 
          "endTime": 1670078958
        }, 
```

Sorry for adding to your confusion! 😓
