### ISSUE TITLE
Tfb-status benchmark stuck!!

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#7787]
![image](https://user-images.githubusercontent.com/249085/207090325-4f75edd9-aeaf-4687-b965-59420c31099f.png)

**Comment by nbrady-techempower** [comment]
We’ve got an extended power outage happening today. Might not be back up until tomorrow.

**Comment by joanhey** [comment]
In the meantime, Could you try a run in Azure?

**Comment by nbrady-techempower** [comment]
@joanhey No, unfortunately that infrastructure has been down for some time. I'll see if we can get someone to take a look at it, but we're extremely over-utilized atm.

**Comment by joanhey** [comment]
Stuck again !!

**Comment by cirospaciari** [comment]
![image](https://user-images.githubusercontent.com/6379399/208302213-1dd69ef0-6c39-41a8-90e0-fc3b74e09849.png)

yeah I think is stuck again

**Comment by nbrady-techempower** [comment]
We're aware of the issue and are investigating. Hope to have an update tomorrow.

**Comment by nbrady-techempower** [comment]
We'll be bringing the machines up on Thursday morning. We have a scheduled power outage tomorrow so it doesn't make sense to get another run going. Will update here when we're live. Thanks for your patience!

**Comment by nbrady-techempower** [comment]
We are back up and running. Will keep an eye on it but should be good for a full run now!

**Comment by cirospaciari** [comment]
@nbrady-techempower i think something is wrong again 
![image](https://user-images.githubusercontent.com/6379399/217956253-8d857dab-0bee-4810-8aeb-2749a19aed6c.png)
