### ISSUE TITLE
Round 21 cloud results not available

### ISSUE THREAD

**Issue by ravihara** [TechEmpower/FrameworkBenchmarks#7796]
### OS (Please include kernel version)
Windows 10 Business (22H2) - 64-bit operating system, x64-based processor

### Expected Behavior
Results for round 21 should be available when the Hardware selected is "Cloud"

### Actual Behavior
No Results shown. On inspecting the page, it has been found that, the page is unable to get the JSON https://www.techempower.com/benchmarks/results/round21/cl.json

### Steps to reproduce behavior
Open the link https://www.techempower.com/benchmarks/#section=data-r21&l=zijz7j-6bj&f=0-0-0-0-0-0-9zlds-6bk-0-0-9zlds-0-0-0&test=composite&hw=cl in Chrome or Firefox

Further, one can open the developer console using "Inspect" element option by right-clicking on the page. In the console tab you can see "Failed to load resource" error.

### Other details and logs
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/383541/208108476-1bd55f7f-e2e2-4e80-aad1-3e3e89331b3c.png">

**Comment by nbrady-techempower** [comment]
Thanks. Unfortunately, we did not release results on cloud for the last round. Only the physical hardware.

**Comment by ravihara** [comment]
> Thanks. Unfortunately, we did not release results on cloud for the last round. Only the physical hardware.

Thank you. Will it be available anytime soon for the cloud?
