### ISSUE TITLE
PostgreSQL table "world" has column "randomnumber", JSON check requires "randomNumber"

### ISSUE THREAD

**Issue by RockinRoel** [TechEmpower/FrameworkBenchmarks#783]
I'm working at Emweb to implement the benchmarks for Wt, but the PostgreSQL backend of Wt::Dbo uses case-sensitive column names. For the next release of Wt, we're working on a JSON serializer that can directly serialize Wt::Dbo objects to JSON. However, the tests require the randomNumber field in the returned JSON to be written with a capital N, whereas it is actually called randomnumber with a lower letter n in the table. Wt::Dbo maps both to the same name, however, and uses case sensitive PostgreSQL queries. Can either the column name change, or can the test validator allow for variations in case?

**Comment by KostyaTretyak** [comment]
In SQL scripts, the "randomNumber" field is first created, but later "randomnumber" is already accessed. And this is not considered a bug? Why?

https://github.com/TechEmpower/FrameworkBenchmarks/blob/6f69295366504897b74ede5f5397af3644a42285/toolset/databases/postgres/create-postgres.sql#L7-L12
