### ISSUE TITLE
Framework not accepting requests from client machine

### ISSUE THREAD

**Issue by saru-tora** [TechEmpower/FrameworkBenchmarks#7836]
When trying to test a new framework, it says "ERROR: Framework is not accepting requests from client machine", but not much else. It's running on 127.0.0.1:8080, and the port is EXPOSED in the docker file. Is there something I'm missing? Also, each time a test is run, it seems to add several gigabytes to disk. I tried pruning dangling images, but that didn't seem to do anything. Is there a way around this?

**Comment by nbrady-techempower** [comment]
Hi @saru-tora - Can you open a draft PR with the current state so I can take a look.

**Comment by saru-tora** [comment]
Thanks, @nbrady-techempower - here it is: https://github.com/TechEmpower/FrameworkBenchmarks/pull/7842

**Comment by gkresic** [comment]
@nbrady-techempower Do you have any advice regarding this? I'm experiencing exactly the same problem. Pulled master in a hope that there is a fix, but I'm getting that error even with up-to-date code from master?
