### ISSUE TITLE
Wrong RoadRunner config + update is recommended

### ISSUE THREAD

**Issue by tarampampam** [TechEmpower/FrameworkBenchmarks#7854]
Could you please comment or remove the following line, since this option is not required and was added in the readme just as an example:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/a2c074a6bb48eee45e87cd7cc2a56c819c46d5b6/frameworks/PHP/laravel/deploy/roadrunner/.rr.yaml#L12

And in addition, could you update the RoadRunner up to [v2.12.1](https://github.com/roadrunner-server/roadrunner/releases/tag/v2.12.1)?

**Comment by nbrady-techempower** [comment]
Please feel free to open a PR yourself or ping the maintainer of the test. We rely on the community to maintain the tests.

**Comment by tarampampam** [comment]
Hi @nbrady-techempower! I have made PR #7857
