### ISSUE TITLE
Tfb-status benchmark stuck again

### ISSUE THREAD

**Issue by cirospaciari** [TechEmpower/FrameworkBenchmarks#7913]
@nbrady-techempower 

same as https://github.com/TechEmpower/FrameworkBenchmarks/issues/7787

![image](https://user-images.githubusercontent.com/6379399/218148062-37915b9e-b351-4caf-83ad-ae772735adf0.png)

just opening this so we keep track of the resolution

**Comment by nbrady-techempower** [comment]
Resolved this on Friday. Thanks!
