### ISSUE TITLE
Can you add some frameworks about io_uring, such as monoio

### ISSUE THREAD

**Issue by favouriter** [TechEmpower/FrameworkBenchmarks#7930]
I hope I can pay attention to the framework test related to io_uring

**Comment by volyrique** [comment]
The current benchmarking environment does not support `io_uring` properly because the host kernel is too old; issue #7321 tracks the OS update.

**Comment by fakeshadow** [comment]
FYI you can look into https://github.com/monoio-rs/monoio-http which can at least be used to implement json and plaintext benchmark.

**Comment by nbrady-techempower** [comment]
The Citrine environment has been upgraded.
