### ISSUE TITLE
JavaScript/NodeJS tests realistic?

### ISSUE THREAD

**Issue by JesseDocken** [TechEmpower/FrameworkBenchmarks#7974]
I was looking at the benchmarks and the configuration for the JavaScript dockerfile, and it looks like it only spins up one instance of the application, which means it only utilizes a single thread for event processing.  In contrast, a large number of frameworks spin up a worker thread for each core present, which means that the comparison is not necessarily production-realistic.

**Comment by pavelmash** [comment]
They forks inside a app - see, for example, https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/express/app.js#L17
