### ISSUE TITLE
SPDY support

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#810]
There has been some interest in testing SPDY in a future round.  In order to do so, we'd need to have web and/or application servers equipped with SPDY functionality (for example, nginx) that are configured appropriately.  Additionally, we'd need to ask @wg to participate by enhancing Wrk to support SPDY.

Although I've read a bit on SPDY, I've never actually deployed it, so I don't know the particulars.

All of this makes SPDY support a wish-list item.  If it can happen without causing too much pain in the future, we'd like to have it.  But I don't want it to be a gate for any specific future round.

**Comment by methane** [comment]
[h2load](https://github.com/tatsuhiro-t/nghttp2#benchmarking-tool) supports SPDY and HTTP/2

**Comment by nbrady-techempower** [comment]
SPDY now deprecated. Closing for now.
