### ISSUE TITLE
[Python] Falcon unification issues

### ISSUE THREAD

**Issue by cirospaciari** [TechEmpower/FrameworkBenchmarks#8137]
@remittor Thanks for unifying the Falcon code, I really appreciate that and it's the right move for sure. Just opened this issue so we can chat about it.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/8111

This PR has some issues:
Falcon does not need to add Server and Date when using socketify and it adds unnecessary overhead, checking global scope is slow on CPython (but acceptable on PyPy).
The servers should emit these headers or a simple wrapper only on apps that need that to emit this would be a better solution, and fairer with servers that already include this natively.

Performance diffs for socketify WSGI on CPython:
Before: 433,316
After: 356,027

**Comment by remittor** [comment]
> checking global scope is slow on CPython (but acceptable on PyPy).
> socketify WSGI on CPython:  Before: 433,316  After: 356,027

I think that the drop in speed is not caused by the addition of the common function `add_ext_headers`.
It is very likely that the drop in speed caused the downgrade of `CPython` to version 3.9 (previously used version 3.10).

Speeds for Falcon+FastWSGI: before: 497,777 after: 496,506

**Comment by cirospaciari** [comment]
For socketify CPython can run on 3.11 the latest version (with includes a lot of performance improvements) I think all servers can run on 3.11

**Comment by remittor** [comment]
> I think all servers can run on 3.11. ( and soon 3.12)

I don't mind at all. I just thought that there would be compatibility issues with some modules.
So I suggest you do the following:
1) Convert all `falcon` tests to python 3.10...311.
2) Fix `django` (since you yourself promised to do it)
3) Help to understand the reason for not started `flask` + `uwsgi` (everything works on CI)
4) Help to understand the reason for not working `flask` test `update` (everything works on CI)

**Comment by cirospaciari** [comment]
Agreed, unfortunately, I'm working a lot in my current job, and spending my little free time with my family, soon I should be able to have more time  to work on this
