### ISSUE TITLE
Issues with the benchmarking instructions on the Wiki

### ISSUE THREAD

**Issue by volyrique** [TechEmpower/FrameworkBenchmarks#8141]
The getting started [guide](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Benchmarking-Getting-Started) for benchmarking on the Wiki is missing some details or contains outdated data:
- The final `docker run` command is missing a parameter:
`-e USER_ID=$(id -u)`
- there are no instructions how to build the `techempower/tfb` image, i.e. by running:
`docker build --build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) -t techempower/tfb .`
(I think that simply executing `./tfb --help` would work too)
- the operating system is no longer `Ubuntu Server 16.04 LTS 64-bit`

Veteran contributors to the project are aware of these steps, of course, but beginners might have difficulties figuring them out.

**Comment by nbrady-techempower** [comment]
Thanks @volyrique!
