### ISSUE TITLE
It is required to finally determine the value of the parameter net.core.somaxconn

### ISSUE THREAD

**Issue by remittor** [TechEmpower/FrameworkBenchmarks#8151]
Now the CI system sets the value of the parameter `net.core.somaxconn` = **65536** ([proof link](https://github.com/TechEmpower/FrameworkBenchmarks/commit/d5cd2a78d147b24a09a1f29194bcc220eba4b941#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R221))
(Note: in fact, I don’t know the exact value, because `travis CI` is not currently in use)

But in production system, all tests are run with the value **4096** ([proof link](https://tfb-status.techempower.com/unzip/results.2023-04-13-01-30-40-927.zip/results/20230406155252/uwsgi-nginx-uwsgi/run/uwsgi-nginx-uwsgi.log))

There are many issues and pull requests on this subject: https://github.com/TechEmpower/FrameworkBenchmarks/issues?q=somaxconn

It is already necessary to decide what value should be in production.

--------
I also want to clarify the value of the `net.ipv4.tcp_max_syn_backlog` parameter, because some tests refer to it.

--------
The value of these [parameters in 2017](https://github.com/TechEmpower/FrameworkBenchmarks/issues/2854) were as follows:
```
net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
```

**Comment by nbrady-techempower** [comment]
Those were the settings in vagrant. We never adjusted those settings in Citrine. `net.core.somaxconn` has always been `4096` in this environment as far as I'm aware.

Though I'm happy to leave this open to have a discussion about changing these.

**Comment by remittor** [comment]
@nbrady-techempower 
> We never adjusted those settings in Citrine. net.core.somaxconn has always been 4096

This is unlikely, because until 2023, projects using `uWSGI` were correctly launched (they had into config `listen = 65535`).
Then something happened and this appeared in the run logs: [run.log](https://tfb-status.techempower.com/unzip/results.2023-04-13-01-30-40-927.zip/results/20230406155252/uwsgi-nginx-uwsgi/run/uwsgi-nginx-uwsgi.log)

On the `CI` system, everything always started without errors.

**Comment by remittor** [comment]
It was possible to find out more precisely when everything broke.
2022-01-22: **OK** https://tfb-status.techempower.com/unzip/results.2022-01-27-10-45-01-139.zip/results/20220122165234/uwsgi/run
2022-01-31: **Fail** https://tfb-status.techempower.com/unzip/results.2022-02-05-08-28-48-272.zip/results/20220131174100/uwsgi/run

**Comment by remittor** [comment]
I even managed to find out the exact values of this parameter.

2022-01-22: https://tfb-status.techempower.com/unzip/results.2022-01-27-10-45-01-139.zip/results/20220122165234/racket/run
```
racket: 7:M 26 Jan 11:04:56.441 # WARNING: The TCP backlog setting of 65535 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 16384.
racket: 7:M 26 Jan 11:04:56.441 # Server started, Redis version 3.2.6
```

2022-01-31: https://tfb-status.techempower.com/unzip/results.2022-02-05-08-28-48-272.zip/results/20220131174100/racket/run
```
racket: 8:M 11 Apr 11:06:39.480 # WARNING: The TCP backlog setting of 65535 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 4096.
racket: 8:M 11 Apr 11:06:39.480 # Server started, Redis version 3.2.6
```

That is, the value has changed from **16384** to **4096**.

**Comment by nbrady-techempower** [comment]
It's possible the machines were commissioned with those set and that first upgrade reverted config values. I'll let this run finish and we'll see about updating them.

**Comment by nbrady-techempower** [comment]
Unfortunately couldn't get in to get to this today, but coming first thing Monday!

**Comment by nbrady-techempower** [comment]
Citrine is updated

**Comment by nbrady-techempower** [comment]
@michaelhixson:

```
net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
```

Putting it into the wiki

**Comment by michaelhixson** [comment]
The `net.ipv4.tcp_te_reuse = 1` is a change from what we had in 2020 at least.  See https://github.com/TechEmpower/FrameworkBenchmarks/issues/4092#issuecomment-614772349

At that time, we noticed that changing it to `1` would "solve" issues for a few frameworks, but we decided not to change it because the real problem was those frameworks not reusing their own connections.  If we want to go back on that decision, it's fine, but setting this to `1` would be something brand new for us.

**Comment by remittor** [comment]
> ...we decided not to change it because the real problem was those frameworks not reusing their own connections.

780 * 60 sec = 46800 sec = 780 min = **13 hours**

And here you need to choose an option:
1) greater realism
2) testing acceleration

**Comment by remittor** [comment]
@nbrady-techempower , too early you closed this issue.
After the `imi-workerman` test, everything completely broke down.

![image](https://user-images.githubusercontent.com/9350115/234832944-5ff81b92-90f0-4fdd-a072-cb0d584b1381.png)

![image](https://user-images.githubusercontent.com/9350115/234833436-3cadcaed-c2d6-4b28-865d-3f803528c7c5.png)

It's too bad that the `run.log` can't be viewed now.

**Comment by remittor** [comment]
here is another place where everything broke:

```
    "ronykit": "20230429155022", 
    "ronykit-prefork": "20230429155612", 
    "routerling": "20230429160913", 
    "sailsjs": "20230429161412", 
    "salvo": "ERROR: Problem starting salvo", 
    "salvo-diesel": "ERROR: Problem starting salvo-diesel", 
    "salvo-moka": "ERROR: Problem starting salvo-moka", 
    "salvo-mongo": "ERROR: Problem starting salvo-mongo", 
    "salvo-mongo-raw": "ERROR: Problem starting salvo-mongo-raw", 
    "salvo-pg": "ERROR: Problem starting salvo-pg", 
    "salvo-pg-pool": "ERROR: Problem starting salvo-pg-pool", 
    "salvo-sqlx": "ERROR: Problem starting salvo-sqlx", 
    "sanic": "ERROR: Framework is not accepting requests from client machine", 
    "scalene": "20230429165232", 
    "scorper": "20230429165834", 
    "servant": "ERROR: Problem starting servant", 
    "servant-psql-simple": "ERROR: Problem starting servant-psql-simple", 
    "servicestack-v6": "20230429170709", 
    "servicetalk": "20230429171318", 
    "servlet": "20230429171901", 
    "servlet-lib-native": "ERROR: Problem starting servlet-lib-native", 
    "servlet-mysql": "20230429173136", 
    "servlet-postgresql": "20230429174439", 
    "servlet3": "20230429175027",
```

**Comment by remittor** [comment]
build `imi-workerman`:
```
imi-workerman: No releases available for package "pecl.php.net/event"
imi-workerman: install failed
imi-workerman: Removing intermediate container b5c9940ba4a5
imi-workerman: Docker build failed; terminating
imi-workerman: Traceback (most recent call last):
imi-workerman:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
imi-workerman:     raise Exception(token['errorDetail']['message'])
imi-workerman: Exception: The command '/bin/sh -c pecl install event &&     echo "extension=event.so" > /usr/local/etc/php/conf.d/event.ini' returned a non-zero code: 1 
```

build `inverno`:
```
inverno: Step 1/7 : FROM maven:3.8.2-openjdk-16 as maven
inverno: Docker build failed; terminating
inverno: Traceback (most recent call last):
inverno:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
inverno:     raise Exception(token['errorDetail']['message'])
inverno: Exception: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
inverno: Build time: 15s 
```

build `japronto`:
```
japronto: Step 1/6 : FROM python:3.8.12
japronto: Docker build failed; terminating
japronto: Traceback (most recent call last):
japronto:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
japronto:     raise Exception(token['errorDetail']['message'])
japronto: Exception: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
japronto: Build time: 15s 
```

build `salvo`:
```
salvo: Step 5/7 : RUN cargo build --release
salvo:  ---> Running in 992b0ce6a390
salvo:     Updating git repository `https://github.com/salvo-rs/salvo.git`
salvo:     Updating crates.io index
salvo: error: failed to select a version for the requirement `salvo = "^0.38"`
salvo: candidate versions found which didn't match: 0.39.1, 0.37.9, 0.37.8, ...
salvo: location searched: crates.io index
salvo: required by package `salvo_test v0.15.0 (/salvo)`
salvo: Removing intermediate container 992b0ce6a390
salvo: Docker build failed; terminating
salvo: Traceback (most recent call last):
salvo:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 55, in __build
salvo:     raise Exception(token['errorDetail']['message'])
salvo: Exception: The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
salvo: Build time: 1m 20s 
```

Сreating containers sometimes ends with an error.

**Comment by remittor** [comment]
@nbrady-techempower 
Looks like I was worrying for nothing. Probably on April 27, just the docker server was unavailable for some time.

**Comment by nbrady-techempower** [comment]
@remittor That's good news! Thanks for staying on top of it.

**Comment by nbrady-techempower** [comment]
Wow, my mistake! It's set permanently now.
