### ISSUE TITLE
Run framework tests only if there are fresh changes in the repository

### ISSUE THREAD

**Issue by remittor** [TechEmpower/FrameworkBenchmarks#8185]
@nbrady-techempower , @joanhey 

I don't see the point in re-running every week TFB tests that haven't been changed.

I know that some TFB tests try to download the latest source code of a module before building. I'm sure this is the wrong approach, since I've already noticed that it can break the TFB test.
For example, the `Django` framework just broke down due to the update of the major version.

Here's what to do:
1) Before running the test, you need to use the `git` utility to check the last change time for the framework to which the test belongs.
2) After running all 780 tests, you need to merge the new file `results-<current>.json` with the previous file `results-<prev>.json`.
3) Before creating a new file `results-<current>.zip`, unpack the missing frameworks from the previous file `results-<prev>.zip`.

**Comment by joanhey** [comment]
This is very difficult, of course that together we need to find better ways to be faster and useful.

Why is difficult ?
For example, the many security mitigations in the kernels.
The frameworks didn't change, but results change completely.

Or you don't change the framework, but change the server, and we are again with the same problem.

**Comment by remittor** [comment]
> ... many security mitigations in the kernels ... frameworks didn't change, but results change completely ... don't change the framework, but change the server

In this case, it should be possible to run all tests regardless of the freshness of the data in the repository.

> This is very difficult ...

Why is that difficult?

**Comment by volyrique** [comment]
The same suggestion has already been discussed in issue #5925 (and other places) before. Another reason to keep things as they are now is that it makes it possible to obtain statistics, which is an important aspect of any performance work. Also, in addition to kernel updates, all tests should be rerun whenever there is a change in the Docker version.

**Comment by joanhey** [comment]
I'll show only all the frameworks, working with  Nginx, it's the same with others.
![image](https://user-images.githubusercontent.com/249085/235014389-4bd10517-09d1-4156-87e1-2725537d2207.png)

No framework using Nginx, have any change.
And it isn't a problem with Nginx, was with the security mitigations in the kernel, for the CCPUs.

**Comment by joanhey** [comment]
Not only that, a lot of frameworks use Nginx as a Proxy.

**Comment by joanhey** [comment]
It's for that than I say that is NOT easy.
And we'll try to be better, but is not too easy.

**Comment by joanhey** [comment]
A lot of people, see  the bench like a competition.

Please use it like a tool, to fix the problem in the frameworks.

**Comment by joanhey** [comment]
And exist bigger problems, like cache the response in fortunes.
And ....

**Comment by remittor** [comment]
@volyrique 
> are now is that it makes it possible to obtain statistics, which is an important aspect of any performance work.

Imagine that framework `X` has not been changed for a whole year. For such frameworks, you can make a forced launch every 45 days, regardless of the freshness of the data in the repository. That is, in a year there will be 8 launches of framework tests even without creating a pull request in the repository.

> Also, in addition to kernel updates, all tests should be rerun whenever there is a change in the Docker version.

It's OK. Within 45 days, a test with a new version of docker will be launched.

**Comment by nbrady-techempower** [comment]
Thanks for the suggestion, but this isn't something we're going to spend any time trying to accomplish right now. The fact that we have continuous benchmarking running is a huge improvement. Instead of this, I'd really like to cut down on the number of superfluous permutations. Also, I'm ok with removing test implementations that haven't been touched in years and are out of date; assuming the people involved are pinged that it's happening and given the chance to refresh the implementation.

**Comment by remittor** [comment]
> but this isn't something we're going to spend any time trying to accomplish right now.

Someday in TFB there will be 1...2 new tests and you will have to think about running tests that have no changes more rarely.
