### ISSUE TITLE
Verify the dart-start and dart-stream results

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#819]
Our round 9 preview data shows dart-start and dart-stream at the top of the charts for Multiple queries in the Peak environment.  It's not inconceivable that they really are the fastest in that test, but we should do a sanity check on it.  It's a much higher relative placement of Dart frameworks than in the other tests.  It's also much higher than the plain Dart (no framework) version of that test.

Let's do a couple of quick tests just to give us more confidence in the results.
1. While the multi query test is running, curl the test urls a few times from the command line and visually inspect the results.
2. In the source code for the tests, in the handler for multi query requests, add a line to throw an error, and make sure that error is not being swallowed by the framework and resulting in 200 OK responses.  I think `throw "error";` would be enough.

**Comment by msmith-techempower** [comment]
We are still seeing these odd results and the code doesn't suggest any nefarious actions. I am going to remove the milestone, but this should remain under investigation.

**Comment by michaelhixson** [comment]
@msmith-techempower Do you know if anyone tried the two tests I suggested in the OP?

**Comment by msmith-techempower** [comment]
@michaelhixson No, I do not believe anyone has attempted these tests yet.

**Comment by nbrady-techempower** [comment]
I've verified these results. I've placed print statements in every area, confirmed that promises and updates are resolving before response is set. #2536 also confirms that the updates for start/stream persist to the db.
