### ISSUE TITLE
vm.max_map_count OS limit

### ISSUE THREAD

**Issue by itrofimow** [TechEmpower/FrameworkBenchmarks#8203]
Hi! 
First of all, thank you for the excellent benchmarking tool, really helpful with regards to measuring/optimizing code.

I maintain [benchmarking suite](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C%2B%2B/userver) for https://github.com/userver-framework/userver, and i noticed that in the https://tfb-status.techempower.com/results/aab00736-445c-4b7f-83b5-451c47c83395 run the framework failed to finish tests, with errors about likely hitting `vm.max_map_count` OS limit.

I didn't notice such issues before and afaik there recently were some OS updates (bump Ubuntu to 22.04), and i'm wondering whether that could lead to the limit of per-process memory mappings being lowered.

Could you please have a look?

**Comment by itrofimow** [comment]
I'm seeing this in run_id: bc7f7570-a88e-48e3-9874-06d7dc0a0f74 as well, so kindly requesting your @nbrady-techempower assistance on this.

**Comment by itrofimow** [comment]
I took a closer look into logs, and turns out userver was hitting this limit all the way since its very introduction into suite.
It was even crashing from time to time, however this wasn't always registered for some reason.

Would it be possible to increase `vm.max_map_count` to some very high (say, 2**20?) values?
I could disable plaintext benchmarks in userver as a workaround for this (basically in userver every in-flight request is backed by a memory mapping, and in plaintext benchmarks there are up to 256k in-flight requests), however it would be very upsetting to lose such a valuable benchmarking scenario.

**Comment by itrofimow** [comment]
@nbrady-techempower pinging you on this ^

**Comment by nbrady-techempower** [comment]
I have a reminder set to try this on Friday after the current run when I'm in my office.

**Comment by nbrady-techempower** [comment]
This setting has now been applied: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Environment
