### ISSUE TITLE
Play-slick: Update to Slick 2 and enable "compiled" queries?

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#825]
According to the following StackOverflow question and answer, there are optimizations for play-slick that could be made by someone who is comfortable with both of these.

http://stackoverflow.com/questions/22917924/why-is-java-ebean-faster-than-play-slick-in-this-benchmark

I'm not certain what a "compiled" query is in this context, but if it's simply a parameterized PreparedStatement, that would be great.

**Comment by msmith-techempower** [comment]
Kicking down the road.

**Comment by msmith-techempower** [comment]
I believe this was address in #1842
