### ISSUE TITLE
Using http pipelining 

### ISSUE THREAD

**Issue by waghanza** [TechEmpower/FrameworkBenchmarks#8376]
Hi,

I can see in https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/wrk/query.sh#L10 that http pipelining is used here.

As I understand, http pipelining is disabled on major browsers
https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x#http_pipelining

And not sure if pipelining is made when a server-side API is consumed by an API (not browser).

I'm interested in why this feature is enabled on `wrk`.

Regards,

**Comment by waghanza** [comment]
Related to https://github.com/the-benchmarker/web-frameworks/pull/6623

**Comment by fakeshadow** [comment]
I don't see where pipeline is used in the shell you referenced. With `wrk` you need `-s` argument and a lua script to enable pipeline.

**Comment by waghanza** [comment]
Sorry, I think I am confused between keeping alive, and http pipelining
