### ISSUE TITLE
grails controller calls as API need to 'return false'

### ISSUE THREAD

**Issue by orubel** [TechEmpower/FrameworkBenchmarks#841]
Grails calls that act as api calls need to have a 'return false' at the end otherwise it attempts to render a view. This creates additional overhead for the call. The return false tells it to end all processing.

See the Grails Api Toolkit example projects and look at the controllers.

**Comment by msmith-techempower** [comment]
I think this is still outstanding; kicking down the road.

**Comment by msmith-techempower** [comment]
Resolved by #1340
