### ISSUE TITLE
Remove Vert.x results for now

### ISSUE THREAD

**Issue by purplefox** [TechEmpower/FrameworkBenchmarks#846]
Basically the same reasoning as Spray used here:

https://github.com/TechEmpower/FrameworkBenchmarks/pull/842

The version used in round 9 is really old (2.1M3) and there have been lots of performance improvements since then, so the results are misleading.

BTW, this is by no means a criticism of the work you guys do, I know it takes a long time to collate results and get them out :)

**Comment by pacohernandezg** [comment]
Is it going to be included in the new Round 10?

Thanks.

**Comment by bhauer** [comment]
@pacohernandezg We received an updated implementation recently in #1569.

However, my understanding from messages on the Vert.x Google Group, @purplefox would prefer to wait until a test can be implemented for Vert.x 3.0 [1].  Although we have merged the above pull request, I'd like to hear from Tim Fox to confirm that he is agreeable to its inclusion in Round 11, and perhaps that would be predicated on the actual timing of Round 11.  We presently have an ETA of June 22, but as with any of our ETAs, that is subject to change.

[1] https://groups.google.com/d/msg/vertx/Ez0ZheJvxec/AetLpuwunowJ

**Comment by purplefox** [comment]
Hi Brian,

I would like to wait until we get Vert.x 3 out.

Strangely enough Vert.x 3 has an ETA of 22nd June too!

https://github.com/vert-x3/wiki/wiki/Vert.x-Roadmap

**Comment by bhauer** [comment]
@purplefox Sounds good.  We'll defer including Vert.x results until we have an implementation that works on Vert.x 3.

**Comment by mbonaci** [comment]
You should simply make a rule to clone the latest stable release and go out with all the results. 
Wait for v3 while Vert.x boasts with the test from 2013 on their front page. Not cool! 
Vert.x :-1:

**Comment by poiuytrez** [comment]
Any update about Vert.x 3 to be included?

**Comment by purplefox** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/pull/1754
