### ISSUE TITLE
Node & Express Thread Configuration

### ISSUE THREAD

**Issue by Code-Mythos** [TechEmpower/FrameworkBenchmarks#8505]
While investigating the codes, I've noticed that the Node JS & Express JS codes are missing the **_UV_THREADPOOL_SIZE_** environment variable setting.
While some libraries and frameworks are designed in the way to employ the full potential of threads without additional configurations, libuv based frameworks and libraries by default use 4 threads. 
I want to know in the current test environment how the result would change if Node & Express be updated to their latest versions and the **_UV_THREADPOOL_SIZE_** environment variable be set to 1024 or max available threads. 
Thank you in advance.

**Comment by nbrady-techempower** [comment]
Feel free to make some PR's to update these and check the results. We don't track those kinds of issues here.
