### ISSUE TITLE
Flask five times slower in Round 21 than Round 20

### ISSUE THREAD

**Issue by dbohdan** [TechEmpower/FrameworkBenchmarks#8519]
Flask with a full ORM on physical hardware has become much slower.

| Round | Fortunes RPS |
|---|---|
| [19](https://www.techempower.com/benchmarks/#section=data-r19&f=zhb2tb-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-35r&o=e&w=35w-0-0-0&hw=ph) | 10101 |
| [20](https://www.techempower.com/benchmarks/#section=data-r20&f=zhb2tb-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-35r&o=e&w=35w-0-0-0&hw=ph) | 10212 |
| [21](https://www.techempower.com/benchmarks/#section=data-r21&f=zhb2tb-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-35r&o=e&w=35w-0-0-0&hw=ph) | 1869 |

Additionally, in Round 21 it began to return errors. (I think it failed to run in Round 22?)

The decrease in performance seems like something to investigate. It may be related to the switch from MySQL to PostgreSQL and from SQLAlchemy to PonyORM in https://github.com/TechEmpower/FrameworkBenchmarks/pull/6688.

**Comment by nbrady-techempower** [comment]
Thanks for reporting this, but we don't track issues with specific frameworks here unless it's related to the toolset. Please open an issue with the maintainer or in the framework's repo.
