### ISSUE TITLE
Test for transactional database access

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#858]
Here is a modest proposal for a new test type, exercising the transactional capabilities of databases.  That is, we want database reads and writes to execute in such a way that it looks as if each page request is being run atomically, with no other page requests executing simultaneously.  Of course, in reality, there is plenty of concurrency, thanks to the database engine's clever algorithms.  This sort of database access model is considered essential for many applications where data integrity is critical, like banking.

So, why not use the textbook example of transactional concurrency, transferring money between bank accounts?

For simplicity, I suggest an abuse of the `World` table that already exists.  We'll pretend it stores bank accounts, each with account number `Id` and dollar balance `RandomNumber`.  A single page request should run the following code _within a single transaction_, or in some other way that preserves atomicity.
1. Choose two random `Id`s, called `from` and `to`.
2. Choose a random nonnegative amount of "money" `M`.
3. Decrease the balance of `Id` `from` by `M`, probably using an SQL `UPDATE`.
4. Increase the balance of `Id` `to` by `M`, probably using an SQL `UPDATE`.

How do we validate that an implementation really preserves the transactional abstraction?  One simple way (which doesn't catch all misbehaviors, but is a good sanity check) is to compute the sum of all account balances before and after a round of web requests.  Correct code should keep this sum the same at all times, from the perspective of an external script running queries.  Without transactions, a change in the total money supply could be observed between steps 3 and 4 of any execution.

My description here fleshes out one test type idea from #133.

**Comment by nbrady-techempower** [comment]
I don't see this in our near future, but I added the idea to the [Test Types Roadmap](https://github.com/TechEmpower/FrameworkBenchmarks/projects/3)
