### ISSUE TITLE
Filter option to list each framework only once?

### ISSUE THREAD

**Issue by achlipala** [TechEmpower/FrameworkBenchmarks#859]
For someone interested in comparing frameworks, it could be useful to generate results lists that only show each framework once, picking just its permutation with the best results on the current test.  Frameworks like Undertow and Cpoll are hogging so many of the top slots, and it would be nice to easily see "top N" results that don't double-count. :)

**Comment by msmith-techempower** [comment]
This is relating to the website specifically, which now has filters that allow this.
