### ISSUE TITLE
Holiday Break

### ISSUE THREAD

**Issue by NateBrady23** [TechEmpower/FrameworkBenchmarks#8622]
Hi everyone -

I've been out sick this week and we'll be shutting down the citrine servers around the end of the current run until ~12/18. PR review, etc, might be a little slow the next couple of weeks. 

Take care!

Edit: Until the new year! Happy holidays!

**Comment by NateBrady23** [comment]
New update posted to tfb-status. We have new machines coming in and will be returning the current ones. No exact timeline on when everything will be back and configured and up and running but will keep everyone posted.

**Comment by bhauer** [comment]
New test environment! Woohoo!

**Comment by joanhey** [comment]
Specifications of the new servers ??

**Comment by NateBrady23** [comment]
@joanhey they're HPE ProLiant DL360 Gen10 Servers, but I don't have exact specs yet. Will let everyone know when I know!

**Comment by volyrique** [comment]
@NateBrady23 If you still intend to run Ubuntu 22.04 LTS on the new machines, I suggest going straight for [the Hardware Enablement (HWE) kernels](https://ubuntu.com/kernel/lifecycle). This is accomplished by running the following command after completing the operating system installation:
`sudo apt-get install --install-recommends linux-generic-hwe-22.04`

**Comment by NateBrady23** [comment]
Thanks @volyrique - Will take a look and discuss with the team. The servers have just arrived. Will take some time to set up and get all the config right, but will keep everyone posted.

**Comment by joanhey** [comment]
Com  on with  the  news  !!!
:)

**Comment by NateBrady23** [comment]
@joanhey haha sorry for the delay. It's going to be a little bit longer. We had to order some fiber optic cables. We're testing connections today and starting setup. Likely won't have more info for you until next Thursday when I'm back in the office and we have everything we need. (We also had a flooding incident this morning, so had to make sure everything was safe. It's always something when it rains in California!)
