### ISSUE TITLE
Expired SSL `tfb-status.techempower.com`

### ISSUE THREAD

**Issue by AliRn76** [TechEmpower/FrameworkBenchmarks#8724]
SSL of `https://tfb-status.techempower.com/` has been expired.

> 
> Websites prove their identity via certificates, which are valid for a set time period. The certificate for tfb-status.techempower.com expired on 26/01/2024.
>  
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by NateBrady23** [comment]
Thanks. Fixed.
