### ISSUE TITLE
Please upgrade hardware for extreme testings

### ISSUE THREAD

**Issue by ouvaa** [TechEmpower/FrameworkBenchmarks#8820]
it's great for the past few years but we now have 192 core cpu, 100gb network card and http2 / quic h3 etc now.

possible to upgrade the hardware for these framework tests? current core count and limited hw does not reflect the actual performance of the software.

pls also do h2 and h3 as http1.1 is not a real world test case in 2024.

pls consider these for real world use. thx!

**Comment by NateBrady23** [comment]
It's 2024!? With the issues the last few days, you'd think I didn't know what year it was!

Please see other threads about upgrades.
