### ISSUE TITLE
Mysql 9.0 released and `mysql_native_password` it's gone

### ISSUE THREAD

**Issue by joanhey** [TechEmpower/FrameworkBenchmarks#9175]
https://blogs.oracle.com/mysql/post/mysql-90-its-time-to-abandon-the-weak-authentication-method

https://dev.mysql.com/doc/refman/9.0/en/mysql-nutshell.html#mysql-nutshell-removals

We know that some frameworks, use clients that only work with `mysql_native_password` or only have enabled this auth method.

We need to decide how to act with this change.

**Comment by NateBrady23** [comment]
We upgraded to 8.4 in May and it's not default loaded there, so we should be able to easily identify the frameworks that had to adjust based on that? Hopefully there aren't many of them. 

Nonetheless, we should upgrade and framework maintainers simply have to fix for deprecated items, especially where it's security related.

If we can ping maintainers that we know would be affected by this, that would be awesome. But wouldn't stop us from moving forward.

**Comment by joanhey** [comment]
If anybody need to check for any error, here are the consecutive runs:

### Mysql 8.4
https://tfb-status.techempower.com/results/96ee4baf-23c0-4ae1-8a53-04bb27333f97

### Mysql 9.0
https://tfb-status.techempower.com/results/b0a928a6-ff24-462e-8445-fa2dc1bbc7ee

**Comment by joanhey** [comment]
All seems OK :ok_hand:

**Comment by joanhey** [comment]
Frameworks still failing:

- [ ] mesh-mysql @gabrielcursino 
       `mesh-mysql: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`
- [ ] mochiweb @cgarvis 
       `"Client does not support authentication protocol requested by server; consider upgrading MySQL client"}}}}`
- [ ] elli @cgarvis 
      ` "Client does not support authentication protocol requested by server; consider upgrading MySQL client"}}}`
- [ ] turbogears @methane 
       `turbogears: OperationalError: (_mysql_exceptions.OperationalError) (2059, "Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/x86_64-linux-gnu/mariadb18/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory")`
- [ ] cowboy @cgarvis 
        `cowboy: {"init terminating in do_boot",{{badmatch,{error,{bad_return,{{hello_world_app,start,[normal,[]]},{auth_fail,{error_packet,2,1251,<<"08004">>,"Client does not support authentication protocol requested by server; consider upgrading MySQL`
