### ISSUE TITLE
[Feature Request] add denoland/fastwebsockets

### ISSUE THREAD

**Issue by Malix-Labs** [TechEmpower/FrameworkBenchmarks#9207]
# Feature Request

Add https://github.com/denoland/fastwebsockets to the list of websocket comparison

## Related

- https://github.com/denoland/fastwebsockets/tree/main/benches
- https://github.com/denoland/deno/discussions/25003

**Comment by joanhey** [comment]
It's an open source benchmark.
Add the code or talk to the devs of fastewebsockets to add it to the bench.

Thank you !!

**Comment by Malix-off** [comment]
>talk to the devs of fastewebsockets to add it to the bench.

Will do it, thanks !

**Comment by Malix-off** [comment]
Done, see https://github.com/denoland/fastwebsockets/issues/86

**Comment by p8** [comment]
@Malix-Labs Can this be closed?

**Comment by Malix-Labs** [comment]
Closed as not planned, if nobody plans on implementing a denoland/fastwebsockets

I am not able to do that myself, unfortunately

**Comment by Malix-Labs** [comment]
Closed as not planned

Unless it's completed ?
