### ISSUE TITLE
https://www.techempower.com/benchmarks/ is unavailable.

### ISSUE THREAD

**Issue by SetoKaiba** [TechEmpower/FrameworkBenchmarks#9248]
### OS (Please include kernel version)
Not related.

### Expected Behavior
https://www.techempower.com/benchmarks/ is available to access.

### Actual Behavior
https://www.techempower.com/benchmarks/ is unavailable.

### Steps to reproduce behavior
Open the url in browser https://www.techempower.com/benchmarks/

**Comment by NateBrady23** [comment]
Thanks. Fixed.
