### ISSUE TITLE
Upgrade SQLAlchemy in FastAPI ORM Tests

### ISSUE THREAD

**Issue by alexandrubese** [TechEmpower/FrameworkBenchmarks#9299]
Hello,
As the request in the title, would like to see how FastAPI benchmarks look with the latest SQLAlchemy (for future tests).

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/fastapi/requirements-sqlalchemy.txt

**Comment by joanhey** [comment]
Don't create a issue for that, only create a PR and do it.
