### ISSUE TITLE
Servlet 3.0 Async

### ISSUE THREAD

**Issue by dimitarg** [TechEmpower/FrameworkBenchmarks#945]
Request to add  Plain Servlet 3.0 Async to framework implementations.
It would require an executor for the JDBC-related stuff.

**Comment by marko-asplund** [comment]
FYI, a test implementation that uses Servlet 3 API asynchronous processing (for test types 2, 3 and 5) can be found here:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/servlet3-cass

**Comment by hamiltont** [comment]
Does that mean this can be closed? E.g. does servlet3-cass meet the desired goal?

**Comment by nbrady-techempower** [comment]
Closed, see #1803 for future discussion on new frameworks and languages
