### ISSUE TITLE
Check for passwordless sudo access before running 

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#955]
`run-tests.py` assumes in many places that there is passwordless sudo access to the current box (the server), the client (aka load) machine, and the database machine. While this is outlined in the main readme, it's an easy thing to forget to setup. It would be fairly trivial to run a quick check in run-tests.py before we even create the Benchmarker to ensure that this is the case, and print an understandable error message for the user instead of attempting to run and causing lots of weird "no askpass program specified" messages somewhere in the middle of the run

**Comment by msmith-techempower** [comment]
Removing milestone as this is a generic improvement.

**Comment by nbrady-techempower** [comment]
I've moved this to the roadmap https://github.com/TechEmpower/FrameworkBenchmarks/projects/1
