### ISSUE TITLE
TFB_* variables in config/benchmark_profile override benchmark.cfg

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#959]
This is mostly a note to me...

The replace_environ call in run-tests.py loads benchmark_profile, which injects multiple TFB_* variables. Future calls to replace_environ maintain these variables. It hasn't caused and problems yet, because all of the future calls occur too late (e.g. after then environment variables are read), so the values from benchmark.cfg are still being used. However, it's definitely a bug. I'm not sure how to handle this yet, this issue is mostly just a notepad for ideas and to ensure we don't forget this

**Comment by msmith-techempower** [comment]
Mmmm, we should consider the values in `benchmark.cfg` to be the authority. Eventually, `benchmark_profile` should be deprecated, but it's happening organically one PR at a time.
