### ISSUE TITLE
Enable continuous benchmarking

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#979]
With travis approaching completion, I wanted to point out that travis supports post-success hooks that would allow us to send a HTTP notification when a framework test passes verification checks. 

The natural thought is that TechEmpower could setup a server to field these notices and automatically run a benchmark+post the results online. This would enable developers to get commit-by-commit access to benchmark results. 

While the holy grail would be to have these automated benchmarks on bare metal hardware, that would minimally require some skills with automating an operating system re-installation. It's not unreasonably hard, but perhaps for a quick turn around you could consider setting up https://www.eucalyptus.com/ on a few computers. Then write a small server to handle accepting the notices from travis, launching a new VM in eucalyptus, and triggering a benchmark run. I say eucalyptus simply because it has a near identical deployment API as amazon, so if you can successfully launch a vm and trigger a benchmark in eucalyptus then the same scripts should allow anyone to do the same for EC2, which would obviously be exceedingly useful for everyone involved.

**Comment by nbrady-techempower** [comment]
boom.
