### ISSUE TITLE
Create isolated environment for each framework

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#995]
As mentioned in #966, most languages with package systems also have tools to isolate environments (e.g. environment A has packages foo-v1,bar-v1.2,zlib-v0.6 while environment B has foo-v3,bar-v4.4,zlib-v0.6). We should use this! The first step is to separate all the framework-specific requirements out into their respective directories. @methane is making huge strides for python over in #984, @jberger basically finished this for perl with #986. This leaves languages like scala, php, etc, many of which already have some of their dependencies declared inside each framework folder. 

The next step is to choose an environment isolation framework for each language. In #966 we discuss this step for Perl. @jberger prefers Carton, but also mentions local::lib and some other stuff I don't know (perlbrew, plenv). Once we settle on an environment manager for that language, we can apply it to all the tests. 

~~Personally I think we should delay this until #448 is completed as it will become much cleaner to implement with a language-based directory structure (e.g. stuff like `frameworks/php/...` and `frameworks/perl/...`)~~ Done

**Comment by msmith-techempower** [comment]
This is now the overarching design of the tests, and while probably still not perfect it is essentially in the master branch.
