### ISSUE TITLE
Add termination detection timer to run-ci.py

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#998]
For times like https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/32189289 it's really hard to troubleshoot what went wrong, becuase the build timed out without ever printing out and err. It would be fairly simple to add a 45-minute timer to `run-ci.py` that prints something like `The travis build may terminate soon, so I'm going to output OUT and ERR immediately!`. Alternately, we could just upload out and error to `http://sprunge.us/`. I didn't want to do this for *all* of our builds because it's a huge number of useless uploads to their free service, but seeing as very few of our tests time out it seems like a non-abusive use of their service, and a way for us to store out.txt and err.txt without cluttering the log twice if the build does complete within the 50 minute timer

**Comment by msmith-techempower** [comment]
This is implemented.
