### ISSUE TITLE
Add expert contacts to test README's

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#999]
For a lot of the minor "improve framework Foo" pull requests that tweak a framework slightly, e..g add final to the variables, techempower can't know if this is actually an improvement or not without consulting an expert. We should ask experts that show up on our project somewhere if they are willing to allow us to occasionally ping them for advice. If they agree, we can add their github username to the README for that project and then ping them if we need help looking at a pull request

**Comment by LadyMozzarella** [comment]
Closing. I have added suggestions to add experts in the Ruby and Python Readmes (that don't already have experts listed) as examples for other contributors. Also, the [documentation now has some basic outline ideas for the Readmes](http://frameworkbenchmarks.readthedocs.org/en/latest/Development/Readme-Formats/), which include suggestions to add expert contacts.
